### ISSUE TITLE
Issue with node attributes not persisting their value across recipes in 12.16.42+

### ISSUE THREAD

**Issue by majormoses** [chef/chef#6563] opened 2017-11-03 23:30 UTC
## Description

When setting attributes in one recipe another recipe can not see the updated attributes. When attributes are accessed from a recipe other than the one that modified it we do not see the updated values. I was unable to reproduce the issue within the same recipe.

Our use case for doing something like this is that there is an attribute with a hash that we want to always insert into even if someone decides to specify a higher attribute precedence than default.

## Chef Version
Breaks on: `>= 12.16.42` and is functional on `=< 12.15.18`

## Platform Version

Tested on Ubuntu 14.04 and 16.04

## Replication Case

Here is a cookbook to replicate the behavior:
https://github.com/CloudCruiser/ops_chef_cc_reproduce-node-issue

In https://github.com/CloudCruiser/ops_chef_cc_reproduce-node-issue/blob/master/.kitchen.yml#L6-L13 you will see the list of `chef-client` versions I tested and their result. When wanting to test I had to completely remove the chef images and related folders to ensure a clean test for clean and broken states.

Good output:
```
$ bundle exec kitchen converge reproduce-ubuntu-1404
-----> Starting Kitchen (v1.16.0)
-----> Creating <reproduce-ubuntu-1404>...
       Creating container chef-12.15.19
       Creating kitchen sandbox at /home/babrams/.dokken/kitchen_sandbox/e35c4017ff-reproduce-ubuntu-1404
       Creating verifier sandbox at /home/babrams/.dokken/verifier_sandbox/e35c4017ff-reproduce-ubuntu-1404
       Building work image..
       Creating container e35c4017ff-reproduce-ubuntu-1404
       Finished creating <reproduce-ubuntu-1404> (0m3.01s).
-----> Converging <reproduce-ubuntu-1404>...
       Creating kitchen sandbox in /home/babrams/.dokken/kitchen_sandbox/e35c4017ff-reproduce-ubuntu-1404
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
Starting Chef Client, version 12.15.19
Creating a new client identity for reproduce.kitchen using the validator key.
resolving cookbooks for run list: ["cc_repoduce_node_issue::reproduce"]
Synchronizing Cookbooks:
  - cc_repoduce_node_issue (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
original attributes: {"chef"=>{"client"=>{"node"=>"reproduce.kitchen"}}}
---
key: baz, values: {"user"=>"baz", "home"=>"/home/baz"}
---
key: reproduce, values: {"user"=>"usernone", "home"=>"/home/homeone"}
---
updated attributes: {"chef"=>{"client"=>{"node"=>"reproduce.kitchen"}}, "baz"=>{"user"=>"baz", "home"=>"/home/baz"}, "reproduce"=>{"user"=>"usernone", "home"=>"/home/homeone"}}
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 01 seconds
       Finished converging <reproduce-ubuntu-1404> (0m2.05s).
-----> Kitchen is finished. (0m5.25s)
```

Bad output:
```
$ bundle exec kitchen converge reproduce-ubuntu-1404
-----> Starting Kitchen (v1.16.0)
-----> Converging <reproduce-ubuntu-1404>...
       Creating kitchen sandbox in /home/babrams/.dokken/kitchen_sandbox/e35c4017ff-reproduce-ubuntu-1404
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
Starting Chef Client, version 12.16.42
Creating a new client identity for reproduce.kitchen using the validator key.
resolving cookbooks for run list: ["cc_repoduce_node_issue::reproduce"]
Synchronizing Cookbooks:
  - cc_repoduce_node_issue (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
original attributes: {"chef"=>{"client"=>{"node"=>"reproduce.kitchen"}}}
---
key: baz, values: {"user"=>"baz", "home"=>"/home/baz"}
---
key: reproduce, values: {"user"=>"usernone", "home"=>"/home/homeone"}
---
updated attributes: {"chef"=>{"client"=>{"node"=>"reproduce.kitchen"}}}
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 01 seconds
       Finished converging <reproduce-ubuntu-1404> (0m1.94s).
```

**Comment by stefanwork** [comment] 2017-11-07 00:44
Hi @majormoses 

I'm having a similar problem. v12.21.4 is fine, but v12.21.10 is broken.

Of course none of the versions in between have been published, so I can't narrow it down further. Here's the diff though: https://github.com/chef/chef/compare/v12.21.4...v12.21.10

Can you test these two versions in your repo? I wasn't able to run it myself.

Probably one of these two commits caused the breakage in 12.21:

```
$ git log --oneline v12.21.4...v12.21.10 lib/chef/node/attribute.rb
899203f59 immutablize on the fly and reduce duping
de7b8f9ea node attributes: remove useless dup in merge_all
```

These kinds of breakages are so incredibly annoying. Not sure if I'm using something the wrong way, but it's darn annoying.

**Comment by huynt1979** [comment] 2017-11-07 01:07
@stefanwork It's not only annoying. It could have catastrophic consequences as well. For example, when you write a wrapper cookbook, you may want to set the some node attributes (defined by the upstream cookbook) to some customized values in your recipe. Because of this bug(?), those attributes won't have the values you intended, which in turn would take the default values specified in the upstream cookbook. That could mean the dead/live of a cluster like Elasticsearch...

**Comment by majormoses** [comment] 2017-11-07 01:29
I will try to make the reproduction case a bit better and will see if I can add tests for those versions. Glad it's not just me.

**Comment by stefanwork** [comment] 2017-11-07 01:30
I've been struggling to build a minimal test case, and failing so far. I'm not sure yet if we are encountering the same bug, but your test of these two versions should confirm this.

**Comment by majormoses** [comment] 2017-11-07 03:18
Well I am not sure what to say after writing some real tests for this as it is now working on 12.21.20 but the rest seem right:
```
$ bundle exec kitchen list
Instance                   Driver  Provisioner  Verifier  Transport  Last Action  Last Error
chef-12-10-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-10-24-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-12-15-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-12-15-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-14-89-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-14-89-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-15-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-15-19-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-16-42-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-16-42-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-17-44-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-17-44-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-18-31-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-18-31-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-4-ubuntu-1404   Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-4-ubuntu-1604   Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-10-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-10-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-20-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-20-ubuntu-1604  Dokken  Dokken       Busser    Dokken     Verified     <None>
```

You can look at the reproduction code and tests here: https://github.com/CloudCruiser/ops_chef_cc_reproduce-node-issue/tree/5f31d850aa02db0334224d314d7d7136f0f82cea

**Comment by majormoses** [comment] 2017-11-07 04:09
I am struggling with the fact that .20 was not working and now magically is...I will chalk that up to either mixing something up or the test case only catches a portion of the bug and needs to be enhanced. Just because I was paranoid I added more versions and saw similar results:
```
$ bundle exec kitchen list
Instance                   Driver  Provisioner  Verifier  Transport  Last Action  Last Error
chef-12-10-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-12-15-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-14-89-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-15-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-16-42-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-17-44-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-18-31-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-4-ubuntu-1404   Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-10-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-12-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-14-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-18-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-20-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-21-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-22-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-25-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-26-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
```

If you are wondering why I dropped testing both platforms it did not seem to be an issue between platforms and it sped up my testing.

**Comment by majormoses** [comment] 2017-11-07 05:14
I have retested my cookbook and it is still failing, so we probably need a better test though it certainly shows some odd failures for a subset of `chef-client` versions being tested.

**Comment by majormoses** [comment] 2017-11-07 20:55
OK I fixed my tests and it now breaks on the appropriate version. What is interesting is that looks like there was a regression, was fixed, and then another regression:
```
$ bundle exec kitchen list
Instance                   Driver  Provisioner  Verifier  Transport  Last Action  Last Error
chef-12-10-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-12-15-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-14-89-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-15-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-16-42-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-17-44-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-18-31-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-4-ubuntu-1404   Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-10-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-12-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-14-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-18-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-20-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-21-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-22-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-21-25-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-26-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
```

**Comment by majormoses** [comment] 2017-11-07 22:18
Nope I goofed something and should be good (broken) now:
```
$ bundle exec kitchen list
Instance                   Driver  Provisioner  Verifier  Transport  Last Action  Last Error
chef-12-10-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-12-15-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-14-89-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-15-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Verified     <None>
chef-12-16-42-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-17-44-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-18-31-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-4-ubuntu-1404   Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-10-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-12-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-14-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-18-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-19-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-20-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-21-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-22-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-24-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-25-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
chef-12-21-26-ubuntu-1404  Dokken  Dokken       Busser    Dokken     Set Up       Kitchen::ActionFailed
```

**Comment by majormoses** [comment] 2017-11-08 00:42
@stefanwork the bug I am seeing is affecting anything from 12.16+ and affects 13 (I only tested with 13.6.4).

**Comment by stefanwork** [comment] 2017-11-08 00:57
That makes me think that we're seeing two different bugs. I haven't had time to resume work on this yet, but I will let you know if I have any progress.

**Comment by lamont-granquist** [comment] 2017-11-08 18:22
@stefanwork see #6519

**Comment by lamont-granquist** [comment] 2017-11-08 18:22
@stefanwork see #6519

**Comment by lamont-granquist** [comment] 2017-11-08 18:23
@stefanwork see #6519

**Comment by lamont-granquist** [comment] 2017-11-08 18:23
@stefanwork see #6519

**Comment by lamont-granquist** [comment] 2017-11-08 18:48
this bug is more a cookbook bug than a core chef bug:

```
node['bar']['foo']['tokens'].each do |key, values|
  # puts "key: #{key}, values: #{values}"
  # puts '---'
  node['foo']['bar']['additional_attributes'].store(key, values)
end
```

that line of code is using the `Hash#store` method to update the merged "Immutable" attribute.  if I change that to use `Hash#[]=` instead then on Chef 13.5.3 (testing this to avoid having to consider the other bug in 13.6.4):

```

================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/cc_repoduce_node_issue/recipes/reproduce.rb
================================================================================

Chef::Exceptions::ImmutableAttributeModification
------------------------------------------------
Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
```

That is the correct behavior.

What you might be trying to do is:

```
node['bar']['foo']['tokens'].each do |key, values|
  # puts "key: #{key}, values: #{values}"
  # puts '---'
  node.override['foo']['bar']['additional_attributes'][key] = values
end
```

If that doesn't work, you might need to look at the `node.rm('foo', 'bar', 'additional_attributes', key)` API in order to wipe everything from all levels at that key location first.

We do have a bug in core chef here, but its around the `#store` call not immediately throwing an exception.  The fact that it ever worked is very weird, and was not supported or documented behavior, and I suspect someone tried `#[]=` first, and then they decided to solve that by using `#store` which produced undefined behavior based on the implementation details of how we do the deep merge cache from revision to revision.

**Comment by lamont-granquist** [comment] 2017-11-08 19:05
Since we're already getting a dogpile of users who are probably being bit by #6519 into this issue, I'm going to close and lock it.

I'm opening #6575 to track the core chef work of properly throwing exceptions on Hash#store against ImmutableMash.

**Closed by lamont-granquist** 2017-11-08 19:05 UTC

**Comment by lamont-granquist** [comment] 2017-11-08 22:47
A note as the result of a long slack discussion...

```
node['bar']['foo']['tokens'].each do |key, values|
  node['foo']['bar']['additional_attributes'].store(key, values)
end
```

What that code is trying to do is assert "look I don't care about what anyone else says, I just want to set this value, and I don't want any merging".

My first suggestion was to use `force_override` instead since that is the highest precedence level:

```
node['bar']['foo']['tokens'].each do |key, values|
  node.force_override['foo']['bar']['additional_attributes'][key] = values
end
```

The goofy thing there is that if "values" is an array you get array merging between precedence levels if someone sets an override value in a role/attribute/etc.

The correct way to state in a recipe "look I just want to set this thing" is to use `node.force_override!`:

```
node['bar']['foo']['tokens'].each do |key, values|
  node.force_override!['foo']['bar']['additional_attributes'][key] = values
end
```

This blows away anything which is set at the override level (clearing out any arrays) and then sets the highest precedence level, so will always win.  The `!` at the end of `force_override!` basically means "and don't even array merge, I'm not kidding, just go away"

While we mostly advise people to stay away from force_default/force_override and keep everything as simple as possible, if you hit the use case of 'look i want the recipe to always win on this hash key and i don't care' then you've hit the use case that we engineered `node.force_override!` around.

Another approach would be to simply use a plain old ruby hash.  If you're fighting this hard with attributes a perfectly acceptable solution is to not use attributes at all.  This is the equivalent of the old joke:

Patient:  Doctor, it hurts when I do this.
Doctor:  Stop doing that.

```
overrides = {
  'baz' => 'quux'
}
config = node['foo']['bar'].to_hash
config.merge!(overrides)

template "/etc/whatever.conf" do
  source "whatever.conf.erb"
  variables(config)
end
```

Here we convert a node object to a hash, then merge another hash over the top of it.  Now whatever anyone tries to set at any precedence level will get blown away.

The two downsides to this approach is that the config hash is not saved to the node object and is not searchable, and the config hash in this recipe cannot be shared with another recipe.  That latter issue can be solved by using the node.run_state hash:

```
overrides = {
  'baz' => 'quux'
}
node.run_state['config'] = node['foo']['bar'].to_hash
node.run_state['config'].merge!(overrides)

template "/etc/whatever.conf" do
  source "whatever.conf.erb"
  variables(node.run_state['config'])
end
```

The `node.run_state` object is just a normal Hash (not a Mash or VividMash so there's no autovivification and you need to worry about strings-vs-symbols) which is a scratchpad that recipes can scribble on to ship data between different recipes.  I would strongly suggest not actually using a key like `'config'` and use some kind of namespacing (like an `acme.org` or at least the name of the cookbook as the top level hash key here).

Another way would be to use a method:

```
def my_config
  overrides = {
    'baz' => 'quux'
  }
  config = node['foo']['bar'].to_hash
  config.merge!(overrides)
end
```

That could be memoized, and could even be memoized on the run_state, but you have to decide what behavior you want to see if `node['foo']['bar']` is written to in between calls to this method.  Package that method in a module and then include it into Chef::DSL::Recipe and then the same method can be accessed from any recipe/resource in order to extract `node['foo']['bar]` and apply the hard overridden policy to that array.

**Comment by lamont-granquist** [comment] 2017-11-13 22:05
@stefanwork @huynt1979 This issue was definitely not related to any breakage in  v12.21.4 to v12.21.10

The other #6519 issue has also been around since at least v12.5.1 and may not be a regression at all, just an old, old bug that nobody had reported.

If you've hit issues in 12.21.10 they should get reported in a new issue.
