### ISSUE TITLE
chef_gem/gem_package resource eagerly populates candidate_version when gem is already installed

### ISSUE THREAD

**Issue by vinyar** [chef/chef#5553] opened 2016-11-16 08:53 UTC
## Description

chef_gem resource attempts to reach out to internet for already installed gems.

## Chef Version & ## Platform Version

root@default-bento-ubuntu-1404:~# chef-client -v
Chef: 12.15.19

## Replication Case

use chef_gem resource to install a gem on a machine.
unplug network, run chef-client, converge will fail because we can't reach rubygems.org

## Client Output
```
* chef_gem[chef-vault] action install[2016-11-16T08:36:59+00:00] WARN:  failed to find gem chef-vault (>= 0) from [https://rubygems.org/]


           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-vault]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
           STDOUT:
           STDERR: ERROR:  Could not find a valid gem 'chef-vault' (>= 0), here is why:
              Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
           ---- End output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
           Ran /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  returned 2
```

## Stacktrace

```
        * chef_gem[chef-vault] action install[2016-11-16T08:36:59+00:00] WARN:  failed to find gem chef-vault (>= 0) from [https://rubygems.org/]


           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-vault]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
           STDOUT:
           STDERR: ERROR:  Could not find a valid gem 'chef-vault' (>= 0), here is why:
              Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
           ---- End output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
           Ran /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  returned 2

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/bbip_chef_vault/recipes/default.rb:12:in `from_file'
           /tmp/kitchen/cache/cookbooks/svops_exportc_usermgmt_linux/recipes/linux.rb:11:in `from_file'
           /tmp/kitchen/cache/cookbooks/svops_exportc_usermgmt_linux/recipes/default.rb:15:in `from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/bbip_chef_vault/recipes/default.rb

            12: chef_gem 'chef-vault' do
            13:   version node['bbip_chef_vault']['version']
            14:   compile_time true
            15: end
            16:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/bbip_chef_vault/recipes/default.rb:12:in `from_file'

           chef_gem("chef-vault") do
             package_name "chef-vault"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_gem
             cookbook_name "bbip_chef_vault"
             recipe_name "default"
             compile_time true
             gem_binary "/opt/chef/embedded/bin/gem"
           end

           Platform:
           ---------
           x86_64-linux
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/svops_exportc_usermgmt_linux/recipes/default.rb
         ================================================================================

         Mixlib::ShellOut::ShellCommandFailed
         ------------------------------------
         chef_gem[chef-vault] (bbip_chef_vault::default line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
         ---- Begin output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
         STDOUT:
         STDERR: ERROR:  Could not find a valid gem 'chef-vault' (>= 0), here is why:
            Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
         ---- End output of /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  ----
         Ran /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri  returned 2

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/bbip_chef_vault/recipes/default.rb:12:in `from_file'
           /tmp/kitchen/cache/cookbooks/svops_exportc_usermgmt_linux/recipes/linux.rb:11:in `from_file'
           /tmp/kitchen/cache/cookbooks/svops_exportc_usermgmt_linux/recipes/default.rb:15:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/bbip_chef_vault/recipes/default.rb:

          11:
          12>> chef_gem 'chef-vault' do
          13:    version node['bbip_chef_vault']['version']
          14:    compile_time true
          15:  end
          16:
          17:  require 'chef-vault'
          18:

         Platform:
         ---------
         x86_64-linux
```
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by vinyar** [comment] 2016-11-16 09:10
My workaround for now is:

```
chef_gem 'chef-vault' do
  # require 'pry';binding.pry
  version node['geip_chef_vault']['version']
  compile_time true
  not_if {Gem::Specification::find_all_by_name('chef-vault').any?}
end
```

**Comment by shortdudey123** [comment] 2016-11-16 17:22
FWIW, since you have `version` specified, the `not_if` does not valid you have the correct version installed, just that some version is installed.

Since `ChefGem` inherits from `Chef::Resource::Package::GemPackage`, this more than likely affects the `gem_package` resource as well (although i did not test to verify)

**Comment by lamont-granquist** [comment] 2016-11-16 18:51
Okay, so actually this report is vague.

You need to do more than just show that it tries to talk to rubygems.org because there's two possible bugs here:

- it really violates idempotency and if rubygems.org was able to be contacted then it would have done the install action when it shoudn't have
- it tries to resolve the candidate_version (by hitting rubygems.org) when the idempotency check is successful and it would work if rubygems.org was able to be contacted, but it is doing unnecessary work that fails behind a firewall.

I can't tell from your output which of those cases it is.  I'm fairly certain its the latter case since otherwise we'd be crushed with bug reports, but as it stands this bug report is not useful enough.  I also can look through the rubygem provider code and i'm not seeing calls to candidate_version that would unlazy it inappropriately.

A link to the stackoverflow issue that you mentioned would be useful to also include.

**Comment by lamont-granquist** [comment] 2016-11-16 18:53
And the full stacktrace.out (like the output prompts you to report and the issue form also prompts you to report) would be highly useful in this case, since its likely that the culprit that is calling candidate_version is right there in the stacktrace.

**Comment by vinyar** [comment] 2016-11-19 07:00
Yum, of course it's the second, which is why I keep hitting these edge-cases when I visit large enterprises. I'll pull debug logs tomorrow.

Stackoverflow - http://stackoverflow.com/questions/8490167/how-do-i-find-out-whether-a-gem-is-installed-in-the-system-or-not

**Comment by lamont-granquist** [comment] 2016-11-21 02:06
just the /var/chef/cache/stacktrace.out would most likely point out exactly where the problem is

**Comment by lamont-granquist** [comment] 2016-11-30 18:46
ping on needing the stacktrace.out

i looked at the code and i don't see the bug.  the stacktrace.out would immediately point out what the buggy calling code is.

**Comment by lamont-granquist** [comment] 2017-01-25 18:18
looking at this again its blowing up in the actual attempt to install the package:

```
 /opt/chef/embedded/bin/gem install "chef-vault" -q --no-rdoc --no-ri 
```

that means that the idempotency check has already failed.

that looks more like the gem just wasn't installed to begin with.

closing this since it doesn't seem to be actionable right now, i can't see from the code what went wrong, and the output looks like it was functioning as well as it could.

anyone who hits this in the future, please open a new issue with:

- debug logs
- stacktrace.out
- validate state of the gem being installed before/after

**Closed by lamont-granquist** 2017-01-25 18:18 UTC
Labels: Status: Pending Contributor Response
