### ISSUE TITLE
knife-configure-initial is broken w/ chef server 11

### ISSUE THREAD

**Issue by achakraborty-zulily** [chef/chef#3839] opened 2015-08-28 23:07 UTC
configure-initial calls user-create. The backwards compatibility code in user-create which redirects it to osc-user-create assumes that ARGV will be a user-create command, which is not true when call comes from configure-initial.

**Comment by achakraborty-zulily** [comment] 2015-09-04 21:16
Pull request with fix.
https://github.com/chef/chef/pull/3880

**Comment by cheeseplus** [comment] 2018-01-31 15:29
Even though this is older, closing as dupe of https://github.com/chef/chef/issues/4814 as it has more information.

**Closed by cheeseplus** 2018-01-31 15:29 UTC
Labels: Priority: Low
