### ISSUE TITLE
support for a manually entered sudo password with knife-bootstrap is broken

### ISSUE THREAD

**Issue by btm** [chef/chef#11359] opened 2021-04-13 21:14 UTC
Infra Client: 16.7.61 
Platform: Ubuntu 20.04
Customer issue: https://github.com/chef/customer-bugs/issues/333

When running `knife bootstrap --use-sudo-password` against a system that 1) uses password based authentication, NOT key-based, and 2) requires a password for sudo, it fails with this error:

```
ERROR: Train::UserError: Sudo failed: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

This is the same error as #9987, however sudo is correctly configured in this. If the password is specified on the command line it works fine, e.g. `knife bootstrap --sudo -x username -P PASSWORD --use-sudo-password PASSWORD`.

**Comment by msys-sgarg** [comment] 2021-06-07 12:48
@btm By going through the issue I figured that the problem is with ` not so user-friendly error message` and did updates as required in inspec/train repo here - https://github.com/inspec/train/pull/690 - I am hoping logically functionality is working as expected

**Comment by msys-sgarg** [comment] 2021-08-03 11:41
Since https://github.com/chef/chef/pull/11654 is merged the issue can be closed

**Closed** 2021-08-03 11:42 UTC
Labels: Focus: knife bootstrap, Status: Sustaining Backlog, Type: Bug
