### ISSUE TITLE
The mount resource is not idempotent on windows

### ISSUE THREAD

**Issue by jaym** [chef/chef#3861] opened 2015-09-02 16:17 UTC
I cannot run the mount resource twice. If I run the following recipe twice, it fails on the second go.
```ruby
mount "T:" do
  action [:mount]
  device "\\\\localhost\\C$"
end
```

```
C:\workspace\chef [jdm/bundle-exec +31 ~0 -0 !]> bundle exec chef-apply mount.rb
DL is deprecated, please use Fiddle
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[T:] action mount

    ================================================================================
    Error executing action `mount` on resource 'mount[T:]'
    ================================================================================

    Chef::Exceptions::UnsupportedAction
    -----------------------------------
    #<Chef::Provider::Mount::Windows:0x4336fe0> does not implement #mount_options_unchanged?

    Resource Declaration:
    ---------------------
    # In mount.rb

      1: mount "T:" do
      2:   action [:mount]
      3:   device "\\\\localhost\\C$"
      4: end

    Compiled Resource:
    ------------------
    # Declared in mount.rb:1:in `run_chef_recipe'

    mount("T:") do
      action [:mount]
      supports {:remount=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      mount_point "T:"
      device "\\\\localhost\\C$"
      device_type :device
      fsck_device "-"
      fstype "auto"
      options ["defaults"]
      dump 0
      pass 2
      declared_type :mount
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2015-09-02T09:10:49-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-09-02T09:10:49-07:00] FATAL: Chef::Exceptions::UnsupportedAction: mount[T:] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::UnsupportedAction: #<Chef::Provider::Mount::Windows:0x4336fe0> does not implement #mount_options_unchanged?
```

stacktrace.out:
```
C:\workspace\chef [jdm/bundle-exec +31 ~0 -0 !]> cat C:/chef/cache/chef-stacktrace.out
Generated at 2015-09-02 09:10:49 -0700
Chef::Exceptions::UnsupportedAction: mount[T:] ((chef-apply cookbook)::(chef-apply recipe) line  1) had an error: Chef::Exceptions::UnsupportedAction: #<Chef::Provider::Mount::Windows:0x4336f e0> does not implement #mount_options_unchanged?
C:/workspace/chef/lib/chef/provider/mount.rb:126:in `mount_options_unchanged?'
C:/workspace/chef/lib/chef/provider/mount.rb:46:in `action_mount'
C:/workspace/chef/lib/chef/provider.rb:144:in `run_action'
C:/workspace/chef/lib/chef/resource.rb:585:in `run_action'
C:/workspace/chef/lib/chef/runner.rb:49:in `run_action'
C:/workspace/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/workspace/chef/lib/chef/runner.rb:81:in `each'
C:/workspace/chef/lib/chef/runner.rb:81:in `block in converge'
C:/workspace/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_re source'
C:/workspace/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/workspace/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block '
C:/workspace/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/workspace/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/workspace/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/workspace/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/workspace/chef/lib/chef/runner.rb:80:in `converge'
C:/workspace/chef/lib/chef/application/apply.rb:189:in `run_chef_recipe'
C:/workspace/chef/lib/chef/application/apply.rb:198:in `run_application'
C:/workspace/chef/lib/chef/application/apply.rb:211:in `run'
C:/workspace/chef/bin/chef-apply:25:in `<top (required)>'
C:/tools/Ruby200p645/lib/ruby/gems/2.0.0/bin/chef-apply:23:in `load'
C:/tools/Ruby200p645/lib/ruby/gems/2.0.0/bin/chef-apply:23:in `<main>'
```

**Comment by lamont-granquist** [comment] 2015-10-07 17:21
I think I've seen this a few times now in tickets, i think this is a dup.

**Comment by eguerints** [comment] 2015-10-29 08:05
I have the same problem since the last update of chef azure extensions, workaround with a guard:
```ruby
mount "Z:" do
    action :mount
    device "\\\\localhost\\C$"
    guard_interpreter :powershell_script
    not_if "Test-Path z:"
end
```

**Comment by MichaelPereira** [comment] 2016-02-02 20:23
@lamont-granquist: This problem is still biting anyone who tries to use the mount resource on Windows, can the workaround provided by @eguerints be integrated into the [official mount resource doc](https://docs.chef.io/resource_mount.html) while the problem is not resolved? I can make the change and submit the PR at [chef/chef-web-docs](https://github.com/chef/chef-web-docs/)

**Comment by btm** [comment] 2016-04-01 00:06
Fixed by https://github.com/chef/chef/pull/4692.

**Closed by btm** 2016-04-01 00:06 UTC
Labels: Bug, Medium Priority, Windows
