### ISSUE TITLE
Resources with `ignore_failure true` don't report failure details to A2

### ISSUE THREAD

**Issue by trickyearlobe** [chef/chef#10099] opened 2020-07-02 08:19 UTC
# Description

An enterprise customer reported that if a resource in a Chef run fails, but it has `ignore_failure true` the error doesn't show up in the A2 UI as a stack trace.

![image](https://user-images.githubusercontent.com/3001322/86259384-dc6ea400-bbb3-11ea-8d3b-f55b2125c142.png)

In the screenshot you can see one resource has a `Error Log` button against it, but when clicked, the stack trace is empty.

## Chef Version
15.6.18

## Platform Version
Windows 10.0.14393

## Replication Case

- Run a cookbook with a failing resource that has `ignore_failure true` set.
- Look at the list of updated resources and see one has an `Error Log` button.
- Click the `Error Log` button and observe the empty stack trace.
- Observe the stack trace is visible in the Chef client logs
- Observer the client run completes successfully.

## The actual stacktrace from the example

```
    ================================================================================
    Error executing action `run` on resource 'powershell_script[Disbale administrator]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile
-ExecutionPolicy Bypass -InputFormat None -File "C:/Users/t635414/AppData/Local/Temp/chef-script20200213-7040-iblr4x.ps1
" ----
    STDOUT:
    STDERR: The user name could not be found.
    More help is available by typing NET HELPMSG 2221.
    ---- End output of "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -E
xecutionPolicy Bypass -InputFormat None -File "C:/Users/t635414/AppData/Local/Temp/chef-script20200213-7040-iblr4x.ps1"
----
    Ran "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy
Bypass -InputFormat None -File "C:/Users/t635414/AppData/Local/Temp/chef-script20200213-7040-iblr4x.ps1" returned 2

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/cis-windows-ms-2016/recipes/account_and_local_policies.rb

     31:   powershell_script 'Disbale administrator' do
     32:     code <<-EOH
     33:     net user administrator /active:yes
     34:     EOH
     35: ignore_failure true
     36:   end
     37:   # xccdf_org.cisecurity.benchmarks_rule_2.3.4.2_L1_Ensure_Devices_Prevent_users_from_installing_printer_driver
s_is_set_to_Enabled

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/cis-windows-ms-2016/recipes/account_and_local_policies.rb:31:in `from_file'

    powershell_script("Disbale administrator") do
      action [:run]
      default_guard_interpreter :powershell_script
      command nil
      backup 5
      interpreter "powershell.exe"
      declared_type :powershell_script
      cookbook_name "cis-windows-ms-2016"
      recipe_name "account_and_local_policies"
      code "    net user administrator /active:yes\n"
      ignore_failure true
      domain nil
      user nil
      flags "-NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None"
    end

    System Info:
    ------------
    chef_version=15.6.18
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
```

**Comment by lamont-granquist** [comment] 2020-07-02 19:06
All that the client reports is the overall set of exceptions in the `run_status` which led to a run failure.

There's no per-resource field in the JSON payload to include an exception in an ignore_failure resource, and it looks like if I push that exception into the overall run data that it'll show up as failing the whole run.

So from the client perspective there's no bug here, its functioning as designed.

This should get kicked over to the A2 team to extend the JSON payload to include per-resource exceptions and then they're going to need to do the UX/UI work to expose that.  But it can't be fixed here.

**Comment by lamont-granquist** [comment] 2020-07-02 19:09
Yeah the per-resource record does have an `error_message` but its just the text, not the backtrace:

```
{"type"=>:ruby_block,
 "name"=>"blow up",
 "id"=>"blow up",
 "after"=>{},
 "before"=>{},
 "duration"=>"5",
 "delta"=>"",
 "ignore_failure"=>true,
 "result"=>"run",
 "status"=>"failed",
 "cookbook_name"=>"test",
 "cookbook_version"=>"0.0.1",
 "recipe_name"=>"default",
 "error_message"=>"boom"}
```

It's easy enough to just jam the whole backtrace in there, but that won't make it show up on A2

**Comment by trickyearlobe** [comment] 2020-07-26 00:16
Raised https://github.com/chef/automate/issues/4133 on the A2 side of the house.

**Comment by vsingh-msys** [comment] 2020-07-28 12:14
@lamont-granquist I am able to reproduce the issue and Yes, per resource record only has a short error description. 

I think if we have `ignore_failure` kind of option the adding full error with stack trace detail per resource would be the better.

As I can check if we provide `ignore_failure` true then only `Error Description`, `Resource Declaration`  and `Compiled Resource` data we are populating but not the backtrace data,
```
sudo chef-client -o 'recipe[starter::default@1.0.18],recipe[learn_chef_apache2]'
Starting Chef Infra Client, version 16.2.73
[2020-07-28T10:56:29+00:00] INFO: *** Chef Infra Client 16.2.73 ***
[2020-07-28T10:56:29+00:00] INFO: Platform: x86_64-linux
[2020-07-28T10:56:29+00:00] INFO: Chef-client pid: 7702
[2020-07-28T10:56:30+00:00] WARN: Run List override has been provided.
[2020-07-28T10:56:30+00:00] WARN: Original Run List: [recipe[starter]]
[2020-07-28T10:56:30+00:00] WARN: Overridden Run List: [recipe[starter::default@1.0.18], recipe[learn_chef_apache2]]
[2020-07-28T10:56:30+00:00] INFO: Run List is [recipe[starter::default@1.0.18], recipe[learn_chef_apache2]]
[2020-07-28T10:56:30+00:00] INFO: Run List expands to [starter::default@1.0.18, learn_chef_apache2]
[2020-07-28T10:56:30+00:00] INFO: Starting Chef Infra Client Run for node1
[2020-07-28T10:56:30+00:00] INFO: Running start handlers
[2020-07-28T10:56:30+00:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["starter::default@1.0.18", "learn_chef_apache2"]
[2020-07-28T10:56:30+00:00] INFO: Loading cookbooks [starter@1.0.18, learn_chef_apache2@0.1.1]
[2020-07-28T10:56:30+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - starter (1.0.18)
  - learn_chef_apache2 (0.1.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 4 resources
Recipe: starter::default
  * file[/tmp/index.php] action create[2020-07-28T10:56:30+00:00] INFO: Processing file[/tmp/index.php] action create (starter::default line 6)

    * cannot determine user id for 'abcd', does the user exist on this system?[2020-07-28T10:56:30+00:00] ERROR: file[/tmp/index.php] (starter::default line 6) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'abcd', does the user exist on this system?; ignore_failure is set, continuing

    ================================================================================
    Error executing action `create` on resource 'file[/tmp/index.php]'
    ================================================================================
    
    Chef::Exceptions::UserIDNotFound
    --------------------------------
    cannot determine user id for 'abcd', does the user exist on this system?
    
    Resource Declaration:
    ---------------------
    # In /.chef/cache/cookbooks/starter/recipes/default.rb
    
      6: file '/tmp/index.php' do
      7:   content '<html>This is a placeholder for the home page.</html>'
      8:   mode '0755'
      9:   user 'abcd'
     10:   ignore_failure true
     11: end
    
    Compiled Resource:
    ------------------
    # Declared in /.chef/cache/cookbooks/starter/recipes/default.rb:6:in `from_file'
    
    file("/tmp/index.php") do
      action [:create]
      default_guard_interpreter :default
      declared_type :file
      cookbook_name "starter"
      recipe_name "default"
      content "<html>This is a placeholder for the home page.</html>"
      mode "0755"
      owner "abcd"
      ignore_failure true
      path "/tmp/index.php"
      group nil
      verifications []
    end
    
    System Info:
    ------------
    chef_version=16.2.73
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
    
Recipe: learn_chef_apache2::default
  * apt_package[apache2] action install[2020-07-28T10:56:30+00:00] INFO: Processing apt_package[apache2] action install (learn_chef_apache2::default line 7)
 (up to date)
  * service[apache2] action enable[2020-07-28T10:56:30+00:00] INFO: Processing service[apache2] action enable (learn_chef_apache2::default line 9)
 (up to date)
  * service[apache2] action start[2020-07-28T10:56:31+00:00] INFO: Processing service[apache2] action start (learn_chef_apache2::default line 9)
 (up to date)
  * template[/var/www/html/index.html] action create[2020-07-28T10:56:31+00:00] INFO: Processing template[/var/www/html/index.html] action create (learn_chef_apache2::default line 14)
 (up to date)
[2020-07-28T10:56:31+00:00] WARN: Skipping final node save because override_runlist was given
[2020-07-28T10:56:31+00:00] INFO: Chef Infra Client Run complete in 0.438949694 seconds
[2020-07-28T10:56:31+00:00] INFO: Skipping removal of unused files from the cache

Running handlers:
[2020-07-28T10:56:31+00:00] INFO: Running report handlers
Running handlers complete
[2020-07-28T10:56:31+00:00] INFO: Report handlers complete
Chef Infra Client finished, 0/4 resources updated in 01 seconds

``` 

In order to fix this issue:

a) Chef Infra changes:
- Investigate the way to populate stack trace detail.
- Add full error detail to resource record.

b) A2 Changes:
- Update the backend ingest service and update the resource record.
- Take required action to show stack trace to Error log on Automate UI.

Happy to take ownership of both Chef infra and A2 changes. Thanks

**Comment by vsingh-msys** [comment] 2020-08-18 08:40
Infra side work has been done in #10237. closing this issue from here as automate side changes have been tracking in issue https://github.com/chef/automate/issues/4133

**Closed by vsingh-msys** 2020-08-18 08:40 UTC
