### ISSUE TITLE
macosx hostname resource error when previously unset

### ISSUE THREAD

**Issue by hawksight** [chef/chef#8477] opened 2019-05-07 14:44 UTC
## Description

Using the [hostname](https://docs.chef.io/resource_hostname.html) resource on macosx, the chef run will fail if the hostname has not been set before. I've found this common across our mac devices. Obviously this is somewhat counter intuitive as I am attempting to use the resource to set the hostname on said devices.

## Chef Version
14.12.9
Hosted Chef currently.

## Platform Version
Macosx:

```
platform_version: 10.14.4
platform_build: 18E226
```

## Replication Case

Use something like the following in a recipe and run against a macosx machine where the command `/usr/sbin/scutil --get HostName` returns `HostName: not set`

```
hostname 'set-machine-hostname' do
  hostname config['hostname']
  action :set
  retries 1
end
```

## Client Output

Output from run locally.

```
hostname[set-machine-hostname] (enroll::default line 65) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[set HostName via scutil] (/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource/hostname.rb line 112) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/scutil --get HostName ----
STDOUT:
STDERR: HostName: not set
---- End output of /usr/sbin/scutil --get HostName ----
Ran /usr/sbin/scutil --get HostName returned 1
```

Verifying whether the hostname is set with the same command the code uses:

```
❯ /usr/sbin/scutil --get HostName

HostName: not set

❯ echo $?

1
```

Possible line where code is failing:
https://github.com/chef/chef/blob/master/lib/chef/resource/hostname.rb#L114

## Stacktrace

 N/A

**Comment by rishichawda** [comment] 2021-08-17 16:40
Closing this issue since it doesn't seem to be reproducible with newer chef releases (>=16). @hawksight Please feel free to reopen the issue if the problem persists.

**Closed by rishichawda** 2021-08-17 16:40 UTC
Labels: Priority: Medium, Platform: macOS, Status: Sustaining Backlog, Focus: Resources, Focus: Desktop
