### ISSUE TITLE
Changing policy of node does not trigger update to policy_name and policy_group attributes

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#5344] opened 2016-09-19 17:48 UTC
## Description

After updating a client node's Policy and Policy Group values by editing `/etc/chef/client.rb` on the client node and running `chef-client`, the attributes `policy_name` and `policy_group` do not get updated to match the new values.
## Chef Version

Client version:

```
[hendrenj@nowhere ~]$ chef-client --version
Chef: 12.12.15
```

Server version:

```
[authoritah ~]% sudo yum info chef-server-core
Loaded plugins: package_upload, product-id, rhnplugin, search-disabled-repos, security,
              : subscription-manager   
Installed Packages
Name        : chef-server-core
Arch        : x86_64
Version     : 12.6.0
Release     : 1.el6
Size        : 1.3 G
Repo        : installed
Summary     : The full stack of chef-server
URL         : https://www.chef.io
License     : Apache-2.0
Description : The full stack of chef-server
```
## Platform Version

Chef client:

```
[hendrenj@nowhere ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

Chef Server:

```
[authoritah ~]% cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
```
## Replication Case

I've censored some hostnames in the example below to prevent this information from leaking outside our org.
1. Verify that the current values for `policy_name` and `policy_group` match in `/etc/chef/client.rb` on the client node and in corresponding attributes on the Chef Server:
   
   ```
   [hendrenj@nowhere ~]$ cat /etc/chef/client.rb 
   log_location     STDOUT
   chef_server_url  "https://authoritah.***/organizations/unixops"
   validation_client_name "unixops-validator"
   # Using default node name (fqdn)
   trusted_certs_dir "/etc/chef/trusted_certs"
   
   # Policyfile Settings
   use_policyfile true
   policy_group "production"
   policy_name "cub_policy_vault_server"
   ```
   
   ```
   [jay@birdsnest ~]$ knife node show nowhere.*** -a policy_name
   nowhere.***:
     policy_name: cub_policy_vault_server
   [jay@birdsnest ~]$ knife node show nowhere.*** -a policy_group
   nowhere.***:
     policy_group: production
   [jay@birdsnest ~]$ knife node show nowhere.*** -a run_list
   nowhere.***:
     run_list: recipe[cub_policy_vault_server::default]
   ```
2. Update the values `policy_name` and `policy_group` in `/etc/chef/client.rb` on the client node.  In this example, I'm changing the Policy from `cub_policy_vault_server` to `cub_policy_nowhere.***` and the Policy Group from `production` to `dev`:
   
   ```
   [hendrenj@nowhere ~]$ cat /etc/chef/client.rb 
   log_location     STDOUT
   chef_server_url  "https://authoritah.***/organizations/unixops"
   validation_client_name "unixops-validator"
   # Using default node name (fqdn)
   trusted_certs_dir "/etc/chef/trusted_certs"
   
   # Policyfile Settings
   use_policyfile true
   policy_group "dev"
   policy_name "cub_policy_nowhere.***"
   ```
3. Run Chef.
   
   ```
   [hendrenj@nowhere ~]$ sudo /usr/bin/chef-client
   
   [...snip...]
   
   Chef Client finished, 166/534 resources updated in 07 minutes 12 seconds
   [hendrenj@nowhere ~]$ echo $?
   0
   ```
4. Observe that the node attributes `policy_name` and `policy_group` on Chef Server have not been updated to match the names of the new Policy and Policy Group, though the value of `run_list` has been updated:
   
   ```
   [jay@birdsnest ~]$ knife node show nowhere.*** -a policy_name
   nowhere.***:
     policy_name: cub_policy_vault_server
   [jay@birdsnest ~]$ knife node show nowhere.*** -a policy_group
   nowhere.***:
     policy_group: production
   [jay@birdsnest ~]$ knife node show nowhere.*** -a run_list
   nowhere.***:
     run_list: recipe[cub_policy_nowhere.***::default]
   ```

**Comment by coderanger** [comment] 2016-09-19 21:05
Those aren't attributes, they are node data and are orthogonal to client.rb values overriding them. In general I wouldn't recommend you set those values in your client config, they should live on the server.

Unless @danielsdeleo disagrees I would say this is working as intended.

**Comment by Poohblah** [comment] 2016-09-19 22:50
@coderanger explained to me via Slack why and how I should be setting node policies via node data instead of via client.rb.  IIRC, the node data workflow wasn't supported for Policyfile when we first started experimenting with Policyfiles, which would explain why a client.rb-based workflow stuck around in my org. We working to move our policy declarations to node data with a knife-based workflow instead.

**Comment by danielsdeleo** [comment] 2016-09-19 22:56
Looks like the changes should get copied to the node, though: https://github.com/chef/chef/blob/f2a047d222cd620d66394d092eea5f92c503ac67/lib/chef/policy_builder/policyfile.rb#L343-L369

Regardless of which way of doing things is best, the data on the server should be updated with what chef-client did so searches and stuff work correctly.

**Comment by lamont-granquist** [comment] 2016-10-05 17:16
this should be desired state and covered under https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md

**Comment by tas50** [comment] 2019-09-16 18:05
I'm going to close this out at this point since we don't believe that nodes should be manipulating their own workflows. We'd be willing to accept a PR in the future for this, but it's not something we'll be keeping in our backlog.

**Closed by tas50** 2019-09-16 18:05 UTC
Labels: Priority: Low
