### ISSUE TITLE
Chef cannot install chocolatey packages when passed in array from Artifactory

### ISSUE THREAD

**Issue by poblahblahblah** [chef/chef#6303] opened 2017-08-01 16:59 UTC
## Description

It looks like chef does a `downcase` on chocolatey package names, which means packages like "GoogleChrome" cannot be installed via chef depending on your nuget/chocolatey repo.

## Chef Version

12.19.36

## Platform Version

windows2012r2
windows2016

## Replication Case

Note: We are using JFrog's Artifactory product as a chocolatey repo source which is case sensitive, so this issue is specific to that product. The official chocolatey repository works fine. I can provide private access to this for testing if required.

1. Have an artifactory chocolatey (nuget) repository
2. Upload the `GoogleChrome` choco package to artifactory
3. `chocolatey_package 'GoogleChrome'` in a recipe
4. Run chef-client.

## Client Output

```
       ---- Begin output of C:\ProgramData\chocolatey/bin/choco.exe install -y --version 60.0.3112.78 googlechrome ----
       STDOUT: Chocolatey v0.10.7
       Installing the following packages:
       googlechrome
       By installing you accept licenses for the packages.
       googlechrome not installed. The package was not found with the source(s) listed.
        If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
        Version: "60.0.3112.78"
        Source(s): "https://our-artifactory.jfrog.io/us/api/nuget/chocolatey"

       Chocolatey installed 0/1 packages. 1 packages failed.
        See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

## Stacktrace

N/A

**Comment by dheerajd-msys** [comment] 2017-08-11 13:03
@poblahblahblah Please share private repo access to test, however I am working on to setup my own Artifactory repo.

**Comment by dheerajd-msys** [comment] 2017-08-14 16:50
@poblahblahblah According to https://github.com/chocolatey/choco/wiki/CreatePackages#naming-your-package and https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart#common-mistakes there shouldn't be mixed case in names by `chocolatey naming convention`.

**Comment by poblahblahblah** [comment] 2017-08-14 17:31
@dheerajd-msys understood, although unfortunately this is not enforced even for officially maintained packages:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/googlechrome/googlechrome.nuspec#L5

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/cygwin/cygwin.nuspec#L5

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/winpcap/winpcap.nuspec#L5

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/sourcetree/sourcetree.nuspec#L5

And so on

**Comment by poblahblahblah** [comment] 2017-08-14 17:32
@dheerajd-msys I can give you access, although I would prefer to not share the credentials via github - do you use keybase or twitter?

**Comment by dheerajd-msys** [comment] 2017-08-16 13:47
I setup my own Artifactory Nuget Repo and pushed package

**Comment by dheerajd-msys** [comment] 2017-08-16 13:48
I setup my own Artifactory Nuget Repo and pushed `nuget push C:\Users\Administrator\Downloads\googlechrome.57.0.2987.98.nupkg -Source Artifactory`

**Comment by dheerajd-msys** [comment] 2017-08-17 13:21
@poblahblahblah I tried using `chocolatey_package` with my Artifactory setup and issue hasn't reproduced.

I was getting some checksum issue so added an option in recipe to ignore.

**My recipe content** 
```
chocolatey_package 'GoogleChrome' do
	source  "http://localhost:8081/artifactory/api/nuget/nuget"
	options "--ignore-checksums"
end
```
**Chef Output**
```
PS C:\Users\Administrator> chef-apply C:\chocolatey_recipe.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chocolatey_package[GoogleChrome] action install
    - install version 57.0.2987.98 of package GoogleChrome
PS C:\Users\Administrator>
```
**Chef Version**
12.19.36

**Platform Version**
Windows 2012 R2

**Comment by poblahblahblah** [comment] 2017-08-17 16:14
Hey @dheerajd-msys, I am still able to reproduce this locally, although it looks like I can only get it to fail when:

* We specify a package with a capital letter and a package version
* We pass any package as an array
* We pass packages as an array and versions as an array

Please note that the gist of the successes show that it's able to install the versions that I am requesting.

Failure scenarios (code and failure):
  fails: https://gist.github.com/poblahblahblah/bbeefbd6b2154dc8217aff7c9f63ee33
  fails: https://gist.github.com/poblahblahblah/156118ad33aea0a9e2acf2fa8f577dd7
  fails: https://gist.github.com/poblahblahblah/11428f360e1c69536d8eb374dd3f2e27
  fails: https://gist.github.com/poblahblahblah/e0eb70f761644c274f212b2121e33bae
  fails: https://gist.github.com/poblahblahblah/43e292a012f9f9fbaec4b019508a9b70

Success scenarios (code and success messages):
  succeeds: https://gist.github.com/poblahblahblah/b6ac9e0b87a91d3f6e87014caa7b6278
  succeeds: https://gist.github.com/poblahblahblah/492499ec6b8a90f0bf6a92751cad9e31

Chef Version
12.19.36

Platform Version
Windows 2016

**Comment by dheerajd-msys** [comment] 2017-08-18 13:24
@poblahblahblah I have tested with all your scenarios and it seems when you loop through the code it works as expected.
fails: https://gist.github.com/poblahblahblah/bbeefbd6b2154dc8217aff7c9f63ee33 worked in my case(added comment in gist). 
fails: https://gist.github.com/poblahblahblah/e0eb70f761644c274f212b2121e33bae worked in my case (Please check candidate version)

For other failed scenarios I got issue reproduced.  It seems passing option as an Array is creating issue. We might work onto it to get it fixed.

**Comment by dheerajd-msys** [comment] 2017-08-29 07:47
Issues fixed in PR https://github.com/chef/chef/pull/6360
fails: https://gist.github.com/poblahblahblah/11428f360e1c69536d8eb374dd3f2e27 is not resolvable for now since choco doesn't list the candidate versions for dependent packages like `notepadplusplus` which depends on `notepadplusplus.install` from Artifactory Repo.
```
PS C:\Users\Administrator\chef> choco list -r notepadplusplus telegraf -source http://localhost:8081/artifactory/api/nug
et/nuget
aqnotepadplusplus|6.8.8
Metrics.NET.Telegraf|1.0.0
Telegraf|2.0.1
```

**Closed** 2017-10-17 01:42 UTC
Labels: Area: Windows
