### ISSUE TITLE
knife cookbook install not retrieving correct dependencies

### ISSUE THREAD

**Issue by robnasby** [chef/chef#5411] opened 2016-10-05 12:51 UTC
## Description

Dependency resolution when installing a cookbook using knife can retrieve an incompatible dependency version.  For example, the `postgresql 4.0.6` cookbook in Supermarket lists a dependency of `openssl ~> 4.0`.  However, `knife` installed `openssl 6.0.0`.  Uploading the cookbooks to Chef Server reports a dependency issue.
## Chef Version

chef-client version: 12.14.89
## Platform Version

RedHat Linux 7.2, kernel 3.10.0-327.el7.x86_64
## Replication Case

`$ knife cookbook site install postgresql`
`$ knife cookbook upload --all`
## Client Output

Uploading apt            [4.0.2]
Uploading build-essential [7.0.0]
Uploading compat_resource [12.14.7]
Uploading linux-common-admin-tools [1.0.0]
Uploading mingw          [1.2.4]
Uploading openssl        [6.0.0]
Uploading postgresql     [4.0.6]
**ERROR:** Cookbook postgresql depends on cookbooks which are not currently
**ERROR:** being uploaded and cannot be found on the server.
**ERROR:** The missing cookbook(s) are: 'openssl' version '~> 4.0'
## Stacktrace

N/A

**Comment by coderanger** [comment] 2016-10-05 13:02
I'm pretty sure the `knife cookbook site` commands all just grab the latest version of the dependency and hope that works. They predate having a constraint solver in Chef at all. Not my call, but I would say we should `WONTFIX` this in favor of Berks, Policies, Librarian, Batalli, or any of the many other fully featured downloaders out there.

**Comment by coderanger** [comment] 2016-10-05 13:03
@robnasby For you specifically, definitely don't use `knife cookbook site install` for anything serious anymore. We should probably formally deprecate that but it's definitely laughably outdated and surpassed by other tools in the ecosystem.

**Comment by robnasby** [comment] 2016-10-05 14:13
Thanks for the info @coderanger.  I'm new to Chef, so I haven't yet looked into Berks et. al.  I was following documentation from [learn.chef.io](http://learn.chef.io).

**Comment by lamont-granquist** [comment] 2016-10-06 18:39
yeah, @tpetchel you probably shouldn't be sending people to `knife cookbook site install` for this kind of reason.

this is definitely a wontfix because the solution would be to bolt berks or policyfile to it under the covers, which would be breaking and a ton of work, when people can just use those apis directly.

**Comment by lamont-granquist** [comment] 2016-10-06 18:41
we should probably mark this as deprecated, at the same time it probably works fine for some people who don't want to use berks and i certainly don't feel like dying on that particular hill...

**Comment by lamont-granquist** [comment] 2016-10-06 18:42
leaving this open so that @thommay can take a look at it, but i think this is just operating exactly as designed and more of a learnchef bug...

**Closed** 2018-06-13 17:22 UTC
Labels: Type: Documentation, learnchef
