### ISSUE TITLE
doc bug:  chocolatey_package cannot be shortened to package (unlike apt_package, yum_package, etc)

### ISSUE THREAD

**Issue by spuder** [chef/chef#4870] opened 2016-04-26 23:03 UTC
## Description

If you use the package resource and specify the chocolatey provider, you get an error

Chef 12.9.38 

Windows 2012R2
## Replication Case

``` ruby
package 'pstools' do
  provider Chef::Provider::Package::Chocolatey
  action :install
end
```
## Client Output

```
    ================================================================================
    Error executing action `install` on resource 'windows_package[pstools]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `map' for "pstools":String

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/nd-web/recipes/schedtasks.rb

    169: package 'pstools' do
    170:   provider Chef::Provider::Package::Chocolatey
    171:   action :install
    172: end
    173:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/nd-web/recipes/schedtasks.rb:169:in `from_file'

    windows_package("pstools") do
      package_name "pstools"
      provider Chef::Provider::Package::Chocolatey
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "nd-web"
      recipe_name "schedtasks"
    end

    Platform:
    ---------
    x64-mingw32
```

If you use the following syntaxes, it works fine

``` ruby
chocolatey_package 'pstools' do
  action :install
end
```

However the documentation discourages using 'chocolatey_package' in favor of 'package'

https://docs.chef.io/resource_chocolatey_package.html

**Comment by lamont-granquist** [comment] 2016-04-27 17:19
the `package` provider on windows is wired up to the `windows_package` provider -- which you can see from the output under "Compiled Resource".  that is by design and this will never work.  the copypasta "note" at the top of the docs is 180 degrees incorrect for this provider and instead should have words stating that you MUST use `chocolatey_package` and cannot shorten that.

**Comment by lamont-granquist** [comment] 2016-04-27 17:22
https://docs.chef.io/resource_gem_package.html is also incorrect and `package` can never be used in place of `gem_package` either

**Comment by stuartpreston** [comment] 2018-11-21 13:59
This was fixed long ago, with the wording: "The chocolatey_package resource must be specified as chocolatey_package and cannot be shortened to package in a recipe.".  As such I'm closing this issue.

**Closed by stuartpreston** 2018-11-21 13:59 UTC
Labels: Type: Documentation
