### ISSUE TITLE
journald don't have chef-client logs on some servers

### ISSUE THREAD

**Issue by grdz** [chef/chef#8751] opened 2019-07-18 07:44 UTC
## Description
I am not sure if it is an error with chef-client or some other element, sorry if it does not belong here. I have 2 servers with the same chef-client version 14.5.33, the same chef-client configuration, the same chef-client.service in systemd. Both servers are CentOS 7.6, but on one server chef-client is logging to journald, and on the other not (only logging things like stopping and starting chef-client). The only difference between servers is kernel versions. The one where chef-client is logging to journald is `3.10.0-962.3.2.lve1.5.24.8.el7.x86_64` and the other where it is not is `3.10.0-962.3.2.lve1.5.24.4.el7.x86_64` (both are CloudLinux kernels, it is basically CentOS 7.6). Subtle difference.

My client.rb configuration logs to file (`log_location` set to file, `log_level` set to `:info`), if it changes anything. If this issue does not belong here, please tell me. I just found no information on how to turn on logging to journald in chef-client and assumed that it should log by default, but it does not on some machines. 

## Chef Version
14.5.33

## Platform Version
CentOS 7.6 (CloudLinux 7.6)

## Replication Case
Unfortunately I believe that I could not provide a proper replication instructions. I would bootstrap a node using chef-client cookbook on CentOS 7.6 servers with different kernels for example and check if chef-client will log it's execution logs to journald. If there is any more info that I could provide, please let me know, I just can't locate any differences between servers other than kernel versions.

## Client Output

Server with kernel `3.10.0-962.3.2.lve1.5.24.8.el7.x86_64`, where journald have chef-client logs:

```
[xxx@machine1 ~]# journalctl -u chef-client
-- Logs begin at wto 2019-07-16 10:40:01 CEST, end at śro 2019-07-17 12:22:32 CEST. --
lip 16 16:35:35 machine1.com chef-client[4896]: Starting Chef Client, version 14.5.33
lip 16 16:35:41 machine1.com chef-client[4896]: resolving cookbooks for run list: ["example:test1", "example::test2"]
lip 16 16:35:41 machine1.com chef-client[4896]: Synchronizing Cookbooks:
[...]
```

and the other server, with kernel `3.10.0-962.3.2.lve1.5.24.4.el7.x86_64` (only logging things like stopping and starting chef-client, no sign of chef-client execution logs):

```
xxx@machine2 ~ # journalctl -u chef-client
-- Logs begin at wto 2019-07-16 06:10:32 CEST, end at czw 2019-07-18 09:33:04 CEST. --
lip 18 07:57:16 machine2.com systemd[1]: Started Chef Client daemon.
xxx@machine2 ~ #
```

## Stacktrace
There is no stacktrace

**Comment by lamont-granquist** [comment] 2019-07-24 17:41
nope, i wouldn't even know what to ask.  since its the same chef-client version in both cases, it looks like not a bug and some kind of config issue, most likely some kind of config on the system itself, which is well out of scope with my expertise these days.

this looks like a better question for stackoverflow or something.

**Closed by lamont-granquist** 2019-07-24 17:41 UTC
Labels: Status: Untriaged
