### ISSUE TITLE
malformed notification target strings should trigger a parse error

### ISSUE THREAD

**Issue by diegows** [chef/chef#5015] opened 2016-06-09 22:26 UTC
## Description

I had this in a service definition and was failing. Thanks to someone in IRC, the problem was a missing "]" at the end of the target. This should trigger a parse error I think.

`subscribes :restart, "template[#{node[:tango][:settings]}", :delayed`
## Chef Version

chef-client 12.7.2
## Platform Version

RHEL7

**Comment by coderanger** [comment] 2016-06-09 22:35
I could have sworn this used to error on bad strings, but maybe I just imagined that?

**Comment by thommay** [comment] 2016-06-15 17:12
confirmed
```
18:11 ~ % chef exec chef-apply foo.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * file[/tmp/foo] action create
    - create new file /tmp/foo
chef exec chef-apply foo.rb  3.50s user 3.85s system 97% cpu 7.540 total
18:11 ~ % cat foo.rb
file "/tmp/foo" do
  subscribes :restart, "template[foo"
end
```

**Comment by smurawski** [comment] 2016-06-15 17:15
I just tested against 12.11.18 and did get a proper error

```
 ================================================================================
       Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/test/recipes/default.rb
       ================================================================================
       
       Chef::Exceptions::InvalidResourceSpecification
       ----------------------------------------------
       The string `reboot[Buwahahahaha' is not valid for resource collection lookup. Correct syntax is `resource_type[resource_name]'
       
```

**Comment by tas50** [comment] 2019-08-12 17:33
Closing this out since it looks like we fixed this up based on @smurawski's comment. If someone runs into this again please open up a new issue.

**Closed by tas50** 2019-08-12 17:33 UTC
