### ISSUE TITLE
slow performance in yum_package provider in 12.7.x through 12.9.x

### ISSUE THREAD

**Issue by downneck** [chef/chef#4691] opened 2016-03-10 19:22 UTC
## Description

* running chef-solo from the chef11 gem completes in roughly 14 seconds
* running chef-solo from the chef12 gem completes in over 2 minutes

## Chef Version

11.8.2 -> 12.8.1

## Platform Version

CentOS release 6.7 (Final)

## Replication Case

run the exact same recipes on the exact same hardware under both versions. 

behind the scenes, i noticed that yum-dump.py was running a LOT more under chef12. it appears to run on every single package idempotency check.

## Client Output

https://gist.github.com/downneck/d019bfa4e9cccc65f7ad

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

**Comment by lamont-granquist** [comment] 2016-03-10 21:51
Unless you've got more productive info I'm going to close this as a dup of #4122

**Comment by toadstule** [comment] 2016-03-18 20:32
I am seeing the same problem.  I don't know if it is related to #4122.
It seems that verifying installed packages (yum packages) performs much worse than it used to.  I assume it has something to do with effective use of caching yum information.  Anyway, I saw this problem in chef 12.7.x and when I downgraded to chef 12.6.0 and the problem went away.

**Comment by lamont-granquist** [comment] 2016-04-13 17:14
So #4122 has been around with the multipackage stuff and is 12.1.x/12.2.x era ish stuff.  So the yum package perf issue can't be that.  

Unfortunately, I suspect that we fixed a bug by resetting the yum cache every time.  Which renders the yum cache useless.  But it was always causing a bug because we were never updating it correctly and we just started flushing it because it was causing bugs.  Which creates a performance issue because yum is exceedingly slow from the command line.

#4122 probably makes this whole thing worse, but the perf degradation from 12.6.0 to 12.7.x in the yum provider, particularly on first-install when it does work is likely something that we're stuck with.  The second-run perf could be made a lot better by fixing #4122, and then calling `rpm -qa` (which is fast) as an idempotency check to populate the current_resource.version stuff instead of calling yum.

I really suspect that the yumcache has been rendered useless because it was always buggy and we should probably just rip it out now as well.

@thommay had an idea to take the c-library for rpm and create some ruby ffi bindings to it and use /that/ instead of calling the yum command line.  We could ship that in the omnibus packages and ship it on centos5 and get pretty good speed and coverage that way.

DNF will hopefully be better...

**Comment by thommay** [comment] 2016-04-13 17:17
https://fedoraproject.org/wiki/Features/Hawkey is the thing i mentioned, ftr.

**Comment by wfindley** [comment] 2016-04-26 22:24
Take a look at this.  I tried upgrading chef-client from 12.5.1 to 12.9.38.  Yum_package made my chef runs take about %600 longer.  I downgraded to 12.6.0 and now they don't suck anymore.

[https://gist.githubusercontent.com/wfindley/4e2469fe815c162030f2f99f8738365c/raw/052b5b4f4c497708246a429764432e16478e6fe3/chef_client.elapsed_time.png](url)

**Comment by lamont-granquist** [comment] 2016-05-04 21:54
On 12.6.0 with CentOS 7.1 I get this for a simple timing test with idempotent packages:

```
# ./apply.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[strace] action install (up to date)
  * yum_package[lsof] action install (up to date)
  * yum_package[tcpdump] action install (up to date)
  * yum_package[git] action install (up to date)
  * yum_package[dmidecode] action install (up to date)
  * yum_package[ltrace] action install (up to date)
  * yum_package[bc] action install (up to date)
  * yum_package[zsh] action install (up to date)
  * yum_package[vim-minimal] action install (up to date)
  * yum_package[systemtap] action install (up to date)
  * yum_package[telnet] action install (up to date)
  * yum_package[mtr] action install (up to date)
  * yum_package[subversion] action install (up to date)
  * yum_package[nmap] action install (up to date)
  * yum_package[gdb] action install (up to date)
  * yum_package[iptraf-ng] action install (up to date)
  * yum_package[tmux] action install (up to date)
  * yum_package[zlib-devel] action install (up to date)
  * yum_package[wget] action install (up to date)
  * yum_package[postfix] action install (up to date)
  * yum_package[sysstat] action install (up to date)
  0.290000   0.020000   0.840000 (  0.878679)
```

with 12.9.38 i get nearly identical results:

```ruby
# ./apply.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[strace] action install (up to date)
  * yum_package[lsof] action install (up to date)
  * yum_package[tcpdump] action install (up to date)
  * yum_package[git] action install (up to date)
  * yum_package[dmidecode] action install (up to date)
  * yum_package[ltrace] action install (up to date)
  * yum_package[bc] action install (up to date)
  * yum_package[zsh] action install (up to date)
  * yum_package[vim-minimal] action install (up to date)
  * yum_package[systemtap] action install (up to date)
  * yum_package[telnet] action install (up to date)
  * yum_package[mtr] action install (up to date)
  * yum_package[subversion] action install (up to date)
  * yum_package[nmap] action install (up to date)
  * yum_package[gdb] action install (up to date)
  * yum_package[iptraf-ng] action install (up to date)
  * yum_package[tmux] action install (up to date)
  * yum_package[zlib-devel] action install (up to date)
  * yum_package[wget] action install (up to date)
  * yum_package[postfix] action install (up to date)
  * yum_package[sysstat] action install (up to date)
  0.280000   0.010000   0.820000 (  0.858275)
```

on 11.18.12 it is slightly slower:

```
# ./apply.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * package[strace] action install (up to date)
  * package[lsof] action install (up to date)
  * package[tcpdump] action install (up to date)
  * package[git] action install (up to date)
  * package[dmidecode] action install (up to date)
  * package[ltrace] action install (up to date)
  * package[bc] action install (up to date)
  * package[zsh] action install (up to date)
  * package[vim-minimal] action install (up to date)
  * package[systemtap] action install (up to date)
  * package[telnet] action install (up to date)
  * package[mtr] action install (up to date)
  * package[subversion] action install (up to date)
  * package[nmap] action install (up to date)
  * package[gdb] action install (up to date)
  * package[iptraf-ng] action install (up to date)
  * package[tmux] action install (up to date)
  * package[zlib-devel] action install (up to date)
  * package[wget] action install (up to date)
  * package[postfix] action install (up to date)
  * package[sysstat] action install (up to date)
  0.320000   0.010000   0.850000 (  0.881880)
```

looking at the count of times that yum-dump.py runs:

11.18.12:  1
12.6.0: 1
12.9.38: 1

I'm somewhat confused now as to what the bug is...

**Comment by lamont-granquist** [comment] 2016-05-04 22:18
And I certainly can't guess from the code what is going on.

Could use a Minimal, Complete, and Verifiable Example for this:

http://stackoverflow.com/help/mcve

**Comment by lamont-granquist** [comment] 2016-05-04 22:26
What I see on 12.9.38 in debug mode:

```
  * yum_package[sysstat] action install[2016-05-04T22:21:17+00:00] INFO: Processing yum_package[sysstat] action install ((chef-apply cookbook)::(chef-apply recipe) line 4)
[2016-05-04T22:21:17+00:00] DEBUG: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2016-05-04T22:21:17+00:00] DEBUG: Provider for action install on resource yum_package[sysstat] is Chef::Provider::Package::Yum
[2016-05-04T22:21:17+00:00] DEBUG: yum_package[sysstat] checking yum info for sysstat
[2016-05-04T22:21:17+00:00] DEBUG: yum_package[sysstat] installed version: ["10.1.5-7.el7"] candidate version: 10.1.5-7.el7
[2016-05-04T22:21:17+00:00] DEBUG: yum_package[sysstat] sysstat 10.1.5-7.el7 already installed
[2016-05-04T22:21:17+00:00] DEBUG: yum_package[sysstat] is already installed - nothing to do
 (up to date)
```

what I see in master (12.10.32) in debug mode:

```
  * yum_package[sysstat] action install[2016-05-04T22:24:40+00:00] INFO: Processing yum_package[sysstat] action install ((chef-apply cookbook)::(chef-apply recipe) line 4)
[2016-05-04T22:24:40+00:00] DEBUG: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2016-05-04T22:24:40+00:00] DEBUG: Provider for action install on resource yum_package[sysstat] is Chef::Provider::Package::Yum
[2016-05-04T22:24:40+00:00] DEBUG: yum_package[sysstat] checking yum info for sysstat
[2016-05-04T22:24:40+00:00] DEBUG: yum_package[sysstat] installed version: ["10.1.5-7.el7"] candidate version: 10.1.5-7.el7
[2016-05-04T22:24:40+00:00] DEBUG: yum_package[sysstat] sysstat 10.1.5-7.el7 already installed
[2016-05-04T22:24:40+00:00] DEBUG: yum_package[sysstat] is already installed - nothing to do
 (up to date)
```

so it looks like the yum provider does not benefit at all from #4869, so this is unlikely to have been fixed by that.

**Comment by wfindley** [comment] 2016-05-19 13:26
Almost our entire fleet is on centos 6.  Did you test on centos 6?

**Comment by jaymzh** [comment] 2016-08-26 20:11
@lamont-granquist we just started an upgrade to 12.13 from 12.6 and are seeing MASSIVE problems. 25seconds per unchanged yum_package rule. And it looks like yum-dump is running a bunch.

**Comment by jaymzh** [comment] 2016-08-26 20:17
I'm not seeing it consistently though. Only in some places. Somethign is very weird though.

**Comment by jaymzh** [comment] 2016-08-26 20:20
In particular on affected hosts we see each yum_package take ~ 26 seconds... with no work to do. This is crazysauce.

**Comment by jaymzh** [comment] 2016-08-26 20:28
we have some debug logs and straces of multiple yum-dump calls, fwiw.

**Comment by jaymzh** [comment] 2016-08-26 20:32
Here's some fun stuff:

```
[pid 1542886] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1544355] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1545270] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1546104] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1546959] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1547974] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1548774] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1549458] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1550322] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1551066] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1551906] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1552553] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1553618] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1554459] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1555332] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1556344] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1557023] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1557879] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1558908] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1559705] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1560501] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1561181] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1562092] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */]strace: Exit of unknown pid 1562094 seen
[pid 1562940] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1563757] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1564608] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1565238] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */]strace: Exit of unknown pid 1565242 seen
[pid 1566182] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1567050] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1567820] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1568680] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1569339] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1570199] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1571161] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1572052] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1573044] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1573846] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1574577] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
[pid 1575544] execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 28 vars */] <unfinished ...>
```

**Comment by lamont-granquist** [comment] 2016-08-26 20:37
heh, yep, i think i told you about this one at chefconf...

**Comment by jaymzh** [comment] 2016-08-26 20:48
And on the same version, but on a CentOS7 box:

```
[phild@dev8344 ~]$ grep execve /tmp/strace | grep yum-dump
2000961 execve("/usr/bin/python", ["/usr/bin/python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 61 vars */] <unfinished ...>
[phild@dev8344 ~]$ 
```

**Comment by jaymzh** [comment] 2016-08-26 20:55
But here's another box with 12.13 that is CentOS6 and doesn't trigger the problem:

```
# grep execve /tmp/strace | grep yum-dump
450844 execve("/usr/bin/env", ["/usr/bin/env", "python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 39 vars */] <unfinished ...>
450844 execve("/opt/local/libexec/gnubin/python", ["python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 39 vars */]) = -1 ENOENT (No such file or directory)
450844 execve("/usr/local/sbin/python", ["python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 39 vars */]) = -1 ENOENT (No such file or directory)
450844 execve("/usr/local/bin/python", ["python", "/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider/package/yum/yum-dump.py", "--options", "--installed-provides", "--yum-lock-timeout", "30"], [/* 39 vars */]) = 0
```

**Comment by jaymzh** [comment] 2016-08-26 21:07
This is very odd. Even on a 'remove' it takes 15 seconds (when the package isn't there)

**Comment by lamont-granquist** [comment] 2016-08-26 21:14
can you binary search and find the version that caused the regression?

**Comment by jaymzh** [comment] 2016-08-26 21:23
that's my next approach, but right now I'm doing some good old printf-debugging.

```
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
PHILD: someone called flush_cache
```

**Comment by lamont-granquist** [comment] 2016-08-26 21:24
that's what i expected to see -- `puts caller` to see who is doing it?

**Comment by jaymzh** [comment] 2016-08-26 21:32
that function is a lie - it's just `load_current_resource` CHECKING.

```
PHILD: yum_package[fb-**********] flushing cache before
PHILD: yum_package[fb-**********] flushing cache before
PHILD: yum_package[fb-*********] flushing cache before
```

So maybe the resource's lambda? still digging.

**Comment by lamont-granquist** [comment] 2016-08-26 21:39
is something poking the flush_cache method as part of some sort of introspection of resources / properties and that is causing it to actually flush the cache?

maybe we property-ized that?

**Comment by jaymzh** [comment] 2016-08-26 21:42
Even on a fleet of identical boxes all centos6, it only affects 1-in-5. this is a super weird bug.

**Comment by jaymzh** [comment] 2016-08-26 21:45
It seems to be this case:

```
        elsif v.any?
          puts "PHILD: not an array but we any? it??"# #{flush_cache}"
          v
```

Which I don't understand, because that's an `elsif` of `if v.is_a?(Array)` - so what does `any?` do on a non-array?

**Comment by jaymzh** [comment] 2016-08-26 21:45
Oh. Ignore that... it's a hash.

**Comment by jaymzh** [comment] 2016-08-26 21:48
The resource is seeing flush_cache set:

```
PHILD: v is {:before=>true, :after=>false}
PHILD: not an array but we any? it??
PHILD: yum_package[fb-XXXXXXX] flushing cache before
PHILD: v is {:before=>true, :after=>false}
PHILD: not an array but we any? it??
PHILD: yum_package[fb-XXXXXXX] flushing cache before
PHILD: v is {:before=>true, :after=>false}
PHILD: not an array but we any? it??
PHILD: yum_package[fb-XXXXXX] flushing cache before
```

**Comment by jaymzh** [comment] 2016-08-26 21:51
@lamont-granquist 

Uh. If I try to print `flush_cache` there I get StackTooDeep ceptions, but yet it's being called. I'm very confused, should that be some temp variable?

**Comment by lamont-granquist** [comment] 2016-08-26 21:52
so 12.7.2 shipped this:

https://github.com/chef/chef/commit/b743fcdbd172862386d172b42bbbc31cfe2f4239

can you try 12.7.2 with that commit reverted and see if it fixes it?

**Comment by jaymzh** [comment] 2016-08-26 21:57
OK so I have a "fix" though I don't fully understand what the code was trying to do in the first place so I'm not 100% sure it's right:

```
--- /root/yum-orig.rb	2016-08-26 14:56:35.000000000 -0700
+++ resource/yum_package.rb	2016-08-26 14:57:03.000000000 -0700
@@ -30,13 +30,15 @@
       property :flush_cache, Hash, default: { before: false, after: false }, coerce: proc { |v|
         # TODO these append rather than set. This is probably wrong behavior, but we're preserving it until we know
         if v.is_a?(Array)
-          v.each { |arg| flush_cache[arg] = true }
-          flush_cache
+          x = {}
+          v.each { |arg| x[arg] = true }
+          x
         elsif v.any?
           v
         else
           # TODO calling flush_cache({}) does a get instead of a set. This is probably wrong behavior, but we're preserving it until we know
-          flush_cache
+          #flush_cache
+          x
         end
       }
       property :allow_downgrade, [ true, false ], default: false
```

**Comment by jaymzh** [comment] 2016-08-26 21:58
note that the `else` there is never getting called...

**Comment by jaymzh** [comment] 2016-08-26 22:00
OK so fixing the `else` too, my diff is:

```
--- /root/yum-orig.rb	2016-08-26 14:56:35.000000000 -0700
+++ resource/yum_package.rb	2016-08-26 14:58:51.000000000 -0700
@@ -30,13 +30,15 @@
       property :flush_cache, Hash, default: { before: false, after: false }, coerce: proc { |v|
         # TODO these append rather than set. This is probably wrong behavior, but we're preserving it until we know
         if v.is_a?(Array)
-          v.each { |arg| flush_cache[arg] = true }
-          flush_cache
+          x = {}
+          v.each { |arg| x[arg] = true }
+          x
         elsif v.any?
           v
         else
           # TODO calling flush_cache({}) does a get instead of a set. This is probably wrong behavior, but we're preserving it until we know
-          flush_cache
+          #flush_cache
+          { before: v, after: v}
         end
       }
       property :allow_downgrade, [ true, false ], default: false
```

**Comment by jaymzh** [comment] 2016-08-26 22:01
the weird recursive call in there seems odd to me. Leftover from when it was a function. This seems more correct, but I still don't understand what it was trying to do before. @lamont-granquist  thoughts?

**Comment by jaymzh** [comment] 2016-08-26 22:06
through you a PR.

**Comment by jaymzh** [comment] 2016-08-26 22:18
I should note here I don't understand the problem fully. It only happens on some boxes ... it's fucking weird. But that code seems wrong to me, and this seems write to me and it fixes the bug and passes the tests. Calling @lamont-granquist  for opinions (I know you have them!!)

**Comment by jaymzh** [comment] 2016-08-26 23:28
OK this seems to work....
```
  Chef::Log.info('Monkey-patching yum_package resource')
  opts = Chef::Resource::YumPackage.properties[:flush_cache].options
  opts[:coerce] = proc { |v|
          if v.is_a?(Array)
            v.each_with_object({}) { |arg, obj| obj[arg] = true }
          elsif v.any?
            v
          else
            { before: v, after: v}
          end
          }
  Chef::Resource::YumPackage.property(:flush_cache, opts)
```

If I specify a type, the validator becomes `... is => [Hash, Hash]` which is weird.

**Comment by jaymzh** [comment] 2016-08-27 00:27
OK, for everyone else... so in this case the problem is that if you ever use `flush_cache` on a yum_package you basically end up fucking the rest of your run over. The attached PR fixes it.

**Closed** 2016-08-27 10:00 UTC
Labels: High Priority

**Comment by lamont-granquist** [comment] 2017-04-11 15:20
For future reference, this was due to mutation of the default value.  Setting the flush_cache property mutated the default and caused all future yum providers to flush the cache.

This is the "reference bug" for why we freeze property defaults in Chef-13:  #6003

Freezing of defaults also turned up bugs in other cookbooks as well (e.g. tomcat)
