### ISSUE TITLE
cron resource mailto property should support setting an empty string

### ISSUE THREAD

**Issue by griffint61** [chef/chef#4900] opened 2016-05-05 22:44 UTC
## Description

If you don't specify a mailto setting for a cron resource, it inherits whatever MAILTO setting is previously defined in the crontab file, which could be for something completely unrelated.

## Chef Version

12.4.1

## Platform Version

CentOS 6.7

## Replication Case

Use the cron resource twice. In the first case explicitly set the mailto option. In the second case don't set the mailto option at all. In both cases use commands that generate some output.

When the first cron job fires, email will be sent to the specified address, as expected.

When the second cron job fires, mail will be sent to the address specified for the first cron resource, instead of having no mail sent at all, which is likely what was intended.

Note also that you can't workaround this problem by passing an empty string as the mailto setting for second cron resource. According to the crontab(5) man page on CentOS 6, An empty string is a valid MAILTO setting, but the cron resource bombs out when passed an empty mailto string.

## Client Output

N/A

## Stacktrace

N/A

**Comment by lamont-granquist** [comment] 2016-05-06 16:06
Doing this globally to everyone's crontabs would most likely be a breaking change.

The bug where you can't pass empty string to the cron resource is certainly a bug.

**Comment by pwalz** [comment] 2016-07-20 14:53
I'd also like to see this one fixed. It looks like it was fixed in #311, but the PR never got merged due to a lack of regression tests.

For the moment, I've worked around the issue by adding shell output redirection (` >/dev/null 2>&1`) to the `command` property of my cron resource.

**Closed** 2016-08-02 08:08 UTC
Labels: Bug, Chef Core, Medium Priority

**Comment by mconigliaro** [comment] 2016-09-27 18:28
I think this is just how cron works (i.e. setting `MAILTO` causes every subsequent job to inherit that setting). This would be fine except for the fact that Chef does not necessarily write the crontab in the order in which jobs are defined (i.e. new jobs are always just appended to the end of the crontab). This means even if you only want to set `mailto` for a single job, you end up having to explicitly set it back to the default on every other job to ensure that mail gets delivered to the correct recipient.
