### ISSUE TITLE
locale resource is executed over and over on ubuntu 18.04

### ISSUE THREAD

**Issue by nicutor** [chef/chef#9983] opened 2020-06-11 11:37 UTC
Hi,

This resource is executed each time on ubuntu 18.04.

## Description
```
  * locale[set_locale] action update
    * execute[localectl set-locale LANG=en_US.UTF-8] action run
      - execute localectl set-locale LANG=en_US.UTF-8
```

## Chef Version
Chef Client: 16.1.16

## Platform Version
Ubuntu 18.04

**Comment by antima-gupta** [comment] 2020-10-13 12:51
@nicutor I am not able to reproduce this issue. Could you please provide me more information to reproduce this issue?

#### I followed below steps to reproduce this issue:

### Platform:
`Ubuntu 18.04`

### Chef Infra Client version:
 `16.5.77`

### Recipe:
```
locale 'set locale' do
  lang 'en_IN.utf8'
  action :update
end
```

### Command: 
`chef-client --local-mode --override-runlist chef_resources`


### Output:

### First time run:
```
[2020-10-13T18:01:18+05:30] INFO: Started Chef Infra Zero at chefzero://localhost:1 with repository at /home/antima/workdir (One version per cookbook)
Starting Chef Infra Client, version 16.5.77
Patents: https://www.chef.io/patents
[2020-10-13T18:01:18+05:30] INFO: *** Chef Infra Client 16.5.77 ***
[2020-10-13T18:01:18+05:30] INFO: Platform: x86_64-linux
[2020-10-13T18:01:18+05:30] INFO: Chef-client pid: 33647
[2020-10-13T18:01:32+05:30] WARN: Run List override has been provided.
[2020-10-13T18:01:32+05:30] WARN: Original Run List: []
[2020-10-13T18:01:32+05:30] WARN: Overridden Run List: [recipe[chef_resources]]
[2020-10-13T18:01:32+05:30] INFO: Run List is [recipe[chef_resources]]
[2020-10-13T18:01:32+05:30] INFO: Run List expands to [chef_resources]
[2020-10-13T18:01:32+05:30] INFO: Starting Chef Infra Client Run for antimagupta
[2020-10-13T18:01:32+05:30] INFO: Running start handlers
[2020-10-13T18:01:32+05:30] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef_resources"]
[2020-10-13T18:01:33+05:30] INFO: Loading cookbooks [chef_resources@0.1.0]
[2020-10-13T18:01:33+05:30] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
[2020-10-13T18:01:33+05:30] INFO: Storing updated cookbooks/chef_resources/recipes/default.rb in the cache.
  - chef_resources (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: chef_resources::default
  * locale[set locale] action update[2020-10-13T18:01:33+05:30] INFO: Processing locale[set locale] action update (chef_resources::default line 6)

    * file[Updating system locale] action create[2020-10-13T18:01:44+05:30] INFO: Processing file[Updating system locale] action create (/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/resource/locale.rb line 153)
[2020-10-13T18:01:45+05:30] INFO: file[Updating system locale] created file /etc/locale.conf

      - create new file /etc/locale.conf[2020-10-13T18:01:45+05:30] INFO: file[Updating system locale] updated file contents /etc/locale.conf

      - update content in file /etc/locale.conf from none to 9b09c7
      --- /etc/locale.conf	2020-10-13 18:01:44.997170106 +0530
      +++ /etc/.chef-locale20201013-33647-zhdvje.conf	2020-10-13 18:01:44.997170106 +0530
      @@ -1 +1,2 @@
      +LANG=en_IN.utf8
    - update set locale
    -   set lang to "en_IN.utf8" (was nil)
[2020-10-13T18:01:45+05:30] WARN: Skipping final node save because override_runlist was given
[2020-10-13T18:01:45+05:30] INFO: Chef Infra Client Run complete in 12.787319684 seconds
[2020-10-13T18:01:45+05:30] INFO: Skipping removal of unused files from the cache

Running handlers:
[2020-10-13T18:01:45+05:30] INFO: Running report handlers
Running handlers complete
[2020-10-13T18:01:45+05:30] INFO: Report handlers complete
Chef Infra Client finished, 2/2 resources updated in 26 seconds
```
### Second time run:
```
[2020-10-13T18:01:49+05:30] INFO: Started Chef Infra Zero at chefzero://localhost:1 with repository at /home/antima/workdir (One version per cookbook)
Starting Chef Infra Client, version 16.5.77
Patents: https://www.chef.io/patents
[2020-10-13T18:01:49+05:30] INFO: *** Chef Infra Client 16.5.77 ***
[2020-10-13T18:01:49+05:30] INFO: Platform: x86_64-linux
[2020-10-13T18:01:49+05:30] INFO: Chef-client pid: 34099
[2020-10-13T18:01:56+05:30] WARN: Run List override has been provided.
[2020-10-13T18:01:56+05:30] WARN: Original Run List: []
[2020-10-13T18:01:56+05:30] WARN: Overridden Run List: [recipe[chef_resources]]
[2020-10-13T18:01:56+05:30] INFO: Run List is [recipe[chef_resources]]
[2020-10-13T18:01:56+05:30] INFO: Run List expands to [chef_resources]
[2020-10-13T18:01:56+05:30] INFO: Starting Chef Infra Client Run for antimagupta
[2020-10-13T18:01:56+05:30] INFO: Running start handlers
[2020-10-13T18:01:56+05:30] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef_resources"]
[2020-10-13T18:01:56+05:30] INFO: Loading cookbooks [chef_resources@0.1.0]
[2020-10-13T18:01:56+05:30] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - chef_resources (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: chef_resources::default
  * locale[set locale] action update[2020-10-13T18:01:56+05:30] INFO: Processing locale[set locale] action update (chef_resources::default line 6)
 (up to date)
[2020-10-13T18:02:07+05:30] WARN: Skipping final node save because override_runlist was given
[2020-10-13T18:02:07+05:30] INFO: Chef Infra Client Run complete in 11.235269549 seconds
[2020-10-13T18:02:07+05:30] INFO: Skipping removal of unused files from the cache

Running handlers:
[2020-10-13T18:02:07+05:30] INFO: Running report handlers
Running handlers complete
[2020-10-13T18:02:07+05:30] INFO: Report handlers complete
Chef Infra Client finished, 0/1 resources updated in 17 seconds
```


###  Also tried by using Test kitchen and  Chef Infra Client version `16.1.16`:

### Command: 
` kitchen converge`

### Output:

### First time run:
```
-----> Starting Test Kitchen (v2.7.2)
-----> Creating <default-ubuntu-1804>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-18.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-18.04' version '202008.16.0' is up to date...
       ==> default: Setting the name of the VM: kitchen-chef_resources-default-ubuntu-1804-00a07f33-91f4-4738-862c-cea18feea399
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection reset. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Connection reset. Retrying...
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
           default: The guest additions on this VM do not match the installed version of
           default: VirtualBox! In most cases this is fine, but in rare cases it can
           default: prevent things such as shared folders from working properly. If you see
           default: shared folder errors, please make sure the guest additions within the
           default: virtual machine match the version of VirtualBox you have installed on
           default: your host and reload your VM.
           default: 
           default: Guest Additions Version: 6.1.12
           default: VirtualBox Version: 5.2
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /home/antima/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1804> created.
       Finished creating <default-ubuntu-1804> (1m52.59s).
-----> Converging <default-ubuntu-1804>...
       Preparing files for transfer
       Installing cookbooks for Policyfile /home/antima/workdir/cookbooks/chef_resources/Policyfile.rb using `chef install`
       Installing cookbooks from lock
       Installing chef_resources 0.1.0
       Preparing dna.json
       Exporting cookbook dependencies from Policyfile /tmp/default-ubuntu-1804-sandbox-20201013-30572-ze8bki...
       Exported policy 'chef_resources' to /tmp/default-ubuntu-1804-sandbox-20201013-30572-ze8bki
       
       To converge this system with the exported policy, run:
         cd /tmp/default-ubuntu-1804-sandbox-20201013-30572-ze8bki
         chef-client -z
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       ubuntu 18.04 x86_64
       Getting information for chef stable 16.1.16 for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=16.1.16&p=ubuntu&pv=18.04&m=x86_64
         to file /tmp/kitchen/metadata.txt
       trying wget...
       sha1	1466b9dbfcce80987e145d58e12c076216f9a5b5
       sha256	f1f1cc5787bb56d5d3cb37339bb458f8d715e0be9a58abaad7e52ade90a2bfec
       url	https://packages.chef.io/files/stable/chef/16.1.16/ubuntu/18.04/chef_16.1.16-1_amd64.deb
       version	16.1.16
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef_16.1.16-1_amd64.deb exists
       Comparing checksum with sha256sum...
       Installing chef 16.1.16
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 41459 files and directories currently installed.)
       Preparing to unpack .../cache/chef_16.1.16-1_amd64.deb ...
       Unpacking chef (16.1.16-1) ...
       Setting up chef (16.1.16-1) ...
       Thank you for installing Chef Infra Client! For help getting started visit https://learn.chef.io
       Transferring files to <default-ubuntu-1804>
       +---------------------------------------------+
       ✔ 2 product licenses accepted.
       +---------------------------------------------+
       Starting Chef Infra Client, version 16.1.16
       Creating a new client identity for default-ubuntu-1804 using the validator key.
       Using policy 'chef_resources' at revision '4669600478e0472702a8fe50fab6b8d135a43571941664a9343196474e8e211f'
       resolving cookbooks for run list: ["chef_resources::default@0.1.0 (3048908)"]
       Synchronizing Cookbooks:
         - chef_resources (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_resources::default
         * locale[set locale] action update
           * file[Updating system locale] action create
             - create new file /etc/locale.conf
             - update content in file /etc/locale.conf from none to 9b09c7
             --- /etc/locale.conf	2020-10-13 12:28:41.113422878 +0000
             +++ /etc/.chef-locale20201013-1747-8r8syu.conf	2020-10-13 12:28:41.113422878 +0000
             @@ -1 +1,2 @@
             +LANG=en_IN.utf8
           - update set locale
           -   set lang to "en_IN.utf8" (was nil)
       
       Running handlers:
       Running handlers complete
       Chef Infra Client finished, 2/2 resources updated in 17 seconds
       Downloading files from <default-ubuntu-1804>
       Finished converging <default-ubuntu-1804> (0m50.11s).
-----> Test Kitchen is finished. (2m43.94s)
```
### Second time run:
```
-----> Starting Test Kitchen (v2.7.2)
-----> Converging <default-ubuntu-1804>...
       Preparing files for transfer
       Installing cookbooks for Policyfile /home/antima/workdir/cookbooks/chef_resources/Policyfile.rb using `chef install`
       Installing cookbooks from lock
       Installing chef_resources 0.1.0
       Preparing dna.json
       Exporting cookbook dependencies from Policyfile /tmp/default-ubuntu-1804-sandbox-20201013-33500-s6o6ew...
       Exported policy 'chef_resources' to /tmp/default-ubuntu-1804-sandbox-20201013-33500-s6o6ew
       
       To converge this system with the exported policy, run:
         cd /tmp/default-ubuntu-1804-sandbox-20201013-33500-s6o6ew
         chef-client -z
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       chef installation detected
       install_strategy set to 'once'
       Nothing to install
       Transferring files to <default-ubuntu-1804>
       Starting Chef Infra Client, version 16.1.16
       Using policy 'chef_resources' at revision '4669600478e0472702a8fe50fab6b8d135a43571941664a9343196474e8e211f'
       resolving cookbooks for run list: ["chef_resources::default@0.1.0 (3048908)"]
       Synchronizing Cookbooks:
         - chef_resources (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_resources::default
         * locale[set locale] action update (up to date)
       
       Running handlers:
       Running handlers complete
       Chef Infra Client finished, 0/1 resources updated in 17 seconds
       Downloading files from <default-ubuntu-1804>
       Finished converging <default-ubuntu-1804> (0m24.48s).
-----> Test Kitchen is finished. (0m26.91s)
```

**Comment by antima-gupta** [comment] 2020-10-21 12:35
@nicutor Can you please get back to me on this?

**Comment by antima-gupta** [comment] 2020-11-02 14:23
@nicutor Closing this issue since we are unable to reproduce. Could you please check with latest chef and let me know if you still facing the same.

**Closed by antima-gupta** 2020-11-02 14:23 UTC
Labels: Platform: Debian-like, Priority: Medium, Type: Bug

**Comment by nicutor** [comment] 2020-11-02 18:01
@antima-gupta thank you.

As soon I will be able to spend some time to re-test this, I will let you know if works or not.

**Comment by Tab10id** [comment] 2021-03-02 13:23
Problem coused by be1191b72d72887713048538e72a11b3940c6eb8. In this commit is a bug in load_current_value method. Loaded only lang property, lc_env property was ignored.
So bug is apear only if lc_env property was given.
It's not a so minor bug, locale update can cause errors on running server. E.g we received errors in postgresql for several seconds while chef run.
