### ISSUE TITLE
var in csh not work correctly - reopen

### ISSUE THREAD

**Issue by ensean** [chef/chef#3747] opened 2015-08-03 10:00 UTC
cookbook

remote_file '/tmp/stopDB2.sh' do
  source node['chefparam']['script_url']
  owner  'root'
  group  'system'
  mode '755'
  action :create
end

csh 'call shell' do
  \code <<-EOH
    LOGFILE=chef-ops-`date +"%Y-%m-%dT%H:%M:%S"`.log
    #/tmp/stopDB2.sh #{node['chefparam']['script_opts']}>> /tmp/chef-ops.log
    /tmp/stopDB2.sh -l $LOGFILE #{node['chefparam']['script_opts']}
    EOH
end
~
~
When running, it seems that the $LOGFILE var can not work correctly, is this work as design?

A-EAST-DBB     Compiled Resource:
A-EAST-DBB     ------------------
A-EAST-DBB     # Declared in /var/chef/cache/cookbooks/getnrunscript/recipes/aix.rb:20:in `from_file'
A-EAST-DBB     
A-EAST-DBB     csh("call shell") do
A-EAST-DBB       action "run"
A-EAST-DBB       retries 0
A-EAST-DBB       retry_delay 2
A-EAST-DBB       default_guard_interpreter :default
A-EAST-DBB       command "call shell"
A-EAST-DBB       backup 5
A-EAST-DBB       returns 0
A-EAST-DBB       code "    LOGFILE=chef-ops-`date +\"%Y-%m-%dT%H:%M:%S\"`.log\n    #/tmp/stopDB2.sh -i db2inst1 -d eastdb>> /tmp/chef-ops.log\n    /tmp/stopDB2.sh -l $LOGFILE -i db2inst1 -d eastdb\n"
A-EAST-DBB       interpreter "csh"
A-EAST-DBB       declared_type :csh
A-EAST-DBB       cookbook_name "getnrunscript"
A-EAST-DBB       recipe_name "aix"
A-EAST-DBB     end
A-EAST-DBB     
A-EAST-DBB 
A-EAST-DBB Running handlers:
A-EAST-DBB [2015-08-03T17:52:51+08:00] ERROR: Running exception handlers

**Comment by juliandunn** [comment] 2015-08-04 00:45
It works fine for me. Under `csh` you cannot simply assign a value to a variable; you have to use `set`:

```
$ /opt/chef/bin/chef-apply -s
csh 'wat' do
  code <<EOH
set LOGFILE=chef-ops-`date +"%Y-%m-%dT%H:%M:%S"`
echo $LOGFILE
EOH
end
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * csh[wat] action run
    - execute "csh"  "/var/folders/8y/8kn55v7x0c9_kpt9l2mqqps00000gn/T/chef-script20150803-37877-25ww7q"
```

**Comment by lamont-granquist** [comment] 2015-08-04 16:05
closing as not a chef bug

**Comment by ensean** [comment] 2015-08-05 07:49
I modified the .rb code according to @juliandunn 's advice

The test.sh script on AIX works fine(the logfile is generated when the codes runs)
---------------------------------------csh code----------------------------------------------------------------
#!/bin/csh
set LOGFILE=chef-ops-`date +"%Y-%m-%dT%H:%M:%S"`.log
echo "hello chef" >> $LOGFILE
/tmp/stopDB2.sh -l $LOGFILE -i inst1 -d dbadm
~
----------------------------------------------csh code--------------------------------------------------------------

But the following .rb code seems to be not working(It seems that the var $LOGFILE can not be accessed)

------------------------------------------rb code--------------------------------------------
csh 'call shell' do
  code <<-EOH
    set LOGFILE=chef-ops-`date +"%Y-%m-%dT%H:%M:%S"`.log
    echo "hello chef" >> $LOGFILE
    /tmp/stopDB2.sh -l $LOGFILE -i inst1 -d dbadm
    EOH
end
------------------------------------------rb code--------------------------------------------

Any advice would be appreciated.

**Comment by juliandunn** [comment] 2015-08-07 17:36
I still can't reproduce this @ensean.

```
borkbork ~$ chef-apply -s
csh 'call shell' do
code <<-EOH
set LOGFILE=chef-ops-`date +"%Y-%m-%dT%H:%M:%S"`.log
echo "hello chef" >> $LOGFILE
EOH
end
^D
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * csh[call shell] action run
    - execute "csh"  "/var/folders/56/vlf96yyx30vdx5qlq6n4pkxw0000gp/T/chef-script20150807-47022-711lxp"
borkbork ~$ ls chef-ops-2015-08-07T13\:34\:27.log
chef-ops-2015-08-07T13:34:27.log
borkbork ~$ cat chef-ops-2015-08-07T13\:34\:27.log
hello chef
```

Can you post an error message or something? What platform is this on?

**Comment by ensean** [comment] 2015-08-13 02:47
Thanks for you response @juliandunn , I found that I have forget to set cwd attribute for csh resource...

**Comment by juliandunn** [comment] 2015-08-13 03:18
Okie dokie.

**Closed by juliandunn** 2015-08-13 03:18 UTC
