### ISSUE TITLE
File resource Checksums should match truncated Checksums

### ISSUE THREAD

**Issue by goacid** [chef/chef#2689] opened 2014-12-19 13:41 UTC
while deploying a file with remote_file I have following errors : 

```
Chef::Exceptions::ChecksumMismatch
----------------------------------
Checksum on resource (713570) does not match checksum on content (713570)
```

As you see both checksum match.

chef-client  release 12.0.0-1 and also 12.0.3-1 on ubuntu report the problem, chef until 11.16.4-1 work fine.

chef code : 

```
 remote_file("hidden_app") do
  provider Chef::Provider::RemoteFile
  action "create"
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  path "/hidden/path/7135700/package.tgz"
  backup 5
  atomic_update true
  source ["http://hidden.ip/path//package.tar.gz"]
  use_etag true
  use_last_modified true
  declared_type :remote_file
  cookbook_name "application"
  recipe_name "hidenanme"
  mode "0644"
  checksum "7135700"
end
```

Checksum of the file manually : 
`# sha256sum package.tar.gz 
713570049424aee165d8dcc83bd27c3fc8281e61a2f268a215adf920f3ee7e9b  package.tar.gz`

Cheksum found in chef cache file : 
`{"etag":null,"mtime":null,"checksum":"713570049424aee165d8dcc83bd27c3fc8281e61a2f268a215adf920f3ee7e9b"}
`  
If I download manually the file and put it in the good place /hidden/path/7135700/package.tgz, then it works. Checksum against an existing file is working.

**Comment by evan2645** [comment] 2015-01-23 21:18
We've hit this problem and I've looked a little bit into it. `remote_file` is using `file`, which calls `do_validate_content`, which now matches the checksum in it's entirety:
https://github.com/chef/chef/blob/f27001eb9a22c34dfab2ac38c2f66978fc8bb46c/lib/chef/provider/file.rb#L345

Here is an example of prefix match in `remote_file`:
https://github.com/chef/chef/blob/f27001eb9a22c34dfab2ac38c2f66978fc8bb46c/lib/chef/provider/remote_file/content.rb#L67-L69

Furthermore, the `file` resource has enforced 64 char length checksum forever:
https://github.com/chef/chef/blob/f27001eb9a22c34dfab2ac38c2f66978fc8bb46c/lib/chef/resource/file.rb#L71-L77

Checksum prefixes should be globally supported IMO - currently, support is scattered. We can change `do_validate_content` to support prefixes, and relax the regex restrictions on the `checksum` attribute for the `file` resource... That should both fix `remote_file` and add flexibility to `file` while not breaking what currently works. I'm willing to submit a patch for whatever the most appropriate approach may be.

**Comment by lamont-granquist** [comment] 2015-01-25 18:03
Yeah somehow it forked way back in 2009.  At the very least do_validate_content shouldn't break remote_file.

**Comment by johntdyer** [comment] 2015-03-16 19:39
bump

**Comment by johntdyer** [comment] 2015-03-16 19:43
We are running into this with templates ( https://github.com/sensu/sensu-chef/issues/332 ).  We are unsure how best to address this. I did try switching from File to Template in hopes that would avoid the checksum but that didnt seem to help

**Comment by lamont-granquist** [comment] 2015-03-16 20:05
Why are you using checksums on a template resource?  Even on a file resource, you've uploaded the file to the chef server, and the download will validate the content length (which is a good enough integrity check to catch http protocol errors and such) and be SSL encrypted (good enough to prevent tampering).

Also, the workaround is to just use the full sha256 instead of the prefix, it shouldn't be a blocking bug.

**Comment by johntdyer** [comment] 2015-03-16 20:11
@lamont-granquist  - I am not using checksum on a template resource, or the file resource, for that matter.  But that doesn't seem to make a difference in our case.   FWIW Chef was working just fine w/ 12.0 but now w/ 12.1 we are running into this issue ( https://github.com/sensu/sensu-chef/issues/332 )

**Comment by johntdyer** [comment] 2015-03-16 20:15
So I think I see what was happening, we were writing a template two times in our run list, with a subtle, but not breaking change.   This wasn't noticed in our env since it didn't break anything but is now causing this error since the checksum is different

**Comment by lamont-granquist** [comment] 2015-03-16 20:29
So you're getting a CHEF-3694 error and because the resource is cloned, it clones the checksum which breaks the second invocation?

**Comment by johntdyer** [comment] 2015-03-16 20:43
That sounds about right.

**Comment by lamont-granquist** [comment] 2015-03-16 20:58
Yeah so if you just rename the second resource or something that'll fix it.

**Comment by adamedx** [comment] 2015-04-28 21:53
@lamont-granquist, I'm trying to understand if this is a defect / regression -- did the behavior change from 12.0? Or is there simply an issue with cloning?

**Comment by lamont-granquist** [comment] 2015-04-28 22:14
Everything is operating as designed.

Cloning is still stupid and confusing, which is why there are the 3694 warnings.

**Comment by evan2645** [comment] 2015-04-28 22:25
I want to clarify that there was a change in behavior. @johntdyer's problem is different than the one this issue was opened for. `remote_file` previously allowed truncated checksums... it no longer supports that, and the checksum must be defined in it's entirety. Code that previously worked using a truncated checksum broke following the change.

This change was brought with Chef 12. Personally, I think truncated checksums should be supported. I can send a patch if you are interested.

**Comment by evan2645** [comment] 2015-04-29 18:48
@adamedx @lamont-granquist we should re-open this issue... else I can open another and include a suggested fix. whether we treat it as a regression or an enhancement request i think is the most pertinent question at the moment. i'm inclined towards the former.

**Comment by lamont-granquist** [comment] 2015-04-30 18:01
Updated the title accurately, deleted content that was irrelevant to this actual issue.

**Comment by wilb** [comment] 2015-06-18 18:30
Think I'm seeing this. Using an old ssh cookbook on some hosts to manage ssh pub keys, it has a provider which calls a pretty basic file resource (https://github.com/gchef/ssh-cookbook/blob/master/providers/authorized_keys.rb).  

Recently updated to a chef 12 client, now each run is failing with:

[2015-06-18T19:13:20+01:00] ERROR: file[/root/.ssh/authorized_keys] (/var/chef/cache/cookbooks/ssh/providers/authorized_keys.rb line 9) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (954a25) does not match checksum on content (d76ccf)

**Comment by lamont-granquist** [comment] 2015-06-18 20:44
That file provider does not explicitly set a short checksum on the resource, so it is not this bug.  You are probably seeing #3168 fixed by #3295 which will be fixed with 12.4.0 as soon as we get that code stable enough to ship.

**Comment by wilb** [comment] 2015-06-19 08:16
Apologies & thanks!

**Comment by raam86** [comment] 2015-06-30 14:56
==> default: [2015-06-30T14:52:38+00:00] INFO: *** Chef 12.4.0 ***

Using vagrant truncated checksum doesn't work 
```
 Chef::Exceptions::ChecksumMismatch: Checksum on resource (ac3b84) does not match checksum on content (ac3b84)
```


full checksum works fine.

**Comment by ianrossi** [comment] 2015-08-18 12:15
I'm seeing this in the sensu cookbook's use of `remote_file`. https://github.com/sensu/sensu-chef/issues/332

It's a pain in the butt.

**Comment by evan2645** [comment] 2015-08-18 20:53
@ianrossi your issue looks different as the checksums are actually different (`6a3150` vs `025106`). This issue represents a bug in which the checksums are actually the same

**Comment by ianrossi** [comment] 2015-08-19 10:48
@evan2645 Ah, thanks for the clarification.

**Comment by ianrossi** [comment] 2015-09-24 16:16
I know this is off-topic still, but if anyone hits the same issue as I did with sensu and the checksum mismatch, an upgrade to 12.4.2 solved the problem. That issue was only present for me in 12.3.0.

**Comment by goacid** [comment] 2016-06-01 09:44
Hi

I had the same issue in chef-client version 12.10.24 
  

> Chef::Exceptions::ChecksumMismatch
>     ----------------------------------
>     Checksum on resource (2f04ed) does not match checksum on content (2f04ed)

**Comment by tas50** [comment] 2021-10-03 04:25
Moving this to Chef Ideas with a link back to here: https://chef-software.ideas.aha.io/ideas/INFRA-I-41

**Closed by tas50** 2021-10-03 04:25 UTC
Labels: Type: Bug, Priority: Medium, Focus: Resources
