### ISSUE TITLE
Exit on run lock

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4754] opened 2016-03-25 21:39 UTC
Jotting this down for external memory after a report on IRC. Would be cool if we had an option (or just the default for non-interval runs) to exit if a run lock is detected rather than waiting on it. Helps when running from Cron or some other external orchestration tool to prevent runs from stacking up if something is wedged.

**Comment by lamont-granquist** [comment] 2016-03-28 16:32
:+1:

**Comment by vegardx** [comment] 2016-03-29 19:29
This would be greatly appreciated by my family who had to suffer minutes (oh, the horrors!) of no Netflix as the gateway nuked itself from orbit. It's sort of funny when you can't reboot the server because it can't even fork the shutdown process. 

All jokes a side it also happened to some production servers, which wasn't as fun. Ok, a little fun, not every day you get to see load average over 700. I should also get some monitoring on long running processes.

**Comment by thommay** [comment] 2016-04-13 17:04
"Definitely a dupe of something in Lamont's head"

**Comment by dimsh99** [comment] 2017-09-26 14:59
Doesn't starting client with `--run-lock-timeout 1` solve this problem?

**Comment by tas50** [comment] 2021-01-05 04:54
@lamont-granquist would it make sense to have a default for the run lock timeout so that we don't end up with 100 waiting chef-client processes?

**Closed** 2024-01-19 21:01 UTC
Labels: Priority: Medium, Status: Good First Issue
