### ISSUE TITLE
Uploading "raw" data bag items fails, and we now write raw items.

### ISSUE THREAD

**Issue by tpetchel** [chef/chef#4815] opened 2016-04-08 17:58 UTC
## Description

Uploading an encrypted data bag to Chef server fails with this error:

```
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil
```

This issue blocks our Learn Chef tutorials. Users reported the issue on the RHEL and Ubuntu flavors of the same tutorial:

https://learn.chef.io/manage-a-web-app/rhel/run-your-web-application-on-a-node/#comment-2597692112

https://learn.chef.io/manage-a-web-app/ubuntu/run-your-web-application-on-a-node/#comment-2609047548

The user in the second thread worked around the issue by manually adding the `id` field to the encrypted data bag item's .json file.

I can repo this using Chef DK 0.12.0. I'm almost certain that it does not repro from 0.10.0.
## Chef Version

```
$ chef --version
Chef Development Kit Version: 0.12.0
chef-client version: 12.6.0
berks version: 4.3.0
kitchen version: ERROR
```
## Platform Version

Applies to all platforms. Can repro from Windows 8.1 and Mac OS workstations.
## Replication Case

I believe this bug would apply to uploading any encrypted data bag item to the Chef server, but here's a quick way to repo. `knife` needs to be configured to communicate with a Chef server.

Perform [step 2](https://learn.chef.io/manage-a-web-app/rhel/bring-up-the-web-app-using-test-kitchen/#step2) from the tutorial's quick start page to set up the encrypted data bag locally.

Perform [step 3](https://learn.chef.io/manage-a-web-app/rhel/run-your-web-application-on-a-node/#step3) on this page to upload the data bag to the Chef server.
## Client Output

```
$ knife data bag from file database_passwords mysql_customers.json
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil
```
## Stacktrace

```
$ knife data bag from file database_passwords mysql_customers.json -VV
INFO: Using configuration from /Users/thomaspetchel/learn-chef/.chef/knife.rb
/Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/data_bag_item.rb:44:in `validate_id!': Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil (Chef::Exceptions::InvalidDataBagItemID)
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/data_bag_item.rb:73:in `validate_id!'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/data_bag_item.rb:80:in `raw_data='
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/data_bag_from_file.rb:94:in `block in load_data_bag_items'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/data_bag_from_file.rb:85:in `each'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/data_bag_from_file.rb:85:in `load_data_bag_items'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/data_bag_from_file.rb:58:in `run'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife.rb:212:in `run'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/knife.rb:142:in `run'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/knife:25:in `<top (required)>'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/bin/knife:23:in `load'
    from /Users/thomaspetchel/.rbenv/versions/2.1.1/bin/knife:23:in `<main>'
```

**Comment by thommay** [comment] 2016-04-08 18:27
I can't reproduce this with a current version of chef:
```
ubuntu@ip-172-31-37-200:~/learn-chef$ chef-client -v
Chef: 12.9.27
ubuntu@ip-172-31-37-200:~/learn-chef$ knife data bag from file database_passwords mysql_customers.json --secret-file .chef/encrypted_data_bag_secret --local-mode
WARNING: No knife configuration file found
Updated data_bag_item[database_passwords::mysql_customers]
```

**Comment by mwrock** [comment] 2016-04-09 00:26
yeah 12.7 should have fixed this.

**Comment by tpetchel** [comment] 2016-04-14 14:05
A user reported that this continues to fail using chef-client 12.9.36. 

https://learn.chef.io/manage-a-web-app/ubuntu/run-your-web-application-on-a-node/#comment-2623267662

One thing to note is that the tutorial has the user encrypt the data bags locally so they can be run through Test Kitchen. (@thommay's example is a bit different than that.) The user later uploads the already-encrypted data bags to the Chef server (e.g. `knife data bag from file` and not `knife data bag from file --secret-file`. Users report that while the upload succeeds, the node fails to decrypt the data. 

I feel that I have a valid use case, but if this is not the recommended pattern, please let me know. I could imagine doing this differently by having the user encrypt a second copy of the data bags for Test Kitchen to use. However:

1) it's more steps, more files to keep track of.
2) the source data bags are less source control friendly because you essentially have unencrypted data under your chef-repo/data_bags directory.

As a second alternative, we could have the user validate the cookbook using unencrypted data bags, and later encrypt & upload them per @thommay's example. However, it seems to me that you're no longer faithfully testing what would happen on your node. I can imagine that if the decryption process fails on the node, it would be frustrating for the user (who's just learning about all of this) to debug the issue on a node. The method we use on Learn Chef enables the user to troubleshoot any issues on local test instances before applying the config to something real.

That said, I would love to ensure this is working if my use case is valid.

**Comment by bwhitacrejha** [comment] 2016-04-20 16:39
I am able to reproduce this error simply by attempting to upload a data_bag.  With or without encryption.  Here are my current versions:

Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

Also note that when I created the data bag via Knife, I had to log out of the Chef Server and back in for the data bag to even show up in the GUI.  Knife however was able to list it immediately.

**Comment by lamont-granquist** [comment] 2016-04-20 17:30
@tpetchel note that you're using 12.6.0 on rbenv and not omnibus-chefdk which isn't what learnchef users should be doing...

**Comment by lamont-granquist** [comment] 2016-04-20 17:35
for me with master:

```
% knife --version
Chef: 12.10.11
% knife data bag from file encrypted ./creds.json
Updated data_bag_item[encrypted::creds]
```

**Comment by lamont-granquist** [comment] 2016-04-20 17:35
that is an already-encrypted databag saved on disk that i am re-uploading

**Comment by lamont-granquist** [comment] 2016-04-20 17:42
So, if people want to fix this then we need a better repro fix.  You should validate that you are using chef-client 12.8.1 or better since we know fixes went into that version.  We also need to see the full contents of the data bag item that you are trying to upload, because guessing what you all are doing does not seem to be working...     reminder on minimal, complete, verifiable example:  http://stackoverflow.com/help/mcve

**Comment by bwhitacrejha** [comment] 2016-04-20 19:57
I am encountering this issue whether I am attempting to upload an encrypted data bag or not encrypted.

I am using a Windows 7 Workstation with WinRM 5.0, latest Chef DK (0.12.0) and Chef Server(12.5.0).
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
Chef Server: 12.0.5

I have validated the JSON to be good format.

Here is an sample of trying it without encrypting it:
knife data bag from file serverDataBag .\serverDataBag\bsl.json
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil

Here is an example of the new data bag I am attempting to upload.  I have removed the specific user/pass info:
{
  "BizAccount": {
    "phypath":"Jha.Account.WebHost",
    "user":"xxxxx",
    "pass":"xxxxx"
  },
  "BizAuthentication":{
    "phypath":"Jha.Authentication.WebHost",
    "user":"xxxxx",
    "pass":"xxxxx"
  },
  "BslMfa":{
    "phypath":"Jha.Authentication.WebApi",
    "user":"xxxxx",
    "pass":"xxxxx"
  },
  "Jha.Account.WebApi":{
    "phypath":"Jha.Account.WebApi",
    "user":"xxxxx",
    "pass":"xxxxx"
  }
}

I had an existing encrypted data_bag on the server that I am no longer able to update with the same command, which results in the same error.
The existing databag that I have had on the server for months has not had any changes to the JSON.  So I do not anticipate this is an issue related to the JSON.

Thanks

**Comment by lamont-granquist** [comment] 2016-04-20 20:29
So to state the obvious here if you're getting this error message:

```
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[.-[:alnum:]_]+$/, you gave: nil
```

Check your json and make sure that you have an "id" field at the top level of the json which identifies the data bag item.  When you are doing `knife data bag from file <databag>` there is no 'ITEM' argument passed on the command line and that value has to be read from the JSON.

If you don't have that field in your JSON the error message is simply 100% accurate -- you haven't given us enough information in the JSON for us to know what to do.

It may be possible that data bags which were `knife download`'ed before 12.8.1 were having the id field deleted from them, and may be corrupted on disk.  There's not a whole lot we can do[*] about that either, the easiest solution would be to re-run `knife download /data_bags` again.

[*] We could start to assume the id from the filename and fatal if there is a different id in the file, but I really don't want to go down that route and add more confusion going forwards.

**Comment by tpetchel** [comment] 2016-04-21 02:03
@lamont-granquist: It's not so much that I'm using 12.6.0, the sample output just wasn't updated in awhile. I'll take a look tomorrow and build a better repo case if the issue persists. 

That said, this all used to work for the longest time. Were there any major changes made in recent releases?

**Comment by lamont-granquist** [comment] 2016-04-21 04:30
It was definitely buggy around 12.6.0-era but that should have been fixed in 12.8.1

And like I speculated its possible that people are hitting this who have downloaded data bag items using 12.6.0 and then trying to upload with 12.8.1 and the id field got stripped by the bugginess in 12.6.0

Still need a replication case that /has/ a valid id field in it and then fails on 12.8.x/12.9.x/12.10.x

**Comment by lamont-granquist** [comment] 2016-04-21 04:56
the output of `knife data bag from file encrypted mysql_customers.json --secret-file MYSECRETFILE --local-mode` is:

```ruby
% ruby -rjson -e 'puts JSON.pretty_generate(JSON.parse(STDIN.read))' < mysql_customers.json
{
  "name": "data_bag_item_encrypted_mysql_customers",
  "json_class": "Chef::DataBagItem",
  "chef_type": "data_bag_item",
  "data_bag": "encrypted",
  "raw_data": {
    "id": "mysql_customers",
    "root_password": {
      "encrypted_data": "noDOsTpsTAZlTU5sprhmYZzUDfr8du7hH/zRDOjRAmoTJHTZyfYoR221EOOW\nXJ1D\n",
      "iv": "Bnqhfy6n0Hx1wCe9pxHLoA==\n",
      "version": 1,
      "cipher": "aes-256-cbc"
    },
    "admin_password": {
      "encrypted_data": "TcC7dU1gx6OnE5Ab4i/k42UEf0Nnr7cAyuTHId/LNjNOwpNf7XZc27DQSjuy\nHPlt\n",
      "iv": "+TAWJuPWCI2+WB8lGJAyvw==\n",
      "version": 1,
      "cipher": "aes-256-cbc"
    }
  }
}
```

Which clearly lacks the 'id' field.  Then I can replicate:

```ruby
% knife data bag from file encrypted mysql_customers.json
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil
```

A properly formatted encrypted data bag item downloaded from the chef-server looks like this:

```ruby
% cat mysql_customers.json
{
  "id": "mysql_customers",
  "root_password": {
    "encrypted_data": "8R966HFobcC+m+woksdtTbC/fWqHy2KovSAkr71zwBAt2CBLKamXcdS/jSrA\nQl9w\n",
    "iv": "04i16AAnWRCWgbx58j539w==\n",
    "version": 1,
    "cipher": "aes-256-cbc"
  },
  "admin_password": {
    "encrypted_data": "u8l3yczEBzD+yhD77CL+XTIjW03KaBC8O8QyG3pAML2/GkCFyfhW40sWvEVK\nNMWW\n",
    "iv": "nliIDZy12ypYGXhSxRrdPQ==\n",
    "version": 1,
    "cipher": "aes-256-cbc"
  }
}
```

You're getting the on-disk format for chef-zero by using --local-mode.  I don't know if that changed or what, but that smells really incorrect.

Maybe @jkeiser or @thommay has more information on if that might have changed recently.  I'm somewhat skeptical that ever worked right.  And definitely feel like that is the wrong API to be using...

I'm leaning towards this being a doc-bug in learnchef...

**Comment by lamont-granquist** [comment] 2016-04-21 05:05
So this bug *may* actually be "we need a supported API to encrypt a data bag on disk with the user's secret-key (without involving bizzare hacks that try to round trip through chef-zero)"

**Comment by tpetchel** [comment] 2016-04-21 21:52
Here's a more minimal repro case. I'm chatting with @jkeiser offline.

```
#!/bin/bash

mkdir -p data_bags/passwords

(
cat <<'EOF'
{
  "id": "my",
  "password": "ABCD123!"
}
EOF
) > data_bags/passwords/my.json

knife data bag from file passwords my.json --local-mode --secret-file .chef/encrypted_data_bag_secret
knife data bag from file passwords my.json --local-mode
```

**Comment by ChadScott** [comment] 2016-04-27 17:35
This happens regardless of whether the data bag is encrypted or not.

Either chef-zero needs to write the format expected of `knife data bag from file` or knife needs to be smart enough to do the translation. There are lots of use cases where you'd need to upload a data bag JSON from chef-zero, such as when you're bringing up an entire infrastructure in AWS, including a chef server, and you then need to make that new chef server aware of the AWS environment.

Other examples include encryption, as indicated here, as well as writing out a data bag from a local recipe for later upload elsewhere.

This has worked in the past but I'm unsure what changed. It sorta looks like chef-zero started writing the on-disk version or something.

**Comment by ChadScott** [comment] 2016-04-27 17:49
Also, if this helps anyone, I've used this script to translate my data bags en-masse... just use `find` to locate the JSON and shove them through this script into a new one.

```
#!/usr/bin/env ruby

require 'json'

data = JSON.parse(ARGF.read)

if data.include?('raw_data')
  puts JSON.pretty_generate(data['raw_data'])
else
  puts JSON.pretty_generate(data)
end
```

**Comment by lamont-granquist** [comment] 2016-04-27 21:04
So @tpetchel the "workaround" here is the fix you should use:

https://learn.chef.io/manage-a-web-app/ubuntu/run-your-web-application-on-a-node/#comment-2623267662

Simply keep the on-disk format unencrypted, and don't try to solve that problem in the learnchef tutorial.

We may wind up patching this to reinstate the old behavior to address @ChadScott's use-cases, but just because the --local-mode hack worked doesn't mean that anyone should be documenting that -- and particularly we should not be teaching chef newbies to use that as an API, ever, even if its fixed.  That is well down the "one strange trick" path and not canonical chef, and the reasons why it worked are way too obscure to put in front of newbies.

We probably do need to support encrypting data-bags in the chef-repo with the secret-key but that API should not be identical.  The output should be the same format as one gets from `knife download /data_bags` and not the on-wire format that chef-zero is saving to disk.

**Comment by lamont-granquist** [comment] 2016-05-04 17:16
we probably broke this with some combination of

- removing json_class
- the PR for #4664 which fixed #4392

before anyone suggests reverting #4664, we can't do that because that just pushes the problem around, and #4664 affects many more users.  we're also not reverting the removal of json_class, we just need to fix bugs here.

we apparently have a requirement to support both pretty 'user' format and on-wire 'chef-server' format that we weren't ever aware of (and had zero tests around, etc).

what i'd really like to see is a mixin for all our object models which supported reading from a file and decoding either format, for all our object models.  along with tests so that we don't break it in the future.  along with nuking some of the code in knife's object loader which seems to be getting into a fight with core-chef code.

at the very least i'd like to see that mixin created and the data bag item object patched to support it along with sorting out the conflicting logic in knife.  we can be iterative about fixing our entire object model, but i'd like to see some progress in the direction of making things sane.

**Comment by lamont-granquist** [comment] 2016-05-04 17:18
we also need to support a better knife API for encrypting an on-disk data bag item without round-tripping through chef-zero and writing out a wire-format encrypted data bag -- that is terrible for many different reasons, not the least of which is that it'll inherently and by-design break knife diff and that 'bug' will never be fixable because that API should never have been used.

**Comment by tpetchel** [comment] 2016-06-30 15:19
Sorry for not closing this out earlier. I got some more information offline and understand how to make my scenario work now using the correct APIs/patterns.

**Comment by thommay** [comment] 2016-06-30 16:38
not closed because we still need to do the work

**Comment by usrme** [comment] 2017-01-12 09:27
I arrived at this issue from #4892 and I'm not sure how related this issue exactly to the one just mentioned, but the comments section referred here. I had the exact same error message, namely:

```
Chef::Exceptions::ValidationFailed: Option data_bag's value {"encrypted_data"=>"6zYvton8uCvsJfTbeuf5huwxWzsZ5TZoF6oJ1jsFb+s=\n", "iv"=>"FrlwhrRL3A/KGsyATYtsLw==\n", "version"=>1, "cipher"=>"aes-256-cbc"} does not match regular expression /^[\-[:alnum:]_]+$/
```

I resolved this by switching my default *EDITOR* to Notepad instead of Sublime Text as Sublime Text didn't keep the file open for the duration of the edit, which caused a mismatch with the regular expression as just the **id** key and value made it to the Chef Server during the creation of the data bag item. Again, not quite sure if this is helpful, but just throwing this out there for anyone who might be running into the same issue.

**Comment by jdblack** [comment] 2017-03-08 09:10
I came here the same way that usrme did.  Running  a "knife data bag edit  bag item  --encrypt"  and exiting the editor with or without changes  causes the data bag to become corrupted  with any further attempts to edit the data bag (with or without --encrypt) impossible.

Knife version 12.17.44, against  a chef server of :  12.13.0

**Comment by GreyArea765** [comment] 2017-03-14 13:38
Came here following a tutorial which first creates a data bag and then encrypts it after the fact.

$ knife -v
Chef: 12.18.31

Steps to reproduce:
$ knife data bag create user_password
Created data_bag[user_password]

$ knife data bag from file user_password ../../../bofh.json
Updated data_bag_item[user_password::bofh]

$ knife data bag show user_password bofh
WARNING: Unencrypted data bag detected, ignoring any provided secret options.
id:       bofh
password$W./fF8LJQtN9IXnUt6WNl1

$ EDITOR=vim knife data bag edit user_password bofh --secret-file ../../../chef-data-bag-shared-secret.txt
Encrypting data bag using provided secret.
Saved data_bag_item[bofh]

$ knife data bag show user_password bofh --secret-file ../../../chef-data-bag-shared-secret.txt 
ERROR: Chef::Exceptions::ValidationFailed: Option data_bag's value {"encrypted_data"=>"4Pc1wRINte5r/jw5wf6GvpCh/61pU5IkNu6fULPVioK5hHZ1Y6aXV/lthZUl\nNCob\n", "iv"=>"q96kYsHC8rX/9WfgZTxZlA==\n", "version"=>1, "cipher"=>"aes-256-cbc"} does not match regular expression /^[\-[:alnum:]_]+$/

The workaround appears to be ensuring that the data bag is encrypted on creation then I don't get the error the 2nd on 'knife data bag show' command.

**Comment by btm** [comment] 2019-03-07 20:32
The original bug seems to be around using the *on-disk* data bag format from something like chef-solo, as opposed the the format that we use against the Chef Server API. Which perhaps worked at one point but was never intended to work. Something like `knife data bag show test_data_bag bob -F json` (without --secret-file) would give you the JSON to save on disk that would be compatible with `knife data bag from file test_data_bag bob`.

I believe the issue @jdblack and @usrme had is a different bug that the OP that results when using `knife node edit --secret-file` with an editor.

I reproduced @GreyArea765's issue on 14.8.12, which isn't latest but is what happens to be on my laptop. I'm don't think that's the same as @tpetchel's original bug though. The bug there is probably to have `knife data bag edit --secret-file` fail if it is editing an unencrypted data bag.

**Comment by lamont-granquist** [comment] 2019-03-07 20:47
Issues around using `knife data bag edit --encrypt` against an unencryped data bag and having it corrupted have been moved to #8282, and distracting comments in this PR have been cleaned up.

**Closed** 2024-01-19 21:01 UTC
Labels: Priority: Medium, Focus: knife
