### ISSUE TITLE
knife bootstrap no longer looks for a default key (~/.ssh/id_rsa) with ChefDK 4

### ISSUE THREAD

**Issue by mattray** [chef/chef#8821] opened 2019-08-15 07:05 UTC
In ChefDK 3.11.3 ```knife bootstrap``` without specifying ```-i``` would use ```~/.ssh/id_rsa``` as the default key. ChefDK 4.x has a regression where it no longer respects this and requires a default key be provided via ```-i```.

**Comment by vsingh-msys** [comment] 2019-09-17 12:49
ChefDK 3.11.3 resolved as `chef-client 14.13.11`. As per my analysis, I have tested the vagrant ubuntu 16.04 node on the following scenario:

|chef version | cmd  | target node ssh config | comments |
|-----------------| ------------- | ------------- |-----------------|
|14.11.13| knife bootstrap node2.test  -x vagrant  | without authetication_keys added | ask for password |
|14.11.13| knife bootstrap node2.test  -x vagrant  | with authetication_keys added | successfully bootstrap |
|15.4.1| knife bootstrap node2.test  -U vagrant  | without authetication_keys added | ask for password |
|15.4.1| knife bootstrap node2.test  -U vagrant  | with authetication_keys added | successfully bootstrap  |

Also I have looked into the code it never set  `~/.ssh/id_rsa` in identity_file config option in both chef-14 and chef-15.

Let me know if I am missing something at my end?

Thanks!

```
vagrant@node1:~$ chef -v
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3

**Comment by Vasu1105** [comment] 2019-09-18 06:16
@vivek I feel we should check with ChefDk 4.x once.

**Comment by vsingh-msys** [comment] 2019-09-18 07:35
@Vasu1105  I tried to bootstrap the ubuntu node from ChefDK 4.3.1 as well seems showing expected behaviour as my earlier testing with one know issue,

it won't ask for password due to https://github.com/chef/chef/pull/8856 not yet merge

**Comment by vsingh-msys** [comment] 2019-10-11 13:45
It seems no response from @mattray, as I am waiting for more info.

@marcparadise could you please help me out how `~/.ssh/id_rsa` is associated with the chef-15 bootstrap process as from my side in both chef-14 & 15 does not have any default consideration?

Thanks!

**Comment by vsingh-msys** [comment] 2019-10-22 16:05
@lamont-granquist & @tas50 could you please suggest something on this issue. As per my analysis  `~/.ssh/id_rsa` key associated only if we make an entry in node known_host which working as expected for both chef-14/15

**Comment by marcparadise** [comment] 2019-10-29 21:05
@vsingh-msys there's no direct usage, but net-ssh does default to using id_rsa/dsa if present, but only if we don't pass in any `keys`. 

Did we or train have any earlier issues where we were setting `keys` in the option list, even if we had none? That would have prevented them from loading, since net-ssh checks to see [if the hash key exists](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/session.rb#L67) in order to exclude default keys - but it does not check  if  the value is  empty/nil.

I could also see this happening if  had turned off the default behavior of allowing net-ssh to use a running ssh-agent . It defaults to true, we would have had to be explicit in turning it off.  We currently do not disable it.

Your tests show that the issue is not currently occurring; I checked in with @mattray as well, and he has not come across this since filing the issue. I recommend closing this one as not reproducible.

**Comment by vsingh-msys** [comment] 2019-10-30 05:49
Hi @marcparadise,

Thank you so much for your help.

> Did we or train have any earlier issues where we were setting keys in the option list, even if we had none? That would have prevented them from loading, since net-ssh checks to see if the hash key exists in order to exclude default keys - but it does not check if the value is empty/nil.

As I can check we are not setting any key in the options list. will look into more into later.

Closing for now as I am not able to replicate expected behavior. Thanks!

**Comment by lamont-granquist** [comment] 2019-10-30 22:31
@vsingh-msys i think i've seen a related problem happen with my macbook in target mode using train.

i suspect it has something to do with the mac keystore (?) acting as an ssh-agent and therefore bypassing using the files on disk.  if my suspicion is correct, it won't repro on ubuntu or anything like that.  IDK if it is due to something that changed in the macOS or in train.

@mattray a repro with the actual output and error message and the stack trace would be useful since i'm currently forced to speculate two levels deep here.

**Comment by mattray** [comment] 2019-10-31 01:30
Using ChefDK version: 4.5.0 I can confirm that this has not been fixed.

```
$ ssh crushinator
Linux crushinator 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
mattray@crushinator:~$ logout
$ knife bootstrap crushinator -N crushinator --policy-group home --policy-name x86 
Connecting to crushinator
WARNING: Failed to authenticate  to crushinator - trying password auth
Enter password for @crushinator.
^C
Connection to crushinator closed.
$ knife bootstrap crushinator -i ~/.ssh/id_rsa -N crushinator --policy-group home --policy-name x86 
Connecting to crushinator
The authenticity of host 'crushinator (10.0.0.5)' can't be established.
fingerprint is SHA256:TbRYVVLx5QtZhOYQjErHIetU+bgIeQ5DZ879qhCNXdA.

Are you sure you want to continue connecting
? (Y/N) n
You said no, so I'm done here.
```

**Comment by vsingh-msys** [comment] 2019-10-31 12:52
Hey @mattray thanks for the info.

> $ ssh crushinator
Linux crushinator 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
mattray@crushinator:~$ logout
$ knife bootstrap crushinator -N crushinator --policy-group home --policy-name x86 
Connecting to crushinator
WARNING: Failed to authenticate  to crushinator - trying password auth
Enter password for crushinator.

Will check and revert back accordingly and assuming that your workstation is MacOS?

As I tried on from Ubuntu workstation and it's working fine.

RE:
>$ knife bootstrap crushinator -i ~/.ssh/id_rsa -N crushinator --policy-group home --policy-name x86 
Connecting to crushinator
The authenticity of host 'crushinator (10.0.0.5)' can't be established.
fingerprint is SHA256:TbRYVVLx5QtZhOYQjErHIetU+bgIeQ5DZ879qhCNXdA.

Are you sure you want to continue connecting
? (Y/N) n

Seems this is expected behaviour as you confirmed you did not want to override fingerprint.

**Comment by mattray** [comment] 2019-11-01 00:46
Yes, my workstation is MacOS 10.14. 

The fingerprint override bit was extraneous, I was just showing that -i would use the id_rsa key.

**Comment by mattray** [comment] 2020-02-06 00:59
Verified on MacOS 10.14 and Debian Linux 10 with Chef Client 15.7.32 that this is still an issue.

knife bootstrap machine -N machine -U mattray
Connecting to machine
WARNING: Failed to authenticate mattray to machine - trying password auth
Enter password for mattray@machine.

**Comment by yogeshlc** [comment] 2020-04-21 07:09
I am facing the similar issue.
For more details can go through the Bug #9675

**Comment by lamont-granquist** [comment] 2020-04-21 22:33
@yogeshlc did you have an ssh-agent process running on linux?

**Comment by yogeshlc** [comment] 2020-04-22 06:13
@lamont-granquist Yes ssh-agent is running on the linux.
here is the output:
-bash-4.2$ ps aux | grep ssh-agent
ABC   11892  0.0  0.0  72480   780 ?        Ss   05:36   0:00 /usr/bin/ssh-agent

**Comment by ayushbhatt29** [comment] 2020-10-15 16:42
@mattray @yogeshlc  i have tested on MacOS 10.15.6 using chefdk 4.11.0, 4.5.0 and 3.11.3 with debian 10.6 node and ubuntu node, the bootstrap is being succeeded without password prompt.

For me starting ssh agent and adding private key to SSH agent worked.

can you please go through these steps and let me know if i am missing anything?

Thanks!

These are the steps that i have followed -

- Setup SSH key in Mac with `ssh-keygen -t rsa -b 4096 `

- Put public key `id_rsa.pub` from workstation to authorized_key in node

- Started the SSH agent with `eval "$(ssh-agent -s)"`

- Added ~/.ssh/id_rsa to SSH agent with `ssh-add ~/.ssh/id_rsa`

- Bootstrapped the node without `-i` option. 

**Command** - `knife bootstrap 52.90.85.168 -U 'ubuntu' --sudo -c /Users/administrator/ayush/chef-repo/chef-repo/.chef/knife.rb -N ubuntu1010`
**output** - 
```
Bootstrapping 52.90.85.168
 [52.90.85.168] -----> Installing Chef Omnibus (stable/15)
 [52.90.85.168] downloading https://omnitruck.chef.io/chef/install.sh
 [52.90.85.168]   to file /tmp/install.sh.1811/install.sh
 [52.90.85.168] trying wget...
 [52.90.85.168] ubuntu 20.04 x86_64
 [52.90.85.168] Getting information for chef stable 15 for ubuntu...
 [52.90.85.168] downloading https://omnitruck.chef.io/stable/chef/metadata?v=15&p=ubuntu&pv=20.04&m=x86_64
 [52.90.85.168]   to file /tmp/install.sh.1815/metadata.txt
 [52.90.85.168] trying wget...
 [52.90.85.168] sha1    c0202b67c12988f1dbad01bb3c4431e5ae14ed1d
sha256  a98043d49bf0f8439a75ea4308f6e9789e8ebb1fc29646756fa005cd2324a2a2
url     https://packages.chef.io/files/stable/chef/15.14.0/ubuntu/20.04/chef_15.14.0-1_amd64.deb
version 15.14.0
 [52.90.85.168]
 [52.90.85.168] downloaded metadata file looks valid...
 [52.90.85.168] downloading https://packages.chef.io/files/stable/chef/15.14.0/ubuntu/20.04/chef_15.14.0-1_amd64.deb
 [52.90.85.168]   to file /tmp/install.sh.1815/chef_15.14.0-1_amd64.deb
 [52.90.85.168] trying wget...
 [52.90.85.168] Comparing checksum with sha256sum...
 [52.90.85.168] Installing chef 15
 [52.90.85.168] installing with dpkg...
 [52.90.85.168] Selecting previously unselected package chef.
 [52.90.85.168] (Reading database ... 87598 files and directories currently installed.)
 [52.90.85.168] Preparing to unpack .../chef_15.14.0-1_amd64.deb ...
 [52.90.85.168] Unpacking chef (15.14.0-1) ...
 [52.90.85.168] Setting up chef (15.14.0-1) ...
 [52.90.85.168] Thank you for installing Chef Infra Client! For help getting started visit https://learn.chef.io
 [52.90.85.168] Starting the first Chef Infra Client Client run...
 [52.90.85.168] +---------------------------------------------+
✔ 2 product licenses accepted.
+---------------------------------------------+
 [52.90.85.168] Starting Chef Infra Client, version 15.14.0
 [52.90.85.168]
 [52.90.85.168] Creating a new client identity for ubuntu1010 using the validator key.
 [52.90.85.168]
 [52.90.85.168] resolving cookbooks for run list: []
 [52.90.85.168]
 [52.90.85.168] Synchronizing Cookbooks:
 [52.90.85.168]
 [52.90.85.168] Installing Cookbook Gems:
 [52.90.85.168]
 [52.90.85.168] Compiling Cookbooks...
 [52.90.85.168]
 [52.90.85.168] [2020-10-15T04:33:43+00:00] WARN: Node ubuntu1010 has an empty run list.
 [52.90.85.168] Converging 0 resources
 [52.90.85.168]
 [52.90.85.168]
 [52.90.85.168]
 [52.90.85.168] Running handlers:
 [52.90.85.168]
 [52.90.85.168] Running handlers complete

 [52.90.85.168] Chef Infra Client finished, 0/0 resources updated in 01 seconds
 [52.90.85.168]
```

**Comment by lamont-granquist** [comment] 2020-10-15 19:24
my target mode stuff got magically fixed at some point.

@mattray does this work now for bootstrap?

**Comment by mattray** [comment] 2020-10-16 06:58
@lamont-granquist yes, it finds ~/.ssh/id_rsa and works now

**Comment by ayushbhatt29** [comment] 2020-10-16 08:42
@mattray Thank you so much, closing the issue now as this is no longer a issue.

**Closed by ayushbhatt29** 2020-10-16 08:42 UTC
Labels: Focus: knife bootstrap, Priority: Critical, Status: Sustaining Backlog, Type: Bug
