### ISSUE TITLE
knife download fails with "undefined method `child' for nil:NilClass"

### ISSUE THREAD

**Issue by sersut** [chef/chef#1509] opened 2014-06-18 16:29 UTC
https://tickets.opscode.com/browse/CHEF-4718

`knife download /` fails with: 

```
/Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/file_system.rb:320:in `block in copy_entries': undefined method `child' for nil:NilClass (NoMethodError)
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:95:in `call'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:95:in `process_input'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:70:in `each'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/file_system.rb:422:in `to_a'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/file_system.rb:422:in `parallel_do'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/file_system.rb:319:in `copy_entries'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/file_system.rb:357:in `block in copy_entries'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:95:in `call'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:95:in `process_input'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:112:in `worker_loop'
	from /Users/st/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/chef_fs/parallelizer.rb:24:in `block (2 levels) in initialize'
```

due to:

```
Created cookbooks
DEBUG: Signing the request as johndoe
DEBUG: Initiating GET to https://chef.example.org/cookbooks/?num_versions=all
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: johndoe
DEBUG: X-OPS-TIMESTAMP: 2013-11-01T14:10:33Z
DEBUG: X-OPS-CONTENT-HASH: *removed*
DEBUG: X-OPS-AUTHORIZATION-1: *removed*
DEBUG: HOST: chef.example.org:443
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: nginx/0.7.67
DEBUG: date: Fri, 01 Nov 2013 14:10:33 GMT
DEBUG: content-type: application/json; charset=utf-8
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: ---- End HTTP Status/Header Data ----
```

@jkeiser any fix recommendations?

**Comment by gnowxilef** [comment] 2015-01-22 21:45
+1

**Comment by mihalis68** [comment] 2015-02-13 21:40
I'm running into this issue too, whilst attempting to pull all information from elderly production Chef 10 servers in preparation for building shiny new Chef 11 (or perhaps 12) servers.

**Comment by jahasty** [comment] 2015-02-19 20:20
Any progress on this issue? It is causing us trouble as we plan on upgrading to V12. Is there a release of the Chef Client V11 we can fall back to that this doesn't happen?

**Comment by mihalis68** [comment] 2015-02-23 22:31
Confirmed today that neither chef 11 nor chef 12 work using knife download against my production chef 10 servers, so https://www.chef.io/blog/2013/03/12/5106/ doesn't work. We have now formally raised this issue with our representative at Chef.io

**Comment by mmzyk** [comment] 2015-02-24 14:17
It would be helpful if you all could provide us with more information. Which versions of chef client are you seeing this failing and against which chef server versions? Are there combinations that it works? Having this information would be helpful in narrowing things down.

**Comment by mihalis68** [comment] 2015-02-24 15:10
This error happens with the latest versions of both Chef 11 and Chef 12 acting as download clients against servers running Chef server 10.18.2.

In all cases, the -VV output ends like the following (a null member 'child' is accessed in file_system.rb when recursively copying a directory structure). --concurrency 1 has no effect

/opt/chef/embedded/apps/chef/lib/chef/chef_fs/file_system.rb:323:in `block in copy_entries': undefined method `child' for nil:NilClass (NoMethodError)
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:195:in `each_with_exceptions_unordered'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:74:in `wait'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:48:in `parallel_do'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:29:in `parallel_do'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/file_system.rb:425:in `parallel_do'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/file_system.rb:322:in `copy_entries'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/file_system.rb:360:in `block in copy_entries'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `call'
	from /opt/chef/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'

**Comment by mmzyk** [comment] 2015-02-24 21:38
@mihalis68 Is this issue only with Chef server 10? There is some question if knife download ever worked with Chef Server 10. I'll have to check into that. Is anyone else seeing this against a server other than 10, or is this all related to 10?

Would it be helpful to get some guidance on how to migrate from 10 to 11 or 12?

**Comment by mmzyk** [comment] 2015-02-24 21:55
I've answered my own question that knife download did work with chef 10 once upon a time, as here is the blog post that talks about using it to upgrade from chef 10 to 11. https://www.chef.io/blog/2013/03/12/5106/

We'll work on diving deeper into this.

**Comment by mihalis68** [comment] 2015-02-24 22:13
Yes I mentioned that blog posting previously here in this ticket.

**Comment by mmzyk** [comment] 2015-02-24 22:19
@mihalis68 I over looked it. Sorry about that.

**Comment by mihalis68** [comment] 2015-02-24 22:24
No worries! I'm optimistic the fix may be fairly simple. Let me know if there's anything I can help test.

**Comment by mmzyk** [comment] 2015-02-25 22:47
Just to clarify - everyone in this ticket having issues with Chef Server 10 is using the open source version? If you happen to be using the Enterprise version, let us know, as we have different tooling for that version that might help you move forward.

In the mean time we'll focus on solving this issue assuming the open source 10 server.

@mihalis68 We might take you up on that offer, as we don't exactly have many open source 10 servers around and that was before our omnibus days. We'll let you know.

**Comment by mihalis68** [comment] 2015-02-26 01:39
Yes, open source chef 10 server. It's version 10.18 IIRC because that was the last version packaged as a .deb file and published on apt.opscode.com - it took a while to get away from that since we had tooling around installing chef from a local mirror of that since our production chef servers can't expect Internet access

**Comment by stevendanna** [comment] 2015-02-26 10:13
@mihalis68 Can you post the the entire debug log (with -VV and --concurrency 1) somewhere?  If you don't want to post it here, you can email it to me at steve@chef.io.

**Comment by mihalis68** [comment] 2015-02-26 15:25
Yes absolutely I'll dig that out now

**Comment by mihalis68** [comment] 2015-02-26 15:38
I don't see --concurrency 1 or --concurrency=1 actually change the output at all. Is that correct syntax? In particular the traceback at the end always shows the individual filesystem operations being fed into parallel_do

**Comment by mihalis68** [comment] 2015-02-26 15:48
I have sent the transcript to the email suggested above. Could you at least let me know if it got through. Our email system likes to eat emails with attachment for inscrutable reasons.

**Comment by mmzyk** [comment] 2015-02-26 15:59
@mihalis68 --concurrency 1 should be right. https://docs.chef.io/knife_download.html, so if the output didn't change it's nothing you've done wrong.

**Comment by stevendanna** [comment] 2015-02-26 16:00
@mihalis68 Got your email, checking it out now.  Thanks!

**Comment by mmzyk** [comment] 2015-02-26 21:15
@mihalis68 Can you check something for me? Do you have the knife-essentials gem installed on your system that you're running knife download from? If so, can you uninstall that gem and try again?

**Comment by mihalis68** [comment] 2015-02-27 12:55
No it's not a stray gem, for testing I made two brand-new single-purpose VMs with Ubuntu 12.04 and Chef 11 and Chef 12 respectively. The exception traceback from the error is all from /opt/chef/embedded<blah> no other paths.

Please do let me know if you suspect that verson of ubuntu however, testing with 14 would be quite straightforward.

**Comment by mmzyk** [comment] 2015-02-27 13:00
@mihalis68 Thanks. I asked about knife-essentials because it showed up on a test system and caused this type of error, so I wanted to double check, even though I suspected it wasn't the case based on the output you sent. I highly doubt this is related to ubuntu version, but we'll let you know if our thinking changes on that.

**Comment by mihalis68** [comment] 2015-03-18 20:40
I think I have worked out part of what is happening. I hacked up a bunch of the knife source code with extra trace and after quite a bit of fiddling found that the local path for cookbooks is expanded to nill. This seemed to be straight from the chef config. 

It turns out, my knife-chef10.rb file contained the line

```
cookbook_path nil
```

as per the blog. This causes it to blow up. Removing this line allowed something like this to work

```
knife download -c .chef/knife-chef10.rb cookbooks
```

to succeed. W00t!

However a full download of '/' still fails. A quick bash one-liner, however, seems to get the job done:

```for STUFF in clients cookbooks data_bags environments nodes roles users; do echo "Downloading $STUFF"; echo; echo ;knife download -c .chef/knife-chef10.rb $STUFF; done
```

Ran to completion and initial spot checks on the resulting chef data directories all look good!

**Comment by mihalis68** [comment] 2015-03-19 13:51
Actually this one-liner may not even be necessary. Taking out some of the hacks I had in knife to diagnose the issue with cookbook_path I am seeing knife download / work as expected. Will try a clean install to verify.

**Comment by mmzyk** [comment] 2015-03-19 20:33
Based on my testing, @mihalis68 is right. The cause of this error is having cookbook_path set to nil in the knife.rb. This bug can be worked around by either ensuring that is set or by using the --chef-repo-path option, which is essentially another way to set the cookbook_path for knife download via the command line.

If anyone else is able to verify these work arounds work, it would be appreciated. In the mean time, we'll try to track down why having the cookbook_path being set to nil doesn't work or else make the error message better so it is clear this is the case.

**Comment by mmzyk** [comment] 2015-03-20 18:44
All right, so to close this out. This bug is caused when the cookbook_path is set to nil. Basically, never set cookbook_path to nil. The reason this used to work back before Chef 11.8.0 is that in 11.6.2 we had this code: https://github.com/chef/chef/blob/11.6.2/lib%2Fchef%2Fchef_fs%2Fconfig.rb#L191-L199 that would set the paths for values that were not set, and this would ensure that the nil value got overwritten. 

With 11.8.0 this code was heavily refactored so that the setting of those values was done in the base config and this check ended up being removed. Instead of adding this check back, the way we intend to fix this is to add validation code to mixlib config that enables default value checking to occur (that would validate that a value isn't nil, for instance).

Until that is added, the work around is don't set any values to nil. We will also update the upgrading from Chef 10 blog post to no longer recommend setting the cookbook_path to nil, since that is now bad advice.

I'd like to thank @mihalis68 for his persistence in helping us with looking into the problem and it was his work that ultimately narrowed this down to to cookbook_path being set incorrectly.

I'm going to close this bug out now and we'll be adding a task to add the validation checking and will update the blog post, as already noted.

**Closed by mmzyk** 2015-03-20 18:44 UTC
Labels: Bug, Dev Tools

**Comment by mmzyk** [comment] 2015-03-20 21:01
The Chef blog post with the instructions for upgrading from Chef server 10 has been updated and has a note added to it to not set the cookbook_path to nil. https://www.chef.io/blog/2013/03/12/5106/

**Comment by mihalis68** [comment] 2015-03-31 18:03
Unfortunately in updating the Blog post I think you have disturbed the formatting of the knife configuration files. I am now seeing things like this :

```
transfer<em>repo = File.expand</em>path('..', File.dirname(<strong>FILE</strong>))
chef<em>server</em>url &quot;https://chef-11.example.com&quot;
node<em>name 'admin'
client</em>key &quot;#{transfer<em>repo}/.chef/admin.pem&quot;
repo</em>mode 'everything'
versioned<em>cookbooks true
chef</em>repo<em>path transfer</em>repo
```

it appears to have been html-escaped

**Comment by mmzyk** [comment] 2015-04-07 19:13
@mihalis68 Thanks for the heads up. I've updated the post to fix that. It turns out a markdown plugin that wasn't used on the blog when the post was originally written was messing up the post when it was updated.

Let me know if something else should be corrected. 

A link to the blog, just to make it easy to find: https://www.chef.io/blog/2013/03/12/5106/

**Comment by mihalis68** [comment] 2015-04-08 17:04
That now looks perfect!
