### ISSUE TITLE
ImmutableArray assignment to an AttrArray is evaluating to nil in 13.7 (node values assigned to node values where the value is an Array)

### ISSUE THREAD

**Issue by jschripsema** [chef/chef#6784] opened 2018-01-24 19:49 UTC
## Description
Attributes assigned a value from another node attribute, outside of string interpolation, are not getting assigned. This is often used in wrapper cookbooks, but can be replicated using a single cookbook.

## Chef Version
13.7.16

## Platform Version
CentOS 7

## Replication Case
attributes/default.rb
```default['cookbook1']['yum_servers'] = ['https://yum1.server.net', 'https://yum2.server.net']```

recipes/default.rb
```
node.default['cookbook2']['yum_servers'] = node['cookbook1']['yum_servers']

puts "node['cookbook1']['yum_servers']:"
puts node['cookbook1']['yum_servers']
puts "String node['cookbook1']['yum_servers']: #{node['cookbook1']['yum_servers']}"
puts "node['cookbook2']['yum_servers']:"
puts node['cookbook2']['yum_servers']
```

### 13.7.16
```
$ kitchen converge
-----> Converging <default-centos-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-centos-7>
       Starting Chef Client, version 13.7.16
       resolving cookbooks for run list: ["cookbook2::default"]
       Synchronizing Cookbooks:
         - cookbook2 (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       node['cookbook1']['yum_servers']:
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       node['cookbook2']['yum_servers']:
       Converging 0 resources
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 01 seconds
       Finished converging <default-centos-7> (0m4.50s).
```

### 13.6.4
```
-----> Starting Kitchen (v1.19.2)
-----> Converging <default-centos-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (13.6.4)
       Transferring files to <default-centos-7>
       Starting Chef Client, version 13.6.4
       resolving cookbooks for run list: ["cookbook2::default"]
       Synchronizing Cookbooks:
         - cookbook2 (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       node['cookbook1']['yum_servers']:
       https://yum1.server.net
       https://yum2.server.net
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       node['cookbook2']['yum_servers']:
       https://yum1.server.net
       https://yum2.server.net
       Converging 0 resources
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 01 seconds
       Finished converging <default-centos-7> (0m4.72s).
```

**Comment by mawatech** [comment] 2018-01-24 21:36
It seems that this commit is at least related: https://github.com/chef/chef/commit/0c29acc106ca774e230c8ef45694c8bffd166b69

It overwrites some methods like to_s and uniq.

I've modified the default.rb a bit:

```
tmp = ([] + node['cookbook1']['yum_servers']).uniq

print "node['cookbook1']['yum_servers']: "
puts node['cookbook1']['yum_servers']
puts
print "node['cookbook1']['yum_servers'].class.name: "
puts node['cookbook1']['yum_servers'].class.name
puts
puts "String node['cookbook1']['yum_servers']: #{node['cookbook1']['yum_servers']}"
print 'tmp:'
puts tmp
puts
print 'tmp.class.name:'
puts tmp.class.name
```

### 13.6.26:
```
       node['cookbook1']['yum_servers']: https://yum1.server.net
       https://yum2.server.net
       
       node['cookbook1']['yum_servers'].class.name: Chef::Node::ImmutableArray
       
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       tmp:https://yum1.server.net
       https://yum2.server.net
       
       tmp.class.name:Array
```
### 13.6.27:
```
       node['cookbook1']['yum_servers']: 
       node['cookbook1']['yum_servers'].class.name: Chef::Node::ImmutableArray
       
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       tmp:
       tmp.class.name:Array
```
### 13.7.16:
```
       node['cookbook1']['yum_servers']: 
       node['cookbook1']['yum_servers'].class.name: Chef::Node::ImmutableArray
       
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       tmp:
       tmp.class.name:Array
```

**Comment by mawatech** [comment] 2018-01-24 21:41
Btw.: If i use print instead of puts at least the logging works:

### 13.7.16:
```
       node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       node['cookbook1']['yum_servers'].class.name: Chef::Node::ImmutableArray
       
       String node['cookbook1']['yum_servers']: ["https://yum1.server.net", "https://yum2.server.net"]
       tmp:[]
       tmp.class.name:Array
```

So perhaps the .each method is broken?

**Comment by mawatech** [comment] 2018-01-24 22:30
And a even more simplified test:

```
puts '1'
puts node['cookbook1']['yum_servers']
puts '2'
puts "#{node['cookbook1']['yum_servers']}"
puts '3'
puts node['cookbook1']['yum_servers']
```
### 13.6.26:
```
       1
       https://yum1.server.net
       https://yum2.server.net
       2
       ["https://yum1.server.net", "https://yum2.server.net"]
       3
       https://yum1.server.net
       https://yum2.server.net
```
### 13.6.27:
```
       1
       2
       ["https://yum1.server.net", "https://yum2.server.net"]
       3
       https://yum1.server.net
       https://yum2.server.net
```
### 13.7.16:
```
       1
       2
       ["https://yum1.server.net", "https://yum2.server.net"]
       3
       https://yum1.server.net
       https://yum2.server.net
```
### 14.0.24:
```
       1
       2
       ["https://yum1.server.net", "https://yum2.server.net"]
       3
       https://yum1.server.net
       https://yum2.server.net
```

**Comment by lamont-granquist** [comment] 2018-01-24 23:52
hashes work:

```
#!/usr/bin/env chef-apply
node.default['foo']['baz'] = { one: "two" }
node.default['bar']['baz'] = node.default['foo']['baz']
puts "---- puts ----"
puts node['bar']['baz']
puts "---- pp ----"
pp node['bar']['baz']
```

```
% ./apply.rb
---- puts ----
{"one"=>"two"}
---- pp ----
{"one"=>"two"}
```

strings work:

```
% cat apply.rb
#!/usr/bin/env chef-apply
node.default['foo']['baz'] = "one"
node.default['bar']['baz'] = node.default['foo']['baz']
puts "---- puts ----"
puts node['bar']['baz']
puts "---- pp ----"
pp node['bar']['baz']
```

```
% ./apply.rb
---- puts ----
one
---- pp ----
"one"

arrays fail:

```
#!/usr/bin/env chef-apply
node.default['foo']['baz'] = [ "one", "two" ]
node.default['bar']['baz'] = node.default['foo']['baz']
puts "---- puts ----"
puts node['bar']['baz']
puts "---- pp ----"
pp node['bar']['baz']
```

```
% ./apply.rb
---- puts ----
---- pp ----
["one", "two"]
```

and fail only on puts, not on pp.

**Comment by lamont-granquist** [comment] 2018-01-24 23:55
Also appears to have nothing to do with the assignment of variables:

```ruby
% cat apply.rb
#!/usr/bin/env chef-apply
node.default['foo']['baz'] = [ "one", "two" ]
puts "---- puts ----"
puts node['foo']['baz']
puts "---- pp ----"
pp node['foo']['baz']
```

```
 % ./apply.rb
---- puts ----
---- pp ----
["one", "two"]
```

**Comment by lamont-granquist** [comment] 2018-01-25 00:03
ehrm, no `#to_s` works, which is why string interpolation works, but puts is not using that and is busted.

**Comment by lamont-granquist** [comment] 2018-01-25 00:13
calling anything (e.g. pp/#inspect/#pretty_print) first which results in an `ensure_generated_cache!` call being dispatched will 'fix' any subsequent `puts`.  whatever puts is calling it is not being caught by the dynamic `define_method` dispatch that wraps methods, not clear which api its hitting.  it is not the way that puts calls `to_ary` because that is correctly wrapped and is not being called.  and i can't use `method_missing` to find the API that puts is using, because the method isn't missing.

**Comment by lamont-granquist** [comment] 2018-01-25 01:04
so `io_puts_ary()` in `io.c` is what gets called, and this is one of those apis which discovers that the target inherits from Array using internal APIs and then pokes around in the internals of the Array and never seems to go through proper ruby method dispatch.  i suspect that trying to catch what Kernel.puts is doing and generate the cache lazily is going to fail and that we need to pregenerate the cache on assignment instead as the array is getting assigned at the default level.

**Comment by lamont-granquist** [comment] 2018-01-25 01:16
```
static VALUE
io_puts_ary(VALUE ary, VALUE out, int recur)
{
    VALUE tmp;
    long i;

    if (recur) {
        tmp = rb_str_new2("[...]");
        rb_io_puts(1, &tmp, out);
        return Qtrue;
    }
    ary = rb_check_array_type(ary);
    if (NIL_P(ary)) return Qfalse;
    for (i=0; i<RARRAY_LEN(ary); i++) {
        tmp = RARRAY_AREF(ary, i);
        rb_io_puts(1, &tmp, out);
    }
    return Qtrue;
}
```

i think rb_check_array_type() when it inherits from Array doesn't do anything which could be hooked (but on Objects that do not inherit from Array it calls `#to_ary` on them), and then it rolls its own `#each` loop without calling each, so that can't be hooked and `RARRAY_LEN(ary)` is just going to poke the internal datastructure and see that its empty (before the cache is filled).

**Comment by lamont-granquist** [comment] 2018-01-25 01:17
almost wondering if monkeypatching IO#puts isn't the lesser evil...

**Comment by jschripsema** [comment] 2018-01-25 03:29
It's not just on puts calls, I was just using those to troubleshoot/replicate the actual problem.
We have a cookbook which uses logic to set some attributes for the environment (DC/network segment), `node['cookbook1']['yum_servers']`. We then, by default, assign this in our yum wrapper cookbook `default['wrapper_yum']['yum_servers'] = node['cookbook1']['yum_servers']` and then use a map to create the actual repository urls.

```
current_urls = node['wrapper_yum']['yum_servers'].map { |server| "#{server}/repos/centos/#{major_version}/#{repo_dir}/$basearch/" }
yum_repository "current-#{repo}" do
    description           "CentOS-#{major_version} Current - #{repo.capitalize}"
    baseurl               current_urls.join(' ')
    enabled               false
    fastestmirror_enabled true
    gpgcheck              true
    gpgkey                gpgkeys.join(' ')
    action                current_action
  end
```

In 13.7.16, this creates a repo definition with no baseurls. No `puts` in sight (unless yum_repository uses this under the hood or our join is doing it). Strangely, I did notice in this more complicated example, that inserting a puts statement ahead of the assignment was actually fixing the assignment.

**Comment by lamont-granquist** [comment] 2018-01-25 03:54
okay so now you've got a (probably different) case where it looks like the assignment between nodes matters:

```
#!/usr/bin/env chef-apply

node.default['foo']['baz'] = [ "one", "two" ]
node.default['bar']['baz'] = node['foo']['baz']

node['bar']['baz'].map { |x| puts x }
```

that fails to work properly, but if i comment out the assignment and iterate over `node['foo']['baz']` then it works fine.

**Comment by jschripsema** [comment] 2018-01-25 04:02
I was just about to write up, what I thought was, a different bug (I thought edit_resource was acting oddly). But this fails on a completely normal wrapper cookbook as well. Standard wrapper for the `resolver` cookbook. No `map` methods, no `puts`.

```
node.default['resolver']['search'] = node['cookbook1']['search']

node.default['resolver']['nameservers'] = if node['cookbook1']['nameservers_default']
                                            node['domain']
                                          else
                                            node['cookbook1']['nameservers']
                                          end

include_recipe 'resolver::default'
```

Generates the following error:
```
Compiling Cookbooks...
       [2018-01-25T03:58:29+00:00] WARN: resolver::default requires that attribute ['resolver']['nameservers'] is set.
       Converging 0 resources
```

`nameservers` is also an array, so it looks like it's only affecting arrays (like you pointed out). But it really does seem to not being assigning them properly.

**Comment by lamont-granquist** [comment] 2018-01-25 20:19
actually `Chef::Node::ImmutableArray#[]` seems to be totally broken.  i'm seeing it call `chef/node/mixin/state_tracking.rb, 38` which should then call super at `chef/node/immutable_collections.rb, 127` but i can throw a raise in there and it never gets hit.

**Comment by lamont-granquist** [comment] 2018-01-25 20:32
no that's not it, it's the `['bar']` operator acting on `node['foo']` handing back an ImmutableArray with an empty cache.

**Comment by lamont-granquist** [comment] 2018-01-25 20:36
and then it has to be assigned to something like `node.default` which is actually `VividMash#[]=(key, value)` where the value side is an ImmutableArray.  if you assign the ImmutableArray to a standard variable and call map on it, then everything is fine.  and the problem is that the default value is not getting set at all in `node['bar']['baz'] = node['foo']['baz']`

**Comment by s-bernard** [comment] 2018-01-25 21:22
Hi,

I found a similar behavior with hashes:

In attributes/default.rb:
```ruby
default[cookbook_name]['hash'] = { 'string' => 'some' }
```

In recipe/default.rb:
```ruby
puts({}.merge(node[cookbook_name]['hash']))
puts({}.merge(node[cookbook_name]['hash'].to_h))
puts({}.merge(node[cookbook_name]['hash']))
```

Result:
```
{}
{"string"=>"some"}
{"string"=>"some"}
```

In you use `node[cookbook_name]['hash']` directly, it will work. But if you encapsulate it in a `{}.merge`, it won't. A work-around is to `to_h` it. Then it will continue to work.

**Closed** 2018-01-25 21:54 UTC
