### ISSUE TITLE
Knife SSL Check is not case insensitive

### ISSUE THREAD

**Issue by thommay** [chef/chef#5967] opened 2017-03-30 09:39 UTC
New to chef, however I believe that this could be an issue with knife. My chef-server was running on a VM with hostname "ubuntuVM".

Some info from when this wasn't working:

```
$ knife ssl check
Connecting to host ubuntuVM:443
Successfully verified certificates from 'ubuntuVM'

$ sudo openssl x509 -noout -in /var/opt/opscode/nginx/ca/ubuntuVM.crt -subject -issuer
subject= /C=US/O=YouCorp/OU=Operations/CN=ubuntuVM
issuer= /C=US/O=YouCorp/OU=Operations/CN=ubuntuVM

$ openssl s_client -connect ubuntuVM:443|tee /tmp/server-cert
depth=0 C = US, O = YouCorp, OU = Operations, CN = ubuntuVM
```

However the command was failing:
```
$ knife cookbook upload yum
Uploading yum [3.10.0]
ERROR: SSL Validation failure connecting to host: ubuntuvm - hostname "ubuntuvm" does not match the server certificate
ERROR: SSL Error connecting to https://ubuntuvm/bookshelf/organization-f3486b0086940c6933c77b35ce62fe8d/checksum-2aa31202e0a1433e0e49aa9cca35fad0?AWSAccessKeyId=043b6757e481c123bca417a25097da57ae19b579&Expires=1457354091&Signature=3alD0WJIR0s18f81HdWiJ/7Q2lg%3D, retry 1/5
```
Changing my VM hostname to 'ubuntuvm' fixed the issue:
```
$ knife ssl check
Connecting to host ubuntuvm:443
Successfully verified certificates from 'ubuntuvm'

$ knife cookbook upload yum
Uploading yum [3.10.0]
Uploaded 1 cookbook.
```

originally from @Doormouse2House as as chef/chef-dk#729

**Comment by mrminecart** [comment] 2017-11-27 20:03
Still suffering with this one :(

**Comment by dheerajd-msys** [comment] 2018-06-29 13:20
@thommay, @mrminecart Could you please help me with which chef you are getting this issue?

I've tried with chef v12.19.36, chefDK v2.5.3(chef v13.8.5) and with master branch code but unable to reproduce the issue.

**Chef-server**  : chef-server 12.17.33
```
ubuntu@dh-chef-server-UBU:~$ cat /opt/opscode/version-manifest.txt
chef-server 12.17.33
```
**Outputs for different chefs are:** 

**1. With chef v12.19.36**
```
PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> knife ssl check -c .\.chef\knife.rb
Connecting to host dh-chef-server-UBU.test:443
Successfully verified certificates from `dh-chef-server-UBU.test'

PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> knife cookbook upload starter -o .\cookbooks -c .\.chef\knife.rb
Uploading starter        [1.0.0]
Uploaded 1 cookbook.

PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> knife -v
Chef: 12.19.36
```
**2. With ChefDk v2.5.3 (chef v13.8.5)**
```
PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> chef -v
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> knife ssl check -c .\.chef\knife.rb
Connecting to host dh-chef-server-UBU.test:443
Successfully verified certificates from `dh-chef-server-UBU.test'

PS D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo> knife cookbook upload starter -o .\cookbooks -c .\.chef\knife.rb
Uploading starter        [1.0.0]
Uploaded 1 cookbook.
```
**3. With master branch**
```
PS D:\Chef_Repo\chef> bundle exec knife ssl check -c D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo\.chef\knife.rb
Connecting to host dh-chef-server-UBU.test:443
Successfully verified certificates from `dh-chef-server-UBU.test'


PS D:\Chef_Repo\chef> bundle exec knife cookbook upload starter -o D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo\cookbooks -c D:\Cards_worked\Msys-845-knife-ssl-check-mixcase\chef-starter\chef-repo\.chef\knife.rb
Uploading starter        [1.0.0]
Uploaded 1 cookbook
```

**Comment by dheerajd-msys** [comment] 2018-07-03 06:08
I've also tried this with workstation setup on Ubuntu 14 and tried out to reproduce the issue but issue hasn't been reproduced.

**1. With chef v12.19.36**
```
ubuntu@ip-172-31-86-5:~/chef-starter$ knife ssl check -c chef-repo/.chef/knife.rb
Connecting to host dh-chef-server-UBU.test:443
Successfully verified certificates from `dh-chef-server-UBU.test'


ubuntu@ip-172-31-86-5:~/chef-starter$ knife cookbook upload starter -o chef-repo/cookbooks/ -c chef-repo/.chef/knife.rb
Uploading starter        [1.0.0]
Uploaded 1 cookbook.

ubuntu@ip-172-31-86-5:~/chef-starter$
ubuntu@ip-172-31-86-5:~/chef-starter$ knife -v
Chef: 12.19.36
```
**2. With ChefDk v3.0.36 (chef v14.1.12)**
```
ubuntu@dh-chef-work-ubu:~$ chef -v
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72

ubuntu@dh-chef-work-ubu:~$ chef-client -v
Chef: 14.1.12

ubuntu@dh-chef-work-ubu:~/chef-starter$ knife ssl check -c chef-repo/.chef/knife.rb
Connecting to host dh-chef-server-UBU.test:443
Successfully verified certificates from `dh-chef-server-UBU.test'

ubuntu@dh-chef-work-ubu:~/chef-starter$ knife cookbook upload starter -o chef-epo/cookbooks/ -c chef-repo/.chef/knife.rb
Uploading starter        [1.0.0]
Uploaded 1 cookbook.
ubuntu@dh-chef-work-ubu:~/chef-starter$ 
```

**Comment by dheerajd-msys** [comment] 2019-04-11 06:46
@williamoverton Could you please check with my above comments and verify if you are getting this issue?

**Comment by williamoverton** [comment] 2019-04-11 06:53
@dheerajd-msys sorry I don't use chef any more so no longer have this issue.

Thanks for all your work.

Will

**Comment by dheerajd-msys** [comment] 2019-04-11 07:09
Thank you for update @williamoverton. Closing this issue now.

**Closed by dheerajd-msys** 2019-04-11 07:09 UTC
Labels: Component: Dev Tools, Priority: Medium, Type: Bug
