### ISSUE TITLE
Installing cookbooks from supermarket does work

### ISSUE THREAD

**Issue by karnold** [chef/chef#4157] opened 2015-11-11 23:23 UTC
When trying to install a cook book with dependencies it will attempt to grab the dependency and then fail with **"ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook apache2 in /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks"**

In this case the apache2 cookbook.  I can manually download the cookbook and extract it and it does not complain however.

```
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

And the full output from my terminal
```
it101:chef-repo karnold$ knife cookbook site install cacti
Installing cacti to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-cacti) exists, switching to it.
Downloading cacti from Supermarket at version 0.5.1 to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/cacti.tar.gz
Cookbook saved: /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/cacti.tar.gz
Removing pre-existing version.
Uncompressing cacti version 0.5.1.
Removing downloaded tarball
No changes made to cacti
Checking out the master branch.
Installing apache2 to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-apache2) exists, switching to it.
Downloading apache2 from Supermarket at version 3.1.0 to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/apache2.tar.gz
Cookbook saved: /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/apache2.tar.gz
Removing pre-existing version.
Uncompressing apache2 version 3.1.0.
Removing downloaded tarball
No changes made to apache2
Checking out the master branch.
ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook apache2 in /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks
```

**Comment by karnold** [comment] 2015-11-12 17:41
UPDATE: this seems to be an issue with repositories that only contain a metadata.json file and do not contain a metadata.rb file.  I attempted to open an issue with the apache2 repo owners, but they diverted the issue as a problem in chef

**Comment by btm** [comment] 2015-11-12 17:45
Take a look at https://github.com/chef/chef/issues/3888#issuecomment-155411499 for a little more specifics.

Closing as a duplicate of https://github.com/chef/chef/issues/3888

**Comment by coderanger** [comment] 2015-11-12 17:45
This was a bug between Stove and Supermarket that was fixed a while ago. Installing via berkshelf or librarian should work fine, and the `apache2` cookbook is deprecated so a new release is unlikely unless one of the cookbook team finds some time.

**Closed** 2015-11-12 17:45 UTC

**Comment by tas50** [comment] 2015-11-12 17:52
While the cookbook team maintains the httpd cookbook there is also an actively maintained apache2 cookbook at https://github.com/svanzoest-cookbooks/apache2 <https://github.com/svanzoest-cookbooks/apache2>
