### ISSUE TITLE
"mount" resource puts windows in unrecoverable state

### ISSUE THREAD

**Issue by spuder** [chef/chef#3904] opened 2015-09-10 00:20 UTC
If you attempt to use the `mount` resource, and there is a problem in the chef run. Windows will be unable to remove the network share, even after a reboot. 

```ruby
mount 'N:' do
  device '\\\\nas01.example.com'
  domain 'example.com'
  username 'foo'
  password 'correct-horse-battery-staple'
  action :mount
end

# Note that you need 3 slashes after 'file:'
remote_file 'C:\\someAwesomePackage.msi' do
  source 'file:///N:/someAwesomePackage.msi'
end

```

![screenshot 2015-09-09 18 12 51](https://cloud.githubusercontent.com/assets/242382/9777221/8df8243a-571e-11e5-8947-8440423d4d96.png)

If you look at `get-psdrive` it shows the network point is mounted, even if you explicitly umount it. 

```chef
mount 'N:' do
  action [:disable, :umount]
end
```

![screenshot 2015-09-10 12 47 56](https://cloud.githubusercontent.com/assets/242382/9797825/6a13483c-57ba-11e5-9316-ec74861d63db.png)

Not even a `remove-psdrive -name N -force` can unmount the drive. The VM is completely hosed. 

## Steps to reproduce
Take the above recipe, but change the source to an incorrect location. 

    #ok
    source 'file:///N:/someAwesomePackage.msi'

    #not ok
    source 'N:/someAwesomePackage.msi'

Then run chef

    chef-apply foo.rb

The chef run will fail, and you will now have a mapped network drive 'N' which is impossible to get rid of without editing the registry. All future chef runs will also fail because the N drive is already present. Opening powershell will also error with the following output: `Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.`

## Proposed Solution

If a `mount` resource is present in the catalog and there is a problem with the chef run. Notify all `mount` resources with `:umount` before exiting.

**Comment by spuder** [comment] 2015-09-10 19:22
Note this bug applies regardless if using `chef-apply`, `chef-client` chef zero or chef solo. 

Chef 12.4.1
Windows 2012R2

**Comment by thommay** [comment] 2015-12-01 11:13
cc @chef/client-windows

**Comment by mwrock** [comment] 2015-12-05 01:32
I recall having issues with unmounting on windows several months back and it was likely chef 11. We need to take a deeper look, but if you find yourself in this bad state, instead of using `remove-psdrive` which does not work, try something like this:
```
net use z: /delete
```

**Comment by hk135** [comment] 2015-12-09 15:47
I have this issue on chef 12.5.1, rolled it out to all of our vms and now have this same problem. The way around it I found is:

### Fix Disconnected Mount point
mount "R:" do
	action :umount
	device '\\\\mittens.precedenthost.local\\wincd'
	ignore_failure true
end

above the initial mount resource. Obviously its a workaround not a solution as I still end up with R: on every vm.

**Comment by DavidMcGrathUnionStreet** [comment] 2016-01-13 10:42
I have just run into this issue. Any idea when this will be fixed?

**Comment by chefsalim** [comment] 2016-03-10 00:53
I'm not able to repro this issue with a domain share (with a script very similar to the one above), using Chef 12.5.1 and Windows 2012 R2.  Any thoughts on reliably re-creating would be great.

**Comment by mwrock** [comment] 2016-03-10 03:00
I just tried to repro again as well and also mounted to a domain based share and with domain user credentials:
```
mount 'N:' do
 device '\\\\192.168.137.79\\c$'
 action :mount
 domain 'kitchen.local'
 username 'vagrant'
 password 'Pass@word1'
end

file 'N:/users/vagrant/mything.txt' do
  content 'hello'
  notifies :umount, 'mount[N:]', :immediately
end
```
Everything worked.

**Comment by mwrock** [comment] 2016-03-10 04:22
Closing due to inability to reproduce with latest chef client. Please reopen or file a new issue if you are still having issues.

**Closed by mwrock** 2016-03-10 04:22 UTC
Labels: Bug, High Priority, Windows
