### ISSUE TITLE
Chef attribute merging between colons and quotes is still broken when using force_default

### ISSUE THREAD

**Issue by eric-tucker** [chef/chef#3427] opened 2015-05-26 16:48 UTC
Original issue:
#2712 

I am now seeing that when using force_default the attributes aren't being overwritten when trying to override solr cookbook attributes.

In the solr cookbook's attributes/default.rb:
````
default['solr']['version'] = '4.6.1'
default['solr']['data_dir'] = '/etc/solr'
````

In my cookbook:
````
force_default[:solr][:version] = '4.10.2'
force_default[:solr][:data_dir] = "/opt/solr-#{node[:solr][:version]}/example/solr"
````

When I run this, the data_dir is still /etc/solr.

Only when I change to override in my cookbook does it update the data_dir property.  Interestingly enough the version was updated.  Go figure...

There's obviously still something wonky going on with attribute precedence and setting attributes based on other attributes when using force_default.

@tyler-ball suggested it was something broken with force_*:
https://github.com/chef/chef/issues/2712#issuecomment-68566898

**Comment by lamont-granquist** [comment] 2015-06-01 16:25
I tried to replicate this and couldn't.

- does your cookbook correctly specify a dependency on the solr cookbook so that its attribute files will be parsed first?
- where are you trying to check the attributes and how are you trying to check them?

You should also not be setting force_default in an attributes file, it won't do anything useful over the use of default.  The force_default level is only useful to set in recipes in order to force setting in the recipe to take precedence.   You probably need to back up and explain how you got to the point of trying to set force_default in an attributes file as well.

**Comment by eric-tucker** [comment] 2015-06-01 16:45
Adding the solr dependency to metadata.rb does not make a difference.  I even put an include_attribute line for the solr cookbook inside the attribute file right above my force_default lines and it makes no difference.

At run time, one of my template commands fails because the path does not exist:
````
template "#{node["solr"][:data_dir]}/collection1/conf/data-config.xml" do
````
Output:

````
    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    Parent directory /etc/solr/collection1/conf does not exist.
````

Here is my role run list:
````
  "run_list": [
    "recipe[base]",
    "recipe[solr]",
    "recipe[my_cookbook]",
    "recipe[my_cookbook::solr_server]"
  ],

I question why you suggest not using force_default in an attribute file:
https://docs.chef.io/attributes.html#attribute-precedence

It's right there that force_default in an attribute file is valid and a higher level than default in an attribute file.  I reserve the use of override for when I actually need something higher than force_default.  My reason for using force_default is in case the attribute files get included more than once because of run lists including other run lists which cause multiple loading of attribute files during convergence.  I want to ensure that the force_default value still wins and is not "overwritten" by the double include of another attribute file setting the values with default.

**Comment by lamont-granquist** [comment] 2015-06-01 16:45
Doing interpolation with node attributes in an attribute file is also a huge antipattern and often doesn't work like you think it should (although in your example I think it works fine, but there are ways that you can try to use that by wrapping your wrapper cookbook and setting the `node[:solr][:version]` which will fail to render the data_dir way you might expect.

**Comment by eric-tucker** [comment] 2015-06-01 16:48
Yes I know once has to be careful when defining attributes based on other attributes so I attempt to only do it in my "bottom" or wrapper cookbooks.

If it's an antipattern then what is the recommended method?  Attributes defined in recipes?  Or does one need to copy/paste interpolated values everywhere they are needed?

**Comment by lamont-granquist** [comment] 2015-06-01 16:48
There's no multiple loading of attribute files during convergence.  If its been read before it is skipped.

I'm quite positive that using force_default in an attribute file has zero benefit over using default.  You can use it, but it does nothing particularly useful, which suggests to me that you've got some confusion going on over parse order of the files or of attribute precedence somewhere.

**Comment by eric-tucker** [comment] 2015-06-01 16:50
My experience is that the order in which the run lists loads the attribute files will cause default to behave based solely on what is loaded last.

If the run list is:
cookbook1
cookbook2

And you have cookbook1/attributes/default:rb

````
default[:my_attribute] = 1
````

cookbook2/attributes/default.rb:
````
default[:my_attribute] = 2
````
You end up with node[:my_attribute] = 2

However, if the run list is flipped you end up with the attribute having the value 1.

**Comment by lamont-granquist** [comment] 2015-06-01 16:50
Best thing to do for interpolated values is to put them in recipe code using actual ruby variables.  When you have library cookbooks that use them, the best thing to do is rewrite the library cookbook to stop using attributes, or to rewrite the library cookbook to stop using interpolation.  Barring that, then copypasta is the best solution.  In this case trying to be DRY is going to ultimately be much more confusing than just copying a version string in a couple places.

**Comment by eric-tucker** [comment] 2015-06-01 16:53
Agreed - I've seen hacks to force recalculation of interpolated values such as this:

````
#This forces re-evaluation of all attributes indexed with "tomcat" that might have been derived from base_version
node.from_file(run_context.resolve_attribute(*parse_attribute_file_spec('tomcat')))
````

This seems quite hacky from a Chef standpoint though.

If force_default is really that confusing and you're recommending against its usage, perhaps it should have never been introduced into the Chef attribute precedence tree.   Was there really a scenario where override in an attribute file or recipe was not sufficient?

**Comment by lamont-granquist** [comment] 2015-06-01 16:54
Yes, you've got that correct.   But if you've got multiple cookbooks setting the same attribute you should really have dependencies setup between them so that cookbook2 always comes last.   If you've got multiple app cookbooks setting the same variable and they may not strictly depend on each other, but you always want one to win that sounds like something really badly architected.

**Comment by eric-tucker** [comment] 2015-06-01 17:00
Let me clarify an exact scenario I've dealt with.

I write two roles:
* Batch server
* Web server

Both of these are PHP servers.

Batch server role is something like this:
* php (cookbook)
* batch server (recipe from app cookbook)

Web server role is something like this:
* php
* web server (recipe from the same app cookbook)

However, sometimes I make what we call "all in one" servers so my role is:
* batch server (role)
* web server (role)

This ends up expanding to:
* php
* batch
* php
* web

Keep in mind that the batch and web server recipes are from the SAME cookbook.  In that same cookbook the attributes file tries to set PHP attributes to override the php cookbook attributes.

Without using force_default I would often find that the values would not be reliably set, and they would typically remain set with the values from the php cookbook's attribute file and NOT from my attribute file in my app cookbook.

So either I'm doing something "wrong" or force_default makes sense for this scenario.

**Comment by lamont-granquist** [comment] 2015-06-01 17:06
force_default is in fact evil and probably should never have been invented.

The problem was that back when Chef 11 came out, people were setting node attribute values in cookbook recipes that were considered library cookbooks.  Consumers of those cookbooks wanted a way to override those values with wrapper cookbooks, but the problem is that the recipe code would set the node attr then render it into a template non-lazily (lazy attributes didn't even exist).  So the precedence level of setting default attrs in recipe code was dropped so that roles and attributes had a higher priority, so that a wrapper cookbook could override the recipe code of the wrapped cookbook.

The other users complained about recipe code not taking precedence over attributes and roles but they couldn't use override so force_default was invented solely to restore the old precedence level in recipe code.

The moral of the story, however, is to stop setting attributes in recipe code.   The node object that describes the system being built should be fully built by the time all the attributes files are parsed.  Then the recipe code should use ruby variables to do munging work, and to pass values between cookbooks they should use the node[:run_state] or use plain old ruby libraries.  Recipe code can set data on the node for output to solr but there should be a single 'producer' which sets that attribute and other recipe code should not consume or set that attribute -- its meant for search.

If you don't follow that, its not just that you need to know about force_default and the history of attribute precedence but there's the interpolation problems, there's the hacky re-resolving of attribute files, plus you need to worry about compile/converge mode and you start writing all your templates with lazy {} attributes everyhwere (or getting aggravated that library cookbooks don't use lazy {}). 

So attributes are an enormous footgun.  If you think you're smarter than attributes, then usually you keep digging deeper and deeper and there's no light at the end of the tunnel.  If you keep attributes really stupid -- description of the node that is complete at the end of the attributes file parsing, just use default attributes, don't use interpolation -- then it usually winds up good, and you don't have to become an expert.

Anyway, I'm still not sure that has anything to do with your problem...

**Comment by lamont-granquist** [comment] 2015-06-01 17:13
So one thing I'd suggest is that your batch and web cookbooks both have `depends "php"` lines in them.  If you're using recipes out of the php cookbook you should also `include_recipe "php::whatever"` lines up at the top of the recipes.  Then you can drop the php cookbook out of the explicit run_list.

Also you should probably pull apart the batch and web recipes into different cookbooks.  Are you expecting that `attributes/batch.rb` and `attributes/web.rb` only get parsed when you have the associated recipe in the run_list?  That's a fairly common mistake and it doesn't work that way -- every attributes file in a cookbook is parsed in alphanumeric sort order because it doesn't have accurate information about which recipes might or might not be run later without actually executing the recipes to find all the include_recipe statements that actually execute.

**Comment by lamont-granquist** [comment] 2015-06-01 17:17
Still trying to replicate your actual problem...

Obvious missing question:  which chef-client version?  I'm trying on 12.4.0.rc.0 and can't replicate it.  There were additional patches that went in and I think you may need to be on at least 12.2.0 to get all the patches to attributes.

**Comment by eric-tucker** [comment] 2015-06-01 17:17
12.3.0.  The latest from the ChefDK 0.6

**Comment by lamont-granquist** [comment] 2015-06-01 17:44
That should be good enough.  So, if you switch between force_default and override that doesn't show that you're exercising the bug in question.  The real test is that when you access `node[:solr]` vs. `node['solr']` or switch the setter between strings and symbols that you see different behavior.

**Comment by eric-tucker** [comment] 2015-06-01 17:55
Switching between quotes and colons in the recipe does not seem to make a difference.  I tried switching everything to quotes and the behaviour is still present (the attribute isn't set correctly).

Switching between quotes and colons in the recipe does not seem to make a difference.  I tried switching everything to quotes and the behaviour is still present (the attribute isn't set correctly).

This may help clear things up.  I'm using Chef Zero.  Here is my grep against my chef zero repo directory:

````
/etc/chef/zero/cookbooks/solr/attributes/default.rb:default['solr']['data_dir'] = '/etc/solr'
/etc/chef/zero/cookbooks/solr/recipes/default.rb:directory node['solr']['data_dir'] do
/etc/chef/zero/cookbooks/solr/recipes/default.rb:    :solr_home => node['solr']['data_dir'],
/etc/chef/zero/cookbooks/solr/recipes/default.rb:    :solr_home => node['solr']['data_dir'],
/etc/chef/zero/cookbooks/my_cookbook/attributes/solr_config.rb:force_default["solr"][:data_dir] = "/opt/solr-#{node["solr"][:version]}/example/solr"
/etc/chef/zero/cookbooks/my_cookbook/recipes/solr_server.rb:template "#{node["solr"][:data_dir]}/collection1/conf/data-config.xml" do
/etc/chef/zero/cookbooks/my_cookbook/recipes/solr_server.rb:remote_file "#{node["solr"][:data_dir]}/collection1/conf/schema.xml" do
/etc/chef/zero/cookbooks/my_cookbook/recipes/solr_server.rb:remote_file "#{node["solr"][:data_dir]}/collection1/conf/solrconfig.xml" do
````

**Comment by lamont-granquist** [comment] 2015-06-01 18:01
So I'm pretty sure then that you don't have a reoccurrence of the symbols-vs-strings bug.  I still can't seem to replicate it.

**Comment by eric-tucker** [comment] 2015-06-01 18:03
Hard to say.  force_default should take precedence regardless of anything else going on.  If override works, force_default should in this case.

However, if you're telling me that force_default is bad to use, then I will agree with that and avoid using it.  I currently have no requirement to use force_default over using override.  I've simply been conservative in my precedence usage in case I needed override to overrule force_default at some point.

**Comment by lamont-granquist** [comment] 2015-06-01 18:04
I don't see how you should need to use override though either, and I can't replicate the problem.

**Comment by lamont-granquist** [comment] 2015-06-01 18:05
If you look in the debug logs it'll tell you how its loading the attributes files:

```
[2015-06-01T11:04:30-07:00] DEBUG: Cookbooks to compile: [:solr, :test]
[2015-06-01T11:04:30-07:00] DEBUG: Loading cookbook test's library file: /home/lamont/.chef/local-mode-cache/cache/cookbooks/test/libraries/default.rb
[2015-06-01T11:04:30-07:00] DEBUG: Node coredump.scriptkiddie.lan loading cookbook solr's attribute file /home/lamont/.chef/local-mode-cache/cache/cookbooks/solr/attributes/default.rb
[2015-06-01T11:04:30-07:00] DEBUG: Loading Attribute solr::default
[2015-06-01T11:04:30-07:00] DEBUG: Node coredump.scriptkiddie.lan loading cookbook test's attribute file /home/lamont/.chef/local-mode-cache/cache/cookbooks/test/attributes/default.rb
[2015-06-01T11:04:30-07:00] DEBUG: Loading Attribute test::default
```

**Comment by jaymzh** [comment] 2015-06-01 18:19
@lamont-granquist  is right that you probably don't need want override or force_override.

But, the statement "you should never set attributes in recipes" is patently wrong. It is exactly the place to set data in wrapper cookbooks. Doing it in attributes files is absolutely not guaranteed to work.

Please stop telling people that.

The only way to provide a sane ordered API via data is to set let all callers set that data in recipes. There is no other way to do this sanely (other than to not use attributes at all).

The whole idea if people doing

```
  default['path'] = '/path/'
  default['file'] = 'file'
  default['fullpath'] = node['path'] + node['file']
```

in an attribute file and expecting to be able to change node['file'] in a role file and have that work was because people wanted unrealistic magic... it didn't work because it shouldn't have worked... and then Chef made it work that way which then required things like force_default to get any sort of wrapper cookbooks to work again.

Setting attributes in recipes is *absolutely* the way to change things in between attribute-loading time (cookbooks setting up their API) and run-time (data consumption time), and it's *absolutely* a reasonable thing to do. All of Facebook's published cookbooks require its wrappers to do this, and I hope to release more soon.

**Comment by lamont-granquist** [comment] 2015-08-05 20:36
@jaymzh you don't need to use an attribute for everything.  Just use `fullpath = node['path'] + node['file']` and there's no computed attribute issue.

**Comment by lamont-granquist** [comment] 2015-09-23 17:44
So, closing this because:

1. there's workarounds
2. i couldn't repro
3. i'm literally rewriting all this code anyway #3721

**Closed by lamont-granquist** 2015-09-23 17:44 UTC
