### ISSUE TITLE
Issues with yum packages that have epoch in their version

### ISSUE THREAD

**Issue by andreidum** [chef/chef#8843] opened 2019-08-23 11:24 UTC
## Inconsistent behaviour when installing packages without specifying the epoch

Some packages, like _jdk1.8_ version _2000:1.8.0_191-fcs.x86_ do not converge when the epoch and arch are not provided in the _version_ property, but others, like tcpdump version _14:4.9.2-3.el7.x86_, do.

## Removing packages has no effect unless the full NEVRA string is passed in the version

Unless I provide the full NEVRA string, I am unable to remove packages that have epochs in their version.

## Chef Version
15.2.0
## Platform Version
CentOS 7.6.1810

## Replication Case
```
# chef-apply -e "yum_package 'jdk1.8' do version '1.8.0_191-fcs'; action :install  end"
# chef-apply -e "yum_package 'tcpdump' do version '4.9.2-3.el7' ; action :remove end"
```
## Non-idempotent installs
```
#jdk1.8 is not idempotent

[root@andrei-test ~]# rpm -qi jdk1.8 |head -n5
Name        : jdk1.8
Epoch       : 2000
Version     : 1.8.0_191
Release     : fcs
Architecture: x86_64

 chef-apply -l trace -e "yum_package 'jdk1.8' do version '1.8.0_191-fcs'; action :install  end"
[2019-08-23T11:04:12+00:00] TRACE: Resources for generic yum_package resource enabled on node include: [Chef::Resource::YumPackage]
[2019-08-23T11:04:12+00:00] TRACE: Resource for yum_package is Chef::Resource::YumPackage
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[jdk1.8] action install[2019-08-23T11:04:12+00:00] INFO: Processing yum_package[jdk1.8] action install ((chef-apply cookbook)::(chef-apply recipe) line 1)
[2019-08-23T11:04:12+00:00] TRACE: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2019-08-23T11:04:12+00:00] TRACE: Provider for action install on resource yum_package[jdk1.8] is Chef::Provider::Package::Yum
[2019-08-23T11:04:13+00:00] TRACE: sending '{"action":"whatinstalled","provides":"jdk1.8"}' to python helper
[2019-08-23T11:04:13+00:00] TRACE: got 'jdk1.8 2000:1.8.0_191-fcs x86_64' from python helper
[2019-08-23T11:04:13+00:00] TRACE: parsed jdk1.8-2000:1.8.0_191-fcs.x86_64 from python helper
[2019-08-23T11:04:13+00:00] TRACE: sending '{"action":"versioncompare","versions":["2000:1.8.0_191-fcs.x86_64","1.8.0_191-fcs"]}' to python helper
[2019-08-23T11:04:13+00:00] TRACE: got '1' from python helper
[2019-08-23T11:04:13+00:00] TRACE: sending '{"action":"whatavailable","provides":"jdk1.8","version":"1.8.0_191","release":"fcs"}' to python helper
[2019-08-23T11:04:13+00:00] TRACE: got 'jdk1.8 2000:1.8.0_191-fcs x86_64' from python helper
[2019-08-23T11:04:13+00:00] TRACE: parsed jdk1.8-2000:1.8.0_191-fcs.x86_64 from python helper
[2019-08-23T11:04:13+00:00] TRACE: sending '{"action":"versioncompare","versions":["2000:1.8.0_191-fcs.x86_64","1.8.0_191-fcs"]}' to python helper
[2019-08-23T11:04:13+00:00] TRACE: got '1' from python helper
[2019-08-23T11:04:13+00:00] TRACE: yum_package[jdk1.8] jdk1.8 2000:1.8.0_191-fcs.x86_64 needs updating to 1.8.0_191-fcs
[2019-08-23T11:04:13+00:00] TRACE: sending '{"action":"whatinstalled","provides":"jdk1.8.x86_64"}' to python helper
[2019-08-23T11:04:14+00:00] TRACE: got 'jdk1.8 2000:1.8.0_191-fcs x86_64' from python helper
[2019-08-23T11:04:14+00:00] TRACE: parsed jdk1.8-2000:1.8.0_191-fcs.x86_64 from python helper
[2019-08-23T11:04:14+00:00] TRACE: sending '{"action":"versioncompare","versions":["2000:1.8.0_191-fcs.x86_64","2000:1.8.0_191-fcs.x86_64"]}' to python helper
[2019-08-23T11:04:14+00:00] TRACE: got '0' from python helper
Loaded plugins: fastestmirror, s3, versionlock
Loading mirror speeds from cached hostfile
Excluding 3 updates due to versionlock (use "yum versionlock status" to show them)
Package 2000:jdk1.8-1.8.0_191-fcs.x86_64 already installed and latest version
Nothing to do
[2019-08-23T11:04:14+00:00] INFO: yum_package[jdk1.8] installed jdk1.8 at 1.8.0_191-fcs

    - install version 1.8.0_191-fcs of package jdk1.8
[2019-08-23T11:04:14+00:00] DEBUG: Exiting
```

vs

```
[root@andrei-test ~]# rpm -qi tcpdump |head -n5
Name        : tcpdump
Epoch       : 14
Version     : 4.9.2
Release     : 3.el7
Architecture: x86_64

[root@andrei-test ~]#  chef-apply -l trace -e "yum_package 'tcpdump-4.9.2-3.el7' do action :install end "


Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump-4.9.2-3.el7] action install[2019-08-23T10:47:41+00:00] INFO: Processing yum_package[tcpdump-4.9.2-3.el7] action install ((chef-apply cookbook)::(chef-apply recipe) line 1)
[2019-08-23T10:47:41+00:00] TRACE: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2019-08-23T10:47:41+00:00] TRACE: Provider for action install on resource yum_package[tcpdump-4.9.2-3.el7] is Chef::Provider::Package::Yum
[2019-08-23T10:47:41+00:00] TRACE: sending '{"action":"whatinstalled","provides":"tcpdump-4.9.2-3.el7"}' to python helper
[2019-08-23T10:47:41+00:00] TRACE: got 'tcpdump 14:4.9.2-3.el7 x86_64' from python helper
[2019-08-23T10:47:41+00:00] TRACE: parsed tcpdump-14:4.9.2-3.el7.x86_64 from python helper
[2019-08-23T10:47:41+00:00] TRACE: yum_package[tcpdump-4.9.2-3.el7] tcpdump-4.9.2-3.el7 14:4.9.2-3.el7.x86_64 already installed
[2019-08-23T10:47:41+00:00] TRACE: yum_package[tcpdump-4.9.2-3.el7] is already installed - nothing to do
  * yum_package[tcpdump-4.9.2-3.el7] action install (up to date)
```

## Removing packages has no effect unless the full NEVRA string is passed in the version

```
[root@andrei-test ~]# chef-apply -e "yum_package 'tcpdump' do version '4.9.2-3.el7' ; action :remove end ; execute 'rpm -q tcpdump' " 
Recipe: (chef-apply cookbook)::(chef-apply recipe) 
* yum_package[tcpdump] action remove (up to date) 
* execute[rpm -q tcpdump] action run 
- execute rpm -q tcpdump 
[root@andrei-test ~]# chef-apply -e "yum_package 'tcpdump' do version '4.9.2' ; action :remove end ; execute 'rpm -q tcpdump' " 
Recipe: (chef-apply cookbook)::(chef-apply recipe) 
* yum_package[tcpdump] action remove (up to date) 
* execute[rpm -q tcpdump] action run 
- execute rpm -q tcpdump 
[root@andrei-test ~]# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2' ; action :remove end ; execute 'rpm -q tcpdump' " 
Recipe: (chef-apply cookbook)::(chef-apply recipe) 
* yum_package[tcpdump] action remove (up to date) 
* execute[rpm -q tcpdump] action run 
- execute rpm -q tcpdump 
[root@andrei-test ~]# rpm -q tcpdump 
tcpdump-4.9.2-3.el7.x86_64


## trace
chef-apply -l trace  -e "yum_package 'tcpdump' do version '4.9.2-3.el7' ; action :remove end "

[2019-08-23T11:22:47+00:00] TRACE: Resources for generic yum_package resource enabled on node include: [Chef::Resource::YumPackage]
[2019-08-23T11:22:47+00:00] TRACE: Resource for yum_package is Chef::Resource::YumPackage
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove[2019-08-23T11:22:47+00:00] INFO: Processing yum_package[tcpdump] action remove ((chef-apply cookbook)::(chef-apply recipe) line 1)
[2019-08-23T11:22:47+00:00] TRACE: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2019-08-23T11:22:47+00:00] TRACE: Provider for action remove on resource yum_package[tcpdump] is Chef::Provider::Package::Yum
[2019-08-23T11:22:48+00:00] TRACE: sending '{"action":"whatinstalled","provides":"tcpdump"}' to python helper
[2019-08-23T11:22:48+00:00] TRACE: got 'tcpdump 14:4.9.2-3.el7 x86_64' from python helper
[2019-08-23T11:22:48+00:00] TRACE: parsed tcpdump-14:4.9.2-3.el7.x86_64 from python helper
[2019-08-23T11:22:48+00:00] TRACE: sending '{"action":"versioncompare","versions":["14:4.9.2-3.el7.x86_64","4.9.2-3.el7"]}' to python helper
[2019-08-23T11:22:48+00:00] TRACE: got '1' from python helper
[2019-08-23T11:22:48+00:00] TRACE: sending '{"action":"whatavailable","provides":"tcpdump","version":"4.9.2","release":"3.el7"}' to python helper
[2019-08-23T11:22:48+00:00] TRACE: got 'tcpdump 14:4.9.2-3.el7 x86_64' from python helper
[2019-08-23T11:22:48+00:00] TRACE: parsed tcpdump-14:4.9.2-3.el7.x86_64 from python helper
[2019-08-23T11:22:48+00:00] TRACE: yum_package[tcpdump] package does not exist - nothing to do
 (up to date)
[2019-08-23T11:22:48+00:00] DEBUG: Exiting
```

**Comment by lamont-granquist** [comment] 2019-08-23 22:22
If the epoch is omitted it is zero per the RPM spec, so "4.9.2" is strictly equal to "0:4.9.2" which does not match "14:4.9.2" so that would be correct behavior not to match, not a bug to fix there.

The version string is also not equivalent to inserting the version in the name.  The behavior of `yum_package <ARGUMENT>` should be the same as `yum install <ARGUMENT>` or `yum remove <ARGUMENT>` fairly strictly.  The behavior of the version argument first applies the search criteria of the argument in the name and then filters it after the fact which is going to produce different results.  I'd recommend not using the version property on the yum_package resource due to the inherently different behavior.

I'm honestly not certain why you'd want to remove a specific version rather than removing all versions, that feels very non-declarative.  But if you just need to do that it should work in the name either with `yum_package "tcpdump-4.9.2"; action :remove end` or with the epoch globbed `yum_package "tcpdump-*:4.9.2"; action :remove end` an epoch glob in the version might work as well `version "*:4.9.2"`, but specifying the epoch explicitly really is correct according to the NEVRA definition.

**Comment by andreidum** [comment] 2019-08-26 10:37
My use-case is that I have a custom resource which wraps yum_package and does a few other things. The version property is required for my custom resource for all actions, and I currently pass the name and version arguments verbatim to _yum_package_ 

I will look at refactoring my code to take into account your comment, as it looks like I should avoid using the version argument whenever possible when dealing with yum_package resources. Would you say that these notes apply to dnf package resources as well? 


> an epoch glob in the version might work as well version "*:4.9.2", but specifying the epoch explicitly really is correct according to the NEVRA definition.

This doesn't seem to work...
```
[root@andrei-test ~]#   chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7' ; action :remove end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove (up to date)
[root@andrei-test ~]#   chef-apply -e "yum_package 'tcpdump' do version '*:4.9.2-3.el7' ; action :remove end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove (up to date)
```
Only when specifying the full nevra in the version property I can remove the package.
```
# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7.x86_64' ; action :remove ; arch 'x86_64' ; end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove
    - remove version 14:4.9.2-3.el7.x86_64 of package tcpdump
```

Another potential issue is that `action :install` and `action :remove` are not symmetrical even when providing all the NEVRA attributes.


```
# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7.x86_64' ; action :remove ; end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove
    - remove version 14:4.9.2-3.el7.x86_64 of package tcpdump

# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7.x86_64' ; action :install end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action install
    * No candidate version available for tcpdump
    ================================================================================
    Error executing action `install` on resource 'yum_package[tcpdump]'
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for tcpdump

[root@andrei-test ~]# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7' ; arch 'x86_64' ; action :install ; end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action install
    - install version 14:4.9.2-3.el7 of package tcpdump
[root@andrei-test ~]# chef-apply -e "yum_package 'tcpdump' do version '14:4.9.2-3.el7' ;arch 'x86_64' ;  action :remove ; end ; "
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[tcpdump] action remove (up to date)
    
```

**Comment by tas50** [comment] 2019-09-09 17:22
I'm going to close this based on @lamont-granquist's response. We believe that while odd at times, the current implementation is correct.

**Closed by tas50** 2019-09-09 17:22 UTC
Labels: Status: Untriaged

**Comment by lamont-granquist** [comment] 2019-09-13 18:14
See #8883, we're going to go down the road of forcing users to use epochs in the version property more or less.

It isn't sane to try to support omitting necessary epochs in the version, so chef is going to need to throw in that circumstance, the bug here is that the version property is only doing fuzzy matching in some circumstances against the package version and that behavior actually needs to end.  If the package has an epoch, that needs to be required as part of the chef version property.  Users need to be explicit and Chef needs to not try to do magical inference.
