### ISSUE TITLE
LXC lwrp doesn't work after upgrade to chef 12.5.1

### ISSUE THREAD

**Issue by iroller** [chef/chef#4224] opened 2015-12-02 18:24 UTC
LWRP from LXC cookbook doesn't work after upgrading from 12.4.0 to 12.5.1. Switching back to 12.4.0 works fine.

Didn't have time yet to figure out if it can be fixed in the cookbook itself, in a way we're using that lwrp or it's an issue in Chef.

https://github.com/hw-cookbooks/lxc/blob/master/providers/config.rb#L77

```
ArgumentError
  -------------
  wrong number of arguments (0 for 1)

  Cookbook Trace:
  ---------------
  /var/chef/cache/cookbooks/lxc/providers/config.rb:77:in `block (2 levels) in class_from_file'
  /var/chef/cache/cookbooks/lxc/providers/config.rb:75:in `block in class_from_file'
```

More logs:
```
================================================================================                                                                                      [326/7593]
  Error executing action `create` on resource 'lxc_config[my-sandbox]'
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (0 for 1)

  Cookbook Trace:
  ---------------
  /var/chef/cache/cookbooks/lxc/providers/config.rb:77:in `block (2 levels) in class_from_file'
  /var/chef/cache/cookbooks/lxc/providers/config.rb:75:in `block in class_from_file'

  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/lxc/providers/container.rb

   54:     lxc_config new_resource.name do
   55:       action :create
   56:       default_bridge new_resource.default_bridge
   57:     end
   58:   end

  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/lxc/providers/container.rb:54:in `block in class_from_file'

  lxc_config("my-sandbox") do
    action [:create]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :lxc_config
    cookbook_name "bc_containers"
    cap_drop ["audit_control", "audit_write", "dac_read_search", "mac_admin", "mac_override", "mknod", "setfcap", "setpcap", "sys_module", "sys_nice", "sys_pacct", "sys_rawio", "
sys_resource", "sys_time", "sys_tty_config"]
    tty 0
    default_bridge "lxcbr0"
    utsname "my-sandbox"
    rootfs "/var/lib/lxc/my-sandbox/rootfs"
    mount "/var/lib/lxc/my-sandbox/fstab"
    network {"type"=>"veth", "link"=>"lxcbr0", "hwaddr"=>"00:16:3e:12:f7:00", "flags"=>"up"}
    cgroup {"devices.deny"=>"a", "devices.allow"=>["c *:* m", "b *:* m", "c 1:3 rwm", "c 1:5 rwm", "c 5:1 rwm", "c 5:0 rwm", "c 1:9 rwm", "c 1:8 rwm", "c 136:* rwm", "c 5:2 rwm",
 "c 254:0 rwm", "c 10:229 rwm", "c 10:200 rwm", "c 1:7 rwm", "c 10:228 rwm", "c 10:232 rwm"]}
  end
```

**Comment by jkeiser** [comment] 2015-12-02 22:16
@iroller can you show the full stack trace? The debug output should tell you the location of the stack trace somewhere (it is put out to /var/chef/cache somewhere).

**Comment by iroller** [comment] 2015-12-02 22:23
Here it is @jkeiser :
https://gist.github.com/iroller/75d837f9c5095951969f

**Comment by jkeiser** [comment] 2015-12-02 22:31
@iroller I suspect the issue is here, in the LXCFileConfig code, which is iterating over all public methods of the LXC resource: https://github.com/chrisroberts/elecksee/blob/v1.0.22/lib/elecksee/lxc_file_config.rb#L11-L17

Chef 12.5.1 adds a setter for each property with `def my_property=(value)`, and that code is not taking that into account. Honestly, that code doesn't need to do any of that, the entire loop could be replaced with `resource.to_hash`.

Two external fixes are available:

1. Fix the `elecksee` gem by replacing the hash creator with `result = thing.to_hash`. (You could also change the bit that looks for methods starting with _ and have it look for methods ending with =, but that seems like overkill.)
2. Fix the LXC cookbook by adding `.to_hash` on [line 77](https://github.com/hw-cookbooks/lxc/blob/master/providers/config.rb#L77), like so:
   ```ruby
   content ::Lxc::FileConfig.generate_config(new_resource.to_hash)
   ```

I'll mull over what (if anything) one should do with Chef. Basically, we've added a new feature that conflicts with some existing code. It could be the current version of the LXC cookbook will legitimately not work until fixed.

**Comment by lamont-granquist** [comment] 2015-12-02 22:39
Yeah, this isn't a breaking change, and the code in that cookbook is mucking about metaprogramming things in ways which are not public APIs.  The usage of the resource in the cookbook is not something we've ever documented, or would ever sign up for supporting.

@jkeiser does this require a fix for #4127 so that they can use #to_hash or will it work fine the way it is?

**Comment by jkeiser** [comment] 2015-12-02 22:40
@lamont-granquist I don't think it affects this case directly. But we should fix that one anyway, backcompat = king.

**Comment by iroller** [comment] 2015-12-02 22:41
Thanks for the explanation :+1:. I'll try the fix later tonight.

**Comment by lamont-granquist** [comment] 2015-12-02 23:11
Yeah a better way to write this as chef code would have been to write it using a template, moving all the 'view' logic in generate_config into the template, and then at least doing new_resource.to_hash and injecting that as variables, following the pattern in #4127 (which I already mentioned was pretty 'lolwut' itself).  Here I think this library has largely lost the plot completely.  I assume there's some kind of reason not to use a template here and that the whole point of this is to 'libraryize' the generation of lxc config for utilization by scripts entirely outside of chef?  If not, then just rip all this code out and use a template.  Assuming the code has purpose, though, then the library code should not know anything about Chef::Resources and should take a Hash and it should be up to the 'caller' to translate the resource to a hash.  Ideally this would be as simple as new_resource.to_hash in the cookbook itself.  If that isn't sufficient then the code should still live in the cookbook.  And really if there's a need here for massaging Chef::Resources into hashes that takes more code than just '#to_hash' we really should add a function in core chef to do this and meet those needs.  Otherwise I can just about guarantee that we wind up back here again sometime...  Any code written here library/cookbook code that does custom work to massage Resources into hashes will be inherently brittle, will not be using a public API and will be unsupportable by core chef.

**Comment by jkeiser** [comment] 2015-12-03 16:37
@iroller if possible, I'd look into upgrading the elecksee gem. It doesn't have the offending code in it anymore (though I'm not sure how it handles being passed a resource) and is on a 2.X release.

**Comment by jkeiser** [comment] 2015-12-03 16:44
I'm going to close this; further discussion can happen in the linked patch in the LXC cookbook. That's the minimum fix.

**Closed by jkeiser** 2015-12-03 16:44 UTC
