### ISSUE TITLE
Resource 'mount' and chef 12.5.1

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef/chef#4056] opened 2015-10-14 01:41 UTC
Hello,

I have nodes machines running this mount point:

```
[root@pompeia16 ~]# mount | grep cassandra
/dev/md0 on /cassandra-data type ext4 (rw)
```

With this recipe:

```
mount '/cassandra-data' do
  device 'cassandra-data'
  device_type :label
  fstype 'ext4'
  options 'rw'
end
```

But is not working anymore with Chef 12.5.1:

```
pompeia16.datac.com Chef: 12.5.1  - NOK
pompeia6.datac.com  Chef: 12.3.0 - OK
pompeia4.datac.com  Chef: 12.3.0 - OK
pompeia10.datac.com Chef: 12.4.3 - OK
pompeia5.datac.com  Chef: 12.3.0 - OK
pompeia9.datac.com  Chef: 12.4.3 - OK
pompeia8.datac.com  Chef: 12.4.1 - OK
pompeia2.datac.com  Chef: 12.3.0 - OK
pompeia11.datac.com Chef: 12.4.3 - OK
pompeia7.datac.com  Chef: 12.4.1 - OK
pompeia13.datac.com Chef: 12.4.3 - OK
pompeia12.datac.com Chef: 12.4.3 - OK
```

The error is:

```
  * mount[/cassandra-data] action mount
    
    ================================================================================
    Error executing action `mount` on resource 'mount[/cassandra-data]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of umount /cassandra-data ----
    STDOUT: 
    STDERR: umount: /cassandra-data: device is busy.
            (In some cases useful info about processes that use
             the device is found by lsof(8) or fuser(1))
    ---- End output of umount /cassandra-data ----
    Ran umount /cassandra-data returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/cache/chef/cookbooks/cassandra/recipes/pompeia.rb
    
     42: mount '/cassandra-data' do
     43:   device 'cassandra-data'
     44:   device_type :label
     45:   fstype 'ext4'
     46:   options 'rw'
     47: end
     48: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/cache/chef/cookbooks/cassandra/recipes/pompeia.rb:42:in `from_file'
    
    mount("/cassandra-data") do
      action [:mount]
      supports {:remount=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      mount_point "/cassandra-data"
      device "cassandra-data"
      device_type :label
      fsck_device "-"
      fstype "ext4"
      options "rw"
      dump 0
      pass 2
      declared_type :mount
      cookbook_name "cassandra"
      recipe_name "pompeia"
    end
    

Running handlers:
Running handlers complete
Chef Client failed. 1 resources updated in 17 seconds
```

Thanks!

**Comment by coderanger** [comment] 2015-10-14 02:25
This was crossposted (?) to https://discourse.chef.io/t/resource-mount-and-chef-12-5-1/7050

**Comment by lamont-granquist** [comment] 2015-10-16 19:53
The mount provider running a remount if the options differ between those on the resource and the mountpoint is a feature that was introduced in 12.5.1

Its not a regression, although there's an argument that it appears to be breaking to users and the behavior changed.  I believe that default options did previously need to be specified in the options argument and now you must specify options that match what /proc/mounts returns.

If that's correct, and this usability of this feature is too fussy, then there's a couple alternatives that could be discussed such as a feature flag in Chef::Config to enable/disable it.  We could also try to omit default options from the match, but then I suspect we buy the problem of hand-maintaining a mapping of o/s, kernel version, and filesystem type to default options -- a never ending yak shave.

**Comment by TheLinuxNinja** [comment] 2015-11-04 21:02
I've attempted to fix the mount/re-mount issue we started seeing beginning in client v12.5.1. There seems to be no correct combination of mount options that stops this from happening across all of our managed instances. We've locked the omnibus installer version at v12.4.3 until this is fixed upstream. I've reviewed the documentation for the mount resource and we're following it as documented. In our case, we're using XFS, but we're seeing it happen across the board.

This sort of change in behavior breaks things. If someone WANTS the NEW behavior, they should ask for it using the remount flag that users of existing deployments shouldn't have to firefight for hours to find that it's a broken chef client upgrade to v12.5.1 that's causing everything to constantly umount and have files written underneath the mount that can't be seen when the mount is in place. Setting the mount options to 'default' is desired. It doesn't matter what they come out as at the other end. chef-client should only care that the resource is mounted, and only remount if flagged to do so, in which case the options would matter.

**Comment by gevans** [comment] 2015-11-04 21:13
In my case, I'm using Chef to mount an EBS volume. The first run is successful, but the second run fails (regardless of mount options):

```ruby
mount '/data' do
  device '/data'
  device_type :label
  fstype 'ext4'
end
```

Unfortunately, I've had to resort to awful hacks like the suggested:

```ruby
not_if 'mount | grep /data'
```

**Comment by bmhatfield** [comment] 2015-12-01 03:16
Wow, I just ran across this. Thank god `mount` itself won't remount if the device is in use, because this would have absolutely messed with hundreds of instances. When will this be fixed?

**Comment by bmhatfield** [comment] 2015-12-16 03:42
Bump on this? It looks like ya'll are cutting a 12.6 release. I hope this makes it in, as it really makes Chef unusable for me.

**Comment by btm** [comment] 2015-12-16 07:54
There's definitely no change in 12.6 related to this as a patch has yet to even be proposed.

I realize the consequences of doing the wrong thing with a mount could be bigger than with a file or another resource, but it doesn't change the fact that mount was doing the wrong thing and contributors have been trying to improve it in good faith. Prior to #1796 if you specified properties that differed from a mount point and that mount point was already mounted, chef would not try to bring the mount into desired state. That's a bug.

I haven't really worked with `Chef::Property` yet, but I think the thing to do is to migrate the mount resource over to use it. Then perhaps.... either:

1. change `mount_options_unchanged?` in all the mount providers to check `property_is_set?` to ensure `mount_options_unchanged?` only compares properties set on the resource by the user with actual system state, as opposed to default values.

or

2. make use of Chef::Property.converge_if_changed?

Neither of those two patterns appear to be used yet, so I'd want @jkeiser to chime in on a recommendation.

**Comment by bmhatfield** [comment] 2015-12-16 13:44
Thanks for your response.

I think there's a couple things to consider beyond `Chef::Property` here:
- If the mounted resource has anything using it (at least, on Linux), this cannot succeed, as `mount` itself will reject the remount (this is a good thing). I don't *want* it to try to succeed in the face of this without operator intervention.
- On some distributions, the "rendered" options are a different string than the "input" options to get there. Which means, and this is the behavior some (including myself) are observing, that this resource will *always* consider itself out of compliance. I'm not sure how `Chef::Property` proposes to fix this, but this is a fragile state that should be handled.

While I agree in principle with the concept of "Chef should converge resources to the desired state", sometimes in context that really doesn't make any sense. Once something is using a mountpoint, it's off-limits for Chef until that mountpoint is freed up. To draw a parallel, I don't necessarily always want a service to restart just because something has changed. That decision needs to be made *in context*, which is one reason why services don't restart without being notified or configured to do so.

I believe that "working" should take a higher precedence than "bug in principle" when it's been working in practice all these years. Therefore I propose that #1796 is reverted until:
- There are tests for the conditions that folks are reporting in this thread, especially in the context of how mount reports the mount's current options.
- The resource can more carefully consider when it is appropriate to remount things, and handle it without 1) breaking systems, 2) breaking chef runs.

Thanks again.

**Comment by bmhatfield** [comment] 2016-02-05 17:06
Bump? I see conversation about 12.7. This bug makes chef-client unusable on some Ubuntu systems, which is a very common distribution. Perhaps for 12.7 we should revert https://github.com/chef/chef/pull/1796 until some effort can be placed to make this a functioning change?

**Comment by btm** [comment] 2016-02-09 00:13
If you want to open a pull request with just a revert of #1796 it would be considered for merge. It wouldn't be in 12.7, but could be in the 12.8 release in a month, or could be used from the subsequent build from current if it was merged.

**Comment by evangael** [comment] 2016-03-22 21:09
This is still happening with the latest chef-client version (12.8.1) while mounting a cifs volume. The ugly work around is to do a not_if greping the mount command to see if this is already mounted.

**Comment by drags** [comment] 2016-03-25 08:05
> Thank god mount itself won't remount if the device is in use

Just a heads up that this is not true if the filesystem is in use by an LXC container (docker + friends). If there is nothing on the host system holding open FDs to the filesystem the remount will still occur. It doesn't seem to interrupt the containers operation (which makes sense given LXC has a separate namespace for mounted devices), but this may open the possibility of destructive behavior since the resource cannot see that the filesystem is in use.

**Comment by btm** [comment] 2016-04-01 00:44
Should be fixed by #4775. Someone needs to reimplement #1796 if they want that.

**Closed by btm** 2016-04-01 00:44 UTC
Labels: Chef Core, High Priority, Regression

**Comment by tyler-ball** [comment] 2016-04-08 20:16
Should we re-open this since #1796 got reverted?

**Comment by TheLinuxNinja** [comment] 2016-08-23 21:39
Thank you for finally reverting the breaking change. Sad to see that it took from October 13th until March 31st to get the fix merged.
