### ISSUE TITLE
Sensitive property does not work on execute or batch resource 

### ISSUE THREAD

**Issue by JonGriggs** [chef/chef#6073] opened 2017-04-19 19:00 UTC
## Description

When using the execute or patch resource, if the password property is used, the Chef Client treats the output as sensitive, even if you set the sensitive property to false.

## Chef Version

12.19.36 x64

## Platform Version

Windows Server 2012 R2.

## Replication Case

You need to have a password stored in an encrypted data bag (or I suppose you could just hardcode in the password, but I used a data bag), and then try this in a recipe:

>batch 'run ipconfig' do
>	code 'ipconfig /null'
>	user tauser['id']
>	password tauser['pw']
>end

This will fail but the output will be suppressed.  Modifying the code to this doesn't change the output:

>batch 'run ipconfig' do
>      sensitive false
>	code 'ipconfig /null'
>	user tauser['id']
>	password tauser['pw']
>end

**Comment by lamont-granquist** [comment] 2017-04-21 20:55
that was done deliberately:

https://github.com/chef/chef/blob/acc92959658f2b74286e3c87073d5f3a23d27da2/lib/chef/resource/execute.rb#L133

paging @btm

**Comment by btm** [comment] 2017-08-08 03:45
I don't think this is Windows specific, as even `bash` inherits `script` which inherits `execute`.

@lamont-granquist can we tell inside the coerce if the value is a default or not?

```
property :sensitive, [ TrueClass, FalseClass ], default: false, coerce: proc { |x| 
  if property_is_set?(:sensitive)
    x
  else
    if password
      true
    else
      x
    end
  end
}
```

I don't think we intended to not let you override it, although we definitely intended to default to true if a password was set.

**Comment by lamont-granquist** [comment] 2017-08-08 16:24
i'm pretty sure this is only used on windows codepaths and was part of a PR you did awhile ago.

i wasn't sure if that was intentional or not.

**Comment by btm** [comment] 2017-08-08 16:27
oh yeah, I suppose that you wouldn't pass `password` on other platforms unless we added a fancy sudo property or such.

Any thoughts on if `property_is_set?` might work in `coerce`?

**Comment by MattFenner** [comment] 2017-10-25 08:38
+1 on this.

setting sensitive explicitly to false should override the default caused by specifying a password. 

At the moment if your resource is failing there is no way of telling what the error is, i would like to set sensitive to false temporarily so I can see the error.

**Comment by Vasu1105** [comment] 2017-12-01 10:12
I have verified this with chef-client 13.4.19 and master branch of Chef and this seems to be fixed in current releases.

**Comment by btm** [comment] 2017-12-01 20:21
@MattFenner what version of Chef are you using?

**Comment by btm** [comment] 2017-12-04 16:53
@Vasu1105 it looks like the resources changes in Chef 13 did allow this, but there is an ordering problem. If you declare `sensitive false` after the `password` property, it is still suppressed. 

I think we want to change this line in `lib/chef/resource/execute.rb` to something like:

```
property :sensitive, [ TrueClass, FalseClass ], default: false, coerce: proc do |x| 
                                                                             if x == false
                                                                               false
                                                                             else
                                                                               password ? true : x
                                                                             end
```

**Comment by Vasu1105** [comment] 2017-12-05 05:41
Will be adding the fix for this. Thanks @btm.

**Comment by Vasu1105** [comment] 2017-12-06 10:28
@btm In above solution if user don't set sensitive property and has password the resource will show output in log because default value for sensitive is false. Which means that what is written in execute resource doc will not be true for `password` property i.e. `The sensitive property for this resource will automatically be set to true if password is specified.`
Do we really want to make whole resource sensitive if password property is set since password property is already set to sensitive?

**Closed** 2018-01-05 14:09 UTC
Labels: Area: Windows
