### ISSUE TITLE
Use of the Debian service provider causes unnecessary systemd daemon reload

### ISSUE THREAD

**Issue by sterago** [chef/chef#5823] opened 2017-02-17 16:57 UTC
## Description

I noticed that on a subset of chef nodes in my company's infrastructure, on every chef-client run, the systemd daemon is reloaded, in some cases with undesirable side effects (e.g. swap partition remounting).
Debugging the issue, it looks like the reload happens in correspondence of two service resources (one is with action `start` and one with action `enable`) even though both are up-to-date. 
Those resources are not doing anything fancy, and just declare the usage of `Chef::Provider::Service::Debian` as the provider for the service when the node is a debian machine (https://github.com/sous-chefs/apache2/blob/master/recipes/default.rb#L208)

This provider's `get_priority` method uses the command `/usr/sbin/update-rc.d -n -f <service_name> remove` which is supposed to be a dry-run command, but using strace on a Debian 8.7 I noticed that it causes the systemd reload:

```
root@staging:~# strace -f -e execve /usr/sbin/update-rc.d -n -f apache2 remove
execve("/usr/sbin/update-rc.d", ["/usr/sbin/update-rc.d", "-n", "-f", "apache2", "remove"], [/* 18 vars */]) = 0
Process 11096 attached
[pid 11096] execve("/sbin/insserv", ["/sbin/insserv", "-n", "-f", "-r", "apache2"], [/* 18 vars */]) = 0
insserv: remove service /etc/init.d/../rc0.d/K01apache2
insserv: remove service /etc/init.d/../rc1.d/K01apache2
insserv: remove service /etc/init.d/../rc2.d/S02apache2
insserv: remove service /etc/init.d/../rc3.d/S02apache2
insserv: remove service /etc/init.d/../rc4.d/S02apache2
insserv: remove service /etc/init.d/../rc5.d/S02apache2
insserv: remove service /etc/init.d/../rc6.d/K01apache2
insserv: dryrun, not creating .depend.boot, .depend.start, and .depend.stop
[pid 11096] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=11096, si_uid=0, si_status=0, si_utime=1, si_stime=0} ---
Process 11097 attached
[pid 11097] execve("/usr/local/sbin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 11097] execve("/usr/local/bin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 11097] execve("/usr/sbin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 11097] execve("/usr/bin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 11097] execve("/sbin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 11097] execve("/bin/systemctl", ["systemctl", "daemon-reload"], [/* 18 vars */]) = 0
[pid 11097] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=11097, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
+++ exited with 0 +++
```

## Chef Version

12.18.31

## Platform Version

Debian GNU/Linux 8.7 (jessie)

**Comment by lamont-granquist** [comment] 2017-02-17 23:42
So does this just boil down to update-rc.d causes an unnecessary systemd daemon reload?

The apache2 cookbook forcing the use of the debian service provider on a box that natively has systemd also seems like it is code that needs updating.

How would you suggest the code in chef-client should change?

**Comment by sterago** [comment] 2017-02-19 08:52
If there is a way for `get_priority` to use a command that does not cause side effects, I think it would be preferable.

I can look into that if you deem it reasonable.

Regarding the apache2 cookbook, I can open an issue about that as well.

Regarding update-rc.d causing the reload in dry-run mode, I'd say it could be considered a bug, what do you think? Should I file an issue about that as well?

**Comment by lamont-granquist** [comment] 2017-02-20 02:29
> If there is a way for get_priority to use a command that does not cause side effects, I think it would be preferable.

that sounds like the way to go.  since that would address the root cause of the reload-in-whyrun effect as well i don't think those are separate bugs.

it does feel like opening an issue against the apache2 cookbook that it should use native systemd services on systemd-supporting debian-ish systems would be the most appropriate fix though.

**Comment by sterago** [comment] 2017-02-20 15:26
Thanks for your feedback @lamont-granquist , I did open an issue on the apache2 cookbook repo:
https://github.com/sous-chefs/apache2/issues/467

However, I tried forcing the use of the `Chef::Provider::Service::Systemd` provider for the apache2 service and I still get the systemd reload issue

I might be missing something as I am relatively new to the concept of chef providers 🤔
Any suggestions?

**Comment by tas50** [comment] 2021-05-06 00:17
Closing this out based on the last comment finding the root cause

**Closed by tas50** 2021-05-06 00:17 UTC
Labels: Platform: Debian-like, Priority: Low
