### ISSUE TITLE
Chef Client 13 audit: SystemStackError: stack level too deep if requires 'serverspec'

### ISSUE THREAD

**Issue by kylebevans** [chef/chef#6426] opened 2017-09-20 15:51 UTC
## Description

In Chef Client 13, audit mode fails with the error "SystemStackError: stack level too deep" if the audit recipe contains "requires 'serverspec"

## Chef Version

13.2.20

## Platform Version

RHEL 7.3

## Replication Case

put requires 'serverspec' into an audit recipe and run chef in audit mode

## Client Output

 Failures:
  
    1) 1 Install Updates, Patches and Additional Security Software 1.1 Filesystem Configuration Level 1 1.1.1 Create Separate Partition for /tmp
       Failure/Error: expect(file('/tmp')).to be_mounted
       SystemStackError:
         stack level too deep
         
       # /var/chef/cache/cookbooks/audit-cookbook/recipes/audit-cis-rhel7.rb:42:in `block (4 levels) in from_file'

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment] 2017-09-21 00:15
Unable to reproduce this locally:

```
$ cat cookbooks/tmp/recipes/default.rb
control_group 'test' do
  require 'serverspec'

  control 'asdf' do
    it { expect(1).to eq 1 }
  end
end
$ chef-client --local-mode --audit-mode audit-only --runlist 'recipe[tmp]'
[2017-09-20T17:13:56-07:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /Users/coderanger/src/tmp/chef6426
  One version per cookbook

[2017-09-20T17:13:56-07:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 13.2.20
[2017-09-20T17:13:56-07:00] INFO: *** Chef 13.2.20 ***
[2017-09-20T17:13:56-07:00] INFO: Platform: x86_64-darwin16
[2017-09-20T17:13:56-07:00] INFO: Chef-client pid: 84828
[2017-09-20T17:13:56-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2017-09-20T17:14:02-07:00] INFO: Setting the run_list to [#<Chef::RunList::RunListItem:0x00007f935e9ea720 @version=nil, @type=:recipe, @name="tmp">] from CLI options
[2017-09-20T17:14:02-07:00] INFO: Run List is [recipe[tmp]]
[2017-09-20T17:14:02-07:00] INFO: Run List expands to [tmp]
[2017-09-20T17:14:02-07:00] INFO: Starting Chef Run for coderanger
[2017-09-20T17:14:02-07:00] INFO: Running start handlers
[2017-09-20T17:14:02-07:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["tmp"]
[2017-09-20T17:14:02-07:00] INFO: Loading cookbooks [tmp@0.0.0]
Synchronizing Cookbooks:
  - tmp (0.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Starting audit phase
[2017-09-20T17:14:02-07:00] INFO: Starting audit phase
[2017-09-20T17:14:03-07:00] INFO:
[2017-09-20T17:14:03-07:00] INFO: test
[2017-09-20T17:14:03-07:00] INFO:   asdf
[2017-09-20T17:14:03-07:00] INFO:     should eq 1
[2017-09-20T17:14:03-07:00] INFO: Successfully executed all `control_group` blocks and contained examples
[2017-09-20T17:14:03-07:00] INFO:
Finished in 0.00233 seconds (files took 0.57984 seconds to load)
1 example, 0 failures


test
  asdf
    should eq 1

Finished in 0.00233 seconds (files took 0.57984 seconds to load)
1 example, 0 failures
Auditing complete
[2017-09-20T17:14:03-07:00] INFO: Chef Run complete in 0.627461 seconds

Running handlers:
[2017-09-20T17:14:03-07:00] INFO: Running report handlers
Running handlers complete
[2017-09-20T17:14:03-07:00] INFO: Report handlers complete
Chef Client finished, 0/0 resources updated in 07 seconds
  1/1 controls succeeded
```

**Comment by kylebevans** [comment] 2017-09-21 12:55
Try it this way: I have two audit recipes in the run_list for a node.  The first one is this:

```
level_two_enabled = false
ipv6_disabled     = false

control_group '1 Install Updates, Patches and Additional Security Software' do
  control '1.1 Filesystem Configuration' do
    context 'Level 1' do
      let(:find_cmd) do
        command <<-EOH.gsub(/^\s+/, '')
          df --local -P | \
          awk {'if (NR!=1) print $6'} | \
          xargs -I '{}' \
          find '{}' -xdev -type d \\( -perm -0002 -a ! -perm -1000 \\) \
          2>/dev/null
        EOH
      end

      it '1.1.1 Create Separate Partition for /tmp' do
        expect(file('/tmp')).to be_mounted
      end
    end
  end
end
```

and the second one is this:

```
require 'serverspec'
```

So maybe there has to be two recipes.  Here is the output:

```
# chef-client --audit-mode audit-only
Starting Chef Client, version 13.2.20
resolving cookbooks for run list: ["audit-cis::audit-cis-rhel7", "audit-cis::audit-cis-network"]
Synchronizing Cookbooks:
  - chef-vault (3.0.0)
  - compat_resource (12.19.0)
  - fisher-audit-cis (0.1.121)
Installing Cookbook Gems:
Compiling Cookbooks...
Starting audit phase

1 Install Updates, Patches and Additional Security Software
  1.1 Filesystem Configuration
    Level 1
      1.1.1 Create Separate Partition for /tmp (FAILED - 1)

Failures:

  1) 1 Install Updates, Patches and Additional Security Software 1.1 Filesystem Configuration Level 1 1.1.1 Create Separate Partition for /tmp
     Failure/Error: expect(file('/tmp')).to be_mounted
     SystemStackError:
       stack level too deep
       
     # /var/chef/cache/cookbooks/audit-cis/recipes/audit-cis-rhel7.rb:42:in `block (4 levels) in from_file'

Finished in 0.00718 seconds (files took 0.16299 seconds to load)
1 example, 1 failure

Failed examples:

rspec  # 1 Install Updates, Patches and Additional Security Software 1.1 Filesystem Configuration Level 1 1.1.1 Create Separate Partition for /tmp

Audit phase exception:
  Audit phase found failures - 1/1 controls failed
  
  Running handlers:
  Running handlers complete
  Chef Client finished, 0/0 resources updated in 06 seconds
    0/1 controls succeeded
[2017-09-21T08:46:23-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-09-21T08:46:23-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-09-21T08:46:23-04:00] ERROR: Found 1 errors, they are stored in the backtrace
[2017-09-21T08:46:23-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 42)
```

chef-stacktrace.out:
```
Generated at 2017-09-21 08:46:23 -0400
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) Chef::Exceptions::AuditsFailed -  Audit phase found failures - 1/1 controls failed
```

**Comment by tas50** [comment] 2019-03-11 23:11
I'm going to close this out at this point since we've deprecated Audit mode in Chef 14 and will soon be merging the PR to remove it entirely from Chef 15.

**Closed by tas50** 2019-03-11 23:11 UTC
