### ISSUE TITLE
Node attributes cache entries are not honoring force_default

### ISSUE THREAD

**Issue by jdmurphy** [chef/chef#4345] opened 2015-12-29 16:42 UTC
Version
======

Seen on Chef 12+

Scenario
=======

A legacy cookbook is using `force_default` to override the default attributes set in the attributes file of the same cookbook in a recipe, but when utilizing that attribute, the value from the attributes file is being used and not the value from `force_default`.

Steps to Reproduce
===============

I created a cookbook which highlights the issue called [force_default_issue](https://github.com/jdmurphy/force_default_issue). This cookbook print's the attribute value using the `debug_value` function so that we can see every value at every precedence level, and then prints the actual node's attribute value.

Expected Result
============

```
Starting Chef Client, version 12.6.0
Creating a new client identity for default-centos-71 using the validator key.
resolving cookbooks for run list: ["force_default_issue::default"]
Synchronizing Cookbooks:
 - force_default_issue (0.1.0)
Compiling Cookbooks...
[["set_unless_enabled?", false],
["default", "baz"],
["env_default", :not_present],
["role_default", :not_present],
["force_default", "not-baz"],
["normal", :not_present],
["override", :not_present],
["role_override", :not_present],
["env_override", :not_present],
["force_override", :not_present],
["automatic", :not_present]]
Node attribute value: not-baz
Converging 1 resources
Recipe: force_default_issue::executes

   - execute echo not-baz

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 06 seconds
Finished converging <default-centos-71> (0m39.04s).
```

Actual Result
==========

```
Starting Chef Client, version 12.6.0
Creating a new client identity for default-centos-71 using the validator key.
resolving cookbooks for run list: ["force_default_issue::default"]
Synchronizing Cookbooks:
 - force_default_issue (0.1.0)
Compiling Cookbooks...
[["set_unless_enabled?", false],
["default", "baz"],
["env_default", :not_present],
["role_default", :not_present],
["force_default", "not-baz"],
["normal", :not_present],
["override", :not_present],
["role_override", :not_present],
["env_override", :not_present],
["force_override", :not_present],
["automatic", :not_present]]
Node attribute value: baz
Converging 1 resources
Recipe: force_default_issue::executes

   - execute echo baz

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 06 seconds
Finished converging <default-centos-71> (0m39.04s).
```

This could be related to #3523.

**Comment by lamont-granquist** [comment] 2015-12-30 13:21
I'm fairly positive this line:

```ruby
node.force_default['force_default_issue']['foo']['bar'] = node['force_default_issue']['bar']
```

Is hitting this issue:

https://github.com/chef/chef/issues/4207

The problem has nothing to do with the implementation of force_default.  The problem is that the `#[]=` operator needs to evaluate the expr on the right hand side, and this clobbers the global breadcrumb state.

Something like this probably works as a workaround:

```ruby
temp = node['force_default_issue']['bar']
node.force_default['force_default_issue']['foo']['bar'] = temp
```

If that's the problem, then its fixed in my attributes rewrite branch, that I'll try to push out Q1.

**Comment by jdmurphy** [comment] 2015-12-30 14:38
@lamont-granquist that seems like it might very well be the same issue. Unfortunately, the workaround doesn't seem to make any difference in the result. For now we can get it to work by changing the precedence level we were using for the attribute, but I look forward to testing your changes in Q1.

**Comment by lamont-granquist** [comment] 2015-12-30 14:40
yeah, now that i look at it, the top level attr ('force_default_issue') is the same there.

**Comment by lamont-granquist** [comment] 2015-12-30 14:43
try this in your .kitchen.yml:

```
provisioner:
  name: chef_github
  github_owner: "chef"
  github_repo: "chef"
  refname: "lcg/attributes-v1.99"
```

**Comment by lamont-granquist** [comment] 2015-12-30 14:43
(you'll need to bundle or install the kitchen-appbundle-updater gem)

**Comment by jdmurphy** [comment] 2015-12-30 17:24
Kitchen pukes when I update the provisioner with kitchen-appbundle-update in the Gemfile with the following:
```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/appbundle-updater-0.2.6/bin/appbundle-updater:176:in `chdir': No such file or directory @ dir_chdir - /opt/chef/embedded/apps (Errno::ENOENT)
  from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/appbundle-updater-0.2.6/bin/appbundle-updater:176:in `start'
  from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/appbundle-updater-0.2.6/bin/appbundle-updater:280:in `<top (required)>'
  from /opt/chef/embedded/bin/appbundle-updater:23:in `load'
  from /opt/chef/embedded/bin/appbundle-updater:23:in `<main>'
```

**Comment by lamont-granquist** [comment] 2015-12-30 18:16
looks like chef 12.6.0 broke things, surprised it didn't troll our travis tests...

just pushed appbundle-updater 0.2.7 that should fix it...

**Comment by jdmurphy** [comment] 2015-12-30 19:29
After updating that, I was able to test and your branch fixes the attributes issue I was seeing. If you want you can close this in favor of #3523.

**Comment by lamont-granquist** [comment] 2016-01-01 13:49
yeah, not positive its a strict dup, but i'd venture to guess it is something that rhymes with it, and is solved by removing all the bolted-on-design in 12.0

**Closed** 2016-01-02 13:38 UTC
