### ISSUE TITLE
chef_gem kills chef-client run when source does not have gem, but gem gets installed anyhow from rubygems.org

### ISSUE THREAD

**Issue by pburkholder** [chef/chef#2962] opened 2015-02-20 16:09 UTC
This recipe:

    chef_gem "chef-vault" do
      source "http://mirror.ops.rhcloud.com/mirror/ruby" 
    end

with `kitchen converge` on centos-6.5 generates this: 

      Creating a new client identity for default-centos-65 using the validator key.
       [2015-02-20T16:03:55+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-02-20T16:03:55+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["chef_gem::default"]
       [2015-02-20T16:03:55+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - chef_gem
       Compiling Cookbooks...
       Recipe: chef_gem::default
       [2015-02-20T16:03:56+00:00] WARN:  failed to find gem chef-vault (>= 0) from [http://mirror.ops.rhcloud.com/mirror/ruby]

           - install version  of package chef-vault
         Converging 1 resources

           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-vault]'
           ================================================================================

           Gem::Requirement::BadRequirementError
           -------------------------------------
           Illformed requirement [""]

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/chef_gem/recipes/default.rb

             8: chef_gem "chef-vault" do
             9:  source "http://mirror.ops.rhcloud.com/mirror/ruby"
            10: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/chef_gem/recipes/default.rb:8:in `from_file'

           chef_gem("chef-vault") do
             action :install
             updated true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "chef-vault"
             source "http://mirror.ops.rhcloud.com/mirror/ruby"
             timeout 900
             gem_binary "/opt/chef/embedded/bin/gem"
             declared_type :chef_gem
             cookbook_name "chef_gem"
             recipe_name "default"
           end

       Running handlers:
       [2015-02-20T16:04:10+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-02-20T16:04:10+00:00] ERROR: Exception handlers complete
       [2015-02-20T16:04:10+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 1 resources updated in 16.209192275 seconds
       [2015-02-20T16:04:10+00:00] ERROR: chef_gem[chef-vault] (chef_gem::default line 8) had an error: Gem::Requirement::BadRequirementError: Illformed requirement [""]
       [2015-02-20T16:04:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-centos-65>.

But on the box itself the gem is installed:

    gem list chef-vault

    *** LOCAL GEMS ***

    chef-vault (2.5.0)

If the source does not have the gem, the gem should not get installed.  Or, if the gem does get installed, then the run should not fail.

**Comment by smurawski** [comment] 2015-06-24 17:27
I can't repro this.  Can you verify which chef-client version and if the host had chef-vault before the run started?

**Comment by afiune** [comment] 2015-07-06 18:32
@chef/engineering-leads @smurawski Having the same issue with `chef-sugar` on chef-client version `12.3.0` (bundled with chefdk `0.6.2`)

**Comment by afiune** [comment] 2015-07-06 21:53
Trying to replicate this without luck, the only way I've seen is to set `version` to `''` (empty)..

```ruby
[2] pry(#<Chef::Provider::Package::Rubygems>)> gem_dependency
=> Gem::Dependency.new("chef-sugar", Gem::Requirement.new(["= 3.1.1"]), :runtime)
[3] pry(#<Chef::Provider::Package::Rubygems>)> Gem::Requirement.new([])
=> Gem::Requirement.new([">= 0"])
[4] pry(#<Chef::Provider::Package::Rubygems>)> Gem::Requirement.new([''])
Gem::Requirement::BadRequirementError: Illformed requirement [""]
from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:89:in `parse'
[5] pry(#<Chef::Provider::Package::Rubygems>)>
```

**Comment by afiune** [comment] 2015-07-07 00:47
Alright guys... I couldn't replicate the issue, I was working with @jaym and he recommended to set the `compile` to `false` but apparently the issue is gone. :disappointed: 

That is only telling me that this problem is with Rubygem API and not with Chef! Perhaps next time it happens I will try to debug on time. Thanks!

cc/ @chef/delivery @chef/engineering-leads

**Comment by lamont-granquist** [comment] 2015-09-16 17:15
Seems to be no repro so closing.  Reopen if we can find the repro.

**Comment by pburkholder** [comment] 2015-09-16 17:45
:+1: Sorry couldn't repro, thanks for closing and keeping tidy.

**Comment by kareiva** [comment] 2015-12-31 10:34
I can reproduce similar issue in an isolated environment with a private repo built by http://github.com/Numergy/gemirro-cookbook and specified as source in `/root/.gemrc`

       ...
       Gem::Requirement::BadRequirementError
       -------------------------------------
       Illformed requirement [""]


The below patch fixes the issue:

<pre>-chef_gem 'mixlib-versioning'
+chef_gem 'mixlib-versioning' do
+  version '>= 1.1.0'
+  action :install
+end</pre>

**Comment by lamont-granquist** [comment] 2016-01-13 18:44
hmmm, well this still isn't a good replication case since i can chef_gem install mixlib-versioning just fine.

need a full stacktrace.out dump at the very least to have any hope of understanding what is going on, along with maybe some -ldebug output.

**Closed by lamont-granquist** 2016-01-13 18:44 UTC
Labels: Chef Core
