### ISSUE TITLE
Support restarting/stopping/ the service from state paused on windows

### ISSUE THREAD

**Issue by axos88** [chef/chef#5586] opened 2016-11-28 13:41 UTC
## Description

Currently triggers exception in https://github.com/chef/chef/blob/1991cf97660a38e704eb4cd9609ed6ea84a35442/lib/chef/provider/service/windows.rb#L117

Service should be allowed to be stopped from that state.

## Chef Version

12.16.9

## Platform Version

windows, 2012r2

## Replication Case

Create a service, make it go into stopped state.
Run a cookbook that runs the action stop, restart (or start) on the service.

**Comment by btm** [comment] 2016-12-06 21:27
This is a duplicate of https://github.com/chef/chef/issues/2363, let's move the conversation there.

**Closed by btm** 2016-12-06 21:27 UTC
Labels: Medium Priority, Windows
