### ISSUE TITLE
support timeout attribute for service resource

### ISSUE THREAD

**Issue by ebgc** [chef/chef#5309] opened 2016-09-12 19:57 UTC
## Description

services which need long controlled restart/start cycle (more then 10min) are not supported due to mixlib 600sec default timeout
## Chef Version

12.13.37 and any other which uses chef::mixlib
## Platform Version

any unix version using chef::mixlib
## Replication Case

have a unix service script which has an action (start,stop, reload ...) a 'sleep 610' set and it will fail.
## Mixlib::ShellOut::CommandTimeout

Command timed out after 600s:
Command exceeded allowed execution time, process terminated
## Cookbook Trace:

/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:136:in`run_delayed_notification'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:124:in `block in run_delayed_notifications'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in`each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `run_delayed_notifications'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:113:in`converge'

**Comment by ebgc** [comment] 2016-09-12 20:00
suggestion:

chef/lib/chef/provider/service/*  need update per service action to send a 'timeout' option to mixlib which allows to override the default timeout of 600sec.

**Comment by ebgc** [comment] 2016-09-12 22:49
see also PR https://github.com/chef/chef/pull/5311

**Comment by myoung34** [comment] 2017-01-03 20:50
Any bumps to this? We use chef to deploy workers, and our service respects a timeout for threads to finish (the init.d file allows up to 45min to finish - rare but allowed).

```================================================================================
Error executing action `stop` on resource 'service[stop circusd]'
================================================================================
 
Mixlib::ShellOut::CommandTimeout
--------------------------------
Command timed out after 600s:
Command exceeded allowed execution time, process terminated
---- Begin output of /sbin/service circusd stop ----
STDOUT: Sending 'stop' to all workers
ok
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
There are still active worker threads. Retrying in 30 seconds
STDERR: 
---- End output of /sbin/service circusd stop ----
Ran /sbin/service circusd stop returned ```

**Comment by DennyZhang** [comment] 2017-07-06 21:06
Run into the same issue.

Found a similar ticket: https://github.com/chef/chef/issues/3023

Looks like it's gonna to be like this for a while. Thus we workaround this.

1. Change service initscript, if service start doesn't finish in 10 minutes, it will return OK
2. Add a wait-check mechanism after service start via a chef execute resource.

It's kind of a dirty workaround.

**Comment by myoung34** [comment] 2017-07-10 13:08
I got around it by using the `execute` resource, but its still a hack

**Comment by tas50** [comment] 2021-05-06 00:36
Closing this out as a dupe of https://github.com/chef/chef/issues/3023

**Closed by tas50** 2021-05-06 00:36 UTC
Labels: Priority: Medium, Type: Enhancement
