### ISSUE TITLE
Chef-14 gem metadata broken by backport in issue 8901

### ISSUE THREAD

**Issue by DarrenV79** [chef/chef#8970] opened 2019-10-09 10:48 UTC
## Description
Converging with this client version fails because each_char has been removed.  I assume its in the first pass and only a few cookbooks use this.  Mostly the poise python cookbook, but it now fails.  Could not find any release notes that document that this has been removed.  Solution for us temporarily to go back to 14.13.11.

## Chef Version
14.14.14.

## Platform Version
Windows 2019 Core

## Replication Case
Converging many of our cook books fails because of the mentioned error.

## Client Output
NoMethodError: undefined method `each_char' for ["bundle", "install"]:Array

## Stacktrace
None

**Comment by lamont-granquist** [comment] 2019-10-09 17:05
I'm pretty certain you've misidentified the problem and that something that was a String is now an Array, but you haven't included enough details in this issue to help me to determine what is being affected.

The Array class in Ruby has never had an `#each_char` method and so that wouldn't have ever been removed.

**Comment by lamont-granquist** [comment] 2019-10-09 17:23
This is due to backported features to chef-14 not being compatible with mixlib-shellout 2.x and a large dep mess making mixlib-shellout 3.x difficult to backport.

**Comment by lamont-granquist** [comment] 2019-10-09 17:49
closed by #8974

**Closed** 2019-10-09 17:50 UTC
Labels: Status: Untriaged

**Comment by tas50** [comment] 2019-10-09 18:59
I'm backporting some other fixes from chef 15, but we'll have a new 14.14 release that fixes this regression. Thanks for the report @DarrenV79

**Comment by rojomisin** [comment] 2019-10-10 20:27
windows 2016 as well
