### ISSUE TITLE
chef_gem loads incorrect version

### ISSUE THREAD

**Issue by royaldark** [chef/chef#4429] opened 2016-01-19 03:46 UTC
I have a `chef_gem` entry which explicitly requests the `ipaddress` gem at version 0.8.2, but version 0.8.0 is loaded in my recipe. In my embedded Chef Ruby gem directory, I can see both versions are installed. This results in errors when I try to use 0.8.2 methods, but 0.8.0 is loaded.

Example:
```ruby
chef_gem "ipaddress" do
  action :install
  version "0.8.2"
end

require "ipaddress"

addr = IPAddress("127.0.0.1")
addr[1] = 65
```

This should result in `addr` representing "127.65.0.1" but instead results in ``undefined method '[]=' for #<IPAddress::IPv4:0x0000000666c1e0>`` (`[]=` was added in 0.8.2).

This is running on Chef 12.6.0.

**Comment by coderanger** [comment] 2016-01-19 03:51
As written, that would process the `chef_gem` at converge time, but the `require` is at compile time. See https://coderanger.net/two-pass/ for an explanation of the issues. Alternatively if you were paraphrasing, please include the actual code.

**Comment by royaldark** [comment] 2016-01-19 04:03
Is the [chef_gem example in the docs](https://docs.chef.io/resource_chef_gem.html#examples) wrong, then? 

The only paraphrasing was moving the line `addr` is defined out of a helper Module for use in templates, and into the root of the recipe.

Perhaps I am still misunderstanding the two-pass aspect. Aren't statements in the root of a recipe, like the `require`, processed at converge time?

**Comment by coderanger** [comment] 2016-01-19 04:10
Yes. the docs are incorrect. Please see the article I linked for an explanation of how recipe-level Ruby code will be evaluated. Going to close this out as it sounds like the issue is with the docs, not Chef itself.

**Closed by coderanger** 2016-01-19 04:10 UTC
