### ISSUE TITLE
lazy doesn't work with 'action' attribute

### ISSUE THREAD

**Issue by docwhat** [chef/chef#3615] opened 2015-06-29 20:54 UTC
This recipe code doesn't work:

``` ruby
directory('/tmp/foobar') do
  action lazy { [:create, :delete].sample }
end
```

The code in the `{}` is just random code for the example. I know it is useless.

I expected it to work, but instead I get:

```
NoMethodError: undefined method `to_sym' for #<Chef::DelayedEvaluator:0x00000004b1b5d0>
```

**Comment by coderanger** [comment] 2015-06-29 21:19
Action is not actually an attribute, but :+1: for this being supported anyway.

**Comment by pu239ppy** [comment] 2015-07-02 16:19
Forgive me if my commentary may seem ignorant I am new to both Chef and Ruby

Encountered this issue as well recently, at first glance  my naive assumption was that I could modify action in chef/lib/chef/resource.rb to pass arg through set_or_return would unwind the DelayedEvaluator as I assumed is the purpose in other resource definition that accept lazy such as chef/lib/chef/resource/template.rb variables.  Then pass it to the rest of the function code but that 
did not work, instead it just returned DelayedEvaluator again

@docwhat what version/commit are you running?

**Comment by docwhat** [comment] 2015-07-09 17:39
This was in chef 12.4.0.

**Comment by sempervictus** [comment] 2015-07-13 20:18
Testing a fix for this now in master, looks like there's some serious differences in how resource actions are handled from 12.4.1 though, so that might take a bit longer. 

The issue is that in master, self.action(action,&recipe_block) calls :to_sym on the action param. To resolve this, I've added a check to :responds_to?(:call) and using action.call.to_sym if it does.

**Comment by zedtux** [comment] 2019-08-07 08:02
This is still true today with version 15.1.36.

**Comment by sempervictus** [comment] 2019-08-07 16:30
Their CLA nonsense prevented me from getting the fix merged. We just have it in our base cookbook. Since this issue was created, chef has basically become the red headed step child of devops. We still use actively, but vendors like IBM and their own stepchild, redhat back the "declarative" modalities stating that IT people are too stupid to write actual code (seriously). Meanwhile no corp wants to sign that cla mess either, pay for silly addons only needed because the platform can't be expanded with these functions via FOSS, meaning so many community fixes and improvements don't hit master. In the history books of comp sci, chef will be a sad allegory about the lawyers leading the horse to a desert in search of water for fear of rain.

**Closed** 2019-08-07 19:25 UTC
Labels: Component: Chef Core, Type: Enhancement

**Comment by zedtux** [comment] 2019-08-08 04:17
@sempervictus is there a way to implement it via a gem which would extends Chef?

@lamont-granquist why did you closed that issue?
