### ISSUE TITLE
knife startup performance regression 12.2.1 -> 12.4.1

### ISSUE THREAD

**Issue by iroller** [chef/chef#3940] opened 2015-09-22 00:54 UTC
I noticed a big performance regression when using knife in 12.4.1. It's 6 seconds vs under 1 second in 12.2.1.

To reproduce it you can clone my repo with Gemfiles from https://github.com/iroller/chef-12-4-1-perf-regression, bundle install and try it yourself.

```
$ git clone https://github.com/iroller/chef-12-4-1-perf-regression
$ cd chef-12-4-1-perf-regression
$ cd chef-12-2-1 && bundle install
$ cd ../chef-12-4-1 && bundle install
```

Ruby version:
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
```

Chef 12.4.1:
```
➜  chef-12-4-1  time bundle exec knife --version
Chef: 12.4.1
bundle exec knife --version  0.57s user 0.18s system 12% cpu 5.915 total
```

Chef 12.2.1:
```
➜  chef-12-2-1  time bundle exec knife --version
Chef: 12.2.1
bundle exec knife --version  0.41s user 0.11s system 91% cpu 0.567 total
```

OS version: MacOSX El Capitan 10.11
```
Darwin 15.0.0 Darwin Kernel Version 15.0.0 root:xnu-3247.1.106~5/RELEASE_X86_64 x86_64
```

**Comment by lamont-granquist** [comment] 2015-11-05 18:24
This is likely fixed by #4130, but I can't replicate on my Ubuntu box.  Root cause seems to be a DNS timeout due to the hostname not being in /etc/hosts which is triggered via Chef::HTTP loading in chef-zero and webrick which does DNS lookups at class loading time...  lazied the chef-zero require in Chef::HTTP so we only load chef-zero/webrick if we need to, which should have fixed the problem.

Consistent with what looks like a 5 second timeout in the above output.

**Comment by lamont-granquist** [comment] 2015-11-05 18:25
Closing since we think its fixed, re-open if this didn't fix it, or open another ticket if there's more perf issues with knife that haven't been addressed.

**Closed by lamont-granquist** 2015-11-05 18:25 UTC

**Comment by iroller** [comment] 2015-11-06 01:46
Yes this helped. Thanks a lot :+1:
