### ISSUE TITLE
knife search (data_bag) with specific attribute is parsing results incorrectly.

### ISSUE THREAD

**Issue by gmiranda23** [chef/chef#3410] opened 2015-05-21 17:26 UTC
knife 12.3.0 is displaying search results from data_bags incorrectly.  In the example below, "users" is the name of a data_bag with 2 items in it.

$ knife search users "*:*" -a shell
2 items found

:
  shell: /bin/bash

:
  shell: /bin/bash
$ knife -v
Chef: 12.3.0

Prior versions of knife display results like so:
$ knife search users "*:*" -a shell
2 items found

data_bag_item_users_bobo:
  shell: /bin/bash

data_bag_item_users_frank:
  shell: /bin/bash
$ knife -v
11.18.10

Searching other indexes appears to return proper formatting.  May be related to #3018

**Comment by lamont-granquist** [comment] 2015-08-19 17:43
Confirmed this is still a bug in master

**Comment by sanga1794** [comment] 2021-06-30 11:07
Hi @gmiranda23 , We have gone through all documents and issue description, Existing functionality is working as expected because we are adding attributes filter which gives us only desired output.
@lamont-granquist  please provide your thoughts and please correct me if i'm missing something. Thanks!!

**Comment by sanga1794** [comment] 2021-07-14 07:39
@gmiranda23 For time being we are closing this issue, Please let us know if you still have any queries. Thanks!!

**Closed by sanga1794** 2021-07-14 07:39 UTC
Labels: Focus: knife search, Priority: Medium, Status: Sustaining Backlog, Type: Bug
