### ISSUE TITLE
Make Chef distributable under a configurable name - wordmarks in outputs

### ISSUE THREAD

**Issue by bobchaos** [chef/chef#8376] opened 2019-04-16 00:58 UTC
## Motivation
    As a community member,
    I want to distribute Chef under a different name,
    so that we can all use and contribute to chef OSS.
 
We're attempting to address the various concerns raised by the community following the announcement that all Chef products will become OSS but the Trademark policy prevents redistribution of the software as-is. In short, the code contains multiple  references to Chef wordmarks, including the binary names themselves, that need to be either substituted or removed in a simple way. 

## Context

This problem has multiple facets, at this time the following 3 broad angles have been identified:
- The `chef` gem's binstubs make it impossible to distribute while complying with the trademark policy
  - by removing the binstubs, the chef gem effectively becomes a library and classifies as "internals", which would presumably exclude it from the policy statement 
- The code itself has wordmarks sprinkled in all kinds of log messages and command outputs
  - To comply all outwardly facing messages must have wordmarks removed
- The binaries and folder structure also contain wordmarks (`chef-client`, `/etc/chef`, etc...)
  - These will likely need to have at least some modifications handled at build time

This design proposal aims at addressing the second point, the wordmarks being outputted by `chef`

### cleaning out wordmarks from outputs and logs
this can be solved by creating a new set of constants under the namespace `Chef::Dist`. These new constant would match wordmarks such as "Chef" or "chef-client" in all user-facing messages and outputs as required by https://www.chef.io/trademark-policy/ . An exhaustive list of these changes does not exist at this time.

In log messages and other ruby string objects, wordmarks would be substituted directly through interpolation ie: `"Chef Server" => "#{Chef::Dist::PRODUCT} Server"`.

Other messages may require a bit more work. Windows Event logs come to mind, they are currently present as static files in the code and would require to be made dynamic through ERB or some other solution.

Tests that fail as a result of expecting a wordmark must be modified to ignore the presence of the wordmark, or alternatively to use the distro constant if ignoring the wordmark would break the _intent_ of the test.

The notion of `Chef::Dist` constants could be applied to other projects affected by the recent announcements (Inspec, Automate, Habitat, etc...)

## Downstream Impact

At this point in time the community has identified a number of repositories that will need to be edited in order to make Chef distributable.

| Repo/Product | Patch Needed? | Reason/Example | PR(s)link | Status(es) |
| ------ | ------ | ------ | ----- | ----- |
| chef | Yes | Trademarked Binaries and marks in logs | https://github.com/chef/chef/pull/8368 | Merged |
| chef-workstation | Yes | Transitives binaries from included products |
| chef-dk | Yes | Trademarked, binaries and logs |
| inspec | yes | Trademarked, binaries and logs |
| chef-server | yes | Trademarked, binaries and logs |
| chef-zero | yes | Trademark in binary and outputs | https://github.com/chef/chef-zero/pull/293 | Open |
| Ohai| No | Not trademarked, no reference to a trademarked word in code |
| omnibus | Yes/No | relies on chef-client run |
| cookstyle | No | Not trademarked, no reference |
| chef-vault | Yes | Trademark in binary name  |
| cheffish | Probably no | two occurence of chef_run as output, likely to never be seen by most users |
| opscode-pushy-client | No? | only one Chef occurence in postinst, not a problem when included |

Evaluating the surface is an ongoing effort. It is however safe to assume that the entire ecosystem will feel this change in some form or other.

## Related PRs
~https://github.com/chef/chef/pull/8368 propose an initial implementation of chef/dist.rb with some first replacement~ Closed since this proposal was accepted.

## Words to replace
An incomplete list of words that are or contain wordmarks that will need to be addressed:
- chef-solo
- chef-zero
- ~chef-client~ https://github.com/chef/chef/pull/8418 should handle everything chef-client related
- Chef (Fully expected to get tricky)

**Comment by artem-sidorenko** [comment] 2019-04-17 08:39
https://github.com/inspec/inspec/pull/3954 is the related inspec/dist.rb PR

**Comment by bobchaos** [comment] 2019-04-17 18:08
@Tensibai has raised an interesting issue: even with these constants in, when someone puts a `require 'chef'` in his gemfile he's going to pull from rubygems.org, where there will be the gem published by `Chef` with their own distro constants in there, causing whatever they are building to output trademarks. For `cinc-client` we can inject the new constants in Omnibus, but we'd effectively be forcing anyone that depends on `chef` gem to do some shenanigan or other to replace `lib/chef/Dist.rb`, or alternatively for the `chef` gem to be 100% debranded (make the Distro constants completely generic). Thoughts anyone?

**Comment by artem-sidorenko** [comment] 2019-04-17 18:17
Right. I remember some discussion in slack about that? I'm sure chef folks are aware of this issue: depending on how the binstubs/gem library changes going to be, this can be resolved by having another gem with binstubs and according dist settings or something like that (chef gem as a common library and customer facing part via another gem)

**Comment by nellshamrell** [comment] 2019-04-17 20:58
Thank you for this write up and the input so far!

I'd like to repeat back what I believe I'm hearing to ensure I have it correct:

This proposal proposes to make Chef distributable under a configurable name (i.e. "cinq")

This includes:
1. Removing the binstubs from the Chef gem, therefore making it a library, rather than an executable. (Chef is on board with this change!)
2. Remove Chef wordmarks from the Chef gem's code and replace them with the community distro's name (i.e. "chef exec" would become "cinq exec")
3. Remove Chef wordmarks from binaries and folder structures (this would likely be done at build time).

Focusing on #2 - removing Chef wordmarks from output and logs.
* Create namespace Chef::Dist
* All current word marks in code would be replaced with configurable distribution variable. i.e. "Chef Server" would become "#{Chef::Dist::PRODUCT} Server"

Potential issue with this approach:
* Even if we make the Chef gem a library rather than an executable, the 'chef' gem distributed through RubyGems would contain chef's wordmarks.
* If anyone were to pull the Chef gem into their code through a Gemfile with require 'chef' (assuming they are using RubyGems as their gem library), they would get a version of the library which includes Chef's wordmarks, rather then configurable word marks
* If someone were to want to use the "chef" gem as a library, how would they overwrite Chef's word marks?

Does this sound correct?

**Comment by nellshamrell** [comment] 2019-04-17 23:32
For reference, I'm adding some of Corey Scobie's statements from the Community Slack into here so they don't get lost when we hit the 10,000 message limit.

"Thanks to everyone participating in this discussion over the past week. One thing is for certain, we are definitely breaking new ground here. As a project, Chef and it's ecosystem was never designed to anticipate that there might be multiple parallel distributions of it in the future and I think the progress you've made in a short period of time is fantastic. I know there a bunch of implementation questions on the table and we (myself, Robb, Lamont, Tim, Nell, BTM, and the rest of talented engineering team) are here to help.
One observation is that it feels like this effort is trying to consider too many scenarios right out of the gate. I get that at some point migration between distros is going to be an issue, but my advice is to focus on building something that works in the "net new install" case to start. I would recommend targeting a distro that uses as much of the Chef internals as you can, but can be installed stand alone and parallel to a Chef installation without polluting or overloading the Chef footprint. Once you have that, I think working out the ecosystem interoperability and migration should be a snap.

Some answers I think you are looking for:
- Do you need to change the installation path for stuff? Yes. Don't reuse /opt/chef, /etc/chef, etc. Aside from the trademark guidance earlier, I think by doing this work we will improve Chef and the community distro and other tools as well. No good software is dependent on being present in a specific path on a system. It will create some breakage but we can work out those cases one by one. It will make migration a little harder but that's what symlinks and other tools are for and we are cool if the installer sets it up. Besides, we have a wicked piece of configuration management software that can help us with migration too. :wink:
- What about referencing the chef gem? Not a problem. Yes, it will need some patching too. So will other libraries to deal with the branding stuff, but we can collaborate on that work together. If you think wrapping it is better that's fine, but doesn't really change the fact that the core gem as a library needs some work.
- Do you need to change config variables? Yes. Because it is something external to the software that a user interacts with. Again, it will create some breakage but the variable prefix shouldn't misrepresent the actual distribution being run. (edited) 
I want to reaffirm that we are here to help and that it is in Chef Software's best interest that we maintain interoperability with other distributions as well.
What other questions have I missed?"

"If we make the gem a library and not a pseudo installer, it doesn't need a license. Hence the "removing binstubs" stuff. The problem is that in some places it is being treated as an installer, so changing it will be disruptive so we'll have to handle that with some special care."

**Comment by nellshamrell** [comment] 2019-04-17 23:40
Something I'm wondering - would it be possible to have a "chef" gem and a "cinq" gem? Perhaps each would have its own Gemspec in this repo - one would fill in the Chef wordmarks and one would fill in the Cinq wordmarks. Would this be a potential solution?

**Comment by bobchaos** [comment] 2019-04-18 00:29
it's possible, that would however force people using `chef` as a library in openly distributed projects to migrate their dependency. That said I think we should expect a cascade of major version bumps in the ecosystem anyhow on account of the broad overhaul to all visible outputs, so I suppose the overall impact of changing dependency would be minimal.

If we go for 2 gems tho, wouldn't we be better with a "Chef branded" gem and a "unbranded" gem (as opposed to "community branded")?

Anyhow, 2 gems published by Chef to rubygems, including one that's compliant with the trademark policy, works for me.

**Comment by bobchaos** [comment] 2019-04-18 00:29
I'd like to raise an additional concern: I suspect many community members will want a free and compliant community distro before Chef 14 EOL on account of being unable to pay for a commercial relation with Chef. That's one year to get the work done, which is more than enough, but breaking changes could put us in a situation where we have to wait until Chef 16, or even 17, to implement some required changes. Am I worried for nothing? And if not, what can we do to ensure a community distro is available by Chef 14 EOL? Would Chef be open to things like extending Chef 14's EOL date, or perhaps accelerating it's release cycles for a short time, or some other solution?

**Comment by nellshamrell** [comment] 2019-04-18 17:12
Hi @bobchaos!

These are good points and good questions. We have no plans to delay (or consider delaying) the EOL of Chef 14 at this time. We would likely collaborate with the community to find a different workaround should something require asking that question. 

My instinct is let's wait until something concrete warrants discussing speeding up the release cycle (or another workaround), and let's address it then.

**Comment by nellshamrell** [comment] 2019-04-18 20:36
I'm starting to wonder (not representing official position of Chef here, just my own thoughts) if it makes sense to have the chef gem be the chef branded gem, the cinq gem to be the cinq branded gem, and then have a separate gem be the unbranded gem that both of them depend on.

**Comment by Tensibai** [comment] 2019-04-18 21:28
@nellshamrell In my opinion to avoid breaking too much the ecosystem the best path would be to have chef gem as the library (no user facing things, input/output/path), a chef-official as the branded chef-client and if really needed a cinc gem with cinc branding, the last two depending on chef gem.

This may allow to not break berkshelf for exemple and be compliant with the policy, this was what I meant by talking about splitting the gem in backend and frontend parts on slack. 

The drawback is that's a lot of work to achieve a pure library gem, formatters and Chef::Application::Run outputs are the first obvious one to review, maybe Chef:Application::Run should be removed from the library part also ? (Very unsure this makes sense)

**Comment by lamont-granquist** [comment] 2019-04-19 18:11
I would advise against a cinc gem, certainly not to start with.

Ultimately you're going to be creating more infrastructure problems for yourself.  You've already signed up for a lot of work here, and a cinc gem sounds to me like it would be prone to forking the codebase more directly.  If it not, then it still boils down to the fact that you're going to have to have a build process that pulls down the chef gem and patches out the chef-branded part of it and then you need to produce all the different artifacts.  You should really focus on the omnibus and hab artifacts first.

To the extent that you think the cinc gem gains you anything technically I think you'll find on examination that you're forking the codebase and you're going to get into conflicts (probably with me or tim) when we make changes to the core chef and patching that you have to do in order to ship the cinc gem breaks.  Even just in the gemspec when we tweak that (which has considerable churn) you're signing up for having drift and patch conflicts just over that file.  And that is not an external API file and we may make changes to that in any and every minor release, and we reserve the right to change that file whenever we like, particularly to fix build breakage issues.

I can see where it could be useful to end users, ultimately, but I think you're starting down the road of engaging in waterfall design.  Once you get working omnibus and hab builds you can turn around and decide to produce a cinc gem, but I'd delay that decision until you get to that point and see how much work it is going to be.  If you think you need up-front design work on that, I'd argue again that it sounds like your concept of the cinc gem involves a lot of drift and patching -- conversely if it does not involve a lot of drift and patching it should be easy to do later.  And on the generic topic of waterfall design all I have to do is point at the chef-rfc repo and the large number of unfunded mandates that have never been produced there and the fact that we just voted to close up shop on that process.

Also, we're not splitting the gem into frontend and backend parts in a large engineering effort (we have no human resources to do that work internally within Chef, so it will not happen).  We are removing the binstubs from the gem.  If you like you can view that as removing the frontend and the backend parts.  That is how I view it since the binstubs are the public API of the 'frontend', the Chef::Application classes are implementation details of the frontend which are shipped in the "library".  I see no compelling technical reason to split up the library gem into different parts.  If there are things that need to change there it needs to be made configurable (we're already going to make the license acceptance configurable via a flag exposed into the binstubs, and Chef::Dist is another way to expose a very minimal surface area that needs changes).

And, I think you also need to not be too concerned about the chef branding in the chef gem.  That is entirely our problem.  Right now we're leaving it there, at some point in the future we could choose to leverage Chef::Dist to ship a hey-you're-using-this-as-a-library-without-a-license branded chef gem and replace that file in our omnibus builds to the official version.  That isn't really something for the community effort to worry about though.

So in summary, just worry about implementing Chef::Dist for now and getting omnibus and hab builds out.  That alone is going to be a ton of work.  It isn't going to help you at all to worry about issues around the chef gem that are entirely ours to worry about.  You should also make sure that you're not creating designs that require unfunded mandates internal to Chef to get a lot of work done, or which create churn and patching burden for yourself, those should be top design priorities.  Just Engineer-to-Engineer if you don't keep things as simple as possible and work in an agile/iterative manner you risk not being successful.

Ah right, and you're already trying to cover all the product matrix in this design doc.  Yeah, this is already a massive amount of effort, you need to keep it simple and somewhat focused.

**Comment by Tensibai** [comment] 2019-04-19 18:30
@lamont as long as omnibus itself include Chef gem and that a reconfigure call start a chef run with 'Chef client starting <version>' we can't do omnibus build of chef-server for example without an ugly patching of Chef::Dist during the build.
We may work around that, but folks at gitlab or other using omnibus without being aware of this change will be thrown in breaking Chef's trademark policy without even knowing it.

The binaries are far from the hard part, the hard part is the knife help output, formatters, run start, paths etc. 

I'm very against having to publish a cinc gem as it shouldn't be of any use to anyone, but I hardly see a proper pipeline without it for other omnibus builds as long as the chef gem outputs have the brand in them (which is fairly normal as it's your build). 
If I did miss an option to easily patch the dist.rb file in depended gems with omnibus I'm all ear as it would erase nearly all my concerns. 

I'm all in favor of a community packaging of Chef products, the actual policy just doesn't allow it at my actual knowledge. 

Hab packages are out of talk for now (talking for myself) as we don't know if we'll have acces to builder depot or not, and hosting a community depot doesn't really makes sense to me.

Concernig the builds, we have two omnibus builds of the chef repo and with the PR linked above working for now 10 days, we still don't know if they are satisfying for Chef or not that said.

**Comment by bobchaos** [comment] 2019-04-19 18:41
A Slack conversation involving Corey Scobie that is relevant here (Still viewable in the history as of this writing):
holoway   [Apr 13th at 1:50 PM]
for example, if `/etc/cinc` exists, but the config file still has `Chef::Config[:chef_server_url]`, I think its still clear you're in cinc land
4 replies
cscobie   [6 days ago]
Yes. This.
BobChaos   [6 days ago]
so we're all clear tho, this ALSO will mean that `cinc-client --chef_server_url` will be a thing. If there's no objection to that either then I think we'll have all the answers needed regarding config directives, as I assume this extends to things like `chef_zero_port` and `chef_zero_host` (edited)
holoway   [6 days ago]
@cscobie ^^ what do you think? I would say this is fine, because otherwise we break compatibility
cscobie   [4 days ago]
This is fine.

**Comment by bobchaos** [comment] 2019-04-19 18:48
@lamont-granquist so you would also lean towards the defaults `Chef::Dist::*` in `chef/chef` to be "generic brand"?

**Comment by lamont-granquist** [comment] 2019-04-19 21:27
For now, no, those should be Chef branded.

**Comment by lamont-granquist** [comment] 2019-04-19 21:29
(and we'll modify them to be generic-branded if and when we need that -- right now I don't see the need, but I've already got that one in the back of my mind as a technical solution to suggest if we hit any problems going down the route we're going)

**Comment by lamont-granquist** [comment] 2019-04-19 21:36
> If I did miss an option to easily patch the dist.rb file in depended gems with omnibus I'm all ear as it would erase nearly all my concerns.

that's fairly trivial to replace a file in the build any number of ways.

the somewhat hacky stuff i'm doing to move binstubs around is going to be worse than what you wind up doing:

https://github.com/chef/omnibus-software/blob/7c611c48e006e4284a1ee5909215e746d58296d4/config/software/chef.rb#L84-L99

the replacement of the Chef::Dist file should be one copy statement by comparison.

**Comment by bobchaos** [comment] 2019-04-19 22:49
@nellshamrell is this the sort of thing you had in mind? https://github.com/cc-build/chef/commit/fd615d2b958c37e6f4c2ab4110faf1c9dd928d6b It's not exactly pretty but it should convey the idea I hope,

**Comment by bobchaos** [comment] 2019-04-26 04:16
Original post updated with latest info

**Comment by tas50** [comment] 2019-04-26 05:27
Closing this out since it's been merged into chef.

**Closed by tas50** 2019-04-26 05:27 UTC
Labels: Type: Design Proposal

**Comment by Tensibai** [comment] 2019-04-26 05:43
@tas50 asking here so it doesn't get lost in slack history: don't we should keep this issue open to write the design document?
