### ISSUE TITLE
(windows) knife cookbook site download puts cookbook in a wrong location 

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4162] opened 2015-11-13 01:39 UTC
bug: knife cookbook site download reports placing a cookbook in one location, but actually places cookbook in a different location

example:
PS C:> `knife cookbook site download apache`
WARNING: No knife configuration file found
Downloading apache from Supermarket at version 0.0.5 to C:/apache-0.0.5.tar.gz
Cookbook saved: C:/apache-0.0.5.tar.gz

```
PS C:\> dir
    Directory: C:\

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        10/21/2015   5:53 PM            MSOTraceLite
d----        11/10/2015   4:16 PM            opscode
d----        10/19/2015   6:58 PM            Packages
d----         8/22/2013   8:52 AM            PerfLogs
d-r--        11/11/2015   2:09 PM            Program Files
d----        11/11/2015   2:09 PM            Program Files (x86)
d-r--        10/21/2015   5:48 PM            Users
d-r--        11/11/2015   2:04 PM            Windows
d----        10/19/2015   6:57 PM            WindowsAzure
```

**Actual:**

```
C:\>dir apache*.gz /s
 Volume in drive C has no label.
 Volume Serial Number is 1053-9A7D

 Directory of C:\Users\v-alviny\AppData\Local\VirtualStore

11/12/2015  05:34 PM             3,361 apache-0.0.5.tar.gz
               1 File(s)          3,361 bytes
```

**Comment by PatrickWalker** [comment] 2016-01-04 21:27
Hey on a Windows 10 machine I saw it being downloaded to C:\Users\User\apache-0.0.5.tar.gz and reported correctly

C:\Users\user>knife cookbook site download apache --verbose
WARNING: No knife configuration file found
Downloading apache from Supermarket at version 0.0.5 to C:/Users/user/apache-0.0.5.tar.gz
Cookbook saved: C:/Users/user/apache-0.0.5.tar.gz

C:\Users\user>cd C:/Users/user

C:\Users\user>dir
 Volume in drive C is Windows
 Volume Serial Number is 5CE3-334B

 Directory of C:\Users\user

04/01/2016  21:15    <DIR>          .
04/01/2016  21:15    <DIR>          ..
04/01/2016  21:15             3,361 apache-0.0.5.tar.gz

What Knife version are you using?

C:\Users\user>knife --version
Chef: 12.6.0

Is mine

**Comment by vinyar** [comment] 2016-03-16 06:22
could be related to this: https://github.com/chef/chef-dk/issues/576

**Comment by cheeseplus** [comment] 2018-01-31 14:33
Closing as dupe of https://github.com/chef/chef/issues/4094

**Closed by cheeseplus** 2018-01-31 14:33 UTC
Labels: Area: Windows, Type: Bug
