### ISSUE TITLE
overriding 'status_command' in services is broken:

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#3992] opened 2015-09-29 03:39 UTC
You can no longer override 'status_command' for services, it'll break with:

```
service[test]: unable to locate the init.d script!
```

Sample code:

```
service 'test' do
  status_command '/bin/true status'
  start_command '/bin/true start'
  stop_command '/bin/true stop'
  restart_command '/bin/true restart'
end

file '/tmp/wakakaka' do
  notifies :restart, 'service[test]'
end
```

This will fail with the above error. This worked in 12.0.3 and every release before but seems to be broken as of at least 12.4.1, maybe before.

**Comment by andy-dufour** [comment] 2015-09-29 04:14
I can't reproduce using the above sample - i successfully converge on ubuntu 14 and centos 7. What platform did this error on for you?

**Comment by jaymzh** [comment] 2015-09-29 05:46
CentOS 6. I can repro on 12.4.1 and 12.5.0-daily from a few days ago.

Almost certainly this is limited to Redhat-like OSes, and probably < 7 since C7 uses Systemd.

**Comment by andy-dufour** [comment] 2015-09-29 14:00
Thanks, I can reproduce on CentOS 6.

**Comment by jaymzh** [comment] 2015-09-29 18:37
CC @lamont-granquist  I think he was changing the way this code inherited recently...

**Comment by lamont-granquist** [comment] 2015-10-01 20:13
I can't see where this changed, certainly it was an unintended side-effect of something.  The patch looks obviously correct.

**Comment by thommay** [comment] 2015-11-05 18:26
Fixed in master, hence closing!

**Closed by thommay** 2015-11-05 18:26 UTC
