### ISSUE TITLE
Add a new zip_file Resource to Chef Client

### ISSUE THREAD

**Issue by jeffreycoe** [chef/chef#5956] opened 2017-03-28 22:52 UTC
## Description

The Chef client today does not contain any native resources to extract or manage compressed zip files.  This requires the use of third party Ruby gems and cookbooks which are not included with the Chef client and do not all support the same platform. Having one zip_file resource would help with developing code to support multiple platforms.

## Chef Version

Chef Client 12.19.36

## Platform Version

All platforms

## Replication Case

N/A

## Client Output

N/A

## Stacktrace

N/A

**Comment by coderanger** [comment] 2017-03-28 22:57
Just for the record, poise-archive supports this on all platforms but disclaimer I wrote it :) Given how complex this is to handle, I'm not a fan of putting it in core.

**Comment by lamont-granquist** [comment] 2017-03-30 00:47
Yeah, this is not the highest priority for core, it would be better addressed as a cookbook, and prototyping in a cookbook would most likely be a prerequisite for inclusion into core.

There also just aren't enough details here to implement -- sketch of an API, use cases, what dependent gems would need to get slurped in, etc.

**Comment by lamont-granquist** [comment] 2017-03-30 00:53
Actually closing this since its not a bug, and its product feedback which should get submitted to: 

https://feedback.chef.io/forums/301644-chef-product-feedback

Not necessarily inherently a bad idea, but it needs to go through channels where we can determine how much user support there is for it, and as a proposal there needs to be at least some polish applied to it.

**Closed by lamont-granquist** 2017-03-30 00:53 UTC
