### ISSUE TITLE
chef MSI 13.1.31 fail when using custom location path

### ISSUE THREAD

**Issue by lbn-chef-team** [chef/chef#6189] opened 2017-05-31 07:52 UTC
## Description

On any windows plateform, when running MSI with custom location like "C:\MyPath\Programs\opscode", the installation of MSI fail with this message: Chef Client v13.1.31 Setup Wizard ended prematurely

## Chef Version

Only with chef MSI "stable" release 13.1.31 x64
(Working fine with 13.0.118)

## Platform Version
Tested on Windows 2012r2 and Windows 2016

## Replication Case

Run MSI and change location C:\opscode to C:\TestAnotherPath\Programs\opscode
The window appears:
![image](https://cloud.githubusercontent.com/assets/14806593/26620574/aa7b7872-45e3-11e7-8082-df0b5d0c6208.png)

## trace of MSI
When running msiexec /i chef-client-13.1.31-1-x64.msi INSTALLLOCATION="C:\TestAnotherPath\Programs\opscode" /L*V chefmsi.log

Here the log content:

```
MSI (s) (48:48) [09:38:02:480]: Executing op: FolderCreate(Folder=C:\TestAnotherPath\Programs\opscode\chef\,Foreign=0,SecurityDescriptor=BinaryData,)
CreateFolders: Folder: C:\TestAnotherPath\Programs\opscode\chef\
MSI (s) (48:48) [09:38:02:484]: Executing op: ActionStart(Name=InstallFiles,Description=Copying new files,Template=File: [1],  Directory: [9],  Size: [6])
Action 9:38:02: InstallFiles. Copying new files
MSI (s) (48:48) [09:38:02:487]: Executing op: ProgressTotal(Total=192179097,Type=0,ByteEquivalent=1)
MSI (s) (48:48) [09:38:02:487]: Executing op: SetTargetFolder(Folder=C:\TestAnotherPath\Programs\opscode\)
MSI (s) (48:48) [09:38:02:488]: Executing op: SetSourceFolder(Folder=1\opscode\)
MSI (s) (48:48) [09:38:02:488]: Executing op: ChangeMedia(,MediaPrompt=Please insert the disk: ,MediaCabinet=ChefClient.cab,BytesPerTick=65536,CopierType=2,ModuleFileName=C:\Windows\Installer\9d82daa.msi,,,,,IsFirstPhysicalMedia=1)
MSI (s) (48:48) [09:38:02:488]: Executing op: FileCopy(SourceName=chef.zip,SourceCabKey=filA11494F21FE6160B8815989A459B35D7,DestName=chef.zip,Attributes=512,FileSize=192179097,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=58982400,HashOptions=0,HashPart1=1744283584,HashPart2=-282386709,HashPart3=-1857956628,HashPart4=525996155,,)
MSI (s) (48:48) [09:38:02:488]: File: C:\TestAnotherPath\Programs\opscode\chef.zip;	To be installed;	Won't patch;	No existing file
MSI (s) (48:48) [09:38:02:488]: Source for file 'filA11494F21FE6160B8815989A459B35D7' is compressed
InstallFiles: File: chef.zip,  Directory: C:\TestAnotherPath\Programs\opscode\,  Size: 192179097
MSI (s) (48:48) [09:38:05:052]: Executing op: CacheSizeFlush(,)
MSI (s) (48:48) [09:38:05:052]: Executing op: ActionStart(Name=FastUnzip,Description=Extracting files, please wait...,)
Action 9:38:05: FastUnzip. Extracting files, please wait...
MSI (s) (48:48) [09:38:05:099]: Executing op: CustomActionSchedule(Action=FastUnzip,ActionType=3073,Source=BinaryData,Target=FastUnzip,CustomActionData=FASTZIPDIR=C:\TestAnotherPath\Programs\opscode\;FASTZIPAPPNAME=chef)
MSI (s) (48:84) [09:38:05:105]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIE76D.tmp, Entrypoint: FastUnzip
MSI (s) (48:04) [09:38:05:105]: Generating random cookie.
MSI (s) (48:04) [09:38:05:109]: Created Custom Action Server with PID 1996 (0x7CC).
MSI (s) (48:58) [09:38:05:165]: Running as a service.
MSI (s) (48:2C) [09:38:05:170]: Hello, I'm your 32bit Elevated custom action server.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIE76D.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action CustomActionFastMsi!CustomActionFastMsi.CustomActions.FastUnzip
Starting FastUnzip
FASTZIPDIR = C:\TestAnotherPath\Programs\opscode\
FASTZIPAPPNAME = chef
Starting extraction
Exception thrown by custom action:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> **System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.**
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at CustomActionFastMsi.CustomActions.FastUnzip(Session session)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.InvokeCustomAction(Int32 sessionHandle, String entryPoint, IntPtr remotingDelegatePtr)
CustomAction FastUnzip returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 9:38:45: InstallFinalize. Return value 3.
MSI (s) (48:48) [09:38:45:448]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (48:48) [09:38:45:449]: User policy value 'DisableRollback' is 0
MSI (s) (48:48) [09:38:45:449]: Machine policy value 'DisableRollback' is 0
MSI (s) (48:48) [09:38:45:454]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1254051010,LangId=1033,Platform=589824,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (48:48) [09:38:45:454]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (48:48) [09:38:45:465]: Executing op: DialogInfo(Type=1,Argument=Chef Client v13.1.31)
MSI (s) (48:48) [09:38:45:466]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
Action 9:38:45: Rollback. Rolling back action:
Rollback: Extracting files, please wait...
```

## Identified Cause 
Exception has been thrown by the target of an invocation. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248

**Comment by seththoenen** [comment] 2017-06-01 21:20
I originally had the same problem on 2008 R2, 2012 R2, and 2016. However, I ended up rebooting  and everything worked fine afterwards. I'm not sure if this is a Windows issue or a Chef issue.

**Comment by lamont-granquist** [comment] 2017-09-21 20:08
that looks like the window msi installer can't handle unzipping files into directories that ultimately result in some of the paths exceeding the 248/260 character limit, not sure what could be done about this here.  if it is a bug, its not a bug in this repo and would be something to do with how we package MSIs in chef/omnibus.

**Comment by lamont-granquist** [comment] 2017-09-21 20:10
(and unless we just have some cruft to delete in the install, we're unlikely to start auditing our package for long pathnames, since we pull in external gems and those get put in the ruby libdir directory some of those paths will grow to be large, and there's not a lot we can do about it which won't just break again a few months down the road -- or may not be anything we can do about it at all...  and there will also clearly always be a long enough path that someone could give to the installer that would cause it to blow up)

**Comment by stuartpreston** [comment] 2018-07-18 14:04
Closing this as there's not much we can do other than monitor for the longest path in the Chef install and take action at packaging time.  We package out of the identical path to a default setup so any issues should be found there.  The top 10 paths by length are shown below:

![image](https://user-images.githubusercontent.com/6384654/42886521-aec96cc4-8a9b-11e8-81c0-077b6f0b214a.png)

**Closed by stuartpreston** 2018-07-18 14:04 UTC
Labels: Area: Windows
