### ISSUE TITLE
LWRP kind_of Fixnum default not being set

### ISSUE THREAD

**Issue by chasebolt** [chef/chef#4174] opened 2015-11-16 19:24 UTC
I have a simple LWRP that I am relying on the default value of a Fixnum attribute. In chef 12.4.3 the default value is correctly set, but as of chef 12.5.1 the attribute is unset.

i have a kitchen test case here:
https://github.com/chasebolt/chef-template-bug

and a gist of the new_resource.to_hash:
https://gist.github.com/chasebolt/81dda5eb95f8be5da323

**Comment by coderanger** [comment] 2015-11-16 19:26
Duplicate of #4127

**Closed by coderanger** 2015-11-16 19:26 UTC
