### ISSUE TITLE
DeepMerge#safe_dup is not safe

### ISSUE THREAD

**Issue by brauliobo** [chef/chef#2720] opened 2015-01-07 04:16 UTC
It won't recurse on subhashes so they will change after `deep_merge`

See http://stackoverflow.com/questions/8710642/ruby-dup-clone-recursively

**Comment by lamont-granquist** [comment] 2015-01-27 23:46
Yeah attributes need to be rewritten completely

**Comment by brauliobo** [comment] 2015-03-08 21:17
also, there is another error in behaviour. The right behaviour I believe is implemented on http://apidock.com/rails/Hash/deep_merge!, an example:
```
2.1.5 :001 > {a: {}}.deep_merge({a:nil})
 => {:a=>nil} 
```
And with Chef:
```
irb(main):003:0> Chef::Mixin::DeepMerge.deep_merge({a:{}}, {a:nil})                                                                                                                             
=> {:a=>{}}
```

**Comment by lamont-granquist** [comment] 2015-03-08 21:32
The chef 12 node.rm_* family of methods was introduced to delete attributes.  Merging with nil necessarily returns the attribute unchanged.  That is not a bug.

**Comment by lamont-granquist** [comment] 2015-06-24 17:55
This is getting addressed as part of a major rewrite of attributes, closing this is a dup of that (no PR or issue is open for that now though for tracking, but this will get fixed and closed as part of a current effort).

**Closed by lamont-granquist** 2015-06-24 17:55 UTC
Labels: Bug, Chef Core, Epic
