### ISSUE TITLE
remote_file not working with arrays

### ISSUE THREAD

**Issue by stinnux** [chef/chef#6816] opened 2018-01-31 16:20 UTC
## Description
We have a recipe which uses an array of URLs as an attribute to the source of a remote_file resource. 
This recipe is working perfectly using chef 13.6.4, but not in 13.7.16.
When compiling the recipe it says "remote_file has an empty source"

## Chef Version
13.7.16

## Platform Version
sue 12.3

## Replication Case
```
attributes: 

default['project']['domain']['url'] = [
    'https://url1',
    'https://url2',
    'https://url3',
]
default['project']['domain']['sha'] = 'sha256sum....'

recipe:
 remote_file '/hana/local/sapcar' do
    source node['project']['domain']['url']
    checksum node['project'][domain]['sha']
    owner 'root'
    group 'root'
    mode '0755'
    action :create
    show_progress true
  end

```
## Client Output
```

================================================================================
Recipe Compile Error in private.rb
================================================================================

ArgumentError
-------------
remote_file has an empty source

System Info:
------------
chef_version=13.7.16
platform=suse
platform_version=12.3
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-solo worker: ppid=17328;start=16:09:34;
executable=/opt/chef/bin/chef-solo

```

**Comment by thommay** [comment] 2018-01-31 16:24
Duplicate of #6784

**Comment by lamont-granquist** [comment] 2018-01-31 17:56
yeah closing in favor of #6784, this is an attribute bug not a remote_file bug.

**Closed by lamont-granquist** 2018-01-31 17:56 UTC
