### ISSUE TITLE
Client 12.9.41 gives Chef::Exceptions::ValidationFailed error during EncryptedDataBagItem.load that works on chef-client 12.5.1

### ISSUE THREAD

**Issue by kinnairdclan** [chef/chef#4892] opened 2016-05-04 17:09 UTC
## Description

I'm bootstrapping a node with a cookbook that works fine with chef-client 12.5.1, unfortunately the following code:

```
#Give admin users the borgbackup keypair
node["etc"]["group"]["admin"]["members"].each do |admin_user|

  file "/home/#{admin_user}/.ssh/borgbackup" do
    content Chef::EncryptedDataBagItem.load("borgbackup", "key")["content"]
    mode "0600"
    owner admin_user
    group admin_user
    sensitive true
  end

  file "/home/#{admin_user}/.ssh/borgbackup.pub" do
    content Chef::EncryptedDataBagItem.load("borgbackup", "pubkey")["content"]
    mode "0644"
    owner admin_user
    group admin_user
  end
end
```

Has rendered up the following error with chef-client 12.9.41 that halts the bootstrap:

`Chef::Exceptions::ValidationFailed: Option data_bag's value {"encrypted_data"=>"PffgOkpIpdoEJO8khrUOUQwqv2/vqrtzOf1U/z/a5xD4KqSH2/CkD1zHndzW\nwJL1\n", "iv"=>"d/kiiPRQWQoKBTU5WF8NPw==\n", "version"=>1, "cipher"=>"aes-256-cbc"} does not match regular expression /^[\-[:alnum:]_]+$/
`
Obviously, I'm supplying the same `--secret-file` as I did back then via knife CLI argument. Running `knife data bag show borgbackup key --secret-file /path/to/secret.pem` decrypts the cookbook content appropriately, and doesn't error out. Again, this is only upon bootstrap when a server's chef-client is communicating with the remote chef-server.

I can avoid this error by running with chef-client version 12.5.1, namely with `knife bootstrap --bootstrap-version 12.5.1 [...]`

[Posting on SO](https://stackoverflow.com/questions/35616044/chefexceptionsvalidationfailed-error-during-encrypteddatabagitem-load-due-to) 2 months ago, I was led to another reported instance of this problem at the Hangops Slack. That post involved chef-client 12.7.2. This bug does not seem to be fixed as assumed in my closed issue here: https://github.com/chef/chef/issues/4628

## Chef Version

12.9.41 (chef-client)

## Platform Version

Debian 8.4

## Client Output

https://gist.github.com/kinnairdclan/69b616e04841e05cc71e743699dd946f
## Stacktrace
https://gist.github.com/kinnairdclan/aaa7bce6e8e968ce938ec1e2292407b0

**Comment by thommay** [comment] 2016-05-04 17:15
Hi,
thanks for filing this, but please don't file duplicates of issues - feel free to re-open issues if you find them not to be closed. We're actually hashing out a plan for this in #4815, so I'm going to close this issue as a duplicate, and we'll continue work there.
Thanks!

**Closed by thommay** 2016-05-04 17:15 UTC

**Comment by kinnairdclan** [comment] 2016-05-04 17:20
Apologies, I'll keep an eye on #4815, for some reason I thought re-opening would actually elicit the quick re-close. Sorry for the noise.

**Comment by lamont-granquist** [comment] 2019-03-07 20:55
While it may be possible that #4815 and this share a root cause, it doesn't look like a duplicate use case and cut #8282 to track it separately
