### ISSUE TITLE
.kitchen directory causing path to be too long on Windows machines

### ISSUE THREAD

**Issue by emachnic** [chef/chef#4708] opened 2016-03-14 22:27 UTC
## Description

It appears that with version 12.8.1 of the Chef gem, the `.kitchen` directory being in the gem package is causing issues with Windows' path limitation of 260 characters when being installed via Bundler.

## Chef Version

Chef gem 12.8.1

## Platform Version

Windows 2012 R2

## Replication Case

Install Ruby using RubyInstaller and additionally make sure the DevKit is installed and has the Ruby linked properly and Bundler gem is installed. After that, add chef as a dependency in Gemfile of application. Running `bundle install` should fail and truncate the path. Running `gem install chef -v 12.8.1` should succeed fine but `bundle install` should still fail.

Another option would be to install Ruby and DevKit with Chocolatey which has an even longer path.

## Client Output

Not related to actual Chef Client run

## Stacktrace

```
[16:00:34]Installing chef 12.8.1 with native extensions
[16:00:37]
[16:00:37]Errno::ENOENT: No such file or directory @ dir_s_mkdir - C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/acceptance/top-cookbooks/test_run/learn-the-basics-ubuntu/cookbooks/learn-the-basics-ubuntu/.kitchen/kitchen-vagrant/kitchen-learn-the-basics-ubuntu-learn-the-basics-ubuntu-default-ubuntu-1404
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment] 2016-03-15 02:36
we don't support non-omnibus chef-client or chef-dk installs on windows machines.

everything after 'test_run' is not checked into this repo and was pushed accidentally to github, it'll be cleaned up with the next client release.

**Closed by lamont-granquist** 2016-03-15 02:36 UTC

**Comment by akemner** [comment] 2016-03-22 21:37
@lamont-granquist how am i supposed to test a cookbooks locally on windows? are you saying this isn't supported?

-i have a gemfile with things pinned.
-before every test i'm using chef exec bundle install
-then i run chef exec bundle rake 

except in this case my chef exec bundle install tries to install chef 12.8.1 and cannot and blows up, none of the other gems that would have installed after that are installed.

this makes chef development on a windows laptop very difficult

**Comment by lamont-granquist** [comment] 2016-03-22 22:08
`C:/RailsInstaller/Ruby2.1.0` that indicates you're rolling your own install, you should be using chef-dk.

**Comment by akemner** [comment] 2016-03-22 22:24
my usecase is different from @emachnic but i'm getting the same path issue. 

i'm using chef-dk 0.11.2. and got the error because i'm doing a chef exec bundle install, to make sure the gems that are pinned in my gemsfile are installed. i'm getting these from `source 'https://rubygems.org'`

even a `chef exec gem install chef -v 12.8.1` will reproduce this error on windows because the .kitchen directory

**Comment by pburkholder** [comment] 2016-03-22 22:44
@emachnic @akemner You've hit a gem packaging issue with 12.8.1 that will be fixed with a release in early April, or you can roll back to 12.7.2.  

A lot of test stuff got packaged with the gem so you are exposed that pathlength issue.

**Comment by emachnic** [comment] 2016-03-22 23:44
@pburkholder that's basically all I was saying originally. I wasn't asking for non-ChefDK support. 
Evan

Sent from Outlook Mobile




On Tue, Mar 22, 2016 at 3:45 PM -0700, "Peter Burkholder (@pburkholder)" <notifications@github.com> wrote:












@emachnic @akemner You've hit a gem packaging issue with 12.8.1 that will be fixed with a release in early April, or you can roll back to 12.7.2.  



A lot of test stuff got packaged with the gem so you are exposed that pathlength issue.

**Comment by spuder** [comment] 2016-03-29 01:06
+1

This blocks attempts to use appveyor to test windows cookbooks as documented here: 

http://www.hurryupandwait.io/blog/run-kitchen-tests-in-travis-and-appveyor-using-the-kitchen-machine-driver

**Comment by rossedman** [comment] 2016-03-30 15:17
I understand not supporting non chekdk stuff but this may have been closed prematurely. I am getting this error with ChefDK on Windows 2012 R2. Any advice?

```
30-Mar-2016 14:31:33    Errno::ENOENT: No such file or directory @ dir_s_mkdir - C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/acceptance/top-cookbooks/test_run/learn-the-basics-ubuntu/cookbooks/learn-the-basics-ubuntu/.kitchen/kitchen-vagrant/kitchen-learn-the-basics-ubuntu-learn-the-basics-ubuntu-default-ubuntu-1404
```

**Comment by davidnguy** [comment] 2016-03-30 23:19
I second Ross on his comment that this thread was closed prematurely.   This path length issue need to be resolved to support the Wintel platform.

**Comment by rossedman** [comment] 2016-03-31 15:35
@davidnguy I removed my comment as I wasn't able to formulate my speculations properly but I am still having a lot of problems, but I do believe there is still a problem. Looking for more concrete proof.

**Comment by braxnu** [comment] 2016-04-03 23:30
Still getting the error

`Errno::ENOENT: No such file or directory @ dir_s_mkdir - C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/chef-12.8.1-universal-mingw32/acceptance/top-cookbooks/test_run/learn-the-basics-ubuntu/cookbooks/learn-the-basics-ubuntu/.kitchen/kitchen-vagrant/kitchen-learn-the-basics-ubuntu-learn-the-basics-ubuntu-default-ubuntu-1404`

Win 8.1 64
ruby -v:
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
gem -v:  
2.4.5.1

**Comment by spuder** [comment] 2016-04-12 23:14
Chef 12.9 has been announced. 

https://discourse.chef.io/t/pre-release-announcement-chef-client-12-9/8215

Is there a way to look at the ruby gem that will be generated in 12.9 to see if it still contains this ridiculously long file path?
