### ISSUE TITLE
some kind of race condition with remote_file

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4829] opened 2016-04-14 09:24 UTC
## Description
remote_file resource fails inside an LXC with `http://packagecloud.io/gpg.key - getaddrinfo: Name or service not known` however setting a pry breakpoint and immediately exiting it, results in a successful converge

wget, ping, nslookup, etc all work fine.
I tried with a couple of different URLs all have the same result.

## Chef Version
```
chef-client -v
Chef: 12.9.38
```

## Platform Version
ubuntu 1504 with lxc 0.7
```
dpkg -l | grep lxc
ii  liblxc1                             1.1.5-0ubuntu0.15.04.3
ii  lxc                                 1.1.5-0ubuntu0.15.04.3
ii  lxc-dev                             1.1.5-0ubuntu0.15.04.3
ii  lxc-templates                       1.1.5-0ubuntu0.15.04.3
ii  lxcfs                               0.7-0ubuntu4.1
ii  python3-lxc                         1.1.5-0ubuntu0.15.04.3
```

## Replication Case
recipe:
```
cat a.rb
remote_file("/opt/opscode/embedded/cookbooks/cache/gpg.key") do
#require 'pry'
#binding.pry
  action [:create]
  source ["http://packagecloud.io/gpg.key"]
  atomic_update true
  path "/opt/opscode/embedded/cookbooks/cache/gpg.key"
end
```

error:
```
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * remote_file[/opt/opscode/embedded/cookbooks/cache/gpg.key] action create

    ================================================================================
    Error executing action `create` on resource 'remote_file[/opt/opscode/embedded/cookbooks/cache/gpg.key]'
    ================================================================================

    Errno::EHOSTUNREACH
    -------------------
    No route to host - connect(2) for "packagecloud.io" port 80

    Resource Declaration:
    ---------------------
    # In a

      1: remote_file("/opt/opscode/embedded/cookbooks/cache/gpg.key") do
      2: #require 'pry'
      3: #binding.pry
      4:   action [:create]
      5:   source ["http://packagecloud.io/gpg.key"]
      6:   atomic_update true
      7:   path "/opt/opscode/embedded/cookbooks/cache/gpg.key"
      8: end

    Compiled Resource:
    ------------------
    # Declared in a:1:in `run_chef_recipe'

    remote_file("/opt/opscode/embedded/cookbooks/cache/gpg.key") do
      provider Chef::Provider::RemoteFile
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      source ["http://packagecloud.io/gpg.key"]
      use_etag true
      use_last_modified true
      declared_type :remote_file
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
      atomic_update true
      path "/opt/opscode/embedded/cookbooks/cache/gpg.key"
    end

    Platform:
    ---------
    x86_64-linux
```

Pry breakout output:
```
sudo chef-apply a

Frame number: 0/11

From: /opt/opscode/embedded/cookbooks/cache/a @ line 4 self.run_chef_recipe:

    1: remote_file("/opt/opscode/embedded/cookbooks/cache/gpg.key") do
    2: require 'pry'
    3: binding.pry
 => 4:                                action [:create]
    5:                                source ["https://packagecloud.io/gpg.key"]
    6:                                atomic_update true
    7:                                path "/opt/opscode/embedded/cookbooks/cache/gpg.key"
    8:                              end

[1] pry(#<Chef::Resource::RemoteFile>)> exit
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * remote_file[/opt/opscode/embedded/cookbooks/cache/gpg.key] action create (up to date)
```

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## wget/ping results
ping packagecloud.io
PING packagecloud.io (50.97.198.58) 56(84) bytes of data.

nslookup packagecloud.io
Server:         10.0.3.1
Address:        10.0.3.1#53

Non-authoritative answer:
Name:   packagecloud.io
Address: 50.97.198.58

wget http://packagecloud.io/gpg.key
--2016-04-14 09:17:00--  http://packagecloud.io/gpg.key
Resolving packagecloud.io (packagecloud.io)... 50.97.198.58, 50.97.198.58
...
2016-04-14 09:17:01 (470 MB/s) - ‘gpg.key’ saved [3889/3889]

wget https://packagecloud.io/gpg.key
--2016-04-14 09:17:06--  https://packagecloud.io/gpg.key
...
2016-04-14 09:17:06 (721 MB/s) - ‘gpg.key.1’ saved [3889/3889]

**Comment by lamont-granquist** [comment] 2016-04-14 23:40
is this more first-converge problems caused by caching of /etc/resolv.conf settings in glibc?

similar to #2894 and #3100 and #3552?

if so there's no solution short of "run nscd, and if you hate nscd, get over it and run nscd"

**Comment by thommay** [comment] 2016-04-20 17:05
Hey Alex, gonna close this for now. If it turns out to not be an nscd issue, please feel free to reopen.

**Closed by thommay** 2016-04-20 17:05 UTC

**Comment by btm** [comment] 2016-04-20 17:07
For fun historical context, here's another issue with the same cause (glibc) related to LDAP that was in the back of my memory: https://tickets.opscode.com/browse/CHEF-3780
