### ISSUE TITLE
Running chef-solo in 'interval'/'fork' mode drops node-attributes

### ISSUE THREAD

**Issue by jmanero-r7** [chef/chef#4115] opened 2015-10-28 19:00 UTC
### Version:

`12.5.1`
### Environment:

Ubuntu 14.04
### Scenario:

Running `chef-solo` as an `upstart` task with arguments `-r /path/to/config.rb -j /path/to/node.json -i N -s N`
### Steps to Reproduce:

Run `chef-solo` with, at least, the `-i N` and `-j /path/to...` flags set from a command line. The first run (starts after N seconds) will execute correctly with the `run_list` defined in JSON-attributes (`-j /path/to...`). Subsequent runs will execute with an empty run-list and no other attributes loaded from JSON-attributes.
### Expected Result:

A `chef-solo` instance should be able to re-converge it's `run_list` periodically as a daemon.
### Actual Result:

`chef-solo` instances run as daemons only function correctly for one run. Subsequent runs do not load `run_list` and attributes from the configured JSON file.
## Root Cause?

As far as I can tell, this is a hazard that's only triggered in `solo` mode.  I suspect that it results from https://github.com/chef/chef/blob/master/lib/chef/application.rb#L221, which sets `@chef_client_json` to `nil` after the `Chef::Client` is instantiated. In non-`solo` operation, attributes stored in `@chef_client_json` are not necessary after the node's fist converge as subsequent runs fetch `normal` precedence attributes, including `run_list` from the Chef Server API.

My guess is that, in `solo` mode, either https://github.com/chef/chef/blob/master/lib/chef/application/solo.rb#L229-L230 needs to be called before each run, or https://github.com/chef/chef/blob/master/lib/chef/application.rb#L221 needs to be disabled.

**Comment by lamont-granquist** [comment] 2015-10-30 00:30
The easiest workaround here would be to convert from chef-solo to chef-zero

**Comment by vinyar** [comment] 2016-05-12 07:22
Looks like this bug is present in chef-zero (chef-client -z) mode as well.

I found a couple of workarounds (neither one solves the problem that -j is lost with -i specified):
 - combine run_list and attributes into one json file (example: dna.json)
 - use `-r` instead of `-o` switch to specify the runlist.

**Comment by thommay** [comment] 2016-05-12 10:11
@vinyar i don't think this is the same bug at all. you're saying that `chef-client -z -o 'recipe[foo]' -j dna.json` doesn't save? That's intended behaviour when you provide an override run_list.

**Comment by tas50** [comment] 2019-01-22 20:43
I'm going to close this out at this point based on @lamont-granquist's comment that migrating to chef-zero is the ideal fix.

**Closed by tas50** 2019-01-22 20:43 UTC
Labels: Component: Chef Solo, Triage: Declined, Type: Bug
