### ISSUE TITLE
Compat break in audit-mode changes

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3078] opened 2015-03-14 08:44 UTC
Making this to track https://github.com/chef/chef/commit/4cfb1e47aa8e9501f4f2a01f1d8cc0deb2cfa13b#commitcomment-10197616

This has ramifications for ChefSpec testing as you can no longer test for errors being raised in recipe code (and you get get log output during your tests too). Should be reverted pending Chef 13, if ever.

**Comment by jdmundrawala** [comment] 2015-03-14 16:50
Related to https://github.com/chef/chef/issues/3054

**Comment by jdmundrawala** [comment] 2015-03-14 16:50
cc @adamedx @btm @charlesjohnson

**Comment by tyler-ball** [comment] 2015-03-15 16:29
I understand how this is a breaking change.  For context, we decided to do this because we wanted the audit phase to run independently of the converge phase.  It should run even if the converge phase fails.

If there are errors during both the converge phase and audit phase, we don't have a way of raising both errors.  Thats why I added the wrapping exception.

Now that I am looking at this though, it seems unecessary to wrap ALL errors.  For an improvement, what would you think about always running both phases and capturing errors from each phase.  Then we only wrap both errors if both occured.  Otherwise we re-raise the error if only 1 phase had an error.

For anyone not using audit mode (a new feature introduced in Chef 12) this would maintain backwards compatibility with Chef 11 behavior.

What is the issue with increasing the logging output?  The exceptions are still being sent to the formatting system and I found the increased logging useful for development and debugging.

**Comment by coderanger** [comment] 2015-03-15 21:08
You should have something above the level of `#converge` that handles the catch and audit stuffs. `#converge_with_audit` or something, and make it behave as you describe. As for the logging, because Chef is not always used interactively which is why the formatter system was created. If you need to add a new formatter callback for output, do that (or use the existing generic ones). Logging should be for debugging only basically (/cc @danielsdeleo).

**Comment by btm** [comment] 2015-03-16 17:04
As a general rule, swallowing exceptions is bad because so many other tools in the Chef ecosystem treat us as a library. I agree with @jdmundrawala that we should ```raise e if Chef::Config[:audit_mode] == :disabled``` right now and ship that ASAP in the 12.1.2 regression release.

Then we talk about how audit mode gets implemented here when it's no longer an experimental feature.

**Comment by btm** [comment] 2015-03-23 18:53
This should be fixed in [12.1.2](https://www.chef.io/blog/2015/03/23/chef-client-12-1-2-released/).

**Closed by btm** 2015-03-23 18:53 UTC
