### ISSUE TITLE
gem_package uses incorrect list of installed gems when bundler is included

### ISSUE THREAD

**Issue by mikegreiling** [chef/chef#3389] opened 2015-05-19 10:40 UTC
When I have a separate ruby environment and I want to install a gem, I should be able to do the following:

``` ruby
gem_package 'foo' do
  gem_binary '/path/to/my/gem'
  action :update
end
```

and the code in [/lib/chef/provider/package/rubygems.rb @ line 304](https://github.com/chef/chef/blob/cb8eb59972/lib/chef/provider/package/rubygems.rb#L304) should cause resource to look in the correct place for existing gems.  However, if 'bundler/setup' has been included, bundler [overrides this behavior](https://github.com/bundler/bundler/blob/e8c962ef2a321/lib/bundler/rubygems_integration.rb#L493) with a `Gem.post_reset` hook so no matter what you specify for `gem_binary` it will use its own precompiled gem specs when searching for installed gems.

As a result, I will get odd results like the following, regardless of whether it was already installed or not:

> INFO: gem_package[foo] upgraded from uninstalled to 0.0.2

Even though running `/path/to/my/gem list foo -v=0.0.2 --installed` already yields `true`.

Essentially the gem is reinstalled on every run, and it will trigger notifications as though it was installed fresh, which breaks idempotence.

**Comment by ranjib** [comment] 2015-06-25 02:01
@mikegreiling i dont think this is a chef bug. if you are requiring bundler/setup, then you have to find a workaround for this within your recipe.

**Comment by lamont-granquist** [comment] 2015-09-09 17:36
This might be related to other bugs we're seeing where chef_gem and gem_package get confused about which ruby they're installing to (I think its gem_package refusing to install in the system gems and installing only in omnibus).

**Comment by lamont-granquist** [comment] 2015-09-09 17:37
Might be interesting to see if there's other ways that people might be tickling this behavior other than including 'bundler/setup' as well.

**Comment by mikegreiling** [comment] 2015-09-09 21:13
I found that AWS OpsWorks, which installs Chef via bundler, gets around the issue with the following hack:

https://github.com/aws/opsworks-cookbooks/blob/c1426eee3f/opsworks_commons/libraries/monkey_patch_rubygems_provider.rb

**Comment by lamont-granquist** [comment] 2017-04-02 23:48
oh yeah so `bundler/setup` is the code which literally sets up the wrapping bundle.  so the issue here is running under bundler but needing to defeat that purpose completely.

the opsworks hack is pretty much declaring war on bundler's main purpose with a vengeance.

running chef inside of a bundle, where you need to manage external gems or even where chef_gems are not part of the bundle is most likely a really bad idea.  you're saying you want a strict closure over all your gems (which is what the primary purpose of bundler is) and then you're trying to tell bundler that you lied and you really want to mess with all kinds of other gems and gem environments, and bundler will not like that.

so my primary advice is simply stop using bundler.  the appbundled omnibus-chef binaries solve this problem since we equality pin the gems and load them aggressively at start time but don't do that via bundler or create any kind of closure so while the chef gems are pinned, there's no involvement of bundler.  then you're never going to have a future problem where bundler changes something and you've been poking around internal apis trying to abuse it and you wind up getting breakage in minor versions because you're not using bundler the way it was intended.

i can see a possible feature of /bundler/ here to allow programs to break out of the bundler via an actual API, but that's going to need to get sold to the team that maintains bundler and its a pretty odd request to allow software to defeat bundler's core purpose.   at the same time, i've wanted this before with the chef gem metadata stuff where i want to use bundler to install gems, but don't want the closure over the gemset.

**Comment by coderanger** [comment] 2017-04-03 02:35
+1 to close this as Working as Designed from the bundler side of things.

**Comment by lamont-granquist** [comment] 2017-04-03 21:35
sort of want to keep this open to at least track that opsworks monkeypatch -- one way or another that thing needs to go away.

**Comment by lamont-granquist** [comment] 2019-04-12 23:29
Hopefully this has disappeared, if it hasn't we have no bug to fix and this issue still documents the what and why

**Closed by lamont-granquist** 2019-04-12 23:29 UTC
Labels: Component: Chef Core, Priority: Critical, Type: Bug
