### ISSUE TITLE
cron: property validation for "command" is broken

### ISSUE THREAD

**Issue by kimbernator** [chef/chef#11030] opened 2021-02-12 16:42 UTC
## Description

Validation for the "command" property in cron resources throw errors in a number of contexts that should not be a problem. Originally, I thought it was an issue with chefspec so I opened https://github.com/chefspec/chefspec/issues/1004, though recently I've seen a number of errors where even the :create action is incorrectly bombing even when "command" is defined properly (see output below). 

In summary, I have seen issues where:
1. Chefspec fails when testing the :delete action on cron when "command" is not defined, though chef-client does not appear to be having the same issue. As per the code itself, "command" is only required for the :create action. Testing another resource with a similar constraint on its properties (powershell_package_source's "url" property) in chefspec has no such issue.
2. chef-client itself is failing under some circumstances saying "command" is not set despite it very clearly being set in the error output

## Chef Version

16.8.14 for the node exhibiting the infra client issue, 16.10.8 for the workstation install having the chefspec issue.

## Platform Version

OL7

## Replication Case

I haven't done extensive testing on whether this always happens or not, so at the moment I do not have replication steps beyond doing what I've provided in the client output.

## Client Output

```
    ================================================================================
    Error executing action `create` on resource 'cron[run_script]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    command is a required property
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/<cookbook>/recipes/<recipe>.rb
    
    117:   cron "run_script" do
    118:     minute '*'
    119:     command new_entry
    120:     user 'root'
    121:     action :create
    122:     not_if "crontab -l | grep \"#{new_entry}\" | grep -Ev '^[[:space:]]*#'"
    123:   end
    124: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/<cookbook>/recipes/<recipe>.rb:117:in `block in from_file'
    
    cron("run_script") do
      action [:create]
      default_guard_interpreter :default
      declared_type :cron
      cookbook_name "<cookbook>"
      recipe_name "<recipe>"
      minute "*"
      command "script.sh -a -n"
      user "root"
      not_if "crontab -l | grep "script.sh -a -n" | grep -Ev '^[[:space:]]*#'"
    end
```

## Stacktrace

```
>>>> Caused by Chef::Exceptions::ValidationFailed: command is a required property
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/property.rb:427:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/property.rb:369:in `call'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/property.rb:592:in `command'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider/cron.rb:91:in `block in cron_different?'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider/cron.rb:90:in `any?'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider/cron.rb:90:in `cron_different?'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider/cron.rb:103:in `block in <class:Cron>'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider.rb:276:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/provider.rb:217:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/client.rb:687:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/client.rb:682:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/client.rb:682:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/client.rb:706:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.8.14/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.8.14/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:147:in `load'
```

**Comment by azsec** [comment] 2021-02-19 00:50
A workaround is to put any arbitrary like "echo skipping" in `command`.

**Comment by lehn-etracker** [comment] 2021-06-03 15:13
same here while using https://supermarket.chef.io/cookbooks/managed_directory#berkshelf

**Comment by msys-sgarg** [comment] 2021-08-12 08:47
I could never reproduce the issue for `create` action as mentioned in the issue.. But chefspecs were definitely throwing an error when action is `delete` and no value for property `command` is given. I have raised a PR for the same

**Comment by msys-sgarg** [comment] 2021-08-24 04:56
Since the PR raised on chefspec repo is merged, I am closing the issue.

**Closed by msys-sgarg** 2021-08-24 04:56 UTC
Labels: Type: Bug, Platform: Unix-like, Focus: Resources
