### ISSUE TITLE
yum_package is not correctly version matching for a particular version string

### ISSUE THREAD

**Issue by twforeman** [chef/chef#7567] opened 2018-08-22 14:30 UTC
## Description
When running the following rpm package install the package is installed on every chef run.

```
package 'docker' do
  version  '1.13.1-58.git87f2fab.el7'
  action :install
end
```

If you change the action to :upgrade then chef sees that the package is already up to date and does nothing.

Package info:
```
$ rpm -qi docker
Name        : docker
Epoch       : 2
Version     : 1.13.1
Release     : 58.git87f2fab.el7
Architecture: x86_64
Install Date: Wed 22 Aug 2018 08:41:05 AM CDT
Group       : Unspecified
Size        : 59659113
License     : ASL 2.0
Signature   : RSA/SHA256, Tue 20 Mar 2018 08:50:19 AM CDT, Key ID 199e2f91fd431d51
Source RPM  : docker-1.13.1-58.git87f2fab.el7.src.rpm
Build Date  : Mon 19 Mar 2018 01:56:46 PM CDT
Build Host  : x86-040.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/docker/docker
```

Here is a gist with the output of 'yum list docker --show-duplicates' https://gist.github.com/twforeman/af9526e4e7d2ef0adeb950d997c81236

## Chef Version
Chef: 14.3.37

## Platform Version
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"

## Replication Case
Create a chef recipe that installs the docker package with the version string of '1.13.1-58.git87f2fab.el7'. Run it a second time and it will re-install the package.

## Client Output
```
       Recipe: openshift::docker
         * yum_package[docker] action install[2018-08-22T08:45:19-05:00] INFO: Processing yum_package[docker] action install (openshift::docker line 20)
       [2018-08-22T08:45:19-05:00] INFO: Processing yum_package[docker] action install (openshift::docker line 20)
       [2018-08-22T08:45:20-05:00] INFO: yum_package[docker] installed docker at 1.13.1-58.git87f2fab.el7
       [2018-08-22T08:45:20-05:00] INFO: yum_package[docker] installed docker at 1.13.1-58.git87f2fab.el7

           - install version 1.13.1-58.git87f2fab.el7 of package docker
```

**Comment by twforeman** [comment] 2018-08-22 15:15
Oh, I forgot to mention that this works correctly in Chef 13.8.5

**Comment by tarcinil** [comment] 2018-08-25 02:05
This is likely a duplicate of #7552.

**Comment by lamont-granquist** [comment] 2018-08-29 16:48
`package "docker-1.13.1-58.git87f2fab.el7"` should work correctly.

**Comment by lamont-granquist** [comment] 2018-09-04 16:55
and yeah closing this as a dup

**Closed by lamont-granquist** 2018-09-04 16:55 UTC

**Comment by lamont-granquist** [comment] 2018-11-07 20:03
Same as #7552 this is not a bug in chef.

That package has an epoch of 2, so you have to use `version "2:1.13.1-58.git87f2fab.el7"`

It looks like we fixed a bug that old chef-client was not comparing epochs.  That may have been convenient, but it was also wrong.
