### ISSUE TITLE
Unable to run java process through batch file

### ISSUE THREAD

**Issue by michael-tam** [chef/chef#3865] opened 2015-09-03 02:40 UTC
I have a node that has Java installed on it and created a simple test.bat batch file with the following....

```
@echo off
SETLOCAL

"%JAVA_HOME%\bin\java" -version 2>C:\tmp\blah.log

ENDLOCAL
```

When I run test.bat from the command line it works perfect where I can verify my results in 
c:\tmp\blah.log 

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

When I try to create the following recipe to execute test.bat, I get a different message the the blah.log file.

``` ruby
batch 'run-script' do
  code 'test.bat'
  cwd 'C:\\tmp\\'
end
```

Contents of c:\tmp\blah.log after a Chef run....

```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by lamont-granquist** [comment] 2015-10-07 17:28
So something in the environment in the way that chef launches batch files differs from the command line on windows.  It looks like it is not as simple as `%JAVA_HOME%` not being set, but its probably a similar kind of issue.  There's no indication from the error what it might be, however, but at least the replication case is reasonably simple.  It would be good to know how chef-client is getting invoked (from the command line?  as a service?).

**Comment by michael-tam** [comment] 2015-10-12 16:15
I was experiencing this behavior when running from the command line and as a service.

**Comment by lamont-granquist** [comment] 2015-10-21 22:12
If it doesn't work on the command line, then I'm not sure its a Chef issue?

**Comment by michael-tam** [comment] 2015-10-21 22:33
Sorry, we were experiencing the issue when running the chef-client through command line and when it was running as a service.  Executing the batch file through command line works as expected.

**Comment by stuartpreston** [comment] 2018-07-11 14:53
Closing this as I was unable to reproduce with Chef 14.2.0 on Windows 2012 R2
```
PS C:\vagrant> $env:JAVA_HOME="C:\Program Files (x86)\Java\jre1.8.0_171"
PS C:\vagrant> ./test.bat
PS C:\vagrant> gc .\blah.log
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode, sharing)
PS C:\vagrant> rm blah.log
PS C:\vagrant> gc repro.rb
batch 'run-script' do
  code 'c:\vagrant\test.bat'
  cwd 'c:\vagrant'
end
PS C:\vagrant> chef-apply repro.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * batch[run-script] action run
    - execute "C:\Windows\system32\cmd.exe" /c "C:/Users/vagrant/AppData/Local/Temp/2/chef-script20180711-1436-1ulef34.bat"
PS C:\vagrant> gc .\blah.log
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode, sharing)
PS C:\vagrant>
```

**Closed by stuartpreston** 2018-07-11 14:53 UTC
Labels: Area: Windows, Priority: Low
