### ISSUE TITLE
Chef Truck Factor

### ISSUE THREAD

**Issue by gavelino** [chef/chef#3769] opened 2015-08-11 16:19 UTC
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Chef** and obtained a value of **6**.

The developers responsible for this TF are:

Daniel DeLeo - author of 28% of the files
Adam Jacob - author of 17% of the files
John Keiser - author of 9% of the files
Lamont Granquist - author of 9% of the files
Serdar Sutay (sersut) - author of 4% of the files
Seth Chisamore - author of 4% of the files

To validate our results, we would like to ask **Chef** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Chef**?

(b) Do you agree that **Chef** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Chef** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by lamont-granquist** [comment] 2015-08-11 17:01
- Adam, Serdar and Seth have not been hit by a bus but they've moved on and are generally no longer dedicated core chef developers.  They could be spun up again to contribute to core chef in some kind of crisis.

- Dan has largely moved on, but is somewhat active in core chef.  He could easily switch back to core chef in a crisis and clearly has the largest knowledge base of any developer on chef.

-  Myself and John are the currently active Core Chef developers.

- You are missing others like @btm or @jaym who are active Core Chef developers who could take over for myself or John.

Gonna close this, since its not a bug report against Chef.

**Closed by lamont-granquist** 2015-08-11 17:01 UTC

**Comment by stevendanna** [comment] 2015-08-11 18:08
To specifically answer some of your questions:

(a) The listed developers represents the core chef contributors through time, but ignores many other important developers.  It does ignore people who have been very active more recently (@jaym) and those who have contributed extensively but often work all over the code base (@btm). Lamont's answer covers that well.

(b) If those developers were to all leave the project, we would certainly have a period of lower productivity but we don't believe the project would be in long-term trouble.

(c) Chef has a broad development community and a well-defined maintenance policy.  If we were to lose the core active developers, those listed in MAINTAINER.md would likely step up to take a more active role.  Further, in addition to our current maintainers, Chef's git log quickly reveals a large number of contributors who, despite not being maintainers, have made multiple contributions to the project.  Futher, we have a number of developers who have devoted their time to developing cookbooks rather than core Chef that do not show up in Chef's git logs.  Many of these developers would likely also be interested in filling roles that become available.

You may also be interested in https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained

**Comment by gavelino** [comment] 2015-08-13 15:33
Thank you for the answers. I really appreciate the feedback.
