### ISSUE TITLE
One can create data bags with names that are reserved words

### ISSUE THREAD

**Issue by sandratiffin** [chef/chef#3058] opened 2015-03-11 18:35 UTC
One can create a data bag called role, node, client or environment, but then cannot search that data bag. This happens with the latest chef version.

The data bag creation should probably throw an error and not allow creation of a data bag with one of these names.

**Comment by gmiranda23** [comment] 2015-05-21 17:19
We see this issue create ugly results in Chef training.
:+1:

**Comment by juozasg** [comment] 2015-05-21 20:14
+1

**Comment by larrywright** [comment] 2015-05-21 20:14
:+1:

**Comment by lamont-granquist** [comment] 2015-08-19 17:53
We definitely need to fix this one way or another.

Its possible that we could fix this so that knife data bag show/search would favor data bag names over class methods.  This is similar to the fix that went in so that knife node show/search would pick `node[:keys]` over `node#keys`.  In other words make it so that data bags named 'role' were legal.

**Comment by darrin-wortlehock** [comment] 2016-02-29 11:52
I've also run into problems using the key 'name'

**Comment by sanditiffin** [comment] 2017-10-03 21:33
After nothing happening on this issue for over 2.5 years, I dug into the code today and talked with Lamont and others, and it turns out supporting data bags with these names in search is not so easy. It is specifically called out in the chef-server repo that search on such data bag names is not supported (in https://github.com/chef/chef-server/blob/master/src/oc_erchef/raml-docs/organizations/search.yaml). Also, the knife search code expects 'node' to mean the node index, and will do things differently if the search type is 'node'. I thus still believe the correct answer is to simply not allow data bags to be created with these names, so the client code matches the server code. 

I will submit a PR with this fix.

**Comment by EmFl** [comment] 2017-12-08 16:16
I thought that the data bag could not be named role, node, client or environment but it seems that the data bag cannot contain any of these strings which is a lot different.
For exemple if I want to create a data bag named : ldap-roles, then chef run will fail with Chef::Exceptions::InvalidDataBagName
  ------------------------------------
  DataBags may not have a name matching /node|role|environment|client/

Is this expected behaviour ?

**Comment by sanditiffin** [comment] 2017-12-09 00:06
You're right, but that fix needs to extend to the other code path too, and the tests. I can create a PR for that.

**Comment by tas50** [comment] 2021-04-12 22:47
Closing this out since it looks like it was fixed

**Closed by tas50** 2021-04-12 22:47 UTC
Labels: Type: Bug
