### ISSUE TITLE
problem with installing chef via rubygems on windows

### ISSUE THREAD

**Issue by graf0** [chef/chef#4813] opened 2016-04-08 07:06 UTC
when I try to install chef via rubygems on windows (via ruby installer 2.2.4 or 2.3.0) I get this message:

<pre>
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_s_mkdir - c:/build/ruby/lib/ruby/gems/2.3.0/gems/chef-12.8.1-universal-mingw32/acceptance/top-cookbooks/
test_run/learn-the-basics-ubuntu/cookbooks/learn-the-basics-ubuntu/.kitchen/kitchen-vagrant/kitchen-learn-the-basics-ubuntu-learn-the-basics
-ubuntu-default-ubuntu-1404
rake aborted!
</pre>

**Comment by lamont-granquist** [comment] 2016-04-11 17:00
We don't support chef installs on windows outside of omnibus-chef or omnibus-chefdk, and definitely not on ruby versions that we haven't certified (2.3.0 is likely to make you extremely unhappy).  There were API changes in 2.2.4 as well which are causing failures with long filenames in our acceptance testing.  You're probably hitting one of those bugs which blocked us from getting onto 2.2.4 although it has to do with some errantly pushed files in the chef gem for 12.8.1 which will be fixed when 12.9.x is released this week.  Even if that is fixed by 12.9.x there's still known issues using 2.2.4 and we don't recommend using that until those get fixed.

**Closed by lamont-granquist** 2016-04-11 17:00 UTC

**Comment by spuder** [comment] 2016-04-12 23:12
Duplicate of: https://github.com/chef/chef/issues/4708

This is because the filepath of the learn-the-basics cookbook is greater than the max character limit on windows.
