### ISSUE TITLE
Package on Windows 64-Bit

### ISSUE THREAD

**Issue by rneu31** [chef/chef#5745] opened 2017-01-20 20:20 UTC
Using package to install a .EXE on 64-bit Windows does not correctly detect that the package is already installed, and therefore re-installs.

When using an .MSI installer, there is a fallback that searches for the uninstall string in the MSI if it can't find it in the registry. The fallback made me think the problem was "random" ... of course I had all but one package installing via .MSIs and didn't understand everything.

The debug output that led me down this path: `[2017-01-20T20:01:22+00:00] DEBUG: Failure to read property 'DisplayName'`

The registry uninstall location here only points to the 32-bit registry location for uninstall strings.

https://github.com/chef/chef/blob/db57131ad383076391b9df32d5e9989cfb312d58/lib/chef/provider/package/windows/registry_uninstall_entry.rb#L82

**Comment by btm** [comment] 2017-01-23 16:04
@rneu31 are you using the 32bit or 64bit version of Chef?

**Comment by rneu31** [comment] 2017-01-23 16:13
@btm Does the line of code I referenced get swapped out somewhere in the 64-bit version? We are definitely using the 64-bit Chef client on the boxes that the error occurred on.

Side point not related to this issue in this case, the ChefDK downloads page has two x86_64 and i386 version but they both link to the same file.

**Comment by btm** [comment] 2017-01-23 16:31
@rneu31 no, the line doesn't get swapped out, but I believe accessing `HKEY_LOCAL_MACHINE\SOFTWARE ` from a 32bit or 64bit process gives you different results. From what I've just read, from a 64bit process you can read `HKEY_LOCAL_MACHINE\SOFTWARE` for the 64bit version and `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node` for the 32bit keys.

We currently only build 32bit ChefDK on Windows, so we serve the same package regardless of which architecture is requested.

**Comment by rneu31** [comment] 2017-01-23 18:46
I will look into my issue further. Right now I added a bunch of logs in `registry_uninstall_entry.rb`. When iterating over the keys it shows every key except for the package that was just installed, which is weird, since I can eye-ball verify that it's in the registry.

**Comment by rneu31** [comment] 2017-01-24 21:26
@btm What would cause Chef to not see that a registry key is present? When does Chef read from the registry?

Currently, my .EXE installs, notifies a reboot.. machine reboots, Chef runs again, does NOT detect that is installed so it installs again, which triggers another reboot... then when Chef runs this time it detects it's installed and we're golden.

It is almost as if after the first reboot Chef isn't re-reading the registry keys, the second install is not really doing anything productive except causing another reboot, which after another "extra" reboot causes Chef to see that the reg key is there.

Does this trigger any thoughts?? This issue itself can be closed -- sorry for the noise.

**Comment by btm** [comment] 2017-01-24 22:59
No worries about the issues. Happy to help. 

It should read the registry as necessary, there's no need to cache.

I thought we had a a property on the `windows_package` resource for setting the registry key we search for, but it looks like the registry key that the uninstall string is under must exactly match the name of the resource. Are you sure these match.

https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/registry_uninstall_entry.rb#L43

**Comment by rneu31** [comment] 2017-01-24 23:09
I printed/logged key a few lines prior to that, and manually checked the registry and compared w/ the printed results, and the one I cared about was missing.... until the weird re-install again and reboot yet again then it's found.

**Comment by btm** [comment] 2017-01-25 00:06
After the install is done, before the reboot, have you verified the registry key? Installers finishing on the next startup is a common thing on Windows.

**Comment by jugatsu** [comment] 2017-01-25 19:00
Yoy should double check that package name matches
```powershell
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_LOCAL_MACHINE\Software\Wow6464Node\Microsoft\Windows\CurrentVersion\Uninstall
```
I have some programs which add space at the end of package name.

**Comment by harikesh-kolekar** [comment] 2017-02-20 09:13
Tried to Install and uninstalled MSI and EXE package to reproduce issue
https://gist.github.com/harikesh-kolekar/711bcf2c49271ae3762318465258a826
its execute successfully 

And also tried to install package multiple time but its install and restart at one time. 
https://gist.github.com/harikesh-kolekar/c78a8b18d38a9f82e0995ba3e005b0b8

Can you please provide cookbook and page to reproduce the issue?

**Comment by NimishaS** [comment] 2017-02-20 15:38
@rneu31 , please share the recipe and the steps to reproduce this issue. @harikesh-kolekar has tried with the scenario that you suggested, but the recipes worked successfully if the name of the package provided in the recipe matches with the name in the registry.
Please check this recipe: https://gist.github.com/harikesh-kolekar/711bcf2c49271ae3762318465258a826#file-install-package-32-64-bit-L56
@harikesh-kolekar had to append `(x64)` to the package name while uninstall, since the package name in the registry has it. While during install, providing `(x64)` was not required.

**Comment by rneu31** [comment] 2017-02-20 15:59
@NimishaS It seems like the package that I'm trying to install acts very inconsistently, which made it seem as if Chef was missing something that was in the registry. This can be closed.

**Comment by NimishaS** [comment] 2017-02-21 06:36
@btm , @sjvreddy, please close this issue

**Closed** 2017-02-21 10:22 UTC
Labels: Type: Bug, Windows
