### ISSUE TITLE
Yum Repository with `url` parameter fails

### ISSUE THREAD

**Issue by jonathanmorley** [chef/chef#5317] opened 2016-09-14 19:09 UTC
## Description

Using the `url` property on the `yum_repository` resource causes chef-client to fail the run.
This was supported by the `yum` cookbook through `alias_method` calls (https://github.com/chef-cookbooks/yum/blob/master/resources/repository.rb#L69).

## Chef Version

12.14

## Platform Version

CentOS 7.1

## Replication Case

```ruby
yum_repository 'example' do
  url 'http://example.com/'
end
```

Tested with a dependency on the `yum` cookbook, but I assume it would happen without this dependency

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

```
================================================================================
         Recipe Compile Error in /.../recipes/default.rb
         ================================================================================

         NoMethodError
         -------------
         undefined method `url' for Chef::Resource::YumRepository
```

```
Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/datadog/recipes/repository.rb:

          36:
          37:  when 'rhel', 'fedora'
          38:    include_recipe 'yum'
          39:
          40:    yum_repository 'datadog' do
          41:      name 'datadog'
          42:      description 'datadog'
          43>>     url node['datadog']['yumrepo']
          44:      # Older versions of yum embed M2Crypto with SSL that doesn't support TLS1.2
          45:      prefix = node['platform_version'].to_i < 6 ? 'http' : 'https'
          46:      gpgkey "#{prefix}://yum.datadoghq.com/DATADOG_RPM_KEY.public"
          47:      action :add
          48:    end
          49:  end
          50:
```

**Comment by shortdudey123** [comment] 2016-09-14 19:43
Looks like this is happening since the yum cookbook has `alias_method :url, :baseurl` in the `yum_repository` resource def

The parameter was renamed from `url` to `baseurl` over 2.5 yrs ago in https://github.com/chef-cookbooks/yum/commit/03e455c4798b2eef918381824ca907e839a1207f

**Comment by coderanger** [comment] 2016-09-14 20:20
As a short term fix you can monkeypatch this back in to the core version. Add this in a `libraries/default.rb` somewhere:

```ruby
class Chef::Resource::YumRepository < Chef::Resource
  alias_method :url, :baseurl
  alias_method :keyurl, :gpgkey
end
```

**Comment by tas50** [comment] 2016-09-14 20:36
Even though we deprecated that old property in the docs we didn't actually add a deprecation notice. We should probably support passing URL still, but throw a deprecation notice. We have the same problem with the old actions.

**Comment by coderanger** [comment] 2016-09-14 20:37
@tas50 :+1:

**Comment by tas50** [comment] 2016-09-14 21:25
#5320 is the immediate fix. We can figure out exactly how we'd like to deprecate those properties in another PR

**Comment by tas50** [comment] 2016-09-14 22:24
This is fixed in master

**Closed by tas50** 2016-09-14 22:24 UTC
Labels: Bug

**Comment by atheiman** [comment] 2016-09-15 14:53
whats the process for getting a new release into RubyGems? Do you not publish every release?

**Comment by tas50** [comment] 2016-09-15 16:49
Each release is available via the install.sh script by specifying the 'current' vs. 'stable' channels. Each release is not pushed to Rubygems however. We push what we consider the final release up to Rubygems, which is why 12.14.60 is the only 12.14.X release on Rubygems. We're currently working on 2 additional regressions and we'll make another release once those are complete.

**Comment by atheiman** [comment] 2016-09-15 16:54
thanks for the explanation!
