### ISSUE TITLE
apt_package 14 and later truncates version when supplied as a node attribute

### ISSUE THREAD

**Issue by cread** [chef/chef#8378] opened 2019-04-16 19:40 UTC
## Description
If there is a tilde in the package version, `apt_package` appears to truncate the version at the tilde when it is supplied as a node attribute.

For example, `17.09.0~ce-0~ubuntu` is truncated to `17.09.0`.

Debian version definition: https://www.debian.org/doc/debian-policy/ch-controlfields.html#version

**EDIT:** When the version of the package is supplied inline directly as a string then things work correctly.

## Chef Version
Works correctly in older versions of the chef-client (tested many versions, up to and including `13.12.14`). Breaks in `14.0.190` and later.

## Platform Version
Ubuntu 16.04

## Replication Case
Given this cookbook snippet:

`attributes/default.rb`:
```ruby
default['docker']['version'] = '17.09.0~ce-0~ubuntu'
```

`recipes/default.rb`:
```ruby
apt_repository "docker" do
  uri "https://download.docker.com/linux/ubuntu"
  distribution "#{node['lsb']['codename']}"
  components ["stable"]
  arch "amd64"
  key "https://download.docker.com/linux/ubuntu/gpg"
  action :add
end

include_recipe "apt"

package "docker-ce" do
  version node['docker']['version']
  options '-o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold'
end
```

## Client Output
Broken 14.11.21 client (relevant parts from `chef-client -l debug` run):

```
  * apt_package[docker-ce] action install[2019-04-16T13:50:19-05:00] INFO: Processing apt_package[docker-ce] action install (docker::default line 22)
docker-ce:
  Installed: 17.09.0~ce-0~ubuntu
  Candidate: 5:18.09.5~3-0~ubuntu-xenial

...

apt 1.2.31 (amd64)
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '17.12.1' for 'docker-ce' was not found
```

Working 13.12.14 client (relevant parts from `chef-client -l debug` run):

```
  * apt_package[docker-ce] action installdocker-ce:
  Installed: 17.09.0~ce-0~ubuntu
  Candidate: 5:18.09.5~3-0~ubuntu-xenial

...

 (up to date)
```

## Stacktrace
```
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:297:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:284:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/mixin/shell_out.rb:202:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/mixin/shell_out.rb:124:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package/apt.rb:168:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package/apt.rb:96:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:227:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package.rb:100:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource.rb:578:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:321:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:309:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:309:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:274:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:479:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:468:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:467:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:467:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:451:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:74:in `load'
/usr/bin/chef-client:74:in `<main>'
[2019-04-16T14:37:36-05:00] ERROR: apt_package[docker-ce] (docker::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "docker-ce=17.09.0"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: E: Version '17.09.0' for 'docker-ce' was not found
---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "docker-ce=17.09.0"] ----
Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "docker-ce=17.09.0"] returned 100
[2019-04-16T14:37:36-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lamont-granquist** [comment] 2019-04-17 20:41
looking at the diffs between those versions it isn't at all obvious what code change is responsible for this.

if you can git bisect the problem down to the commit that caused the regression that would probably help.

**Comment by cread** [comment] 2019-04-17 21:08
Agree it's not obvious in the diffs...

I started going down that path when I found this, which is how I found where it broke in stable builds. I should have time later this week to start going through the full bisect process.

**Comment by lamont-granquist** [comment] 2019-04-17 23:05
what happens if you remove `include_recipe "apt"` AND remove the dependency on the apt cookbook entirely and use the apt_update resource instead of calling the apt::default recipe?

because it is working for me:

```
        * apt_update[] action periodic (up to date)
         * apt_package[docker-ce] action install
           - install version 17.09.0~ce-0~ubuntu of package docker-ce
```

i'm kind of leaning towards thinking this is a conflict between the apt cookbook resources and the core-chef resources.

**Comment by lamont-granquist** [comment] 2019-04-17 23:06
although i am testing master so alternatively perhaps this got fixed: 

```
Starting Chef Client, version 15.0.220
```

**Comment by cread** [comment] 2019-04-18 17:03
`git bisect` complete:

```
ab46256c6119dd5a2394e424c2b20dcd1f3ccd47 is the first bad commit
commit ab46256c6119dd5a2394e424c2b20dcd1f3ccd47
Author: Chef Expeditor <eng-services-ops+chef-ci@chef.io>
Date:   Mon Feb 19 10:11:43 2018 +0000

    Bump version to 14.0.60 by Expeditor

:100644 100644 ae1b282af6bc50d72faea49327a192591df7ecbd b6c23086c7302acb59f49c6030cf53b535107601 M	CHANGELOG.md
:100644 100644 0084528c7583ff829991777b7c2fa80688a91f4e 8d8320077533f646945eb258b39901f7b6dfe45c M	Gemfile.lock
:100644 100644 bee978e91bf3f8ee26b733c61869d54ee32987be e76cd1fbec28db9c63f4fc25fff747516f670a06 M	VERSION
:040000 040000 9e7ab4cf27a71afb78d77879cd6ff83ca8038cc3 774ffb06c176fab07a228de381b19119dea5b58e M	chef-config
:040000 040000 a259e8f498aa6a485dc8d272ddd3e7b7b566a6e4 600c035ac63930b35651e6b9720ec4b5127eaeec M	lib
```

Which seemed strange to me, but I've run through the bisect twice with the same result.

`v14.0.59` works as expected, `v14.0.60` fails, so bisect is not wrong.

I've just tested with `v15.0.223`, which also fails, so it's not been fixed yet.

Trying out without the `apt` cookbook next to see if we've got some strange interaction going on there.

**Comment by cread** [comment] 2019-04-18 18:24
I've ruled out `apt` from supermarket as the problem, but I have discovered that my example is not quite correct. The problem occurs only when the version is read as a node attribute. Will update the example shortly.

**Comment by lamont-granquist** [comment] 2019-06-24 17:10
That commit doesn't make a lot of sense at all.  That only bumped the chef + chef-config gems for a merge that came in, which was the prior merge commit and ultimately just a fix to the registry_key resource:  fc70228d6950e023f938ec41cf6de69e8bddd08e

Having it only happen as a node attribute also doesn't shed a lot of clarity on it either.

**Comment by cread** [comment] 2019-06-24 17:28
I agree!

I'll see if I can come up with a kitchen example that can reproduce it...

**Comment by lamont-granquist** [comment] 2019-09-17 17:49
Closing since we can't seem to replicate this

**Closed by lamont-granquist** 2019-09-17 17:49 UTC
Labels: Status: Untriaged
