### ISSUE TITLE
From chef-client 12.1.0, yum package name completion is not effective when specify a version.

### ISSUE THREAD

**Issue by ikosin** [chef/chef#3030] opened 2015-03-05 08:36 UTC
From chef-client 12.1.0, yum package name completion is not effective when specify a version.
===

When I use chef-client 12.0.3, yum_package resource can guess complete package name even if I specify a package version. But on chef-client 12.1.0, it couldn't.

IMHO, this change could be affecting. https://github.com/chef/chef/commit/9e48d56d76f1f45eb348e720c670bb13d708dcbe#diff-264f5e050b4925a33b2102ef668e34eeR1276

## Environments

Using Vagran, provisioning to Amazon Linux on AWS.

- OS X Yosemite
- Vagrant 1.7.2
- vagrant plugin list
    - sahara (0.0.17)
    - vagrant-aws (0.6.0)
    - vagrant-berkshelf (4.0.3)
    - vagrant-omnibus (1.4.1)
    - vagrant-share (1.1.4, system)
    - vagrant-vbguest (0.10.0)

```ruby
# Vagrantfile
  config.vm.provider :aws do |aws, override|
    # Amazon Linux AMI 2014.09.2 (HVM)
    aws.ami = "ami-18869819"
  end

#  config.omnibus.chef_version = '12.0.3'
  config.omnibus.chef_version = '12.1.0'

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.add_recipe 'my_cookbook::python'
  end
```

### recipe

```ruby
package "python_pip" do
  action :install
  version '1.3.1-4.9.amzn1'
end
```

### log

```sh
==> default: [2015-03-05T08:11:45+00:00] DEBUG: yum_package[python-pip] no package found for python-pip but matched Provides for python26-pip
==> default: [2015-03-05T08:11:45+00:00] DEBUG: yum_package[python-pip] checking yum info for python26-pip-1.3.1-4.9.amzn1
==> default: [2015-03-05T08:11:45+00:00] DEBUG: yum_package[python-pip] installed version: (none) candidate version: 1.3.1-4.9.amzn1
==> default: [2015-03-05T08:11:45+00:00] INFO: yum_package[python-pip] installing python26-pip-1.3.1-4.9.amzn1 from amzn-main repository
==> default: [2015-03-05T08:11:45+00:00] DEBUG: Executing yum -d0 -e0 -y install python26-pip-1.3.1-4.9.amzn1
==> default: [2015-03-05T08:11:46+00:00] DEBUG: ---- Begin output of yum -d0 -e0 -y install python26-pip-1.3.1-4.9.amzn1 ----
==> default: [2015-03-05T08:11:46+00:00] DEBUG: STDOUT:
==> default: [2015-03-05T08:11:46+00:00] DEBUG: STDERR:
==> default: [2015-03-05T08:11:46+00:00] DEBUG: ---- End output of yum -d0 -e0 -y install python26-pip-1.3.1-4.9.amzn1 ----
==> default: [2015-03-05T08:11:46+00:00] DEBUG: Ran yum -d0 -e0 -y install python26-pip-1.3.1-4.9.amzn1 returned 0
==> default:
==> default:     - install version 1.3.1-4.9.amzn1 of package python26-pip
```

### recipe

```ruby
package "python_pip" do
  action :install
  version '1.3.1-4.9.amzn1'
end
```

### log

```sh
==> default: [2015-03-04T10:11:54+00:00] DEBUG: yum_package[python-pip] checking yum info for python-pip-1.3.1-4.9.amzn1
==> default: [2015-03-04T10:11:54+00:00] DEBUG: yum_package[python-pip] installed version: [nil] candidate version: (none)
==> default:
==> default:     * No candidate version available for python-pip
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'yum_package[python-pip]'
==> default:     ================================================================================
==> default:
==> default:     Chef::Exceptions::Package
==> default:     -------------------------
==> default:     No candidate version available for python-pip
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/942640c8d4f2e62a862574bb2b537cca/cookbooks/my_cookbook/recipes/python.rb
==> default:
==> default:      30: package "python-pip" do
==> default:      31:   action :install
==> default:      32:   version node['my_cookbook']['python']['pip']['version']
==> default:      33:   notifies :run, "execute[python-pip test]", :immediately
==> default:      34: end
==> default:      35:
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/942640c8d4f2e62a862574bb2b537cca/cookbooks/my_cookbook/recipes/python.rb:30:in `from_file'
==> default:
==> default:     yum_package("python-pip") do
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       package_name "python-pip"
==> default:       version "1.3.1-4.9.amzn1"
==> default:       timeout 900
==> default:       flush_cache {:before=>false, :after=>false}
==> default:       declared_type :package
==> default:       cookbook_name :my_cookbook
==> default:       recipe_name "python"
==> default:     end
==> default:
==> default: [2015-03-04T10:11:54+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-03-04T10:11:54+00:00] ERROR: Converge failed with error message yum_package[python-pip] (my_cookbook::python line 30) had an error: Chef::Exceptions::Package: No candidate version available for python-pip
==> default: [2015-03-04T10:16:38+00:00] DEBUG: Re-raising exception: Chef::Exceptions::RunFailedWrappingError - Found 1 errors, they are stored in the backtrace
==> default: 1) Chef::Exceptions::Package -  yum_package[python-pip] (my_cookbook::python line 30) had an error: Chef::Exceptions::Package: No candidate version available for python-pip
==> default:   /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/provider.rb:159:in `process_resource_requirements'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/provider.rb:135:in `run_action'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> default:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> default:   /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> default:   /usr/bin/chef-solo:52:in `load'
==> default:   /usr/bin/chef-solo:52:in `<main>'
==> default:
==> default:
==> default: Running handlers:
==> default: [2015-03-04T10:16:38+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2015-03-04T10:16:38+00:00] ERROR: Exception handlers complete
==> default: [2015-03-04T10:16:38+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-03-04T10:16:38+00:00] DEBUG: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
==> default: 1) Chef::Exceptions::Package -  yum_package[python-pip] (my_cookbook::python line 30) had an error: Chef::Exceptions::Package: No candidate version available for python-pip
==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
==> default: /opt/chef/embedded/apps/chef/lib/chef/provider.rb:159:in `process_resource_requirements'
==> default: /opt/chef/embedded/apps/chef/lib/chef/provider.rb:135:in `run_action'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
==> default: /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
==> default: /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
==> default: /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
==> default: /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
==> default: /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
==> default: /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> default: /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> default: /usr/bin/chef-solo:52:in `load'
==> default: /usr/bin/chef-solo:52:in `<main>'
==> default:
==> default: Chef Client failed. 0 resources updated in 3.940636073 seconds
==> default: [2015-03-04T10:16:38+00:00] ERROR: Found 1 errors, they are stored in the backtrace
==> default: [2015-03-04T10:16:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### recipe

```ruby
package "python_pip" do
  action :install
end
```

### log

```sh
==> default: [2015-03-04T10:17:24+00:00] DEBUG: python-pip: Unable to match package 'python-pip' but matched 1 , selected 'python26-pip' version '1.3.1-4.9.amzn1'
==> default: [2015-03-04T10:17:24+00:00] DEBUG: yum_package[python-pip] checking yum info for python26-pip
==> default: [2015-03-04T10:17:24+00:00] DEBUG: yum_package[python-pip] installed version: [nil] candidate version: 1.3.1-4.9.amzn1
==> default: [2015-03-04T10:17:24+00:00] DEBUG: yum_package[python-pip] python26-pip not installed, installing 1.3.1-4.9.amzn1
==> default: [2015-03-04T10:17:24+00:00] INFO: yum_package[python-pip] installing python26-pip-1.3.1-4.9.amzn1 from amzn-main repository
==> default: [2015-03-04T10:17:25+00:00] INFO: yum_package[python-pip] installed python26-pip at 1.3.1-4.9.amzn1
==> default:
==> default:     - install version 1.3.1-4.9.amzn1 of package python26-pip
```

**Comment by bdwyertech** [comment] 2015-03-06 17:40
I'm seeing the same issue

```ruby
# => Shorten Hashes
gitlab = node['gitlab']

# => Download Gitlab RPM
remote_file 'Download Gitlab RPM' do
  path ::File.join(Chef::Config[:file_cache_path], ::File.basename(gitlab['down_url']))
  source gitlab['down_url']
  action :create
  notifies :install, 'yum_package[Install Gitlab RPM]', :immediately
end

# => Install Gitlab from RPM
yum_package 'Install Gitlab RPM' do
  package_name 'gitlab'
  source ::File.join(Chef::Config[:file_cache_path], ::File.basename(gitlab['down_url']))
  action :nothing
end
```

Error
```
==> default: ================================================================================
==> default: Error executing action `install` on resource 'yum_package[Install Gitlab RPM]'
==> default: ================================================================================
==> default:
==> default: Chef::Exceptions::Package
==> default: -------------------------
==> default: No candidate version available for gitlab
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/186009cb033a86323fea41d77ce8646e/cookbooks/coocoo-gitlab-omnibus/recipes/default.rb
==> default:
==> default:  23: yum_package 'Install Gitlab RPM' do
==> default:  24:   package_name 'gitlab'
==> default:  25:   source ::File.join(Chef::Config[:file_cache_path], ::File.basename(gitlab['down_url']))
==> default:  26:   action :nothing
==> default:  27: end
==> default:  28:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/186009cb033a86323fea41d77ce8646e/cookbooks/coocoo-gitlab-omnibus/recipes/de
fault.rb:23:in `from_file'
==> default:
==> default: yum_package("Install Gitlab RPM") do
==> default:   action [:nothing]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   package_name "gitlab"
==> default:   source "/var/chef/cache/gitlab-7.8.2_omnibus.1-1.el6.x86_64.rpm"
==> default:   version "7.8.2_omnibus.1-1.el6"
==> default:   timeout 900
==> default:   flush_cache {:before=>false, :after=>false}
==> default:   declared_type :yum_package
==> default:   cookbook_name :"coocoo-gitlab-omnibus"
==> default:   recipe_name "default"
==> default: end
==> default:
```

**Comment by lamont-granquist** [comment] 2015-03-06 18:15
looks like dups of #3008 which is fixed in master, and will be fixed when 12.1.1 releases

**Comment by lamont-granquist** [comment] 2015-03-06 18:17
12.1.1 release should be monday.

**Comment by bdwyertech** [comment] 2015-03-06 18:41
Thanks for the info, will stick to 12.0.3 for now @lamont-granquist

**Comment by btm** [comment] 2015-03-20 18:14
This doesn't mention source, so we're not sure if this is actually a dupe of #3008. I'm going to reopen this until we can confirm that this works on master.

**Comment by btm** [comment] 2015-03-25 01:53
@ikosin @bdwyertech Have you tried 12.1.1+ yet to see if it fixes this issue?

**Comment by bdwyertech** [comment] 2015-03-25 03:16
@btm I haven't done extensive testing, but it seems to be working fine now.  Thank you, sir.

**Closed** 2015-03-25 03:33 UTC
