### ISSUE TITLE
node.force_override['x']['y']  in recipe will not work if some cookbook attribute file read the attribute via node['x']['z'

### ISSUE THREAD

**Issue by yaohaif** [chef/chef#3294] opened 2015-04-28 09:27 UTC
In my case, I found in a cookbook's recipe, we have a code like, we can call this cookbook as 'cookbook-A', it's not in a ruby_block:
node.force_override['openstack']['endpoints']['identity-admin']['scheme'] = 'https'

And this attribute default value is defined in a cookbook-C attribute file:
default['openstack']['endpoints']['identity-admin']['scheme'] = 'http'

The expectation after call cookbook-A's recipe 
node['openstack']['endpoints']['identity-admin']['scheme'] will be 'https'.

But this is not always working as one of my cookbooks has another attribute file, we can call this cookbook as 'cookbook-B', and it contains such line:
default['ibm-openstack']['powervc-driver']['powervc']['mq']['rpc_conn_pool_size'] = node['openstack']['compute']['rpc_conn_pool_size']

If I call the chef-client with run-list from cookbook-A and cookbook-B, then in cookbook-A's recipe, 
node.force_override will not take effect, node['openstack']['endpoints']['identity-admin']['scheme']  value will be 'http' eventually..

If I comment out the line in my cookbook-B's attribute file
default['ibm-openstack']['powervc-driver']['powervc']['mq']['rpc_conn_pool_size'] = node['openstack']['compute']['rpc_conn_pool_size']

then node['openstack']['endpoints']['identity-admin']['scheme']  will be 'https' after call node.force_override in cookbook-A's recipe..

**Comment by lamont-granquist** [comment] 2015-07-29 17:21
This looks like deep merge cache issues that were fixed in 12.1.0

If this is still ongoing in 12.4.x it might be useful to figure out what the problem is with this, however, node attributes are in the process of being completely rewritten so the utility of tracking down this bug is probably low.

**Comment by smurawski** [comment] 2015-07-29 17:22
@yaohaif Please verify that 12.1.0 or newer fixes your problem and reopen this if it still is.

**Closed by smurawski** 2015-07-29 17:22 UTC
