### ISSUE TITLE
knife cookbook upload error.

### ISSUE THREAD

**Issue by chris-sanders-dot-org** [chef/chef#6273] opened 2017-07-13 16:13 UTC
## Description

Trying to upload a new version of a cookbook results in an error.

ERROR: The data in your request was invalid
Response: Invalid key all_files in request body

## Chef Version

Chef server is 12.0.7
My ChefDK is 2.0.26

## Platform Version

MacOSX 

## Client Output

Debug output of knife cookbook upload.

https://gist.github.com/chris-sanders-dot-org/9e78214a1d25c9ecc6f146d5eb899c35

**Comment by thommay** [comment] 2017-07-13 16:26
Hmm, this was supposed to be fixed by #6201 but clearly wasn't.

**Comment by Sivasathivel** [comment] 2017-07-18 18:20
I'm having this issue as well...!
I'm trying to follow the lessons in learning-chef and I got stumped by this issue...! Is there a work around?

**Comment by coderanger** [comment] 2017-07-18 20:02
@Sivasathivel @chris-sanders-dot-org What kind of Chef Server are you uploading to? The debug trace doesn't show any API version headers.

**Comment by Sivasathivel** [comment] 2017-07-18 21:09
I'm using ChefServer 11.1.8. The one mentioned in the learning-chef book...
My Chefdk is version 13.2.20
From what I understand my Chef-Client is 13.2. as well
This following is the stacktrace, I got:
[vagrant@node-centos65 ~]$ sudo cat /var/chef/cache/chef-stacktrace.out
Generated at 2017-07-18 21:05:03 +0000
Net::HTTPServerException: 412 "Precondition Failed"
/opt/chef/embedded/lib/ruby/2.4.0/net/http/response.rb:122:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:152:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/policy_builder/expand_node_object.rb:177:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'`

Could you help me?

**Comment by coderanger** [comment] 2017-07-18 21:13
@Sivasathivel Please fall back to Chef 12.x on your workstation for the short term. We'll get started on a fix.

**Comment by chris-sanders-dot-org** [comment] 2017-08-09 19:30
It's open source Chef version 12.0.7. 
@coderanger Sorry I missed your earlier post.

**Comment by ohdihe** [comment] 2017-08-20 00:31
I am having the same error. I have tried everything under the sun. Please if anyone has a solution around this issue, I would be grateful.

Thanks.

**Comment by ohdihe** [comment] 2017-08-20 00:33
Same situation with Sivasathivel

**Comment by ohdihe** [comment] 2017-08-21 21:37
I have fixed the problem. The issue is with chef_solo vs chef_zero. It seems chef_solo was the old way of doing chef things. So I added "chef_zero.enabled  true" in the knife.rb file to activate chef_zero instead of chef_solo. When you do this, you should be able to upload.

**Comment by ohdihe** [comment] 2017-08-21 21:40
Here is the code:
current_dir = File.dirname(__FILE__)
log_level                :info
ssl_ca_path              "#{current_dir}/trusted_certs/default-centos65.vagrantup.com.crt"
log_location             STDOUT
node_name                '#######'
client_key               "#{current_dir}/#######.pem"
validation_client_name   '########-validator'
validation_key           "#{current_dir}/########-validator.pem"
chef_server_url          'https://default-centos65.vagrantup.com/organizations/#######'
cache_type               'BasicFile'
cookbook_path            ["#{current_dir}/../cookbooks"]
chef_zero.enabled        true

**Comment by thommay** [comment] 2017-08-31 13:06
This is fixed in Chef 13.3.3, which will be released in the ChefDK 2.2 release

**Closed** 2017-08-31 13:06 UTC
