### ISSUE TITLE
windows feature installs are no longer working

### ISSUE THREAD

**Issue by mvangoor** [chef/chef#12349] opened 2021-12-07 08:48 UTC
## Description
with commit https://github.com/chef/chef/commit/16aaea15f91f705a9f87b59005bed699419c248a#diff-fe888148f2023bd6ec86ce5208248f77b4627c8a8a249ff604d57f682082f1ecL218 I believe there is a new bug introduced.
The command was stripped of the `ConvertTo-Json -Compress` while 2 lines below it does a `Chef::JSONCompat.from_json()`

## Chef Version
17.8.25

## Platform Version
windows server 2019

## Replication Case
```ruby
%w(GPMC Web-Mgmt-Tools).each do |feature|
  windows_feature feature do
    all true
    action :install
    install_method :windows_feature_powershell
  end
end
```

downgrade to 17.7.29 and it works fine

Also changing above logic to does not solve it:
```ruby
%w(GPMC Web-Mgmt-Tools).each do |feature|
  windows_feature_powershell feature do
    all true
    action :install
  end
end
```

## Client Output
```
  * windows_feature[GPMC] action install
    * windows_feature_powershell[GPMC] action install

      ================================================================================
      Error executing action `install` on resource 'windows_feature_powershell[GPMC]'
      ================================================================================

      Chef::Exceptions::JSON::ParseError
      ----------------------------------
      input must be a string or IO

      Resource Declaration:
      ---------------------
      # In C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb

      131:           declare_resource(new_resource.install_method, new_resource.name) do
      132:             action desired_action
      133:             feature_name new_resource.feature_name
      134:             source new_resource.source if new_resource.source
      135:             all new_resource.all
      136:             timeout new_resource.timeout
      137:             management_tools new_resource.management_tools if new_resource.install_method == :windows_feature_powershell
      138:           end
      139:         end

      Compiled Resource:
      ------------------
      # Declared in C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb:131:in `run_default_subresource'

      windows_feature_powershell("GPMC") do
        action [:install]
        default_guard_interpreter :default
        declared_type :windows_feature_powershell
        cookbook_name "dms_jumphost_role"
        feature_name ["gpmc"]
        all true
        timeout 600
        management_tools false
      end

      System Info:
      ------------
      chef_version=17.8.25
      platform=windows
      platform_version=10.0.17763
      ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-client
      executable=C:/opscode/chef/bin/chef-client
```

## Stacktrace
see above

**Comment by rahulgoel1** [comment] 2021-12-07 19:41
@rishichawda  This is a high priority issue and we need you to help fix it as soon as possible ? Would you be able to fix it as soon as possible ? cc: @tas50

**Comment by mvangoor** [comment] 2021-12-09 17:06
@rishichawda looking at https://github.com/chef/chef/runs/4461895824?check_suite_focus=true it seems your PR above does not fix the issue?

**Comment by lamont-granquist** [comment] 2021-12-09 19:13
The reason why we shipped this regression is that the kitchen tests for windows are testing against the previously released version of the code and not against the code in the PR because all the powershell stuff was broken.  So even though that PR fixed the code, the test is still broken.  Fixing CI is being done in #12352 which currently has no information in it because I'm just hacking around on CI and trying to determine how broken the whole system was.

**Comment by tas50** [comment] 2021-12-10 03:59
Fixed in https://github.com/chef/chef/pull/12355

**Closed by tas50** 2021-12-10 03:59 UTC
Labels: Status: Untriaged
