### ISSUE TITLE
Group resource on windows is reporting inconsistent member changes

### ISSUE THREAD

**Issue by andrewelizondo** [chef/chef#3411] opened 2015-05-21 22:10 UTC
The group resource used on a windows machine appears to be looking at a different id to gather initial state, which makes accurate before/after diffing of changed users challenging.

```
{
  "chef_server_fqdn": "manage.blah",
  "end_time": "2015-04-30T23:29:41Z",
  "id": "8532ef19-4edb-455f-b5ec-34809d6845b3",
  "message_type": "run_converge",
  "message_version": "0.1.0",
  "node_name": "opscode1",
  "organization_name": "opscode",
  "run_id": "d110a65d-6063-4844-976c-9d25bd9e3377",
  "run_list": [
    "recipe[wingroup]"
  ],
  "start_time": "2015-04-30T23:29:39Z",
  "status": "success",
  "total_resource_count": 10,
  "resources": [
    {
      "cookbook_name": "wingroup",
      "cookbook_version": "0.1.3",
      "delta": "",
      "duration": "7",
      "final_state": {
        "members": [
          "Administrator",
          "random"
        ]
      },
      "initial_state": {
        "members": [
          "S-1-5-21-294568438-2080408112-401244387-500",
          "S-1-5-21-294568438-2080408112-401244387-1002",
          "S-1-5-21-294568438-2080408112-401244387-501"
        ]
      },
      "resource_id": "Administrators",
      "resource_name": "Administrators",
      "resource_result": "modify",
      "resource_type": "group"
    }
  ],
  "updated_resource_count": 1
}
```

**Comment by adamedx** [comment] 2015-08-19 17:54
@jaym, does this look familiar? I'm guessing this is because of the use of SIDs that I added.

**Comment by adamedx** [comment] 2015-08-19 17:56
Yes, this is a reporting issue, most likely caused by my changes to use sids internally.

**Comment by jaym** [comment] 2015-08-19 22:33
This is a fairly easy fix:
```diff
diff --git i/lib/chef/provider/group/windows.rb w/lib/chef/provider/group/windows.rb
index 46d8afc..2770e09 100644
--- i/lib/chef/provider/group/windows.rb
+++ w/lib/chef/provider/group/windows.rb
@@ -39,7 +39,9 @@ class Chef

           members = nil
           begin
-            members = @net_group.local_get_members
+            members = @net_group.local_get_members.map do |member|
+              local_group_name_to_sid(member)
+            end
           rescue => e
             @group_exists = false
             Chef::Log.debug("#{@new_resource} group does not exist")
@@ -80,8 +82,7 @@ class Chef
         end

         def has_current_group_member?(member)
-          member_sid = local_group_name_to_sid(member)
-          @current_resource.members.include?(member_sid)
+          @current_resource.members.any?{|m| m.casecmp(member)==0}
         end

         def remove_group
```

**Comment by jaym** [comment] 2015-08-19 22:49
that diff is so wrong :(

**Comment by stuartpreston** [comment] 2018-07-11 14:17
Closing this due to age. Please repro against the latest Chef Client if you feel this is still an issue.

**Closed by stuartpreston** 2018-07-11 14:17 UTC
Labels: Area: Windows, Priority: Medium, Type: Bug
