### ISSUE TITLE
The gem_package provider should set clear_sources to true if either `Chef::Config[:rubygems_url]` is set or if a `source` is given on the resource

### ISSUE THREAD

**Issue by tstuber** [chef/chef#6729] opened 2018-01-04 18:07 UTC
## Description
Given the following setup: 
* Air-gapped environment
* Local ruby gem repository (linked to rubygems.org)
* `client.rb` has a defined `rubygems_url` to the lokal rubygems repository
 
This works so far. But whenever we install a ruby gem via `chef_gem` resource, it always takes 3 minutes until completion. The only way it works immediatly is, if we use the `clear_sources` flag to set it to true.

Our investigations showed that whenever an installation source is specified, the default `rubygems url` (rubygems.org) is used. It would be possible to set the `clear_sources` flag to clean the `rubygems_url` list and to avoid this problem, but that can not be made for shared cookbooks (such as push_jobs, etc). 

## Chef Version
Client: 13.6.4

## Platform Version
Linux, Red Hat 7.4

## Replication Case

* Ensure an air-gapped client
* Define a custom `rubygems_url` (via `client.rb`)
* Run the following snipped that installs a not existing ruby gems

```
chef_gem 'chef-ruby-lvm' do
  action [ :remove, :install ]
  # clear_source true # uncomment to fix the 3min timeout. 
end
```

The same behaviour can be faced by using `gem install` directly.

**3 Minutes installation duration:**
```
gem install --source http://rubygems.mycustomer.local/repository/rubygems mixlib-install --verbose
...
unable to pull data from https://rubygems.org/': timed out (https://api.rubygems.org/specs.4.8.gz)
1 gem installed
```

**Instant installation duration:** 
```
gem install --clear-sources --source http://rubygems.mycustomer.local/repository/rubygems mixlib-install --verbose
```

## Client Output

The behaviour without the `clear_sources` (with 3 minutes duration) is as follows:

```
[2017-12-14T12:19:26+01:00] DEBUG: chef_gem[chef-ruby-lvm] no installed version found for chef-ruby-lvm (>= 0)
[2017-12-14T12:19:26+01:00] DEBUG: found gem chef-ruby-lvm version 0.3.0 for platform ruby from 
[2017-12-14T12:19:26+01:00] DEBUG: chef_gem[chef-ruby-lvm] chef-ruby-lvm not installed, installing 0.3.0
[2017-12-14T12:22:26+01:00] INFO: chef_gem[chef-ruby-lvm] installed chef-ruby-lvm at 0.3.0
[32m- install version 0.3.0 of package chef-ruby-lvm[0m
[0m[2017-12-14T12:22:26+01:00] DEBUG: chef_gem[chef-ruby-lvm] resetting gem environment to default
```

**Comment by lamont-granquist** [comment] 2018-01-08 17:23
I'll need to investigate this to see if its possible to come up with a way to fix that, but its definitely annoying behavior.  I wonder if clear sources should just be set to default to true (maybe if --source or the config option are set) because that would get the behavior as I intended it to work.

**Comment by thommay** [comment] 2018-01-22 14:48
Potentially if we set `rubygems_url` to nil we should disable hitting external sources at all.

**Comment by quulah** [comment] 2018-02-16 09:00
There's a similar issue with the Gems installed from cookbooks' metadata.

We have an air gapped environment without a local Gem mirror, with the requirement gems installed by other means for Chef before the actual run. But when Chef runs, it will try to install the Gems with Bundler, and this fails as it cannot connect to rubygems.orb.

The problem is, I think I'm not able to clear the sources or add --local.

I'm not sure if I should create another issue on this.

**Comment by lamont-granquist** [comment] 2018-02-16 17:49
@quulah that is unrelated to this, there's another issue somewhere which covers that.

**Comment by rayterrill** [comment] 2018-06-08 23:31
Is setting rubygems_url the recommender way to set a custom Gem source (as opposed to source)?

**Comment by lamont-granquist** [comment] 2019-10-28 18:18
As a implementation detail the `clear_sources` flag should be changed to default to `nil` which should have the semantics in the provider of clearing the sources if the config value or the source property is set.  If clear_sources is true or false that should be the positive forcing by the end user.  Should be doable via a fairly simple `def should_clear_sources?` method addition.

**Comment by phiggins** [comment] 2020-03-07 00:24
In thinking about what the correct behavior is for this, it seems like setting a custom source(s) and the `include_default_source` option can cover the 3 scenarios I can think of. Would it make sense to just remove `clear_sources`?

* I have a custom rubygems repo(s) and want to use it exclusively. In this case, I set the custom source(s) and set `include_default_source` to false.
* I have a custom rubygems repo(s) and want to use it along with rubygeme. In this case, I set the custom source(s) and set `include_default_source` to true (or just not set it because this is the default).
* I want no special behavior and everything should be installed from rubygems. Pretty self-explanatory and a good default.

(Setting `include_default_source` without setting a custom source doesn't make sense and should maybe error out?)

Given this, it's not clear what purpose `clear_sources` has and how it should interact with the other options. For example, if I set `clear_sources` and `include_default_source` to true, which takes precedence?

**Comment by lamont-granquist** [comment] 2020-03-10 21:19
https://github.com/chef/chef/pull/6028 that's the last PR that i did.

**Comment by lamont-granquist** [comment] 2020-03-10 21:21
it sounds more like removing `include_default_source` in favor of `clear_sources` would be better, but I don't remember why I invented that to begin with.

**Comment by lamont-granquist** [comment] 2020-03-10 21:22
https://github.com/chef/chef/pull/5995/files for prior PR before that.

**Comment by lamont-granquist** [comment] 2020-03-10 21:24
i'm pretty sure i was worried about #5995 breaking things so i introduced #6028 but i don't immediately see what the things were

**Comment by lamont-granquist** [comment] 2020-03-10 21:28
so one thing to consider is that there's also external rubygems config which the gem command will pick up from the environment (/root/.gemrc or something in /etc, i can't quite recall).  and i think `--clear-sources` can be useful to obliterate that or not.  the `include_default_sources` only affects the `Chef::Config[:rubygems_url]` being included.  so i think there's edge cases where those two might want to be set differently?

**Comment by lamont-granquist** [comment] 2020-03-10 21:32
so i think at least one use case you may be missing is where `include_default_source: false` or `Chef::Config[:rubygems_url]` is set to nil, but `--clear-sources` isn't intended because the custom source has been dropped into the external rubygems config file.

**Comment by lamont-granquist** [comment] 2020-03-13 23:02
reminding myself that `include_default_source` is there so that while `Chef::Config[:rubygems_url]` may be set globally across the chef-client run that it allows any individual resource to opt out of it, and the combination of that flag, with clear_source and with the source property allows any individual resource full control to override any setting it has inherited.

**Comment by tas50** [comment] 2020-03-28 02:01
The fix for this issue is merged into master and it'll go out with the release of Chef Infra Client 16.0 next month.

**Closed by tas50** 2020-03-28 02:01 UTC
Labels: Priority: Medium, Status: Sustaining Backlog, Type: Enhancement
