### ISSUE TITLE
Requesting revision master for a git resource fails in chef 16

### ISSUE THREAD

**Issue by tomhughes** [chef/chef#9872] opened 2020-05-14 18:21 UTC
## Description

A git resource that requests revision `master` fails in chef 16 when it tries to force update master to the revision of it's own tip.

This works fine in chef 14 and 15 and is presumably related to the changes in the way the git resource works.

## Chef Version

16.0.287

## Platform Version

Ubuntu 18.04 with git 2.26.2 from the git-core PPA

## Replication Case

```
git "/usr/local/lib/supybot/plugins/Git" do
  action :sync
  repository "https://github.com/openstreetmap/supybot-git"
  revision "master"
  depth 1
  user "root"
  group "root"
end
```

## Client Output

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '128'
---- Begin output of git branch -f master 1d6df75f919451a8c1ac7f2cb29766e98bf283d0 ----
STDOUT: 
STDERR: fatal: Cannot force update the current branch.
---- End output of git branch -f master 1d6df75f919451a8c1ac7f2cb29766e98bf283d0 ----
Ran git branch -f master 1d6df75f919451a8c1ac7f2cb29766e98bf283d0 returned 128
```

**Comment by johngun3** [comment] 2020-06-04 20:45
This problem is caused by the changes in this commit https://github.com/chef/chef/commit/165685fdcbd4fbe8138d37d1285b633e3958cf09 in the `fetch_updates` method . It used to just `git reset --hard` but now it uses `git branch -f` which causes a problem when the same branch is updated.

**Comment by KindAchmed** [comment] 2020-06-15 09:21
I'm having the same issue with 16.1.16. 
Is there any kind of work around in order to quickly fix this issue?

**Comment by lotooo** [comment] 2020-06-15 14:36
Same issue here.

The work around I want to use for now is doing a `execute "git checkout deploy"` to switch to a different branch before the call to the `git` resource. But it's annoying.

**Comment by lotooo** [comment] 2020-06-17 09:12
I pushed a PR (still in validation process) : https://github.com/chef/chef/pull/9998

This PR tests if it's already using the proper branch and does a `git reset` instead of the `git branch -f` 

I overrided the `git.rb` provider with this version and it seems to work for us.

**Comment by gyamada619** [comment] 2020-07-06 16:22
This issue is causing failures on a number of our Chef runs as well.

**Comment by lotooo** [comment] 2020-07-12 08:09
This [PR](https://github.com/chef/chef/pull/9998) has been merged to `master`

**Closed** 2020-07-12 17:04 UTC
Labels: Priority: Critical, Status: Sustaining Backlog, Type: Regression
