### ISSUE TITLE
windows_feature_dism refuses to install removed features

### ISSUE THREAD

**Issue by zanecodes** [chef/chef#7263] opened 2018-05-15 19:37 UTC
## Description
The `windows_feature_dism` resource [fails if a resource is in a `Removed` state](https://github.com/chef/chef/blob/master/lib/chef/resource/windows_feature_dism.rb#L60), even though this is a valid use case.
Running the command `dism /online /enable-feature NetFX3 /norestart /All` on the same machine works as expected, downloading the sources from Windows Update.
Not sure if this belongs here or https://github.com/chef-cookbooks/windows now that the windows_feature resource is part of core Chef.

## Chef Version
14.1.1

## Platform Version
Windows Server 2012 R2 in Azure

## Replication Case
```
windows_feature 'NetFX3' do
  install_method :windows_feature_dism
end
```

## Client Output
```
* windows_feature[NetFX3] action install
           * windows_feature_dism[NetFX3] action install

             ================================================================================
             Error executing action `install` on resource 'windows_feature_dism[NetFX3]'
             ================================================================================

             RuntimeError
             ------------
             The Windows feature netfx3 is have been removed from the host and cannot be installed.

             Resource Declaration:
             ---------------------
             # In C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1-universal-mingw32/lib/chef/resource/windows_feature.rb

       83:           declare_resource(subresource, new_resource.name) do
       84:             action desired_action
       85:             feature_name new_resource.feature_name
       86:             source new_resource.source if new_resource.source
       87:             all new_resource.all
       88:             timeout new_resource.timeout
       89:             management_tools new_resource.management_tools if subresource == :windows_feature_powershell
       90:           end
       91:         end

             Compiled Resource:
             ------------------
             # Declared in C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1-universal-mingw32/lib/chef/resource/windows_feature.rb:83:in `run_default_subresource'

             windows_feature_dism("NetFX3") do
        action [:install]
        default_guard_interpreter :default
        declared_type :windows_feature_dism
        cookbook_name "worker_image"
        feature_name ["netfx3"]
        all false
        timeout 600
             end

             System Info:
             ------------
             chef_version=14.1.1
             platform=windows
             platform_version=6.3.9600
             ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client
```

**Comment by NAshwini** [comment] 2018-08-06 11:36
Hi @zanecodes, 
I am able to reproduce this issue when `netfx3` is `Disabled with Payload Removed` and in this case 
I was not able to run `dism.exe /online /enable-feature /featurename:netfx3 /norestart` & to make this command working I followed the step from https://www.wintips.org/fix-dism-source-files-could-not-be-found-windows-10-8/  and was able to run **recipe** too successfully.

As per my analysis if the command `dism /online /enable-feature NetFX3 /norestart /All` works successfully then the `windows_feature_dism` resource should work successfully.

Can I get the output for the command `dism.exe /Get-Features /Online /Format:Table /English | grep "NetFx3"` and `dism.exe /online /enable-feature /featurename:netfx3 /norestart` to get more clarity.

Thank you,
Ashwini

**Comment by btm** [comment] 2018-10-25 15:31
https://github.com/chef/chef/blob/master/lib/chef/resource/windows_feature_dism.rb#L209

When the `windows_feature_dism` resource sees a removed feature, it refuses to try to install it unless there is a local source specified or we can find the source specified in the registry.

We believe that it will still install if we have internet access though, using windows update. The install command in the install action already as `/online`, so it might just work.

We could probably test this by putting the resource in a removed state manually, then commenting out the call to `fail_if_removed` and seeing if it works.

If that works fine, then we might look for a way to detect when `dism.exe /online` has failed because it cannot access the internet and raise an appropriate message inside the install action in that case. Which I think would also mean removing `fail_if_removed` entirely.

**Comment by tas50** [comment] 2018-11-28 03:49
This has been fixed on master and backported fro the upcoming Chef 14.8 release. Thanks for the report @zanecodes

**Closed by tas50** 2018-11-28 03:49 UTC
Labels: Area: Windows, Status: Assigned to Team, Type: Sustaining Backlog
