### ISSUE TITLE
Deprecate and Remove Chef::File::Edit

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5965] opened 2017-03-30 01:29 UTC
People actually try to use it and get sad:

https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/18487798-chef-file-edit-needs-controls-for-backup-file-ha

It needs to get removed and right now people should get pointed at the [line cookbook](https://github.com/someara/line-cookbook) and we should think about a better solution for a file editing resource for core.

**Comment by coderanger** [comment] 2017-03-30 01:31
👍 for removing it but also yeah we need a solution for this in core.

**Comment by tas50** [comment] 2018-05-30 20:42
Closing as a dupe of #7043

**Closed by tas50** 2018-05-30 20:42 UTC
Labels: Area: Chef Core, Type: Enhancement
