### ISSUE TITLE
remote_file unable to download files from Github

### ISSUE THREAD

**Issue by chrisnicola** [chef/chef#4075] opened 2015-10-19 23:33 UTC
I've noticed this behaviour with OpsWorks and the [remote_syslog2](https://github.com/trappar/remote_syslog2-cookbook) cookbook.

However apparently others have noticed this:
- http://stackoverflow.com/questions/33223904/chef-remote-file-download-from-github-fails
- ~~http://stackoverflow.com/questions/23943089/chef-client-throws-403-forbidden-intermittently~~
- https://forums.aws.amazon.com/thread.jspa?messageID=677804&#677804

I'm not sure if this is a Github issue, but using wget or curl works.

**Comment by lamont-granquist** [comment] 2015-10-19 23:54
the second url is for 403s from a template resource and has nothing to do with remote_file.

**Comment by jaym** [comment] 2015-10-20 00:10
Maybe Github is throttling you? Is the instance you are executing on shared? Perhaps try using an api key

**Comment by lamont-granquist** [comment] 2015-10-20 00:14
Yeah third url is pretty useless, no debug logs and the poster later moved the url and it worked and it was speculated that GH was doing some kind of throttling/IP banning.

**Comment by lamont-granquist** [comment] 2015-10-20 00:27
The first URL has debug logs, but all I can see is that we got a 302 redirect from GH to an Amazon signed URL and then followed the redirect and got a 403 back from S3.  

I'm assuming `X-Amz-Expires=300` means a 300 second timeout and it doesn't look like the run hung for any reason which would have caused a timeout there.

I also diff'd the url that was returned in the location: of the 302 and its the same url that we're sending the request to and I don't see any mangling that we're doing.

So, possibilities:

1.  its GitHub
2.  its Amazon
3.  we're mangling the URL somewhere that I can't see it, but dumping the transactions with mitmproxy should show that the 302 location we got back from GH doesn't match the GET we send to S3.

The third case is about all I can think of where it might be our code, in which case some special character would have to be getting mangled in some use case which /nearly/ never occurs.  Since I can't replicate it here (the URL in the first case works just fine for me no matter how much I beat on it with curl, wget, or remote_file), that means it'll take someone suffering this issue to dump it and debug what the SSL connections are doing on the wire and see if they match up or not.  If wget and curl works, then we'd need to see what the difference are on the wire for those requests vs. chef client requests.

**Comment by StephenKing** [comment] 2015-10-20 07:23
_(author of the mentioned [StackOverflow question](http://stackoverflow.com/questions/33223904/chef-remote-file-download-from-github-fails) here)_ Actually, it seems like this (or at least my problem) is an issue that was fixed with Chef 11.14. I was able to reproduce this with test-kitchen and newer/older versions of `chef-client`.

**Comment by lamont-granquist** [comment] 2015-10-20 20:20
If you've got a reproducible test-kitchen case you should share it as a cookbook on github so that we can use it.  I don't see anything in 11.14.2 that would have fixed an issue like this, and don't recall any bugs that got fixed that seem related to this.  Also if it was fixed in 11.14.2 did it regress then at some point in 12.x?

**Comment by StephenKing** [comment] 2015-10-20 21:17
There you go, @lamont-granquist: https://github.com/StephenKing/chef-test-4075 (everything fine for 12.5, only fails for 11.12).

**Comment by lamont-granquist** [comment] 2015-10-20 23:48
Hmmm, if this is fixed in 12.5.1 then this issue is really that Opsworks should update their chef-client?

**Comment by chrisnicola** [comment] 2015-10-21 01:27
Actually, I think OpsWorks offers 12.2, but 11.10 is the default. I'm sure it isn't hard to update if that's the fix.

**Comment by StephenKing** [comment] 2015-10-21 06:55
Btw. I'm not using OpsWorks, but if people can't download files from Github there, they might really change their default..

**Comment by lamont-granquist** [comment] 2015-10-21 15:58
Opsworks is going to be getting updates fairly soon.

**Comment by lamont-granquist** [comment] 2015-10-21 16:14
`git bisect` shows that this was fixed by fd407cddb17003ffcf7318a2f48ebce8084f9074

that was fixed in 11.14.0 and in every released 12.x version.

**Closed by lamont-granquist** 2015-10-21 16:14 UTC
Labels: Bug, Chef Core

**Comment by chrisnicola** [comment] 2015-10-23 05:08
Thanks @lamont-granquist I'll suggest that the Opsworks team updates this.
