### ISSUE TITLE
add a key "OTHER INFO" key in metadata.rb file

### ISSUE THREAD

**Issue by anjutiwari** [chef/chef#3129] opened 2015-03-24 07:09 UTC
In metadata.rb file there should be a way to add any "user define information".
how about adding a new "OTHER INFO" key?? so user can add any useful information in his cookbook.

**Comment by btm** [comment] 2015-03-25 03:06
I think this is a duplicate of https://github.com/chef/chef/issues/3104

**Closed by btm** 2015-03-25 03:06 UTC
