### ISSUE TITLE
knife bootstrap --bootstrap-version command line option not working

### ISSUE THREAD

**Issue by ccrebolder** [chef/chef#8834] opened 2019-08-20 17:52 UTC
## Description
When running knife bootstrap with `--bootstrap-version` option, the option if set in `~/.chef/config.rb` takes precedence. According to https://docs.chef.io/config_rb.html#optional-settings the command line option should take precedence. The code at https://github.com/chef/chef/blob/master/lib/chef/knife/core/bootstrap_context.rb#L189-L205 in the `knife_config` method only appears to check `@chef_config` for the value used in `version_to_install`.

## Chef Version
```
$ chef --version
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3
```

## Platform Version
Ubuntu 16.04 (both workstation and client)

## Replication Case
* add `knife[:bootstrap_version] = '13.9.4'` to `~/.chef/config.rb`
* run `knife bootstrap --bootstrap-version '14.12.9' $HOST`
* expected result: `-----> Installing Chef Omnibus (-v 14.12.9)`
* actual result: `-----> Installing Chef Omnibus (-v 13.9.4)`

## Client Output
```
$ knife bootstrap -VV --bootstrap-version '14.12.9' --no-host-key-verify --ssh-user vagrant -N test 192.168.121.194
INFO: Using configuration from /home/myusername/.chef/config.rb
Creating new client for test
Creating new node for test
Connecting to 192.168.121.194
DEBUG: Adding 192.168.121.194
vagrant@192.168.121.194's password:
192.168.121.194 -----> Installing Chef Omnibus (-v 13.9.4)
192.168.121.194 downloading https://omnitruck.chef.io/chef/install.sh
192.168.121.194   to file /tmp/install.sh.1645/install.sh
```

**Comment by lamont-granquist** [comment] 2020-04-08 20:19
The root cause of this is NOT in how the options are being merged but in how they are being used.

`Chef::Config[:knife][:bootstrap_version]` is deliberately the value from the config file and only the config file.

Within a knife subcommand the correct way to access the merged config is through the `config[:bootstrap_version]` accessor which accesses the mixlib-cli config hash, merged with the `Chef::Config[:knife]` sub-hash.  The `knife_config[:bootstrap_version]` hash is also wrong since that is just the `Chef::Config[:knife][:bootstrap_version]` sub-hash.

The problem is that within the "core/bootstrap_context" object the `config` value which is injected there is not the mixlib-cli `config` hash but is the `Chef::Config` hash -- for maximum confusion.  So that is a completely different object from the Knife subcommands.

**Comment by lamont-granquist** [comment] 2020-04-08 20:30
Or that appears to not quite be correct since `@config` in the bootstrap context appears to be the @config from the knife bootstrap subcommand, but I'm still not getting the CLI overrides, but the knife_config accessor was always wrong...  Looks like after fixing one bug something else is still using Chef::Config[:knife][:bootstrap_version] somewhere...

**Comment by lamont-granquist** [comment] 2020-04-08 21:18
Ah I just had a thinko, the fix looks as simple as not using the chef-config hash

**Closed** 2020-04-09 03:29 UTC
Labels: Focus: knife bootstrap, Type: Bug, Type: Tech Debt

**Comment by ccrebolder** [comment] 2020-04-09 15:39
Thank you both!
