### ISSUE TITLE
chocolatey_package resource now reports non-zero as failure in successful scenarios

### ISSUE THREAD

**Issue by ferventcoder** [chef/chef#5030] opened 2016-06-17 20:40 UTC
## Description

I mentioned this before in April to @mwrock - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today and folks are going to start reporting breakages even though we noted it in our release notes and tried to give plenty of notice to folks that it was coming (2 months notice in this case).

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> - Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)
> 
> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.
## Platform Version

Windows 
## Replication Case

Install a package with Chocolatey 0.9.10 that would exit with 3010 indicating reboot, which is now considered a successful exit code by Chocolatey.
## Client Output

The resource thinks there is an error.

**Comment by ferventcoder** [comment] 2016-06-17 20:41
For context and possibly a better repro - https://gitter.im/chocolatey/chocolatey.org?at=57645acabd67400679da8088 cc @skyguy94

**Comment by mwrock** [comment] 2016-06-17 20:52
awesome @ferventcoder. I think we will do the exact same thing that we do for the `windows_package` resource and expose a `returns` property which is a list of exit codes that we expect to indicate success.

**Comment by ferventcoder** [comment] 2016-06-17 20:53
Perfect. 👍

**Comment by skyguy94** [comment] 2016-06-18 13:44
I am able to get choco to ignore the exit code by (using powershell as an example): 
```
chocolatey 'powershell' do
  options ({ '-ignore-package-exit-codes' => "" })
end
```

Since its a double-dash option and the cookbook prepends a single dash, I prepend a dash in the `-ignore-package-exit-codes` option.

**Comment by pinterl** [comment] 2016-06-23 06:18
I have tried what skyguy94 recommended, but I got the same error message in TestKitchen:
Expected process to exit with [0], but received '3010'
---- Begin output of "C:\ProgramData\chocolatey/bin/choco" install -y  --ignore-package-exit-codes  windowsazurepowershell ----

I could not find any workaround. This is a critical issue, because we cannot launch servers until the error if fixed.
 
My code is:
```
  chocolatey 'windowsazurepowershell' do
    options ({ '-ignore-package-exit-codes' => "" })
  end
```

**Comment by skyguy94** [comment] 2016-06-23 12:35
I'm not sure why that didn't work, but if you don't mind having something external reboot the servers (Restart-Computer from powershell) you could poll for the package to appear in chocolatey's installed list and reboot.

**Comment by mwrock** [comment] 2016-06-23 18:28
I tested this by creatibg a simple chocolatey package that ends with `exit 30` and I ran `choco install test-a -y --ignore-package-exit-codes --source .` but it still fails. So this is either a misunderstanding of the switch or a choco bug. Trying to determine which.

**Comment by mwrock** [comment] 2016-06-23 18:51
actually I "mistested" this. I changed my test package to exit 3010 which choco considers succesful by default and this allows the package to succeed but choco continues to pass through the `3010` exit code even with `--ignore-package-exit-codes` and I'd expect this flag to cause choco to pass 0.

**Comment by mwrock** [comment] 2016-06-23 19:05
I think we have confirmed that the `--ignore-package-exit-codes` behavior here is a bug - https://github.com/chocolatey/choco/issues/821

**Comment by mwrock** [comment] 2016-06-23 19:23
bug got moved to https://github.com/chocolatey/choco/issues/827 and it looks like there is a fix due out soon.

**Comment by ferventcoder** [comment] 2016-06-23 20:11
Testing it now folks. Should be out soon.

**Comment by ferventcoder** [comment] 2016-06-23 21:23
Just pushed the updated Chocolatey that fixes this. Should be live within two hours. You can upgrade to it right now without waiting by specifying `choco upgrade chocolatey --version 0.9.10.3`. Let me know if it still has issues.

**Comment by pinterl** [comment] 2016-06-24 05:54
Thank you, it works great with
```
  chocolatey_package 'windowsazurepowershell' do
    options "--ignore-package-exit-codes"
  end
```

**Comment by skyguy94** [comment] 2016-06-24 12:34
Works with my scripts and my posted workaround :ship:

**Comment by ferventcoder** [comment] 2016-06-24 12:43
Awesome!

**Comment by btm** [comment] 2016-11-11 14:16
@mwrock is there anything left to do in Chef for this?

**Comment by mwrock** [comment] 2016-11-12 09:07
Yes @btm. The chocolatey package resource should expose a `returns` property so that it can succeed when it receives non 0 (but successful) exit codes. Currently we encourage users to use the above workaround of passing the `--ignore-package-exit-codes` option to chocolatey.

**Comment by btm** [comment] 2017-01-05 14:23
This is fixed in https://github.com/chef/chef/issues/5688 and will be in the next Chef release.

**Closed by btm** 2017-01-05 14:23 UTC
Labels: Bug, Chef Core, Windows
