### ISSUE TITLE
knife client/user commands do not actually allow for specifying a public key

### ISSUE THREAD

**Issue by gnowxilef** [chef/chef#2194] opened 2014-10-09 00:43 UTC
creating or editing a user/client does not actually save the public key that is given to it.

**Comment by adamedx** [comment] 2015-05-20 17:26
This is an issue that people hit in Chef training when using knife client create.

**Comment by thommay** [comment] 2015-05-20 17:27
This is part of #3368

**Comment by tas50** [comment] 2019-08-12 17:57
Closing this as a dupe of #2541

**Closed by tas50** 2019-08-12 17:57 UTC
Labels: Component: Chef Core
