### ISSUE TITLE
Execute/Script resource max timeout

### ISSUE THREAD

**Issue by Demonsthere** [chef/chef#5136] opened 2016-07-25 11:43 UTC
## Description

In my deployment I use a script resource that launches a script. This script can take quite a long time (3-4 hours). 
I have set the timeout in my resource to a very large number (50000), however during a chef run, it get a timeout after 9999 seconds. Is this the maximal timeout value, or can it be increased?
### resource

`bash 'Ant install addon' do
  user node['snails_hybris-server']['userName']
  cwd node['snails_hybris-server']['platformPath']
  timeout 50000
  code <<-EOH
    ...
  EOH
end
`
### output

`Mixlib::ShellOut::CommandTimeout
       --------------------------------
           Command timed out after 9999s:
           Command exceeded allowed execution time, process terminated
`

Versions: 
ChefDK 0.10.0
Ruby 2.1.6
Kitchen 1.4.2

**Comment by lamont-granquist** [comment] 2016-07-25 17:10
'9999' as a timeout doesn't exist in the chef-client code or in mixlib-shellout.  the execute provider has a default timeout of 3600s.   mixlib-shellout has a default timeout of 600s.

**Comment by Demonsthere** [comment] 2016-07-26 07:51
the execute provider has a default timeout of 3600s. 
mixlib-shellout has a default timeout of 600s.

Those are the default timers. What is the maximal value for each of them?

**Comment by lamont-granquist** [comment] 2016-08-03 17:54
there is no enforced maximum by ruby, possibly 2 billion or 4 billion seconds by the O/S.

**Comment by Demonsthere** [comment] 2016-08-04 07:21
> there is no enforced maximum by ruby, possibly 2 billion or 4 billion seconds by the O/S.

Sorry, but I cannot agree with that. Like i said in my first post, i set the timeout value to 50000 (or 50_000 as set by rubocop) seconds, yet the task was timeouted after 9999s

**Comment by lamont-granquist** [comment] 2016-11-30 18:14
We can't find anywhere in the mixlib-shellout or chef code where a 9999s timeout was set.

Looking at what chef-client does this simple script:

```ruby
#!/usr/bin/env chef-apply

bash "thing" do
  code do <<-EOH
    echo 'foo'
EOH
  end
  timeout 1234567
end
```

results in the correct arguments to mixlib-shellout:

```
<Mixlib::ShellOut#70176435353660: command: '"bash"  "/var/folders/vl/7__gnv9x5sg745ntrsh0yglm0000gn/T/chef-script20161130-35797-1wv3h3d"' process_status: #<Process::Status: pid 35931 exit 0> stdout: '' stderr: '' child_pid: 35931 environment: {"LC_ALL"=>"en_US.UTF-8", "LANGUAGE"=>"en_US.UTF-8", "LANG"=>"en_US.UTF-8"} timeout: 1234567 user:  group:  working_dir:  >
```

so this is definitely not a bug in this codebase, and its unlikely that its a bug in the mixlib-shellout code base (if that timeout value was getting scribbled over, we'd have heard about it).

closing this ticket as we cannot replicate the bug.

**Closed by lamont-granquist** 2016-11-30 18:14 UTC
