### ISSUE TITLE
knife data bag from file <bag> <file> fails with "raw" json format

### ISSUE THREAD

**Issue by ChadScott** [chef/chef#4868] opened 2016-04-26 19:48 UTC
## Description

When using `knife data bag from file` on a "raw" JSON from chef-zero, it fails with `ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil`

## Chef Version

```
$ chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
```

## Platform Version

MacOS 10.11

## Replication Case

Create a JSON document containing the following:
```
{
  "name":"test_data_bag_item",
  "json_class":"Chef::DataBagItem",
  "chef_type":"data_bag_item",
  "data_bag":"test_data_bag",
  "raw_data": {
    "id":"test_data_bag_item",
    "value":"test"
  }
}
```

and upload it to a chef server with `knife data bag from file test_data_bag the.json`.
## Client Output

`ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil`

**Comment by thommay** [comment] 2016-04-27 17:21
Thanks for the report, this is a duplicate of #4815 so I'm going to close this in favour of that one.

**Closed by thommay** 2016-04-27 17:21 UTC

**Comment by ChadScott** [comment] 2016-04-27 17:33
Nothing about this data bag is encrypted. `knife data bag from file` is simply not figuring out it's looking at the "raw"/on-disk version and taking the `raw_data` component and uploading that. It should just work and it did work in the past.

**Comment by thommay** [comment] 2016-04-27 17:42
Yeah, it's the same bug though.

**Comment by ChadScott** [comment] 2016-04-27 17:44
Well, thanks for the simple dismissal. I've updated the other bug to include my use case.

**Comment by thommay** [comment] 2016-04-27 17:46
I'm sorry that this came across as a dismissal - it was not intended to be, simply trying to keep duplicates to a minimum (and github issues don't allow us to do anything more sophisticated than a simple close).

Again, apologies for any offence caused.

**Comment by ChadScott** [comment] 2016-04-27 17:48
No worries. I think I'm just cranky because I had to mass translate about a hundred data bags. ;)
