### ISSUE TITLE
knife search show specific attribute (-a) broken on 12.1.0 

### ISSUE THREAD

**Issue by gmiranda23** [chef/chef#3041] opened 2015-03-06 19:33 UTC
The command ``knife search node *:* -a foo`` should find any node object and display the value of attribute ``foo``.  In chef-client 12.1.0, this is broken.

Example, using earlier omnibus chef-client distro

    $ knife search node "*:*" -a ipaddress
      1 items found

      i-5149955b:
        ipaddress: 172.31.38.253

    $ knife -v
    Chef: 12.0.3

Example, using omnibus chef-client 12.1.0 distro for OSX 10.9

    $ /opt/chef/bin/knife search node "*:*" -a ipaddress
    ERROR: knife encountered an unexpected error
    This may be a bug in the 'search' knife command or plugin
    Please collect the output of this command with the `-VV` option before filing a bug report.
    Exception: NoMethodError: undefined method `[]' for nil:NilClass
    
    $ /opt/chef/bin/knife -v
    Chef: 12.1.0

Full output of broken knife 12.1.0 command using -VV

    $ /opt/chef/bin/knife search node "*:*" -a ipaddress -VV
    INFO: Using configuration from /Users/gmiranda/Documents/Chef_Fundamentals/repos/fundamentals/chef-repo/.chef/knife.rb
    DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
    DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
    DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
    DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
    DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
    DEBUG: Signing the request as gmiranda23
    DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
    DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
    DEBUG: Initiating POST to https://api.opscode.com/organizations/opscode-gmiranda/search/node?q=*%253A*&sort=X_CHEF_id_CHEF_X%20asc&start=0
    DEBUG: ---- HTTP Request Header Data: ----
    DEBUG: Content-Type: application/json
    DEBUG: Accept: application/json
    DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
    DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
    DEBUG: X-OPS-USERID: gmiranda23
    DEBUG: X-OPS-TIMESTAMP: 2015-03-06T19:27:47Z
    DEBUG: X-OPS-CONTENT-HASH: rIuij2UVvmWjcVnbblJ/iDxpOb4=
    DEBUG: X-OPS-AUTHORIZATION-1: hDJoNT82t0sATipMPE7Nwwrs8DeKTDJD+kYTAo+7xKU2QG91bfPSGUPPRBnK
    DEBUG: X-OPS-AUTHORIZATION-2: 9MYjdAGqQ66Hiy7yj4Z/AuoUFa8ixo1QmTSecu8xOjssZcoaO81Ptcr91ZiJ
    DEBUG: X-OPS-AUTHORIZATION-3: ZuuwQJkLM5NI40pptIZv66KFdmRp12bH0cr/DIJeXjfb0mYPPgFu5wDSNzro
    DEBUG: X-OPS-AUTHORIZATION-4: usMwVcM4Ap3hRaUeq6kjeXIpMPDapEYOSjUJHGYk/xy/v/Co5LdWk6ZZXhCK
    DEBUG: X-OPS-AUTHORIZATION-5: 9v92zIURDD45GJ6n5uV33OdBF4F+pGhIqe/c8FQh8EtuNLHtluMObF+OkAJr
    DEBUG: X-OPS-AUTHORIZATION-6: KcuqLVleOqW7axeKJo//Ww/AtWuotSlYm8c0n5oHxA==
    DEBUG: HOST: api.opscode.com:443
    DEBUG: X-REMOTE-REQUEST-ID: e8855063-ddd0-4dfc-8886-0eeafe643a6a
    DEBUG: Content-Length: 53
    DEBUG: ---- End HTTP Request Header Data ----
    DEBUG: ---- HTTP Status and Header Data: ----
    DEBUG: HTTP 1.1 200 OK
    DEBUG: server: ngx_openresty
    DEBUG: date: Fri, 06 Mar 2015 19:27:49 GMT
    DEBUG: content-type: application/json
    DEBUG: content-length: 185
    DEBUG: connection: close
    DEBUG: x-ops-api-info: flavor=hec;version=12.0.0;oc_erchef=0.29.2
    DEBUG: ---- End HTTP Status/Header Data ----
    DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
    DEBUG: Content-Length validated correctly.
    DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
    DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
    DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
    DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
    DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
    DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
    /opt/chef/embedded/apps/chef/lib/chef/knife/search.rb:109:in `block in run': undefined method `[]' for nil:NilClass (NoMethodError)
    	from /opt/chef/embedded/apps/chef/lib/chef/search/query.rb:90:in `call'
    	from /opt/chef/embedded/apps/chef/lib/chef/search/query.rb:90:in `block in search'
    	from /opt/chef/embedded/apps/chef/lib/chef/search/query.rb:90:in `each'
    	from /opt/chef/embedded/apps/chef/lib/chef/search/query.rb:90:in `search'
    	from /opt/chef/embedded/apps/chef/lib/chef/knife/search.rb:105:in `run'
    	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
    	from /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
    	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
    	from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:138:in `run'
    	from /opt/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
    	from /opt/chef/bin/knife:52:in `load'
    	from /opt/chef/bin/knife:52:in `<main>'
 
 Issue discovered by @MathildeBarr

**Comment by ranjib** [comment] 2015-03-06 19:36
duplicate of https://github.com/chef/chef/issues/3018

**Closed by ranjib** 2015-03-06 19:36 UTC
