### ISSUE TITLE
windows_task is not idempotent on non-English versions of Windows

### ISSUE THREAD

**Issue by jugatsu** [chef/chef#7629] opened 2018-09-07 18:11 UTC
## Description
`windows_task` resource converges each time as `user` property is not `SYSTEM` or any other from https://github.com/chef/chef/blob/master/lib/chef/resource/windows_task.rb#L119.

Task is created successfully but running under `система` or `СИСТЕМА` user. I think that similar problem exists on different versions of Windows (non-English).

https://github.com/chef/chef/blob/2c4f13a14d762a306dbe051c658cb9b848b670b6/lib/chef/provider/windows_task.rb#L330

```ruby
def task_needs_update?(task)
          flag = false
          if new_resource.frequency == :none
            flag = (task.account_information != new_resource.user ||
```

`task.account_information != new_resource.user` is always true because `account_information` is in different language and therefore not `SYSTEM`.

How we can workaround this use case?

## Chef Version
13.9.4

## Platform Version
Windows Server 2016 Datacenter Evaluation Russian Edition
```powershell
PS C:\Users\vagrant> get-winsystemlocale

LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)
```

## Replication Case
```ruby
include_recipe 'chef-client::task'
```

## Client Output
```
[2018-09-07T10:39:49-07:00] DEBUG: Providers for generic windows_task resource enabled on node include: [Chef::Provider::WindowsTask]
       [2018-09-07T10:39:49-07:00] DEBUG: Providers for generic windows_task resource enabled on node include: [Chef::Provider::WindowsTask]
       [2018-09-07T10:39:49-07:00] DEBUG: Provider for action create on resource windows_task[chef-client] is Chef::Provider::WindowsTask
       [2018-09-07T10:39:49-07:00] DEBUG: Provider for action create on resource windows_task[chef-client] is Chef::Provider::WindowsTask
       [2018-09-07T10:39:49-07:00] DEBUG: Looking for existing tasks
       [2018-09-07T10:39:49-07:00] DEBUG: Looking for existing tasks
       [2018-09-07T10:39:49-07:00] DEBUG: windows_task[chef-client] task exists.
       [2018-09-07T10:39:49-07:00] DEBUG: windows_task[chef-client] task exists.
       [2018-09-07T10:39:49-07:00] DEBUG: Finding system date format
       [2018-09-07T10:39:49-07:00] DEBUG: Finding system date format
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /CREATE /TN "chef-client" /F /SC "minute" /ST "10:37" /SD "07.09.2018" /MO "30" /RU "SYSTEM" /RL "HIGHEST" /TR "cmd /c 'C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300' " 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /CREATE /TN "chef-client" /F /SC "minute" /ST "10:37" /SD "07.09.2018" /MO "30" /RU "SYSTEM" /RL "HIGHEST" /TR "cmd /c 'C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300' " 
       [2018-09-07T10:39:50-07:00] DEBUG: looking for existing tasks
       [2018-09-07T10:39:50-07:00] DEBUG: looking for existing tasks
       [2018-09-07T10:39:50-07:00] DEBUG: Removing former execution_time_limit if any
       [2018-09-07T10:39:50-07:00] DEBUG: Removing former execution_time_limit if any
       [2018-09-07T10:39:50-07:00] DEBUG: Setting execution_time_limit as PT72H
       [2018-09-07T10:39:50-07:00] DEBUG: Setting execution_time_limit as PT72H
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /DELETE /TN "chef-client" /F 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /DELETE /TN "chef-client" /F 
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG: running: 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /CREATE /TN "chef-client" /RU "SYSTEM" /XML "C:\Users\vagrant\AppData\Local\Temp/windows_task.xml" 
       [2018-09-07T10:39:50-07:00] DEBUG:     schtasks /CREATE /TN "chef-client" /RU "SYSTEM" /XML "C:\Users\vagrant\AppData\Local\Temp/windows_task.xml" 
       
             - windows_task[chef-client] task created
```

**Comment by Vasu1105** [comment] 2018-09-10 05:44
We will be looking into this meanwhile could you please try this out with newer version of Chef ?

**Comment by jugatsu** [comment] 2018-09-10 06:07
```
[2018-09-09T22:57:05-07:00] DEBUG: Running Ohai with the following configuration: {:logger=>Chef::Log}
       Starting Chef Client, version 14.4.56

chef_client_scheduled_task[Chef Client] action add[2018-09-09T22:57:13-07:00] INFO: Processing chef_client_scheduled_task[Chef Client] action add (chef-client::task line 37)
       
           * windows_task[chef-client] action create[2018-09-09T22:57:13-07:00] INFO: Processing windows_task[chef-client] action create (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef-client/resources/scheduled_task.rb line 55)
       
             - windows_task[chef-client] task updated

```

Also

```
* windows_task[client] action create[2018-09-09T23:05:08-07:00] INFO: Processing windows_task[client] action create (chef-client::test line 1)
       
           - windows_task[client] task updated
```

with following recipe:

```ruby
windows_task 'client' do
  run_level :highest
  command 'ipconfig.exe'
  user 'SYSTEM'
  frequency :hourly
  frequency_modifier 20
end
```

**Comment by Vasu1105** [comment] 2018-09-11 10:27
We also tried running particular recipe share by you. But in that case also I am unable to reproduce the issue.
```
windows_task 'client' do
  run_level :highest
  command 'ipconfig.exe'
  user 'SYSTEM'
  frequency :hourly
  frequency_modifier 20
end
```
First run output:

```
PS C:\Users\manik> chef-client
Starting Chef Client, version 14.4.56
[2018-09-11T12:01:41+03:00] INFO: *** Chef 14.4.56 ***
[2018-09-11T12:01:41+03:00] INFO: Platform: x64-mingw32
[2018-09-11T12:01:41+03:00] INFO: Chef-client pid: 2604
[2018-09-11T12:01:41+03:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
[2018-09-11T12:01:45+03:00] INFO: Run List is [recipe[starter]]
[2018-09-11T12:01:45+03:00] INFO: Run List expands to [starter]
[2018-09-11T12:01:45+03:00] INFO: Starting Chef Run for manik-russian
[2018-09-11T12:01:45+03:00] INFO: Running start handlers
[2018-09-11T12:01:45+03:00] INFO: Start handlers complete.
[2018-09-11T12:01:46+03:00] INFO: Error while reporting run start to Data Collector. URL: https://api.chef.io/organizati
ons/msys_manik/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
resolving cookbooks for run list: ["starter"]
[2018-09-11T12:01:46+03:00] INFO: Loading cookbooks [starter@1.0.0]
Synchronizing Cookbooks:
  - starter (1.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Welcome to Chef, ManikConverging 1 resources
Recipe: starter::default
  * windows_task[client] action create[2018-09-11T12:01:47+03:00] INFO: Processing windows_task[client] action create (s
tarter::default line 9)

    - windows_task[client] task created
[2018-09-11T12:01:48+03:00] INFO: Chef Run complete in 2.421203 seconds

Running handlers:
[2018-09-11T12:01:48+03:00] INFO: Running report handlers
Running handlers complete
[2018-09-11T12:01:48+03:00] INFO: Report handlers complete
Chef Client finished, 1/1 resources updated in 06 seconds
[2018-09-11T12:01:48+03:00] INFO: Sending resource update report (run-id: 02cc650a-d1bf-4aef-91b0-57a62bb7afed)
```
Second run output:

```
PS C:\Users\manik> chef-client
Starting Chef Client, version 14.4.56
[2018-09-11T12:01:56+03:00] INFO: *** Chef 14.4.56 ***
[2018-09-11T12:01:56+03:00] INFO: Platform: x64-mingw32
[2018-09-11T12:01:56+03:00] INFO: Chef-client pid: 2856
[2018-09-11T12:01:56+03:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
[2018-09-11T12:02:00+03:00] INFO: Run List is [recipe[starter]]
[2018-09-11T12:02:00+03:00] INFO: Run List expands to [starter]
[2018-09-11T12:02:00+03:00] INFO: Starting Chef Run for manik-russian
[2018-09-11T12:02:00+03:00] INFO: Running start handlers
[2018-09-11T12:02:00+03:00] INFO: Start handlers complete.
[2018-09-11T12:02:01+03:00] INFO: Error while reporting run start to Data Collector. URL: https://api.chef.io/organizati
ons/msys_manik/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
resolving cookbooks for run list: ["starter"]
[2018-09-11T12:02:01+03:00] INFO: Loading cookbooks [starter@1.0.0]
Synchronizing Cookbooks:
  - starter (1.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Welcome to Chef, ManikConverging 1 resources
Recipe: starter::default
  * windows_task[client] action create[2018-09-11T12:02:02+03:00] INFO: Processing windows_task[client] action create (s
tarter::default line 9)
[2018-09-11T12:02:02+03:00] INFO: windows_task[client] task does not need updating and force is not specified - nothing
to do
 (up to date)
[2018-09-11T12:02:02+03:00] INFO: Chef Run complete in 2.087767 seconds

Running handlers:
[2018-09-11T12:02:02+03:00] INFO: Running report handlers
Running handlers complete
[2018-09-11T12:02:02+03:00] INFO: Report handlers complete
Chef Client finished, 0/1 resources updated in 06 seconds
[2018-09-11T12:02:02+03:00] INFO: Sending resource update report (run-id: 6785b541-8adb-47a0-a533-6f2cad0f9b0e)

```

**Comment by jugatsu** [comment] 2018-09-11 10:29
@Vasu1105 Can you run 
```powershell
 Get-WMIObject win32_group -filter "SID='S-1-5-32-544' AND LocalAccount=True" | select -ExpandProperty Name
```

The output should be in Russian, not English.

**Comment by Vasu1105** [comment] 2018-09-11 10:35
@jugatsu Could you please verify your recipe has the same values setup when you are running the recipe second time for the particular task name.

**Comment by jugatsu** [comment] 2018-09-11 10:44
@Vasu1105 You are running on English system **with** russian UI and locale. In this case `windows_task` resource works as expected because user that task is running is `SYSTEM`.

When the system is **true** Russian version, user that task is running is `СИСТЕМА`.

**Comment by Vasu1105** [comment] 2018-09-11 10:46
@jugatsu its giving me output in English. I am getting that as `Administrator`

But the output for below is same as you told so I am not sure what I am missing in settings.

```
PS C:\Users\manik> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)
```

**Comment by jugatsu** [comment] 2018-09-11 14:18
@Vasu1105 To reproduce this issue i can make repo with test recipe and build vagrant boxes. But it gonna take some time.

**Comment by jugatsu** [comment] 2018-09-11 17:28
OS: Windows Version 2016 Russian
ISO: http://download.microsoft.com/download/0/D/4/0D41501C-EEBC-4481-8A37-14A56A64BFDA/14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_RU-RU.ISO (Russian version)
Idempotent: **NO**

![2018-09-11 20 11 40](https://user-images.githubusercontent.com/2243323/45375997-53adff00-b5ff-11e8-9ded-71b503fdc48a.png)

-------------

OS: Windows Version 2016 English but with Russian UI and locale (in your example)
ISO: http://care.dlservice.microsoft.com/dl/download/1/4/9/149D5452-9B29-4274-B6B3-5361DBDA30BC/14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO (English version)
Idempotent: **YES**

![2018-09-11 20 17 00](https://user-images.githubusercontent.com/2243323/45376128-ba331d00-b5ff-11e8-9b13-8e52474d19f5.jpg)


In both examples `Get-WinSystemLocale` returns
```
LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)
```

But user (also known as Principal) that task is running IS **DIFFERENT** because of _localization_!

First example it's `СИТЕМА`. It's not idempotent and running over and over again because of
https://github.com/chef/chef/blob/2c4f13a14d762a306dbe051c658cb9b848b670b6/lib/chef/provider/windows_task.rb#L330

Second (your example) - `SYSTEM`. It's idempotent as
https://github.com/chef/chef/blob/2c4f13a14d762a306dbe051c658cb9b848b670b6/lib/chef/provider/windows_task.rb#L330
in desired state.

@Vasu1105 correct me if I'm wrong.

**Comment by Vasu1105** [comment] 2018-09-12 11:47
@jugatsu Thank you for detailed information and the image provided. Yes you are correct and we able to reproduce that with given image. We will update you once we have a fix for this.

**Closed** 2018-10-17 08:48 UTC
Labels: Area: Windows, Status: Assigned to Team, Type: Sustaining Backlog
