### ISSUE TITLE
Coercing attributes inside an array

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4368] opened 2016-01-08 22:34 UTC
An odd report from Slack. If you are using Solo, and loading role or environment data from `.rb` files, and in those files you are using symbols as keys (either directly or via the `{a:1}` short syntax), you can end up with a situation where data isn't coerced so that only one of string or symbol keys work.

Specifically when you have an array of hashes in attribute data, we don't seem to coerce those inner hashes to `Mash`/`VividMash`. I feel like this used to work, but I can't find any evidence for that. Regardless, it probably should. Thoughts?

/cc @chef/client-core

**Comment by coderanger** [comment] 2016-01-08 22:39
A clearer example:

```ruby
# myrole.rb
default_attributes({
  foo: [{bar: 1}],
})

# recipe code
node['foo'][0][:bar] == 1
node['foo'][0]['bar'] == nil
```

**Comment by lamont-granquist** [comment] 2016-01-09 02:30
might be fixed by #3721

**Comment by lamont-granquist** [comment] 2016-01-11 14:43
Actually, tried to replicate this on master and I got '1' for both of those.

**Comment by lamont-granquist** [comment] 2016-01-20 18:25
I think there's no fundamental difference between solo and client when it comes to how the attributes get merged, and `lib/chef/run_list/run_list_expansion.rb` has a `#apply_role_attributes` which is responsible in both code paths for the merge:

```
      def apply_role_attributes(role)
        @default_attrs = Chef::Mixin::DeepMerge.merge(@default_attrs, role.default_attributes)
        @override_attrs = Chef::Mixin::DeepMerge.merge(@override_attrs, role.override_attributes)
      end
```

And if calling DeepMerge.merge(<Mash>, <Hash>) didn't work, that would break -j arguments as well and I'd think we'd have heard about this (plus it just doesn't make a whole lot of sense, we definitely get a Mash out of it, and any values merged in will get convert_value'd inside of the Chef::Mash.

**Comment by lamont-granquist** [comment] 2016-01-20 18:29
(although i guess with -j you only pass in JSON so you never get symbols, but still I don't see how DeepMerge would be bypassing Chef::Mash#convert_value...)

**Comment by gravesb** [comment] 2016-01-20 19:15
Could the issue be on [this line of VividMash](https://github.com/chef/chef/blob/master/lib/chef/node/attribute_collections.rb#L198) where it converts arrays to AttrArrays?  I don't see where the values of that attr array would be mashified.

**Comment by lamont-granquist** [comment] 2016-01-20 23:07
oh i see, yeah i think i derp'd when i tried to replicate it and didn't actually test an array.

**Comment by lamont-granquist** [comment] 2016-01-20 23:17
So @gravesb that is plausible, if so then it has been a bug since roughly chef 11.0.0-ish or before.  Should also be fixed by #3721 if you can replicate it.

I'd actually be kinda interested in if this bug is fixed in that rewrite because I made a design decision which was debatable, but which would most likely be directly responsible for inherently getting this use case right on that branch...

**Comment by gravesb** [comment] 2016-01-21 22:07
I threw together a minimal cookbook to reproduce the issue: https://github.com/gravesb/array_attr_test

I wasn't sure how to run test kitchen using the code from your `attributes-v1.99` branch.

**Comment by lamont-granquist** [comment] 2016-01-22 02:37
thanks, i replicated your result:

```bash
# cd /tmp/kitchen
# chef-solo -c solo.rb -j dna.json
Starting Chef Client, version 12.6.0
Compiling Cookbooks...


node['foo'][0]['bar'] == '1': false
node['foo'][0][:bar] == '1': true
node['foo'][0]['baz']:
node['foo'][0][:baz]: ["2", "3"]


Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 00 seconds
```

then updated the chef-client to my branch:

```bash
# export PATH=/opt/chef/bin:/opt/chef/embedded/bin:$PATH
# gem install appbundle-updater
Fetching: appbundle-updater-0.2.10.gem (100%)
Successfully installed appbundle-updater-0.2.10
Parsing documentation for appbundle-updater-0.2.10
Installing ri documentation for appbundle-updater-0.2.10
Done installing documentation for appbundle-updater after 0 seconds
1 gem installed
# appbundle-updater chef chef lcg/attributes-v1.99 --tarball
-----> Cleaning chef checkout
-----> Creating /opt/chef/embedded/apps directory
-----> Installing Packages
    running: yum -y install gcc make git
-----> Extracting chef from https://github.com/chef/chef/archive/lcg/attributes-v1.99.tar.gz
Unkown tar entry: pax_global_header type: g.
-----> Installing dependencies
    running: /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/bundle install --without server docgen test development
-----> Installing gem
    running: /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/bundle exec /opt/chef/embedded/bin/rake install
-----> Updating appbundler binstubs for chef
    running: /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/appbundler /opt/chef/embedded/apps/chef /opt/chef/bin
-----> Finished!
```

and the result is:

```bash
Starting Chef Client, version 12.6.0
    * setting automatic['cookbooks']['array_attr_test']['version'] = 0.1.0
Compiling Cookbooks...


node['foo'][0]['bar'] == '1': true
node['foo'][0][:bar] == '1': true
node['foo'][0]['baz']: ["2", "3"]
node['foo'][0][:baz]: ["2", "3"]


Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 00 seconds
```

fixed on my branch...

**Closed** 2016-09-23 23:49 UTC
Labels: Chef Solo
