### ISSUE TITLE
Knife Profiles credentials file method only works in user's home directory

### ISSUE THREAD

**Issue by SteveDelFante** [chef/chef#9665] opened 2020-04-15 22:04 UTC
### When a Change Needs a Design Proposal

A design proposal should be opened any time a change meets one of the following qualifications:

- Significantly changes the user experience of a project in a way that impacts users.
- Significantly changes the underlying architecture of the project in a way that impacts other developers.
- Changes the development or testing process of the project such as a change of CI systems or test frameworks.

### Why We Use This Process

- Allows all interested parties (including any community member) to discuss large impact changes to a project.
- Serves as a durable paper trail for discussions regarding project architecture.
- Forces design discussions to occur before PRs are created.
- Reduces PR refactoring and rejected PRs.

---

 We can only get the credentials file method to work if everything is setup in my home directory, (not in a new repo) thus utilizing the .chef dir in my home dir. But then we started evaluating the risks of students mucking around in their ~/.chef dir.

Can you please make the credential file method look within its current working directory for the .chef dir so we can have students create a safe repo to configure knife to use profile please?

**Comment by tas50** [comment] 2020-04-20 18:07
Dupe of #9677

**Closed** 2020-04-20 18:07 UTC
Labels: Status: Untriaged
