### ISSUE TITLE
knife bootstrap first 3 lines are always outputted to STDERR

### ISSUE THREAD

**Issue by jauling** [chef/chef#6667] opened 2017-12-14 14:47 UTC
## Description
knife bootstrap outputs the first 3 lines to STDERR, which seems improper

## Chef Version
12.21.4

## Platform Version
Red Hat Enterprise Linux Server release 6.2 (Santiago)

## Replication Case
Run knife bootstrap, with some typical parameters, and redirect the STDOUT and STERR outputs to separate files. Then cat the STDERR file, and you'll see something like:
Creating new client for NODENAME
Creating new node for NODENAME
Connecting to IPADDRESS

## Client Output

```

```

**Comment by jauling** [comment] 2018-01-10 11:53
Please let me know if this is an improperly submitted issue request

**Comment by lamont-granquist** [comment] 2018-02-07 21:50
this is the result of 72658da6feac1ec349eb7c930acf1c714c9d260e which fixed https://tickets.opscode.com/browse/CHEF-4760 and https://tickets.opscode.com/browse/CHEF-1898

the specific lines in boostrap/client_builder could be changed from `ui.info()` to `ui.msg()` but unless there's an actual impact caused by this the safer route is to just consider this as operating as designed and concatenate stderr to stdout with `2>&1` or whatever...  someone out there undoubtedly depends on this behavior and will break if we modify it.

**Comment by jauling** [comment] 2018-02-08 11:50
Hmm, CHEF-1898 does make sense to me, but I'm having a difficult time reasoning through CHEF-4760. Errors should be captured in stderr and diagnostics should be captured by stdout. I agree that in CHEF-4760 that capturing the exit status most likely is best, but outputting text to the appropriate file handle seems necessary too.

While I guess I could parse these 3 lines out when sifting through the error output, it seems slightly silly.

**Comment by tas50** [comment] 2019-10-21 17:47
@jauling In Chef Infra Client 15 we entirely rewrote how bootstrap works for Windows. I'm going to close this out at this point. If you're still seeing this sort of behavior in Chef Infra Client 15 please open it back up so we can dig in further.

**Closed by tas50** 2019-10-21 17:47 UTC
