### ISSUE TITLE
Eliminate formatter and logger distinctions, remove STDOUT magic, reduce user confusion

### ISSUE THREAD

**Issue by tas50** [chef/chef#2514] opened 2014-12-02 00:10 UTC
### Version:

11.16.4
### Environment:

Ubuntu 14.04.1
### Scenario:

Run chef client from command line with an error in the cookbook.
### Steps to Reproduce:

In my case set logging level to :info and log location to /var/log/chef.log in client.rb.  Then have an error in the cookbook that would manifest at compile time.  In my case I tried to notify a service that hadn't been defined.
### Expected Result:

The error should log to the logfile and to the console.
### Actual Result:

Chef client just failed with no error shown in the console.  The log contained the actual error.

End of output on the console:

```
Recipe: mysql::ruby
  * chef_gem[mysql] action install (up to date)  <-- last compile time resource right here
  Converging 310 resources

Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 6.368434115 seconds
```

Real error in the log file:

```
[2014-12-02T00:04:22+00:00] ERROR: Running exception handlers
[2014-12-02T00:04:22+00:00] ERROR: Exception handlers complete
[2014-12-02T00:04:22+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-12-02T00:04:22+00:00] ERROR: resource template[/etc/php5/mods-available/90-llgy.ini] is configured to notify resource service[php5-fpm] with action restart, but service[php5-fpm] cannot be found in the resource collection. template[/etc/php5/mods-available/90-llgy.ini] is defined in /var/chef/cache/cookbooks/land-web/recipes/default.rb:71:in `from_file'

[2014-12-02T00:04:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lamont-granquist** [comment] 2015-05-06 17:52
This isn't really a bug as titled.  The systems are operating as designed and the formatter output is only going to the console, while the log output is only at the WARN level so that INFO logging is suppressed.

The user fix is to bump the log level to INFO from AUTO.

The bigger fix for us would be something like CHEF-4974.  Do something like start sending formatter output to the log_location and undo the magical switching and make STDOUT not be special any more which would dramatically reduce confusion but would be a breaking change due to the expectation that log formats are APIs.

**Comment by runningman84** [comment] 2016-09-14 19:55
@lamont-granquist if this is a high prio bug in chef-core why is this bug still not fixed after more than a year?

**Comment by lamont-granquist** [comment] 2016-09-14 20:07
its a major breaking change, therefore blocked until Chef 13 -- that is why its marked accepted major.

there's also lots of high priority bugs that are not fixed.  the standard answer is that time resources are finite, while bugs seem to be infinite.  best way to make sure a bug gets fixed is to submit a well-formed PR that we can just mash merge on.

**Comment by lamont-granquist** [comment] 2016-09-14 20:14
the other obvious thing to do is to pay for a support contract -- issues that are raised against contracts have a good chunk of a whole team assigned to them and they get priority attention above bugs which are simply marked 'high' priority in issues but which have no sponsor.  which might suck from certain perspectives, but that's reality, which is that people who pay get their concerns escalated to the head of the queue.  although in this case it wouldn't help that much because the log file format is considered an API.  there's also the obvious workaround for this issue which is that if you're simply explict and use --force-formatter and --force-logger and override the tty-based guessing then users get what they want.  since this is a bug about flipping default feature flag behavior around it has to be blocked on a major release.

**Closed** 2017-04-06 16:17 UTC
Labels: Chef Core, Priority: Critical, Type: Enhancement
