### ISSUE TITLE
Kitchen converge failing in  chef 15.0.293

### ISSUE THREAD

**Issue by irfan1azher** [chef/chef#8546] opened 2019-05-15 05:29 UTC
-----> Starting Kitchen (v1.16.0)
[03:43:17][Step 1/1] -----> Creating <default-windows-2012r2>...
[03:43:18][Step 1/1]        Detected platform: windows version 2012rtm on x86_64. Instance Type: m4.large. Default username: administrator (default).
[03:43:18][Step 1/1]        If you are not using an account that qualifies under the AWS
[03:43:18][Step 1/1] free-tier, you may be charged to run these suites. The charge
[03:43:18][Step 1/1] should be minimal, but neither Test Kitchen nor its maintainers
[03:43:18][Step 1/1] are responsible for your incurred costs.
[03:43:18][Step 1/1] 
[03:43:19][Step 1/1]        Instance <i-0664da71820709a54> requested.
[03:43:19][Step 1/1]        Polling AWS for existence, attempt 0...
[03:43:19][Step 1/1]        Attempting to tag the instance, 0 retries
[03:43:19][Step 1/1]        EC2 instance <i-0664da71820709a54> created.
[03:43:19][Step 1/1]        Waited 0/1600s for instance <i-0664da71820709a54> volumes to be ready.
[03:43:21][Step 1/1]        Waited 0/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:26][Step 1/1]        Waited 5/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:32][Step 1/1]        Waited 10/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:38][Step 1/1]        Waited 15/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:44][Step 1/1]        Waited 20/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:50][Step 1/1]        Waited 25/1600s for instance <i-0664da71820709a54> to become ready.
[03:43:56][Step 1/1]        Waited 30/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:02][Step 1/1]        Waited 35/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:09][Step 1/1]        Waited 40/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:15][Step 1/1]        Waited 45/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:21][Step 1/1]        Waited 50/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:27][Step 1/1]        Waited 55/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:33][Step 1/1]        Waited 60/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:39][Step 1/1]        Waited 65/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:46][Step 1/1]        Waited 70/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:52][Step 1/1]        Waited 75/1600s for instance <i-0664da71820709a54> to become ready.
[03:44:58][Step 1/1]        Waited 80/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:04][Step 1/1]        Waited 85/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:10][Step 1/1]        Waited 90/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:16][Step 1/1]        Waited 95/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:23][Step 1/1]        Waited 100/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:29][Step 1/1]        Waited 105/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:35][Step 1/1]        Waited 110/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:41][Step 1/1]        Waited 115/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:47][Step 1/1]        Waited 120/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:53][Step 1/1]        Waited 125/1600s for instance <i-0664da71820709a54> to become ready.
[03:45:59][Step 1/1]        Waited 130/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:06][Step 1/1]        Waited 135/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:12][Step 1/1]        Waited 140/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:18][Step 1/1]        Waited 145/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:24][Step 1/1]        Waited 150/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:31][Step 1/1]        Waited 155/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:37][Step 1/1]        Waited 160/1600s for instance <i-0664da71820709a54> to become ready.
[03:46:38][Step 1/1]        Waited 0/1600s for instance <i-0664da71820709a54> to fetch windows admin password.
[03:46:38][Step 1/1]        Retrieved Windows password for instance <i-0664da71820709a54>.
[03:46:38][Step 1/1]        EC2 instance <i-0664da71820709a54> ready.
[03:47:35][Step 1/1]        [WinRM] Established
[03:47:35][Step 1/1]        
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]            Directory: C:\chef\ohai\hints
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]        Mode                LastWriteTime         Length Name                          
[03:47:39][Step 1/1]        ----                -------------         ------ ----                          
[03:47:39][Step 1/1]        -a----        5/15/2019   1:47 AM              0 ec2.json                      
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]        
[03:47:39][Step 1/1]        Finished creating <default-windows-2012r2> (4m22.25s).
[03:47:39][Step 1/1] -----> Converging <default-windows-2012r2>...
[03:47:39][Step 1/1]        Preparing files for transfer
[03:47:39][Step 1/1]        Preparing dna.json
[03:47:39][Step 1/1]        Resolving cookbook dependencies with Berkshelf 6.2.0...
[03:47:45][Step 1/1]        Removing non-cookbook files before transfer
[03:47:45][Step 1/1]        Preparing validation.pem
[03:47:45][Step 1/1]        Preparing client.rb
[03:47:49][Step 1/1] -----> Installing Chef Omnibus (install only if missing)
[03:47:51][Step 1/1]        Downloading package from https://packages.chef.io/files/stable/chef/15.0.293/windows/2016/chef-client-15.0.293-1-x64.msi
[03:47:57][Step 1/1]        Download complete.
[03:48:03][Step 1/1]        Successfully verified C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-15.0.293-1-x64.msi
[03:48:03][Step 1/1]        Installing Chef Omnibus package C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-15.0.293-1-x64.msi
[03:50:58][Step 1/1]        Installation complete
[03:51:05][Step 1/1]        Transferring files to <default-windows-2012r2>
[03:54:29][Step 1/1] $$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:24:in `join': no implicit conversion of nil into String (TypeError)
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:24:in `default_license_locations'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:10:in `initialize'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:25:in `new'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:25:in `initialize'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:95:in `new'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:95:in `check_and_persist!'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application.rb:254:in `check_license_acceptance'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application.rb:68:in `run'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.0.293/bin/chef-client:25:in `<top (required)>'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/bin/chef-client:167:in `load'
[03:54:29][Step 1/1] $$$$$$ 	from C:/opscode/chef/bin/chef-client:167:in `<main>'
[03:54:29][Step 1/1] >>>>>> ------Exception-------
[03:54:29][Step 1/1] >>>>>> Class: Kitchen::ActionFailed
[03:54:29][Step 1/1] >>>>>> Message: 1 actions failed.
[03:54:29][Step 1/1] >>>>>>     Converge failed on instance <default-windows-2012r2>.  Please see .kitchen/logs/default-windows-2012r2.log for more details
[03:54:29][Step 1/1] >>>>>> ----------------------
[03:54:29][Step 1/1] >>>>>> Please see .kitchen/logs/kitchen.log for more details
[03:54:29][Step 1/1] >>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by lamont-granquist** [comment] 2019-05-28 16:56
This is a test-kitchen and/or license-acceptance bug and may have been fixed by now since that was all in flux.  You will definitely need to be on latest test-kitchen to use chef 15, and that version will only be in the chef-dk 4 version which dropped literally earlier today, and the backport to chef-dk 3 has not happened yet.  But this is not a bug in this repository, and not the appropriate place to track those issues.

**Closed by lamont-granquist** 2019-05-28 16:56 UTC
Labels: Status: Untriaged
