### ISSUE TITLE
`knife node from file` should complain when your file doesn't have a 'name' attribute

### ISSUE THREAD

**Issue by spiffytech** [chef/chef#1721] opened 2014-07-30 20:05 UTC
With `knife node from file $FILE`, if the JSON file does not have a 'name' attribute*, knife explodes with "405 Method Not Allowed", which is very confusing and unhelpful.

Please have knife give the user an appropriate message if the lack of a name attribute causes node creation to fail.
- I'm importing nodes from my Chef Solo setup into Chef Server, and lack of name attributes never caused me any problems with Chef Solo, so I never put them in.

**Comment by kernelsmith** [comment] 2016-02-04 22:15
+1
I will also give a shot at creating a PR, but time is short.  Any pointers as to which source file to drill into?

**Comment by kernelsmith** [comment] 2016-02-04 22:34
holy long line batman: https://github.com/chef/chef/blob/master/lib/chef/chef_fs/file_system/chef_server/organization_members_entry.rb#L46

**Comment by kernelsmith** [comment] 2016-02-04 22:47
a guard could be placed in knife/chef

```
if !(o["name"] || o["clientname"])
  # reject w/a nice message
else
  # do the client api stuff
end
```
but it could also be fixed on the server end no?  I feel like it's better to fix it on chef-server, somewhere in here possibly? https://github.com/chef/chef-server/blob/master/src/chef-mover/apps/oc_chef_wm/src/chef_wm_named_data.erl#L85

I'm not an erlang master, but very interested in getting better, but don't want to waste my time, so would love some input
cc @sersut @smurawski

**Comment by gp2015** [comment] 2017-07-18 14:52
I'm just getting started with Chef and ran into this issue. I hope this is allowed:

For anyone else stumbling across this, I resolved it by adding

`override_attributes({
  
})`

to the bottom of my role. Not sure if this is bad practice, though!

**Comment by stevendanna** [comment] 2017-07-19 23:34
Responding to the old comment about a potential server-side fix.  I don't think that the problem is server-side in this case.

For example, let's take the `knife node from file` case in the original ticket.  The client-side code creates a Chef::Node object and then calls save on it:

https://github.com/chef/chef/blob/master/lib/chef/knife/node_from_file.rb#L41

The save method, is going to try

```
          chef_server_rest.put("nodes/#{name}", data_for_save)
```
(https://github.com/chef/chef/blob/master/lib/chef/node.rb#L596)

When a name is present this will be a PUT to `/organizations/nodes/NODENAME`.  However, if if the name is nil, that PUT will be to `/organizations/nodes/` which indeed is not allowed.  The correct fix is to validate that we have the information required to construct a valid minimally-valid request.

**Closed** 2019-08-07 19:25 UTC
Labels: Component: Chef Core
