### ISSUE TITLE
zypper repo does not import the provided gpg key on refresh

### ISSUE THREAD

**Issue by c-hoeger** [chef/chef#6374] opened 2017-09-01 11:33 UTC
## Description

defining a repository like

    zypper_repo 'OBS repo' do
      repo_name 'OBS'
      uri 'http://download.opensuse.org/repositories/OBS:/Server:/2.8/openSUSE_42.2/'
      key 'http://download.opensuse.org/repositories/OBS:/Server:/2.8/openSUSE_42.2/repodata/repomd.xml.key'
    end

fails with

        ================================================================================
        Error executing action `run` on resource 'execute[zypper refresh OBS]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '4'
        ---- Begin output of zypper refresh OBS ----
        STDOUT: Retrieving repository 'OBS' metadata [.

        New repository or package signing key received:

          Repository:       OBS
          Key Name:         OBS OBS Project <OBS@build.opensuse.org>
          Key Fingerprint:  660FD3F9 F16602A3 722ABF6D E8420AB8 C5C219E7
          Key Created:      Thu 15 Jun 2017 04:02:46 PM CEST
          Key Expires:      Sat 24 Aug 2019 04:02:46 PM CEST
          Rpm Name:         gpg-pubkey-c5c219e7-59429386

        Do you want to reject the key, trust temporarily, or trust always? [r/t/a/? shows all options] (r): error]
        STDERR: Cannot read input: bad stream or EOF.
        If you run zypper without a terminal, use '--non-interactive' global
        option to make zypper use default answers to prompts.
        Repository 'OBS' is invalid.
        [OBS|http://download.opensuse.org/repositories/OBS:/Server:/2.8/openSUSE_42.2/] Valid metadata not found at specified URL
        Please check if the URIs defined for this repository are pointing to a valid repository.
        Skipping repository 'OBS' because of the above error.
        Could not refresh the repositories because of errors.
        ---- End output of zypper refresh OBS ----
        Ran zypper refresh OBS returned 4

        Resource Declaration:
        ---------------------
        # In /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.3.42/lib/chef/provider/zypper_repository.rb

         60:         declare_resource(:execute, "zypper refresh #{escaped_repo_name}") do
         61:           only_if "zypper lr #{escaped_repo_name}"
         62:         end
         63:       end

When a gpg key has been specified, it should be imported using:

zypper --non-interactive --gpg-auto-import-keys refresh

## Chef Version

chef-13.3.42-1.sles12

## Platform Version

openSUSE 42.2

## Replication Case

See initial description

## Client Output

See above

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

**Comment by kleini** [comment] 2017-09-01 11:35
I am stumbling over the same problem but with a different repository:

   zypper_repo "perl modules (#{suse_version})" do
     uri "http://download.opensuse.org/repositories/devel:/languages:/perl/#{suse_version}/"
     autorefresh true
     action :add
     key "http://download.opensuse.org/repositories/devel:/languages:/perl/#{suse_version}/repodata/repomd.xml.key"
   end

**Comment by tas50** [comment] 2017-09-01 16:49
I'll be looking at this one today. We have a fix that went into the upcoming 13.4 release, but I'm still seeing the issue in some places.

https://github.com/chef/chef/pull/6348

**Comment by kleini** [comment] 2017-09-02 09:44
Why does Chef integrate resources from a public cookbook? And furthermore in a broken way? And why is it not possible to use the cookbook resource any more and Chef replaces the cookbook resource without asking?
I can fork the public cookbook and apply fixes there easily. This can fix the broken Chef deployment easily. Now all of our deployments are broken when using SuSE based system. And we have to wait until Chef gets this s... fixed.
How is it possible to deactive in Chef the replacement of the zypper cookbook zypper_repo resource with the broken Chef zypper_repository resource?

**Comment by cheeseplus** [comment] 2017-09-08 16:16
It's a normal pattern for things that don't exist in core Chef to start life off as a cookbook and if utility is high we move these into core, a great example being the `windows` cookbook. It's entirely possible to use the former cookbook resource but not with the latest version of Chef. As for without asking, I'm not sure that's a reasonable expectation in this context as we're trying to improve things for users by moving this into core.
This change is also relatively recent and bugs happen. We advocate our users pin both the version of their chef-client and the cookbooks used in their environments to prevent surprises - this isn't unique to chef either as lots of software you generally wouldn't want to just upgrade without any testing/validation as the end user. Related you can drop the version of chef-client to something below 13.3.42 and then use the cookbook as you were. We have already made a pass at fixing this behaviour as it's a bug.
I believe this answers all your questions. 
The reality is that bugs happen and we, like everyone else, try to prevent them but releasing perfect software every single time is not exactly that easy. I understand your frustration here but this is also why the above advice about controlling versions of software in play in your environment or at the very least validating them in a test environment is something everyone should be doing generally. On top of that this is open source software with an incredibly large surface area and broad platform support which makes catching all the bugs - especially for platforms that are less popular/widely used - difficult. If you'd like these bugs fixed faster there is an easy way to do so: become a customer and you have a direct line to support who can escalate an issue to increase the priority.

**Comment by kleini** [comment] 2017-09-08 18:03
Thanks for your explanation and I understand your motivation.
Still it is understandable how you where able to copy in a wrong way from the zypper cookbook.

**Comment by tas50** [comment] 2017-09-08 19:16
The zypper cookbook and the chef-client zypper resource take very different approaches to adding a zypper repository. The zypper cookbook relied on shelling out to add the repositories, which gave it a pretty limited subset of the total configuration options. The zypper resource instead templates out the config file which gives access to all the configuration options within that config file. The problem is that after templating the config file you must do a zypper refresh and there's some issues with silently accepting the keys when their present within the zypper CLI. The first fix has been merged into master and is available in the current chef-client builds. I'm looking into a better solution that should solve it for everyone which would ideally land in 13.4.  

The goal here was to give a simpler and more robust experience for SLES/openSUSE users on Chef, where a 3rd party cookbook isn't necessary for simple tasks like managing repositories. Obviously this bug made that experience worse in the 13.3 release, but I think we can work it out and provide a solid SLES experience for users.

Give a current build a try. It may be fixed for you already:

https://downloads.chef.io/chef/current

**Comment by cheeseplus** [comment] 2017-09-08 20:04
It's not straight copying, core chef code is very different from resources so it's easy for these things to manifest.

**Comment by tas50** [comment] 2018-03-17 05:25
I did a bunch of rework on this resource and those changes have been released for a while now. I'm going to close this out at this point. Feel free to open it back up if you're still seeing the issue in a current Chef 13 release.

**Closed by tas50** 2018-03-17 05:25 UTC
Labels: Type: Bug

**Comment by kleini** [comment] 2018-03-17 11:05
Will have a look, if we can remove now our workarounds.
