### ISSUE TITLE
git resource Errno::EIO on windows

### ISSUE THREAD

**Issue by blueo** [chef/chef#1622] opened 2014-07-09 14:49 UTC
### Version:
chef client 11.12.8

### Environment: 
Windows 7 x86 and x64, git 1.9.2.msysgit.0.

### Scenario:
I'm trying to use chef to check out a git repo to a windows client node.

### Steps to Reproduce:
I've got the following resource definition in one of my recipes:
```
git "C:\\pathtocheckout" do
    repo "https://gitserver/repo.git"
    action [ :checkout, :sync]
end
```
and including this in a recipe with nothing else will cause the error below.

### Actual Result:
I get the following error:
`Errno::EIO: git[C:\pathtocheckout] (cookbook_name::test line 21) had an error: Errno::EIO: Input/output error - CreateProcessW`

So I've manage to work around this by changing Chef::Provider::Git to include `.exe` in its calls to git eg `git ls-remote` becomes `git.exe ls-remote`. This is obviously not a great solution but I'm not sure how to go about fixing or reporting this...

**Comment by smurawski** [comment] 2015-03-11 17:36
There may be an alias or something similar to the local setup that may conflict.  We should append the .exe though and be more explicit.

**Comment by docwhat** [comment] 2015-09-08 15:50
I think the problem is actually a bug in Ruby...

According to the documentation for [CreateProcessW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx) the contents of `lpCommandLine` may be modified for `CreateProcessW()`:

> The Unicode version of this function, `CreateProcessW`, can modify the contents of this string. Therefore, this parameter cannot be a pointer to read-only memory (such as a const variable or a literal string). If this parameter is a constant string, the function may cause an access violation.

The ruby code uses the passed in cmdline verbatim as a `const WCHAR *cmd`.

**Comment by docwhat** [comment] 2015-09-08 16:09
I created a simple patch and filed a bug with Ruby: https://bugs.ruby-lang.org/issues/11515

**Comment by docwhat** [comment] 2015-09-08 16:14
@smurawski I suspect you should remove the `easy` tag... :grinning:

**Comment by docwhat** [comment] 2015-09-08 16:16
Hmm... this may not be the same thing I'm seeing... My traceback:

```
Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* SystemCallError occurred in chef run: powershell_script[RDP: enable NLA] (mycorp-role-windows::_rdp line 30) had an error: SystemCallError: powershell_script[Guard resource] (dynamically defined) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW
* SystemCallError occurred in delayed notification: windows_task[\chef-client] (chef-client::task line 32) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW

C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:346:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout/windows.rb:86:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:55:in `shell_out!'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:79:in `block in validate_script_syntax!'
C:/opscode/chef/embedded/lib/ruby/2.0.0/tempfile.rb:324:in `open'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:64:in `validate_script_syntax!'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:33:in `action_run'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:72:in `block in evaluate_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:72:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:72:in `evaluate_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:60:in `evaluate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:99:in `evaluate_command'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:95:in `evaluate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:88:in `continue?'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:1259:in `block in should_skip?'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:1258:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:1258:in `find'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:1258:in `should_skip?'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:583:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:67:in `load'
C:/opscode/chef/bin/chef-client:67:in `<main>'
```

I can create a separate issue if desired.

**Comment by tas50** [comment] 2016-08-01 05:05
@blueo It appears that we fixed this problem with an update to our mixlib-shellout library here https://github.com/chef/mixlib-shellout/pull/107 That updated version was shipped in a Chef 12 release. I'm going to close this bug out and this point, but feel free to open it back up if you still encounter the problem with a new Chef 12 release.

**Closed by tas50** 2016-08-01 05:05 UTC
Labels: Bug, Easy, Windows
