### ISSUE TITLE
Chef Client + Server 2008 R2 + PowerShell 5 + PowerShell DSC => Error on 2008 R2, Works fine on 2012 R2.

### ISSUE THREAD

**Issue by DarwinJS** [chef/chef#4175] opened 2015-11-16 19:46 UTC
A recipe receives the below error (at bottom) on Server 2008 R2 w/ PowerShell 5.0.10514.6 (dot net 4.5.2) works fine on Server 2012 R2 w/ PowerShell (dot net 4.5.2).

This error appears where I have previously seen Chef display an error that I must have PowerShell 5 to use PowerShell DSC under Chef.

The above two items lead me to believe that when Chef retrieves the PowerShell version number under *Server 2008 R2 + PowerShell 5.0.10514.6* ONLY - it also pulls in a bunch of spaces and the text "PSVersion".  (There are 13 spaces between "5.0.10514.6" and "PSVersion" - but the markdown interpretter on github collapses them.)

During researching this on the internet, I have seen similar ruby error reports when junk get's into the version number Ruby is trying to compare.

[2015-11-16T19:25:29+00:00] INFO: Processing powershell_script[Guard resource] action run (dynamically defined)
[2015-11-16T19:25:29+00:00] INFO: Processing dsc_resource[addNetFrameworkFeature] action run (cookbookname::SQL-addFeatures line 13)
[2015-11-16T19:25:29+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-11-16T19:25:29+00:00] ERROR: Running exception handlers
[2015-11-16T19:25:29+00:00] ERROR: Exception handlers complete
[2015-11-16T19:25:29+00:00] INFO: Sending resource update report (run-id: a25d52f6-dbb6-4fda-8b01-cf37c12d4b07)
[2015-11-16T19:25:30+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
**[2015-11-16T19:25:30+00:00] FATAL: ArgumentError: dsc_resource[addNetFrameworkFeature] (cookbookname::SQL-addFeatures line 13) had an error: ArgumentError: Malformed version number string 5.0.10514.6             PSVersion**
[2015-11-16T19:25:40+00:00] INFO: Child process exited (pid: 1324)
[2015-11-16T19:25:41+00:00] INFO: Next chef-client run will happen in 1800.6470914809777 seconds

**Comment by DarwinJS** [comment] 2015-11-17 14:11
I dug this down to https://raw.githubusercontent.com/chef/ohai/0e6456ca3e56ae4e84feabff87f3c538bf38964a/lib/ohai/plugins/powershell.rb which appears to use the output of $PSVersiontable to parse PowerShell's version number.

However, the output of $psversiontable on both the 2008 R2 and 2012 R2 systems are identical.

Maybe Ruby somehow parses this output differently on the two OS variations on line 40 ?

D.

**Comment by thommay** [comment] 2015-11-25 18:29
@DarwinJS can you include the output of $PSVersionTable from both your 2k8r2 and 2k12r2 systems?

**Comment by jaym** [comment] 2015-11-25 18:55
Based on the error, I suspect the PSVersion value is `'5.0.10514.6 PSVersion'`
Not sure how that would happen

**Comment by SteveLowe** [comment] 2015-12-09 15:18
I have run into this problem too and believe it is caused by the executionpolicy

When launching 32-bit powershell, I get this:
```
C:\Windows\SysWOW64>powershell.exe -NoLogo -NonInteractive -NoProfile -command $
PSVersionTable
The following error occurred while loading the extended type data file: Microsof
t.PowerShell.Core, C:\Windows\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml: Th
e file was skipped because of the following validation exception: File C:\Window
s\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml cannot be loaded because runnin
g scripts is disabled on this system. For more information, see about_Execution_
Policies at http://go.microsoft.com/fwlink/?LinkID=135170..
Errors occurred while loading the format data file: Microsoft.PowerShell.Core, ,
 C:\Windows\SysWOW64\WindowsPowerShell\v1.0\HelpV3.format.ps1xml: The file was s
kipped because of the following validation exception: File C:\Windows\SysWOW64\W
indowsPowerShell\v1.0\HelpV3.format.ps1xml cannot be loaded because running scri
pts is disabled on this system. For more information, see about_Execution_Polici
es at http://go.microsoft.com/fwlink/?LinkID=135170..

Key                       Value                   Name
---                       -----                   ----
PSVersion                 5.0.10514.6             PSVersion
WSManStackVersion         3.0                     WSManStackVersion
SerializationVersion      1.1.0.1                 SerializationVersion
CLRVersion                4.0.30319.34209         CLRVersion
BuildVersion              10.0.10514.6            BuildVersion
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0...} PSCompatibleVersions
PSRemotingProtocolVersion 2.3                     PSRemotingProtocolVersion
```

Adding `-ExecutionPolicy Bypass` resolves this for me

```
C:\Windows\SysWOW64>powershell.exe -NoLogo -NonInteractive -executionpolicy bypa
ss -NoProfile -command $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by DarwinJS** [comment] 2015-12-09 15:42
SteveLowe,
Thanks for that observation.

I am hoping that when Chef makes this call it always sets the execution policy as you suggest (but hopefully only to remotesigned to avoid code injection).  Could someone at Chef please comment?

For anyone reading this thread the execution policy for 32 and 64 bit powershell execution is set in a redirected registry key - so you must set the desired execution policy in both 32-bit and 64-bit powershell.exe

D.

**Comment by smurawski** [comment] 2015-12-14 15:28
@DarwinJS @SteveLowe  I cannot replicate on Server 2008 R2 with WMF 5 Prod Preview and Chef Client 12.5.1.

Depending on the chef-client version, there was a hiccup where we launched the x86 powershell rather than the x64 powershell for dsc_script and dsc_resource, but that has since been fixed.

The other thing to consider is if there is a GPO enforcing executionpolicy.  If that is the case, using -executionpolicy Bypass will not bypass the GPO settings.

**Comment by DarwinJS** [comment] 2015-12-15 18:40
I experienced the problem on 12.5.1 as well.  

There are no GPOs enforcing an executionpolicy.

This is indeed erroring on an attempt to use DSC.

Is your test case a bare Server 2008 R2 Machine with only PowerShell 5 added?

**Comment by smurawski** [comment] 2015-12-15 20:22
@DarwinJS Yeah, stock 2008 R2 with WMF 5.  Do you have a recipe/cookbook that can replicate?  The regression I mentioned was across all versions of windows server, and yes, it was tested on Server 2008 R2.  

I'm happy to dig deeper, but I can't replicate it.

**Comment by SteveLowe** [comment] 2015-12-18 14:01
The problem I am seeing on Server 2008 R2 is that some of the 32-bit ps1xml files been signed by an out of date cert.
e.g.
```
PS > Get-AuthenticodeSignature C:\Windows\SysWOW64\WindowsPowerShell\v1.0\PowerShellCore.format.ps1xml | fl *


SignerCertificate      : [Subject]
                           CN=Microsoft Corporation, OU=MOPR, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Code Signing PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           61062781000000000008

                         [Not Before]
                           22/10/2008 22:24:55

                         [Not After]
                           22/01/2010 21:34:55

                         [Thumbprint]
                           9E95C625D81B2BA9C72FD70275C3699613AF61E3

TimeStamperCertificate : [Subject]
                           CN=Microsoft Time-Stamp Service, OU=nCipher DSE ESN:7A82-688A-9F92, OU=MOPR, O=Microsoft
                         Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Timestamping PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           6106942D000000000009

                         [Not Before]
                           25/07/2008 20:02:17

                         [Not After]
                           25/07/2013 20:12:17

                         [Thumbprint]
                           05FECB745F7F3B1A0E262A73435CCB7EAAED8B37

Status                 : Valid
StatusMessage          : Signature verified.
Path                   : C:\Windows\SysWOW64\WindowsPowerShell\v1.0\PowerShellCore.format.ps1xml
SignatureType          : Authenticode
IsOSBinary             : False
```

This is changing the format of $PSVersionTable (as seen above), which breaks when chef tries to convert it to a version object.

Chef client is not failing with the version error consistently (most of the time it runs successfully), which I cannot explain.

I have PSVersion 5.0.10514.6, I have this installed on multiple 2008 R2 machines, including a fresh install. They all have the signature out of date issue in SysWow64.
I also don't have an executionpolicy set in the registry.

Running procmon during a chef run shows that ohai is using 32-bit powershell for two calls:
```
powershell.exe "Get-WmiObject -Class Win32_BIOS"
powershell.exe -NoLogo -NonInteractive -NoProfile -command $PSVersionTable
```
I'm not sure why powershell.exe is resolving to the 32-bit version for these two, but not later calls.

I have also see ohai hang on the Win32_BIOS call, I suspect this is because the -NonInteractive flag is missing and it is prompting to allow the ps1xml files to run.

One possible fix for this would be to make sure ohai always uses the sysnative version of powershell? (is it possible to use Chef::Util::Powershell::Cmdlet?)

**Comment by DarwinJS** [comment] 2015-12-18 15:05
PowerShell 5 just went RTM on the 16th - so maybe retest with it? (http://blogs.msdn.com/b/powershell/archive/2015/12/16/windows-management-framework-wmf-5-0-rtm-is-now-available.aspx)

BEWARE - the WMF 5 installer now *absolutely* requires WMF 4 to be installed first.

For the previous version (Production preview) the need for WMF 4 was noted in the release notes, but not enforced in the installer.

And thinking about it now - I realize that in my configuration I did NOT install WMF 4 on 2008 R2 before WMF 5 because the PowerShell team was saying they thought they'd be able to eliminate that dependency - might be the source of my problems ?

**Comment by SteveLowe** [comment] 2015-12-18 15:50
>PowerShell 5 just went RTM on the 16th 

wow - I managed to miss this.
I will re-test with the RTM version.

**Comment by smurawski** [comment] 2015-12-18 16:03
@SteveLowe Regarding the 32 bit powershell calls in ohai, that should be resolved when we start shipping the 64 bit chef-client packages (coming really soon now :) ).  The ruby runtime currently is 32 bit, so by default shell_out uses 32 bit exes (including powershell.exe).  In chef-client, we do some additional work to get around that and use the redirected 64 bit version.

The real solution to the 32/64 is us shipping with a 64 bit ruby.

In regards to the odd powershell signatures - I'd try against RTM and do follow the upgrade process.

@DarwinJS I don't think I did the wmf4 first either on my test images, so there may be something else at play here.

Thanks for the updates both of you and please keep me updated.  I'll also try to replicate with the latest bits.

**Comment by DarwinJS** [comment] 2015-12-18 17:03
Steve,
Shifting the bitness of your service will create a lot of cascaded challenges for your customers - be sure to advertise LOUDLY and to not force them to move on the first release that supports it.  For instance on an upgrade of the service - keep the existing bitnss.

The reason is that since bitness of OS called items is inherited, they will be in for some rude suprises.  Let's say someone used regedit.exe to merge reg files with 3000 entries (didn't want to turn those into recipes) and they are going to HKLM\Software.  If they didn't specifically path the bitness of regedit to 32-bit and you switch the service bitness - those keys will all of a sudden appear in the 64-bit software registry.

I literally wrote the book on 32/64 bit challenges ;) http://www.amazon.com/Deploying-Supporting-Applications-64-bit-Windows-ebook/dp/B0098P9Z22/

D.

**Comment by SteveLowe** [comment] 2015-12-18 17:08
RTM fixes the 32-bit signature issues, so i'm confident this issue is resolved. (Although I've not been able to replicate it for a while so not 100%)
(Tested on 2008 R2, upgraded from WMF 4 to WMF 5 RTM)

ohai is now returning
```
  "languages": {
    "powershell": {
      "version": "5.0.10586.51",
      "ws_man_stack_version": "3.0",
      "serialization_version": "1.1.0.1",
      "clr_version": "4.0.30319.34209",
      "build_version": "10.0.10586.51",
      "compatible_versions": [
        "1.0",
        "2.0",
        "3.0",
        "4.0..."
      ],
      "remoting_protocol_version": "2.3"
    },
```

BTW - don't install WMF5 RTM over the top of the PP. 
The documentation says you can https://msdn.microsoft.com/en-us/powershell/wmf/releasenotes
However it broke all the DSC commands on both test systems I upgraded.

**Comment by smurawski** [comment] 2015-12-18 18:42
:+1: Thanks @SteveLowe 

@DarwinJS I'm going to close this out as issues with the WMF 5 Preview installer.

**Closed by smurawski** 2015-12-18 18:42 UTC
Labels: Medium Priority, Windows
