### ISSUE TITLE
Property in custom resource not picking up overriden default value

### ISSUE THREAD

**Issue by papa-gene** [chef/chef#6989] opened 2018-03-15 17:43 UTC
## Description
Created a custom resource in my cookbook. Gave this resource a property with a default value (an attribute). If I override this attribute in my recipe, the new value is not picked up by the custom resource.

Not entirely sure if this is expected or not, but if it is, I would like to understand the why :)

## Chef Version
Chef Client, version 13.8.5

## Platform Version
Testing on a Windows 2012r2 node, via kitchen.

## Replication Case

Failing example:

> attributes/default.rb
```
default['my_cookbook']['password'] = 'bad_pass'
```

> recipes/recipe_not_working.rb
```
# attempted both node.default and node.override, same result
node.override['my_cookbook']['password'] = 'super_secure_pass'

# Lets see what the attribute looks like...
Chef::Log.warn("in recipe: #{node['my_cookbook']['password']}")

# Call the custom resource, make it use the default value for its property
custom_resource 'alice' do
  action :run
end

```

> resources/custom_resource.rb

```
resource_name :custom_resource

property :username, String, name_property: true
property :password, String, default: node['my_cookbook']['password']

default_action :run

action :run do
  # Lets see what values look like in here...
  Chef::Log.warn("attribute: #{node['my_cookbook']['password']}")
  Chef::Log.warn("property: #{new_resource.password}")
end

```
------------------------
If, however, I explicitly set the property, the value gets passed correctly:
> recipes/recipe_works.rb
```
node.override['my_cookbook']['password'] = 'super_secure_pass'

custom_resource 'alice' do
  # this works as expected
  password node['my_cookbook']['password']
  action :run
end

```

## Client Output
Output of testing `recipe_not_working.rb`:

```
[2018-03-15T16:45:17+00:00] WARN: in recipe: super_secure_pass
[2018-03-15T16:45:17+00:00] WARN: attribute: super_secure_pass
[2018-03-15T16:45:17+00:00] WARN: property: bad_pass

```

## Stacktrace
No stacktrace as no error was thrown.

**Comment by lamont-granquist** [comment] 2018-03-15 18:26
i almost wonder if we shouldn't require that default always takes a block as an argument, so this just becomes `default: { node['my_cookbook']['password'] }` and then we'd have to use `default: { "1" }` which would be mildly silly since that didn't "need" to be lazied, but we'd force everyone down a road which would avoid this issue.  but `lazy {}` is the chef-language way of fixing this issue, and applies also to lazying values in resources to deal with compile-converge issues, so its a common concept.

**Comment by papa-gene** [comment] 2018-03-15 20:24
@lamont-granquist your explanation totally makes sense. What I find interesting is that the resource is still able to pull the "starting" value of the attribute from the attributes file. I guess this would mean attributes files are parsed first?

Regardless, setting this to lazy is a good workaround. Should this maybe be added to the documentation? It would make sense to set these default properties as lazy by default when writing a custom resource, since one can never know where the user will declare his attributes...

At this point, feel free to close this issue i

**Comment by lamont-granquist** [comment] 2018-03-16 00:13
I'm sure its in the documentation somewhere.

The best thing that you could do would be to open an issue or PR against https://github.com/chef/chef-web-docs to make an edit where you went looking for the documentation to make it clearer, or to add an example there.

The problem is that if I go looking for it, I know what I'm doing and I'm probably going to go directly to the documentation that we already have.  You probably wound up on some other page, or you were confused by verbiage or its just buried at the end of a long document or something, and you can give the best feedback on how to better highlight the information.  You're actually much more of an expert in how relative newbies to chef find our documentation than I am...

But yup one way or the other its just a doc thing, so closing...

**Closed by lamont-granquist** 2018-03-16 00:13 UTC
