### ISSUE TITLE
Add the ability to use include_profile in a Policyfile + InSpec

### ISSUE THREAD

**Issue by kmf** [chef/chef#12138] opened 2021-10-05 07:11 UTC
### Describe the Enhancement:
It would awesome to have an `include_profile` in a Policyfile

```
include_profile 'cis-mysql', github: 'cis-benchmarks/cis-mysql', branch: 'main'
include_profile 'cis-docker', git: 'https://gitlab.com/cis-benchmarks/cis-docker.git', tag: 'v1.1.0'
```

### Describe the Need:
- Build an Immutable Reusable Artifact with external InSpec Profiles
- Give you the ability to reuse InSpec Profiles in other Policyfiles, increases the ability to scale

**Comment by tas50** [comment] 2022-02-19 00:29
@kmf this is a dupe of a few other issues we had to tackle this and we're tracking it internally in https://chefio.atlassian.net/browse/INFC-79

**Closed by tas50** 2022-02-19 00:29 UTC
Labels: Status: Untriaged
