### ISSUE TITLE
archive_file failures in Infra Client 17.7 (libarchive issue)

### ISSUE THREAD

**Issue by knightorc** [chef/chef#12228] opened 2021-10-28 16:05 UTC
```
       [2021-10-28T15:55:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2021-10-28T15:55:38+00:00] FATAL: ---------------------------------------------------------------------------------------
       [2021-10-28T15:55:38+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
       [2021-10-28T15:55:38+00:00] FATAL: ---------------------------------------------------------------------------------------
       [2021-10-28T15:55:38+00:00] FATAL: LoadError: Could not open library 'libarchive.so.13': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so.13).
       Could not open library 'libarchive.13': libarchive.13: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.13.so': libarchive.13.so: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive-13': libarchive-13: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive-13.so': libarchive-13.so: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.so': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so).
       Could not open library 'libarchive': libarchive: cannot open shared object file: No such file or directory.
       Could not open library 'archive': archive: cannot open shared object file: No such file or directory
```

Stacktrace

```
cat /tmp/kitchen/cache/chef-stacktrace.out
Generated at 2021-10-28 15:55:38 +0000
LoadError: Could not open library 'libarchive.so.13': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so.13).
Could not open library 'libarchive.13': libarchive.13: cannot open shared object file: No such file or directory.
Could not open library 'libarchive.13.so': libarchive.13.so: cannot open shared object file: No such file or directory.
Could not open library 'libarchive-13': libarchive-13: cannot open shared object file: No such file or directory.
Could not open library 'libarchive-13.so': libarchive-13.so: cannot open shared object file: No such file or directory.
Could not open library 'libarchive.so': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so).
Could not open library 'libarchive': libarchive: cannot open shared object file: No such file or directory.
Could not open library 'archive': archive: cannot open shared object file: No such file or directory
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-libarchive-1.1.3/lib/ffi-libarchive/archive.rb:11:in `<module:C>'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-libarchive-1.1.3/lib/ffi-libarchive/archive.rb:4:in `<module:Archive>'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-libarchive-1.1.3/lib/ffi-libarchive/archive.rb:3:in `<top (required)>'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ffi-libarchive-1.1.3/lib/ffi-libarchive.rb:56:in `<top (required)>'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource/archive_file.rb:135:in `require_libarchive'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource/archive_file.rb:95:in `block in <class:ArchiveFile>'
(eval):2:in `block in action_extract'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_extract'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection.rb:64:in `insert'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/dsl/declare_resource.rb:267:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/dsl/resources.rb:36:in `archive_file'
/tmp/kitchen/cache/cookbooks/alida_consul/resources/consul_installation_binary.rb:33:in `block in class_from_file'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/client.rb:686:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/client.rb:681:in `catch'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/client.rb:681:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/client.rb:705:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/client.rb:285:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/application/base.rb:352:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.7.22/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.7.22/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:160:in `load'
/opt/chef/bin/chef-client:160:in `<main>'
```

**Comment by knightorc** [comment] 2021-10-30 00:04
@lamont-granquist I'm closing this.

 It appears this is a user_data script that emulates our terraform work flow.
It was our expectation that test-kitchen would not do anything until user_data was complete.

I will re-open this again if it turns out not to be our user_data.

**Comment by knightorc** [comment] 2021-10-30 00:05
Our userdata, moves `/opt` to a second disk.  It is a moving of `/opt` that I believe caused this issue.

**Comment by knightorc** [comment] 2021-10-31 19:47
@lamont-granquist @tas50

I've eliminated all of our user_data options and stripped down our run_list.

This is repeatable on AmazonLinux2 (ami-02bcf4285d4895d33 in us-west-2) and CentOS 7.9 (ami-0686851c4e7b1a8e1 in us-west-2) with any chef-client v17.7.x build upto v17.7.29 using the following test recipe.

```
cli_version  = '2.3.2'
cli_checksum = '4a32a5f6e072c7cbdc0d9cd67171061d37fa3c8bd44c4f8fc945309581094a2c'
cli_filename = "awscli-exe-linux-x86_64-#{cli_version}.zip"
cli_fileurl  = "https://awscli.amazonaws.com/#{cli_filename}"

dst_filelocation = "/usr/src/#{cli_filename}"
dst_srclocation  = "/usr/src/awscli-#{cli_version}"

remote_file dst_filelocation do
  action :create
  source cli_fileurl
  checksum cli_checksum
end

archive_file dst_filelocation do
  destination dst_srclocation
  notifies :run, "execute[AWSCLI v2 install/upgrade #{cli_version}]", :immediately
end

execute "AWSCLI v2 install/upgrade #{cli_version}" do
  action :nothing
  cwd "#{dst_srclocation}/aws"
  command './install -u'
end
```

**Comment by lamont-granquist** [comment] 2021-11-02 05:30
If you move /opt/chef to somewhere else that'll definitely break things.  If you just mount /opt on another disk or something so that the path is still there (even if it needs to traverse a symlink) that should work fine.

**Comment by knightorc** [comment] 2021-11-02 15:34
@lamont-granquist I've eliminated our `/opt` relocation.
The sample recipe repeatably reproduces the error in test kitchen with the latest AmazonLinux2 and CentOS 7.x ami using any build of 17.7.x
The sample recipe works with any chef build 17.6.x or lower

**Comment by knightorc** [comment] 2021-11-02 18:14
@lamont-granquist @tas50 

This looks very related to this issue: PR: https://github.com/chef/omnibus-software/pull/1460

```
This ensures that at run-time, supporting libs (lzma, bzip, etc)
are loaded from the correct path embedded path on all platforms. Specifically
resolves load failures on aix, amazon linux and rhel7.

The same change breaks mac_os_x so is excluded for that platform.
```

**Comment by knightorc** [comment] 2021-11-12 18:13
@lamont-granquist @tas50  Sorry to inform, problem persists with 17.8.x builds too.Just tried v17.8.2. The last version to work with AmazonLinux2 and CentOS 7.x is 17.6.18.

**Comment by tas50** [comment] 2021-11-12 19:42
We have a potential fix for this with https://github.com/chef/omnibus-software/pull/1460, but it has not yet been merged @knightorc

**Comment by lamont-granquist** [comment] 2022-01-12 19:38
I validated the fact that the omnibus health checker has gotten itself silently broken, which does explain how this bug could have slipped through.

**Comment by lamont-granquist** [comment] 2022-02-01 17:10
The omnibus health checker has been fixed now but it doesn't find any problems in our builds, and I can't repro on a rhel7 docker container (our amazon2 and rhel7 tests can all be made to blow up in CI though).

**Comment by lamont-granquist** [comment] 2022-02-01 20:19
Using ami-0686851c4e7b1a8e1 I'm not able to repro it using chef-client 17.9.42 using that test script above.

I can reproduce it on some centos-7/amazon-2 CI testers though in our CI environment, though, so its definitely still buggy.

There's some other missing bit of configuration which is probably crucially involved in the repro case.

Playing around with /etc/ld.so.conf.d and I can certainly see the /lib64/liblzma.so.5 and it contains `XZ_5.2.2` instead of `XZ_5.2`:

```
/lib64# strings -a liblzma.so.5 | egrep "XZ_5.2"
XZ_5.2.2
```

**Comment by lamont-granquist** [comment] 2022-02-02 21:43
Is there some kind of enhanced security setting for the dynamic linker that might be ignoring rpath on these images?

**Comment by lamont-granquist** [comment] 2022-02-02 22:56
This fails on AIX 7.1/7.2 as well so that suggests it is probably not a setting on the dynamic linker.

**Comment by lamont-granquist** [comment] 2022-02-02 23:00
Weirdly on AIX though it looks like we're shipping static libraries (although I'm not familiar offhand with what a .la file is):

```
    /opt/chef/embedded/lib/libarchive.a
    /opt/chef/embedded/lib/libarchive.la
    /opt/chef/embedded/lib/libffi.a
    /opt/chef/embedded/lib/libffi.la
    /opt/chef/embedded/lib/liblzma.a
    /opt/chef/embedded/lib/liblzma.la
```

We're also skipping those on health checks.

**Comment by lamont-granquist** [comment] 2022-02-02 23:16
The AIX compile of libarchive seems to lie about if its installing shared libs:

```

                          D | 2022-01-21T21:28:39-06:00 | checking if libtool supports shared libraries... yes

                          D | 2022-01-21T21:28:39-06:00 | checking whether to build shared libraries... yes

                          D | 2022-01-21T21:28:39-06:00 | checking whether to build static libraries... no
```

This smells like two separate issues on AIX and linux though.

**Comment by lamont-granquist** [comment] 2022-02-03 23:54
repros on centos-7 running `bundle exec rspec spec/functional/resource/archive_file_spec.rb` on the spec files that are shipped in the omnibus package.

strace'ing it shows that <something> is causing `/lib64/libzma.so.5` to be loaded early long before archive_file runs and is bypassing rpath enforcement, and it looks like the actual file being loaded is probably `libdw` and it is happening right after a DNS lookup for the google metadata service which makes it seem like it is some ohai-code or ohai-adjacent, but its a bit buried in the middle of the rspec setup, which is all overly complicated.

**Comment by lamont-granquist** [comment] 2022-02-04 00:25
The `gce?` helper in the `spec/support/platform_helpers.rb` file is what tickles the problem.  An actual minimal example of the bug is this:

```
#!/opt/chef/embedded/bin/ruby

require "ohai/mixin/http_helper"
require "ohai/mixin/gce_metadata"
require "chef/log"

class HttpHelper
  extend Ohai::Mixin::HttpHelper
  def self.logger
    Chef::Log
  end
end

HttpHelper.can_socket_connect?(Ohai::Mixin::GCEMetadata::GCE_METADATA_ADDR, 80)

require 'ffi-libarchive'
```

**Comment by lamont-granquist** [comment] 2022-02-04 00:37
The line in the HttpHelper that is loading the library is:

```
saddr = Socket.pack_sockaddr_in(port, addr)
```

Somehow it looks like maybe when the DNS lookup and /etc/hosts lookup fails it does loads these libraries next:

```
openat(AT_FDCWD, "/lib64/libnss_myhostname.so.2", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libcap.so.2", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libdw.so.1", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libattr.so.1", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libelf.so.1", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/lib64/libbz2.so.1", O_RDONLY|O_CLOEXEC) = 6
```

Before it finally does this:

```
uname({sysname="Linux", nodename="dokken", ...}) = 0
```

**Comment by lamont-granquist** [comment] 2022-02-04 00:38
In fact a workaround is to modify /etc/nsswitch.conf and change:

```
hosts:      files dns myhostname
```

To:

```
hosts:      files dns
```

**Comment by lamont-granquist** [comment] 2022-02-04 00:58
The DWARF libraries are pulled in by myhostname on centos-7/rhel-7:

```
# ldd /lib64/libnss_myhostname.so.2
[....]
	libdw.so.1 => /lib64/libdw.so.1 (0x0000ffffb467c000)
[....]
# ldd /lib64/libdw.so.1
[....]
	liblzma.so.5 => /lib64/liblzma.so.5 (0x0000ffff8f7a1000)
[....]
```

That dependency doesn't exist in centos-8/rhel-8 so this isn't an issue

**Closed** 2022-02-07 23:59 UTC
Labels: Status: Untriaged
