### ISSUE TITLE
run_start even handler is not invoked

### ISSUE THREAD

**Issue by y0y0z** [chef/chef#7950] opened 2018-11-19 08:47 UTC
## Description
`run_started`\`run_start` even handler is not invoked

## Chef Version
```bash
$ chef-client --version
Chef: 14.7.17
```

## Platform Version
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```
## Replication Case
when i include the following in my recipe:
```ruby
Chef.event_handler do
  on :run_started do |_run_context|
    Chef::Log.info 'run_started custom handler'
  end

  on :run_completed do |_run_context|
    Chef::Log.info 'run_completed custom handler'
  end
end
```
the `run_completed` handler is invoked, but the `run_started` never invoked.
also tried to use `run_start` rather than `run_started` but the same result.

## Client Output
```bash
[2018-11-19T08:21:47+00:00] INFO: run_completed custom handler
```
as you can see, no output for neither `run_started`, nor `run_start`.

**Comment by lamont-granquist** [comment] 2018-11-20 00:14
that'll never work because the run has already started by the time it is parsing your event handler code.  in order to capture that event you need to insert the handler into the Chef::Config[:event_handlers] array at config parsing time (and if chef-client is managing its own config then you still run into a chicken-and-egg issue on the first run -- if it really matters deeply to capture this information on every run then the chef config and the handler need to be created on the node by the provisioning system before chef ever runs the first time).  duplicate of #4314

**Closed by lamont-granquist** 2018-11-20 00:14 UTC

**Comment by y0y0z** [comment] 2018-11-20 06:02
@lamont-granquist:
thank you.

for others, i utilized the `:converge_start` hook\event instead.
