### ISSUE TITLE
Reporting changes to binary registry keys (CHEF-5323)

### ISSUE THREAD

**Issue by mcquin** [chef/chef#1468] opened 2014-06-03 16:32 UTC
@opscode/client-eng,

I'm working on [CHEF-5323](https://tickets.opscode.com/browse/CHEF-5323), and wondering what thoughts are on how to handle reporting changes in binary registry keys. Two ideas from @sersut and @adamedx are 1) don't send/track any information for binary registry keys or 2) send/track an md5/checksum so that changes to the key can be detected/indicated.

**Comment by keyrage** [comment] 2015-04-23 01:55
Has this fixed made it into master (Sorry I'm a Github newb)? Chef client 12.2.1 still exhibits the same behavior reported in this bug with the core registry_key resource when setting a dword value with binary data. Tested this on Windows Server 2012 R2.

**Comment by adamedx** [comment] 2015-04-23 15:34
@jdmundrawala, @btm, @ksubrama, here's a fun one that got buried, possibly since I don't know how to properly mention @lamont-granquist (see earlier comments).

@keyrage, it's not in master yet I'm sure since we lost track of this one. Have you found a workaround?

**Comment by danielsdeleo** [comment] 2015-04-23 15:40
Maybe it regresssed somehow or there is some edge case that wasn't fixed in the first place? https://github.com/chef/chef/issues/1470 was supposed to be the fix for this, which was merged in https://github.com/chef/chef/commit/74452e993f527d76f46b5fba33993cc477691146 and GitHub says every tag from 11.14.0 up to current contains that commit.

**Comment by keyrage** [comment] 2015-04-23 19:06
@danielsdeleo, possibly one or the other. I cloned the source and had a look and you're right that it should be in all versions from 11.14. I deployed 12.3 and hit the same problems.

@adamedx, Whats best? Should I open a new issue? I'll create a test cookbook and data to use for testing.

**Comment by keyrage** [comment] 2015-04-23 20:39
Sorry, sorry. 
I built a simple test cookbook and couldn't initially recreate the error. Much head scratching and head bashing against walls occurred. 
Turns out the issue isn't with the registry_key resource but actually is in the attributes.rb file where the binary data for the registry_key resource declaration, is set inside double quotes rather than single quotes.

**Comment by adamedx** [comment] 2015-04-23 20:42
@keyrage let's keep this issue. @btm, @jdmundrawala, @ksubrama can you give a yay / nay on picking this up? @btm, if you don't have bandwidth, let's you and I talk to find someone to help.

**Comment by jdmundrawala** [comment] 2015-04-23 20:49
@keyrage can you share your cookbook

**Comment by keyrage** [comment] 2015-04-23 21:02
Link to the test cookbook I created with the attribute set with double quotes which should generate a JSON encoding error.

https://onedrive.live.com/redir?resid=71C0037690790A7!29680&authkey=!AO7poUEgQBcvfNM&ithint=file%2czip

**Comment by jdmundrawala** [comment] 2015-04-23 21:12
I think the best thing to do here would be to base64 encode your attribute.
Thoughts?

**Comment by keyrage** [comment] 2015-04-27 22:05
I seem to be able to get around the issue solely by enclosing the binary data in single quotes. Is that an acceptable approach or is there possible danger in that approach? Whats the benefit of encoding in Base64? My concern is that adds additional complexity and difficulty in debugging?

**Comment by jdmundrawala** [comment] 2015-04-27 22:25
when you do single quotes, it's not actually binary data:
```
2.1.2 (main):0 > '\x61'.length
=> 4
2.1.2 (main):0 > "\x61".length
=> 1
2.1.2 (main):0 > "\x61"
=> "a"
```

The benefit of Base64 encoding is that your string becomes jsonifyable, and Chef likes to turn your data into json when it communicates outside of the process.

**Comment by lamont-granquist** [comment] 2015-04-30 17:45
I'm working on patches to ffi-yajl and chef-client to make sure that the node.save and reporting POST don't ever fail due to non-UTF8 characters.  chef/ffi-yajl#57 is the ffi-yajl patch.

**Comment by btm** [comment] 2016-11-02 15:10
@keyrage We're unable to reproduce the JSON encoding error with your cookbook now. I'm guessing @lamont-granquist's work on ffy-yajl prevents the error. I'm closing this, but if anyone can still replication the JSON encoding error please post reproduction steps.

**Closed by btm** 2016-11-02 15:10 UTC
Labels: Bug, Chef Core, Windows
