### ISSUE TITLE
invalid date error on windows_task with frequency :on_logon

### ISSUE THREAD

**Issue by sarahbakal** [chef/chef#6615] opened 2017-12-04 19:47 UTC
## Description

invalid date error on windows_task with frequency :on_logon

## Chef Version

Chef-client 13.6.24

## Platform Version

Windows Server 2016
Chef-client 13.6.24

## Replication Case

Windows 2016, created the task on the first run and then deleted the trigger to make sure it would re-apply the :on_logon trigger

## Client Output
```
-----> Converging <default-win2016-standard>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-win2016-standard>
       Starting Chef Client, version 13.6.24
       resolving cookbooks for run list: ["compliance_standard_baseline::default"]
       Synchronizing Cookbooks:
         - compliance_standard_baseline (23.19.0)
         - sysctl (2.0.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 188 resources
       Recipe: compliance_standard_baseline::windows2016
         * windows_task[chef-client-hku] action create
           
           ================================================================================
           Error executing action `create` on resource 'windows_task[chef-client-hku]'
           ================================================================================
           
           ArgumentError
           -------------
           invalid date
           
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/compliance_standard_baseline/recipes/windows2016.rb
           
             7:   windows_task 'chef-client-hku' do
             8:     task_name 'chef-client-hku'
             9:     command 'cmd /c C:/opscode/chef/bin/chef-client'
            10:     frequency :on_logon
            11:     action :create
            12:     user 'SYSTEM'
            13:     run_level :highest
            14:   end
            15: # end
           
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/compliance_standard_baseline/recipes/windows2016.rb:7:in `from_file'
           
           windows_task("chef-client-hku") do
             action [:create]
             default_guard_interpreter :default
             task_name "chef-client-hku"
             declared_type :windows_task
             cookbook_name "compliance_standard_baseline"
             recipe_name "windows2016"
             command "cmd /c C:/opscode/chef/bin/chef-client"
             frequency :on_logon
             user "SYSTEM"
             run_level :highest
             execution_time_limit "PT72H"
             start_day "N/A"
           end
           
           System Info:
           ------------
           chef_version=13.6.24
           platform=windows
           platform_version=10.0.14393
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client
           
       
       Running handlers:
       [2017-12-04T13:40:35-06:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-12-04T13:40:35-06:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 06 seconds
       [2017-12-04T13:40:35-06:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-12-04T13:40:35-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-12-04T13:40:35-06:00] FATAL: ArgumentError: windows_task[chef-client-hku] (compliance_standard_baseline::windows2016 line 7) had an error: ArgumentError: invalid date
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-win2016-standard>.  Please see .kitchen/logs/default-win2016-standard.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Stacktrace

```
Generated at 2017-12-04 13:40:35 -0600
ArgumentError: windows_task[chef-client-hku] (compliance_standard_baseline::windows2016 line 7) had an error: ArgumentError: invalid date
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:94:in `parse'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:94:in `block in action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:87:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:87:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:718:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:713:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:713:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:752:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:58:in `load'
C:/opscode/chef/bin/chef-client:58:in `<main>'

>>>> Caused by ArgumentError: invalid date
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:94:in `parse'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:94:in `block in action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:87:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider/windows_task.rb:87:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:718:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:713:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:713:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:752:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.24-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:58:in `load'
C:/opscode/chef/bin/chef-client:58:in `<main>'
```

**Comment by NimishaS** [comment] 2017-12-05 07:47
This issue looks similar to https://github.com/chef/chef/issues/6480 which has been resolved in https://github.com/chef/chef/pull/6544.
@sarahbakal , can you please try with `chef-client` current build: https://downloads.chef.io/chef/current/13.6.24?
Let us know if you still face the issue.

**Comment by tas50** [comment] 2017-12-05 23:53
@sarahbakal What date format does your node use?

**Comment by NimishaS** [comment] 2017-12-06 14:33
The issue is reproducible for all date formats in case of `frequency :on_logon`. Fixing the issue in https://github.com/chef/chef/pull/6618.

**Closed** 2017-12-11 18:00 UTC
