### ISSUE TITLE
api_client/registration.rb -  integer 137438954242 too big to convert to `int'

### ISSUE THREAD

**Issue by gaelik** [chef/chef#6842] opened 2018-02-09 18:40 UTC
## Description
While running chef-client 13.7.16 on an AIX 7.1TL4 system, the client cannot register, the following error is returned, the client.pem file does not get created. 
```
ERROR: integer 137438954242 too big to convert to `int'
```
## Chef Version
13.7.16

## Platform Version
AIX 7.1 TL4. (7100-04-02-1614)

## Replication Case
removing client.pem from /etc/chef directory and running chef-client to reregister the node (after deleting the client record from chef-server)

```
#ls -l /etc/chef/
total 24
-rw-r--r--    1 root     system          297 Feb  9 12:05 client.rb
drwx------    2 root     system          256 Feb  9 11:20 trusted_certs
-rw-r--r--    1 root     system         1678 Feb  9 11:59 validation.pem
```

## Client Output

```
Chef Client failed. 0 resources updated in 05 seconds
[2018-02-09T12:19:00-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-02-09T12:19:00-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-02-09T12:19:00-06:00] ERROR: integer 137438954242 too big to convert to `int'
```

I patched the following recipe to collect the values contained in the variables destination and file_flags and looks like file_flags is the one containing that overflowing integer.

/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/api_client/registration.rb (line 79)

      def write_key
        Chef::Log.warn("in write key")
        Chef::Log.warn("destination=#{destination} - file_flags=#{file_flags}")
        ::File.open(destination, file_flags, 0600) do |f|
          f.print(private_key)
        end

Output
```
webp8019:/etc/chef #chef-client
[2018-02-09T12:18:52-06:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
[2018-02-09T12:18:55-06:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 13.7.16
[2018-02-09T12:18:55-06:00] INFO: *** Chef 13.7.16 ***
[2018-02-09T12:18:55-06:00] INFO: Platform: powerpc-aix6.1.0.0
[2018-02-09T12:18:55-06:00] INFO: Chef-client pid: 11796484
[2018-02-09T12:18:55-06:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.7.1/lib/ohai/mixin/command.rb:35: warning: Insecure world writable dir /var/ifor in PATH, mode 0241777
Creating a new client identity for xxxx using the validator key.
[2018-02-09T12:19:00-06:00] INFO: Client key /etc/chef/client.pem is not present - registering
[2018-02-09T12:19:00-06:00] WARN: in write key
[2018-02-09T12:19:00-06:00] WARN: destination=/etc/chef/client.pem - file_flags=137438954242

================================================================================
Chef encountered an error attempting to create the client "xxxx"
================================================================================
```

## Stacktrace

```
Generated at 2018-02-09 12:19:00 -0600
RangeError: integer 137438954242 too big to convert to `int'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/api_client/registration.rb:81:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/api_client/registration.rb:81:in `open'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/api_client/registration.rb:81:in `write_key'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/api_client/registration.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/client.rb:669:in `register'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/client.rb:267:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:292:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:280:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:280:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:245:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:233:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:59:in `load'
```

**Comment by trickyearlobe** [comment] 2018-03-10 17:28
Problem also occurs on `AIX 7.2` with `chef-13.8.5-1.powerpc.bff`
No problem with the validator key as it is fine on a Linux node.

I can perform a remote validator-less bootstrap and with the valid `client.pem` the CCR completes normally, so this is only a problem with self-registration using the validator.

**Comment by trickyearlobe** [comment] 2018-03-12 23:36
## Cause

The problem seems to be caused by this piece of code in `lib/chef/api_client/registration.rb`

```
      def file_flags
        base_flags = File::CREAT | File::TRUNC | File::RDWR
        # Windows doesn't have symlinks, so it doesn't have NOFOLLOW
        if defined?(File::NOFOLLOW) && !Chef::Config[:follow_client_key_symlink]
          base_flags |= File::NOFOLLOW
        end
        base_flags
      end
```

On the AIX platform, the `File::NOFOLLOW` flag is defined as 0x20:0000:0000 (137,438,953,472) but in this code the `File.open(destination, file_flags, 0600)` can only accept a 32bit `file_flags`

```
      def write_key
        ::File.open(destination, file_flags, 0600) do |f|
          f.print(private_key)
        end
      rescue IOError => e
        raise Chef::Exceptions::CannotWritePrivateKey, "Error writing private key to #{destination}: #{e}"
      end
```

## Workaround

@gaelik you can work around this by adding `Chef::Config[:follow_client_key_symlink] = true` to your  `client.rb` which will remove the `File::NOFOLLOW` flag.

## Fix

Not sure whether this should be fixed by skipping the NOFOLLOW code on AIX, or whether its better to fix the underlying constants and possibly corresponding code in `File.open`.

**Comment by trickyearlobe** [comment] 2018-03-13 00:33
Note: The AIX version of `fcntl.h` on my test machine defines `_FNOFOLLOW` , `O_NOFOLLOW` and FNOFOLLOW` as `0x01000000` which would fit in 32bits. Perhaps the ruby shipped with AIX Chef Client was compiled with a faulty `fcntl.h` ?

**Comment by trickyearlobe** [comment] 2018-03-13 00:55
Hmmm... possible clue in http://www-01.ibm.com/support/docview.wss?uid=isg1IV64988

Seems there was a change in the value of this flag back in ~2015 so we may just have an old `fnctl.h`

**Comment by scotthain** [comment] 2018-03-20 23:24
@trickyearlobe We're seeing this as well and we hope to have a fix incoming asap.

**Comment by bkonick** [comment] 2018-07-05 22:58
@scotthain any update on this bug? I am seeing it in 13.9.4 inside of test kitchen.

**Comment by msgarbossa** [comment] 2018-08-01 23:43
I'm also seeing this on Chef 14.3.37 on AIX 7.1 TL4 SP5 (7100-04-05-1720).

**Comment by jaymalasinha** [comment] 2018-08-21 20:32
https://downloads.chef.io/chef/current/14.4.39  has the fix.  It was successfully and tested on AIX 7.1 TL5 (7100-05-02-1806).

**Comment by gaelik** [comment] 2018-08-21 21:02
Do you know if there will be a backport to  client 13 ?

**Comment by bkonick** [comment] 2018-08-22 14:52
@gaelik I received confirmation that the fix should be in the next release of Chef 13. Don't have a timeline on it though.

**Comment by TechGuyChris** [comment] 2018-10-23 20:05
Hi. This still isnt fixed. Anyone else have any updates on this issue? I used Chef version 14.3.37.1

**Comment by tas50** [comment] 2018-11-28 04:48
@TechGuyChris can you verify this on Chef 14.4 or later. The fix was introduced in that release

**Comment by lamont-granquist** [comment] 2019-12-02 18:37
Chef-13 is receiving no new updates, so Chef > 14.4 is necessary to receive this bugfix.

**Closed by lamont-granquist** 2019-12-02 18:37 UTC
Labels: Platform: Unix-like, Type: Bug
