### ISSUE TITLE
UTF-16LE Not supported

### ISSUE THREAD

**Issue by wjdavis5** [chef/chef#7292] opened 2018-05-24 19:37 UTC
Chef: 14.1.12 Windows 10 Going through the tutorial here I have my knife.rb at ~/learn-chef/.chef/knife.rb (C:\users\wdavis\learn-chef.chef\knife.rb)

I run the ssl fetch knife ssl fetch

```
Results:
    INFO: Using configuration from C:/Users/wdavis/learn-chef/.chef/knife.rb
    WARNING: Certificates from localhost will be fetched and placed in your trusted_cert
    directory (c:\users\wdavis\learn-chef\.chef\trusted_certs).

    Knife has no means to verify these are the correct certificates. You should
    verify the authenticity of these certificates after downloading.

    ERROR: Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect
```

Here is my knife.rb:

```
current_dir = File.dirname(__FILE__)
log_level                 :info
log_location              STDOUT
node_name                 "chefadmin"
client_key                "#{current_dir}/chefadmin.pem"
chef_server_url           "https://synchef.url.com/organizations/syn"
cookbook_path             ["#{current_dir}/../cookbooks/"]
```

However, if I run: knife ssl fetch https://synchef.url.com

It works fine - so why isnt it working when just using the knife.rb?

I should also add I'm seeing similar issues when trying to upload cookbooks. It says its using my knife.rb and the cookbooks are obviously there but it claims it cannot find them.

So it seems to me maybe it isnt really using the knife.rb it should?

and here is another example:

```
knife ssl check -V
INFO: Using configuration from C:/Users/wdavis/learn-chef/.chef/knife.rb
Connecting to host localhost:443
ERROR: Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect
```

Why is it trying to connect to localhost:443? That isnt what is configured in my knife.rb

**RESOLUTION**

I wrote the original file in VS Code - which saved the file as UTF-16 LE. I noticed that in the starter kit I downloaded the file was UTF-8. I resaved my file in UTF-8 and the command worked fine. It seems that the version of ruby shipped with ChefDk doesnt like UTF-16LE?

**Comment by coderanger** [comment] 2018-05-24 19:43
Related issue https://github.com/chef/chef/issues/7054

**Comment by lamont-granquist** [comment] 2018-05-24 22:08
Pretty sure this is fixed by an encoding magic comment at the top of the file like `# encoding: UTF-16LE`

And it looks like UTF-16LE is BOM-less so this is the only solution.  We have to default to UTF-8, so people in other charsets have to decorate their cookbooks with magic encodings.

**Comment by lamont-granquist** [comment] 2018-05-25 16:24
Think I'm going to close this.  There are incredibly strong reasons why Chef defaults to UTF-8 to allow consumption of community cookbooks which are assumed to be written in UTF-8.  That means that Windows users have more trouble, but the root cause there is that Windows NT 3.5.1 chose UTF-16LE before UTF-8 existed, while the rest of the world adopted UTF-8 broadly and Microsoft has never unwound that mistake.  That places a necessary burden on windows users to use magic comments, BOMs or to simply set their editors so that all *.rb files (and Rakefile, etc) are automatically set to UTF-8 encoding.  I'd strongly suggest the latter.  This isn't really a bug Chef can fix.

**Closed by lamont-granquist** 2018-05-25 16:24 UTC

**Comment by wjdavis5** [comment] 2018-05-25 19:46
I'd hope you'd document it as such. Took me 2 days at chefcon with several
ppl trying to help to figure it out.

**Comment by lamont-granquist** [comment] 2018-05-25 20:57
i have no idea where to document that to be useful.  it would need to go somewhere in this repo:  https://github.com/chef/chef-web-docs or against learnchef (which i don't even know what repo to file that against).

**Comment by coderanger** [comment] 2018-05-25 23:27
@wjdavis5 We pass the loaded file content to `instance_eval` under the hood. There is no good way to know what, if anything, went wrong in this case since it just silently does nothing. We would have to do a heuristic analysis of the file content ahead of time and try to work out the file encoding, and down this path lies much sadness.
