### ISSUE TITLE
Chef falsely reports file not existing when it can't find the interpreter

### ISSUE THREAD

**Issue by oneandoneis2** [chef/chef#8251] opened 2019-02-25 09:54 UTC
## Description
Chef was creating (from download) a file containing a python script, then attempting to execute it and reporting "No such file or directory" for the file it had just created. It turned out the problem was the script shebang line called `/usr/bin/python` and python wasn't installed to this path.

Correct behaviour would be what the shell does: Reporting `bad interpreter: /usr/bin/python: no such file or directory`

## Chef Version
13.8.5

## Platform Version
Ubuntu 18.04

## Replication Case
Create a file /tmp/foo.py with the first line having an invalid shebang path and have chef try to run it via an execute.

## Client Output
```
    reverse_proxy_18.04: ================================================================================
    reverse_proxy_18.04: Error executing action `run` on resource 'execute[Install agent]'
    reverse_proxy_18.04: ================================================================================
    reverse_proxy_18.04:
    reverse_proxy_18.04: Errno::ENOENT
    reverse_proxy_18.04: -------------
    reverse_proxy_18.04: No such file or directory - /tmp/packer-chef-client/local-mode-cache/cache/awslogs-agent-setup.py
    reverse_proxy_18.04:
    reverse_proxy_18.04: Resource Declaration:
    reverse_proxy_18.04: ---------------------
    reverse_proxy_18.04: # In /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/uj_cloudwatch/recipes/agent.rb
    reverse_proxy_18.04:
    reverse_proxy_18.04: 30: execute 'Install agent' do
    reverse_proxy_18.04: 31:   command "#{Chef::Config[:file_cache_path]}/#{script} -n -r eu-west-2 -c #{tmp_config_path}"
    reverse_proxy_18.04: 32: end

```

**Comment by lamont-granquist** [comment] 2019-02-25 17:58
We don't parse anything inside of the script to change how we execute it and only call `exec` on it.

This is accurately what `exec` gives back as an exit code.

I'm not sure what the shell command line is doing to give back that exit status, but I'm more inclined to view this as correct behavior in the general case and not a bug.

**Comment by lamont-granquist** [comment] 2019-11-28 00:16
Closing this as insufficient resources to fix this

**Closed by lamont-granquist** 2019-11-28 00:16 UTC
Labels: Triage: Declined
