### ISSUE TITLE
knife status hide by mins not working

### ISSUE THREAD

**Issue by ct0br0** [chef/chef#9376] opened 2020-02-14 13:42 UTC
`knife status --hide-by-mins xx` not working properly

would expect the below to output nothing with value of 80

> knife status --hide-by-mins 40
> 58 minutes ago, xxxxxxx oracle 7.7.
> knife status --hide-by-mins 80
> 58 minutes ago, xxxxxxx oracle 7.7.

Tell us which version of the ChefDK you are running. Run `chef --version` to display the version.

fedora, mac, ubuntu chef-dk 4.50 and 4.7.73

**Comment by tyler-ball** [comment] 2020-02-19 18:13
Thanks for filing this issue @ct0br0 - I went ahead and moved it to the chef/chef repo, which is where the `knife` tool is maintained.

@lamont-granquist I tried to tag this with the appropriate labels

**Comment by ct0br0** [comment] 2020-06-29 16:23
FYI - I will be leaving my position where I am able to test this issue.
It is still outstanding but I can no longer provide input.

**Comment by ashwin-msys** [comment] 2021-07-02 12:32
I've tried to reproduce this issue in the given operating systems ( Ubuntu, Mac & Fedora ). But it seems like the issue is not there and the knife command is working fine as we are expecting it to be. I've attached the screenshots below of each OS. 

**Ubuntu testing:**

![Screenshot from 2021-07-02 15-26-45](https://user-images.githubusercontent.com/82504775/124258824-76f91e80-db4b-11eb-9869-ca6608a424f3.png)

**Mac testing:**

![Screenshot from 2021-07-02 15-28-22](https://user-images.githubusercontent.com/82504775/124258885-8aa48500-db4b-11eb-8217-7c808fa32527.png)

**Fedora testing:**

![Screenshot from 2021-07-02 15-30-26](https://user-images.githubusercontent.com/82504775/124259007-a9a31700-db4b-11eb-8617-791123a352b5.png)

**Comment by ashwin-msys** [comment] 2021-07-16 14:08
Hi @ct0br0 any updates on my previous comment?

**Comment by ashwin-msys** [comment] 2021-07-21 11:34
Hi @ct0br0, I am closing this issue since it doesn't seems reproducible. Please let us know if we we occur to see this problem with `knife status` command.

Thank you!

**Closed** 2021-07-21 11:34 UTC
Labels: Focus: knife, Status: Needs Replication, Status: Sustaining Backlog, Type: Bug

**Comment by JKD9** [comment] 2022-09-22 17:54
TapHere! just ran through the steps to reindex and clean up the Chef Infra Server and modified the search index config "changing read_only_allow_delete to false" and now our knife status --hide-by-mins XXX works normally.

Here are the steps:
curl -XGET http://127.0.0.1:9200/_all/_settings`

curl -XPUT -H "Content-Type: application/json" http://127.0.0.1:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'

chef-server-ctl reindex
