### ISSUE TITLE
Add a 'null' or 'notifies' NOP resource to hang chained notifies off of

### ISSUE THREAD

**Issue by et304383** [chef/chef#3426] opened 2015-05-26 16:43 UTC
Original request here:
https://tickets.opscode.com/browse/CHEF-5324

The item was obviously lost when the issues moved to Github.  Chef still has not provided a way to specify a resource call is to execute at the end of the Chef run.  The work-around was to have a dummy resource do the notify like as follows:

```
bash 'dummy-delay-httpd-start' do
  notifies :restart, 'service[httpd]', :delayed
end

service 'httpd' do
  action :nothing
end
```

However, now a warning is beind thrown that this won't work anymore in Chef 13:

```
 WARN: bash[dummy-delay-httpd-start]: No code attribute was given, resource does nothing, this behavior is deprecated and will be removed in Chef-13
```

You need to either abort the planned removal of this or add the original feature I requested.  It's absurd that there won't be a way to have something run at the end of a Chef run in all circumstances.

**Comment by coderanger** [comment] 2015-05-29 00:21
Just use a ruby_block with `block { }`. The issue is specifically that ` bash resource with no code to run is almost certainly an error.

**Comment by eric-tucker** [comment] 2015-06-01 15:05
How is a ruby_block with block {} any better or worse than a bash block with no code?

It is NOT an error - an empty bash block does nothing.  Hardly an error.  Warning maybe, but not error.

**Comment by coderanger** [comment] 2015-06-01 20:12
You could also use `bash 'dummy' do code '' end` just as well and that should also disable the deprecation warning since you are passing a code attribute. Using a ruby_block is just mildly faster as it doesn't have to shell out to bash.

**Comment by ranjib** [comment] 2015-06-25 01:51
i dont think this is possible at all. resources can be added dynamically , or included from cookbooks, its up to the consumer's usage what will be run. Resources that are notified delayed are also run at the end. So whats run at the end really depends on the chef run as well as on the recipe. 
You can use the event handler to hook any code block to be executed at end of chef run, i.e. after it has converged. I think that will be lot cleaner

**Comment by eric-tucker** [comment] 2015-07-09 16:37
@ranjib  can you explain in a different way perhaps?  I'm not sure I'm following your alternative solution.

An example would be awesome.  :)

**Comment by stevendanna** [comment] 2015-07-09 16:43
I think that we need a top-level "notify this resource" dsl method that you can use in recipes.  We NACK'd this idea several times in the old code-review sessions, but there are so many use cases that it would facilitate that I think that we were just wrong about that.  If we had such a mechanism,  you could just do:

```
service 'httpd' do
  action :nothing
end

notify "service[httpd]" do
  notify_action :restart
  notify_timing :delayed
  action :notify
end
```

In practice a `ruby_block` works fine for this, but I think being more explicit would be better.  It would also allow us to do validations such as the warning we are producing here.

**Comment by eric-tucker** [comment] 2015-07-09 16:44
@stevendanna That would be AWESOME.  This is exactly what I had requested in my initial ticket.

**Comment by coderanger** [comment] 2015-07-09 16:45
@stevendanna How is that different from a resource that just always updates, except that it creates two different APIs for notifications?

**Comment by stevendanna** [comment] 2015-07-10 08:46
> How is that different from a resource that always updates

Clearly it isn't /that/ different since nearly everyone who has to do something like this is using an always-update resource currently.  However, I do think it has some advantages:

1) Much clearer about intent from the perspective of someone reading the recipe
2) Can easily be handled differently by reporting, handlers, etc.
3) Depending on how far we want to go, it wouldn't even clutter up your resource collection with a "resource" that doesn't represent a system resource.

> except that it creates two different APIs for notifications?

The recipe-level API could made to look nearly identical to the resource API:

```
notify :notify_action, "resource_type[notify_resource]", :notify_timing
```

**Comment by lamont-granquist** [comment] 2015-09-16 17:35
The 'supported' way of doing this is with the `log` resource rather than the `bash` resource right now.

#1727 is related to this.  A 'notify' or 'null' resource should probably be constructed.  I really, really hate abusing existing resources to do this -- either the bash resource, the log resource, or an empty ruby_block because then it makes it harder for us to catch common coding mistakes that lead to inadvertent NOPs.   I'm not sure we need to do a lot of work on the API of the 'null' resource though, just have it look like the log resource, only do nothing and not log and just let people chain notifies off of it and use it as a target.

**Comment by s-bernard** [comment] 2016-09-26 15:04
Any news on this?

**Comment by coderanger** [comment] 2017-09-26 02:56
This is now mostly handled with `delayed_action`:

```ruby
service 'httpd' do
  action :nothing
  delayed_action :restart
end
```

Going to close this out, please open a new issue if there is a use case we haven't considered.

**Comment by lamont-granquist** [comment] 2017-09-26 03:02
no, this is the "bundle a pile of resource together and notify them all at once problem"

arguably its a pattern that is crying out for people to refactor their code into a custom resource and then just notify that.  but in practice we wind up with people abusing log resources, ruby_blocks or any other trickery that they can come up with.  when i took out the empty-command-resource and made it error, it turned up that people had been using that as a way to implement that.  don't want to fight with that as a use case, so just want to have a null/nop/notify/whatever resource that i can steer them at...

**Comment by lamont-granquist** [comment] 2017-09-26 03:10
the problem is really something like this:

```ruby
log "do three things" do
  notifies :create, "file[/etc/something.conf", :immediately
  notifies :run, "execute[something]", :immediately
  notifies :restart, "service[somethingd]", :immediately
end
```

so then you have a largeish recipe with those three resources embedded in it, and when certain events happen you can fire off just those three resources to update, and do it in that sequence.

again, crying out for "extract me into a custom resource" but people fight with that a lot and then abuse other resources to get this job done.

**Comment by lamont-granquist** [comment] 2017-09-26 03:24
hrm, yeah, looks like i didn't read this correctly and hijacked it.   `delayed_action` does fix the original CHEF ticket.

problem is that i'd still like the dummy resource for chaining multiple notifications off of.

**Closed** 2020-02-07 01:49 UTC
Labels: Priority: Medium, Status: Good First Issue, Type: Enhancement
