### ISSUE TITLE
yum_repository options does not seem to take hash as it says in docs

### ISSUE THREAD

**Issue by mbassett** [chef/chef#5675] opened 2016-12-22 01:18 UTC
## Description

recipe ops::repo
base_url = db['repository']['baseurl']
snapshot = db['repository']['snapshot']

yum_repository 'CentOS' do
  description "DDI CentOS snapshot repo"
  baseurl "#{base_url}/$releasever/$basearch/#{snapshot}"
  options { :s3_enabled => 1 }
  action :create
end

I have tried a lot of different syntaxes and they all seem to error the same way
options ( 's3_enabled' => 1 ) 
options ( "s3_enabled" => 1 )
options { "s3_enabled" => 1 }
options { 's3_enabled' => 1 }

as well as trying :s3_enabled

I just need the repository file to have s3_enabled = 1  in it.   I can write a template to do this, but seems like it should work in the yum_repository DSL.

## Chef Version

chef-server 12.11.1-1 open source
chef-client 12.17.44

## Platform Version

centos7 64bit

## Replication Case

try to use options hash in yum_repository

## Client Output

Starting Chef Client, version 12.17.44
resolving cookbooks for run list: ["ops::updates", "ops::repo"]
Synchronizing Cookbooks:
  - ops (0.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/ops/recipes/repo.rb
================================================================================

SyntaxError
-----------
/var/chef/cache/cookbooks/ops/recipes/repo.rb:11: syntax error, unexpected =>, expecting '}'
  options { "s3_enabled" => 1 }
                           ^

**Comment by thommay** [comment] 2016-12-22 17:47
hi, when passing a hash like that you need to wrap it in parentheses, ie:
```
yum_repository 'CentOS' do
description "DDI CentOS snapshot repo"
baseurl "#{base_url}/$releasever/$basearch/#{snapshot}"
options({:s3_enabled => 1 })
action :create
end
```
I'm closing this issue since it's not a bug, simply how ruby parses the DSL.

**Closed by thommay** 2016-12-22 17:47 UTC
