### ISSUE TITLE
Mixlib::Shellout can return nil exitstatus in low-RAM situations

### ISSUE THREAD

**Issue by chrisgit** [chef/chef#4857] opened 2016-04-22 14:13 UTC
## Description

We have a large cookbook that fails when running a package 'cronie' resource.
However this is NOT an issue installing the cronie package, if the package 'cronie' resource is removed from the cookbook we get the same error later on installing another package. This appears to be an issue with the YUM package provider.
## Chef Version

12.8.1
## Platform Version

CentOS 6.7
## Replication Case

Unfortunately at present I am unable to re-create the issue in a small cookbook, the problem only appears when running our Environment cookbook (a cookbook containing a collection of application cookbooks).

The failure message is 

```
NoMethodError
-------------
undefined method `>' for nil:NilClass

```

The reason for the message is due to the code in yum_command method of the Chef::Provider::Package::Yum. What we are finding is that the status.exitstatus value is nil

The code runs

```
status = shell_out_with_timeout(command, {:timeout => Chef::Config[:yum_timeout]})
...
if status.exitstatus == 1
....
if status.exitstatus > 0
```

The error is caused by comparing status.exitstatus > 0, hence nil method error.
## Client Output

```
* yum_package[cronie] action install
================================================================================
Error executing action `install` on resource 'yum_package[cronie]'
================================================================================

NoMethodError
-------------
undefined method `>' for nil:NilClass

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/<cookbook>/recipes/<recipe>.rb

39:   package depend_name do
40:     action :install
41:   end
42: end

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/<cookbook>/recipes/<recipe>.rb:39:in `block in from_file'
yum_package("cronie") do
    package_name "cronie"
    action [:install]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :package
    cookbook_name ""
    recipe_name ""
    flush_cache {:before=>false, :after=>false}
end

```

As already mentioned although we saw this error installing 'cronie' but it is a YUM package issue, we've had other similar messages installing different packages (below)

```
===============================================================================
Error executing action `install` on resource 'yum_package[perl-MIME-Lte]'
===============================================================================

NoMethodError
-------------
undefined method `>' for nil:NilClass

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/<cookbook name>/recipes/<recipe>.rb


39:   package depend_name do
40:     action :install
41:   end
42: end

 Compiled Resource:
 ------------------
 # Declared in /tmp/kitchen/cache/cookbooks/<cookbook>/recipes/<recipe>.rb:39:in `block in from_file'

yum_package("perl-MIME-Lite") do
    package_name "perl-MIME-Lite"
    action [:install]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :package
    cookbook_name "nvm_mariadb"
    recipe_name "mariadb_repo"
    flush_cache {:before=>false, :after=>false}
end

```

We do tend to write code like this

```
%w{ list of packages }.each do |package_name|
  package package_name do
    action :install
  end
end

```

So I've added a delay between the installation of each package to eliminate that possibility, it does seem to work better so I'm thinking it could be the number of command calls to yum/rpm combined with cookbooks removing and re-installing packages to quickly?
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
## Misc

Some YUM provider package resources do not even get as far as running yum_command because they do not get past the checks in the package run_action (see below)

```
def action_install
    unless target_version_array.any?
        Chef::Log.debug("#{@new_resource} is already installed - nothing to do")
        return
    end
    ....
```

Of the ones that do pass the check, the majority come back with the status object correctly set.
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment] 2016-04-22 16:17
status.exitstatus being nil isn't a bug in the yum provider, that would be a bug in mixlib-shellout (or possibly the underlying calls that ruby makes -- probably to waitpid? -- to gather the exitstatus)

makes me wonder if its failing to fork and exec because you're running out of RAM+swap or something like that.

**Comment by chrisgit** [comment] 2016-04-22 20:45
Thank you @lamont-granquist 

Agree it is mixlib-shell out not correctly returning rather than Yum provider but as the issue manifests itself there I thought I'd log the bug as that resource.

Thanks for the pointer, I'll up the specs of the VM and keep an eye on the system resources during converge.

**Comment by chrisgit** [comment] 2016-04-25 10:14
@lamont-granquist We bumped the specs of the VM and it converges without issue.

Not sure what you want to do with this?

**Comment by lamont-granquist** [comment] 2016-04-25 16:43
ideally it'd be nice to track down the codepath its going through in mixlib-shellout and have it raise an exception rather than returning nil.  since it can't ever be fixed, though, and bumping up the system limits is the 'fix' its probably very low priority compared to other bugs.

**Comment by itsSaad** [comment] 2016-05-09 14:06
Im having the same problem. Although it started coming up only today. It was working fine. Im testing my cookbooks locally with vagrant, chef-solo.
I get the following error:
```
==> default: Converging 30 resources
==> default: Recipe: base::epel
==> default:   * yum_package[epel-release] action install
==> default:
==> default:
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'yum_package[epel-release]'
==> default:     ================================================================================
==> default:
==> default:     NoMethodError
==> default:     -------------
==> default:     undefined method `length' for nil:NilClass
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/292f7208a0636f73708a65a4b212437d/cookbooks/base/recipes/epel.rb
==> default:
==> default:       1: yum_package 'epel-release' do
==> default:       2:   action :install
==> default:       3: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/292f7208a0636f73708a65a4b212437d/cookbooks/base/recipes/epel.rb:1:in `from_file'
==> default:
==> default:     yum_package("epel-release") do
==> default:       package_name "epel-release"
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :yum_package
==> default:       cookbook_name :base
==> default:       recipe_name "epel"
==> default:       flush_cache {:before=>false, :after=>false}
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
```
The stack trace is as follows:
```
Generated at 2016-05-09 09:57:21 -0400
NoMethodError: yum_package[epel-release] (base::epel line 1) had an error: NoMethodError: undefined method `length' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:59:in `version_parse'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:236:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:252:in `new'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:252:in `parse'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1218:in `block in install_remote_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1213:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1213:in `install_remote_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1268:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:101:in `block (2 levels) in action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:227:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:100:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:99:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:667:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:662:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:662:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:701:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:52:in `load'
/bin/chef-solo:52:in `<main>'
```
Even if I up the VM specs (4gb ram) I still get this error.
My `Vagrantfile` seems like this: 
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = 'base-berkshelf'

  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  # Every Vagrant virtual environment requires a box to build off of.
  # If this value is a shorthand to a box in Vagrant Cloud then
  # config.vm.box_url doesn't need to be specified.
  config.vm.box = 'centos/7'


  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :private_network, type: 'dhcp'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # The path to the Berksfile to use with Vagrant Berkshelf
  # config.berkshelf.berksfile_path = "./Berksfile"

  # Enabling the Berkshelf plugin. To enable this globally, add this configuration
  # option to your ~/.vagrant.d/Vagrantfile file
  config.berkshelf.enabled = true

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      mysql: {
        server_root_password: 'rootpass',
        server_debian_password: 'debpass',
        server_repl_password: 'replpass'
      }
    }

    chef.run_list = [
      'recipe[base::default]'
    ]
  end
end
```
What would be the fix for this if adding more ram can't help?

**Comment by itsSaad** [comment] 2016-05-09 15:49
Ok so i was having the problem installing epel-release via yum_package. so i went ahead and installed that manually so the rest of the cookbook keeps on executing. but this it ran into the same problem when it started to install new-relic.
```
==> default:     yum_package[newrelic-sysmond] (/tmp/vagrant-chef/292f7208a0636f73708a65a4b212437d/cookbooks/newrelic/providers/server_monitor.rb line 35) had an error: NoMethodError: undefined method `length' for nil:NilClass
```
So i think its definitely to do with yum_package and not with chef-solo/vagrant setup.

**Comment by chrisgit** [comment] 2016-05-09 15:59
@itsSaad 

I might be wrong but it looks like a different error, from the back trace appears to be here
````
             if evr =~ %r{:?.*-(.*)$}
                release = $1
>>>>                tail = evr.length - release.length - lead - 1

                if release.empty?
                  release = nil
                end
````
of RPMUtils.version_parse.

The issue I was getting was because the process fork was failing due to lack of resources on the VM.

**Comment by itsSaad** [comment] 2016-05-10 03:36
Hmm. Ok. @chrisgit i would make a separate issue for this then.

**Comment by lamont-granquist** [comment] 2017-11-16 20:40
ultimate root cause was probably caused by yum-dump.py in the yum_package provider consuming too much RAM which will be gone in #6540

fixing the mixlib-shellout error message is so low-priority, that i think we're never going to get to it, so just closing this

**Closed by lamont-granquist** 2017-11-16 20:40 UTC
Labels: Area: Chef Core, Priority: Low, Status: Pending Contributor Response, Type: Bug
