### ISSUE TITLE
Single quotes in attributes lead to bash syntax error in knife bootstrap

### ISSUE THREAD

**Issue by josephta** [chef/chef#3887] opened 2015-09-07 17:29 UTC
If the initial attributes used in with `knife bootstrap` contain an apostrophe / single quote, then a bash syntax error is throw when chef client is started on the remote machine. 

Running with a "nice" set of attributes. Bootstrap connects to the node and tries to trigger the recipe (which fails as expected as the chef server isn't running):

```
$ knife bootstrap host-redacted -j "{\"x\":\"y\"}"
Bootstrapping Chef on host-redacted
host-redacted Starting Chef Client, version 12.1.2
host-redacted [2015-09-03T02:11:37-07:00] ERROR: Connection refused connecting to http://127.0.0.1:8889/nodes/host-redacted, retry 1/5
ˆC
```

Then, running the same thing with an apostrophe in a valid location:

```
$ knife bootstrap host-redacted -j "{\"x\":\"y'\"}"
Bootstrapping Chef on host-redacted
host-redacted bash: -c: line 80: unexpected EOF while looking for matching `"'
host-redacted bash: -c: line 84: syntax error: unexpected end of file
```

Spotted in versions 11.8.2 and 12.1.2.

**Comment by josephta** [comment] 2015-09-08 10:47
It looks like the issue may be with the lack of single quote escaping when generating the template at https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap.rb#L390 as the default template (https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb) uses single quotes.

This opens up for code injection attacks:

    $ knife bootstrap localhost -j "{\"a\": \"b'; echo Hello there; pwd; '\"}"
    Doing old-style registration with the validation key at /root/.chef/chef-validator.pem...
    Delete your validation key in order to use your user credentials instead
    
    Connecting to localhost
    localhost bash: line 80: warning: here-document at line 79 delimited by end-of-file (wanted `EOP')
    localhost Hello there
    localhost /root
    localhost bash: line 85: ","run_list":[]}
    localhost EOP
    localhost 
    localhost echo "Starting first Chef Client run..."
    localhost 
    localhost chef-client -j /etc/chef/first-boot.json -E _default: No such file or directory

**Comment by lamont-granquist** [comment] 2015-10-07 17:41
Since you're bootstrapping the host you've already got all the rights in the world to inject arbitrary code as the user you're bootstrapping the host with, so not sure I'd consider this an 'attack'.

This will be fixed by #3920 which will eliminate the horrible bash command.

**Comment by tas50** [comment] 2019-09-16 17:50
We'll want the sustaining team to try to reproduce this.

**Comment by lamont-granquist** [comment] 2019-09-17 18:38
closing in favor of #8859 tracking the actual work.

**Closed by lamont-granquist** 2019-09-17 18:38 UTC
Labels: Priority: Critical, Status: Sustaining Backlog
