### ISSUE TITLE
Links on windows, create shadow copys, not links

### ISSUE THREAD

**Issue by spuder** [chef/chef#3507] opened 2015-06-08 22:05 UTC
If you attempt to create a soft link on windows server 2012, you get a shadow copy, not a symlink. 

```ruby
link "c:\\foo" do
  to "d:\\bar"
end
```

Notice how if I right click on the file, it only gives me the option to 'restore previous version' 
![screenshot 2015-06-08 15 45 35](https://cloud.githubusercontent.com/assets/242382/8046450/3538e1f0-0df8-11e5-858b-a673cb74f3f8.png)

**Comment by jkerry** [comment] 2015-06-19 02:41
I did some digging here and could reproduce easily enough.  I'm concerned that there isn't much of a resolution available.  The file provider delegates all of the link creation logic directly to the win32 API. Obviously this could be fixed by, instead, utilizing mklink under the hood but my chef newbie senses tell me that's not looked highly upon

**Comment by spuder** [comment] 2015-06-19 02:44
I only tested this when using links across drive letters. 
Did this also happen when making a link on the same drive? 

Unfortunately, I don't see a work around because you can't make a hard link across drives.

**Comment by jkerry** [comment] 2015-06-19 02:56
looks like the same issue is present when both files are on the same drive

**Comment by jkerry** [comment] 2015-06-19 03:15
I'm out of time for the night, but the last bit of testing I can apply here is to try to load up the win32 API in powershell or a c# exe and create a symlink with the same API call to rule out anything suspicious with the ruby win32 API hooks (I don't think this is likely, but worth investigating).

If that shows up negative and the issue is in the win32 api I'm not sure if there's much that can be done without calling out to cmd or powershell.

**Comment by jkerry** [comment] 2015-06-22 13:18
I'm not sure if this list is publicly taggable, but wth.
@chef/client-windows I've yet to test the win32 api implementation in ruby but I'd be shocked to find that the problem is there and not the way the win32 API treats symlinks, but the current soft-link implementation is pretty useless. The softlinks produced by the cmd shell mklink utility however work pretty much like you'd expect.
Once I validate that this is a win32 api limitation and not the chef code, the only real resolution would be to shell-out to mklink rather than utilize the win32 api just for softlink creation.  Would that even be considered? It seems like it could be a code smell at the least.

**Comment by jdmundrawala** [comment] 2015-06-22 13:28
It'd be nice to figure out why the win32 api does not work. mklink should be calling those APIs. We should avoid shelling out if we can, but if that's the only way, it would be ok.
cc @chef/client-windows

**Comment by jdmundrawala** [comment] 2015-06-22 13:43
Weird thing: when I create the link with chef, the target field is missing under the properties of the file. But the link still works

**Comment by jdmundrawala** [comment] 2015-06-22 14:05
procmon does not seem to show mklink calling CreateSymbolicLink. There's a CreateFile operation and a FileSystemControl operation. It intertubes seem to say this means something about reparse points:
http://xxcopy.com/xxtb_050.htm

**Comment by jkerry** [comment] 2015-06-23 08:57
That's pretty interesting. Procmon shows a lot more activity for mklink /H.  The NTFS reparse points are considered hard links, so mklink is using classic hard links for soft links and I'm not quite sure what's up with the hard links.
![image](https://cloud.githubusercontent.com/assets/2170651/8302447/5b2bb960-1964-11e5-8d66-63530f592d29.png)

**Comment by jkerry** [comment] 2015-06-23 09:08
functionally it looks like the hard link is just  a duplicate pointer to the same HDD address. (#CaptainObvious).  I'll try to slap together a pull request that does the soft link with the same API calls as mklink

**Comment by spuder** [comment] 2015-07-31 17:40
It looks like the windows cookbook has a resource called `windows_shortcut`. Would be nice to have that merged into core. 

https://github.com/opscode-cookbooks/windows/blob/master/README.md#windows_shortcut

Here is the resource

https://github.com/opscode-cookbooks/windows/blob/master/providers/shortcut.rb

**Comment by smurawski** [comment] 2015-09-23 17:30
The link resource is doing the right thing.  For local file system links between files, a symlink is created, for links to directories or across volumes, a junction is created.  How Explorer treats them is a UI idiosyncracy and they are different from shortcuts.

**Closed by smurawski** 2015-09-23 17:30 UTC
Labels: Windows
