### ISSUE TITLE
windows_package throwing an error in Chef 16

### ISSUE THREAD

**Issue by hhodzic** [chef/chef#9787] opened 2020-05-04 17:25 UTC
## Description
Customer reported this bug via support ticket. 
They made a cookbook that utilized the windows_package resource to install the MSI file. They reported it worked fine with Chef 15 but with chef 16 it's failing. 

Error: FATAL: RuntimeError: windows_package[Powershell7] (powershell::default line 6) had an error: RuntimeError: implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

## Chef Version
v16.0.257 and v15.10.12.

## Platform Version
Customer used: Windows 10.0.14393
I recreated with test kitchen using windows-2012r2, but with this method I got an error in both client versions (15 and 16)

## Replication Case

This is the recipe code that was ran. 

windows_package 'Powershell7' do
action :install
source 'https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/PowerShell-7.0.0-win-x64.msi'
options '/quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1'
end

## Client Output

```
https://gist.github.com/hhodzic/b4a3cf10457f8d9613ffaf813dbff1af
```

## Additional info
Attached are screenshots from Chef Automate, provided by customer, that show the Windows Version, the Chef Client version and it running successfully on Chef 15. Also attached is initial error reported by customer. 

![2020-05-01 12_12_20-Window](https://user-images.githubusercontent.com/52761757/80994412-794dd480-8df1-11ea-819a-78b2901bdd07.png)
![2020-05-01 12_11_56-Window](https://user-images.githubusercontent.com/52761757/80994414-79e66b00-8df1-11ea-96b5-26e19d098a2b.png)
![2020-04-28 19_35_04-Window](https://user-images.githubusercontent.com/52761757/80994415-79e66b00-8df1-11ea-8d06-d5a55a9e2cd4.png)

**Comment by tas50** [comment] 2020-05-04 17:39
This is a duplicate of #9770 which we're looking into at the moment.

**Closed by tas50** 2020-05-04 17:39 UTC
Labels: Status: Untriaged
