### ISSUE TITLE
Sensitive attribute not working for execute in LWRP for Mac 10.10 with Chef 11.18.12

### ISSUE THREAD

**Issue by dhoer** [chef/chef#3749] opened 2015-08-03 16:40 UTC
Here is the code: https://github.com/dhoer/chef-macosx_gui_login/blob/master/providers/default.rb#L24

Chef 12 works fine, but it outputs the following during a chef client run for both 11.14.6 and 11.18.12 that should be suppressed:
```
- execute           osascript -e '
                tell application "System Events"
                  keystroke "vagrant"
                  keystroke return
                  delay 3.0
                  keystroke "vagrant"
                  delay 3.0
                  keystroke tab
                  keystroke return
                  keystroke return
                end tell'
```

**Comment by juliandunn** [comment] 2015-08-04 00:39
This is expected behavior, because this issue was [only fixed in 12.0.0](https://github.com/chef/chef/commit/45a44d598dafd037212ec7aa2249abe520c0e22e).

**Comment by lamont-granquist** [comment] 2015-08-04 16:04
Closing since this is fixed in 12.

**Closed by lamont-granquist** 2015-08-04 16:04 UTC

**Comment by dhoer** [comment] 2015-08-04 20:14
@juliandunn Thanks.  This article threw me off: http://blog.thefourthparty.com/chef-sensitive/
