### ISSUE TITLE
dsc_script idempotence not working?

### ISSUE THREAD

**Issue by rayterrill** [chef/chef#5588] opened 2016-11-28 20:58 UTC
## Description

I cannot get dsc_script to correctly work with idempotence. Always reporting resources are changing, even though they are not. If I code the same functionality in a powershell_script resources with a not_if guard, idempotence works correctly.

## Chef Version

12.16.42

## Platform Version

Server2012R2

## Replication Case

```
#resource definition
dsc_script 'NetFramework35Core_dscScript' do
  code <<-EOH
    WindowsFeature NetFramework35Core
    {
      Name = "Net-Framework-Core"
      Ensure = "Present"
      Source = 'C:\\Windows\\WinSxS'
    }
  EOH
end
```

run_status.updated_resources shows the above as always updated.

## Client Output

```
myhost.mydomain.com [2016-11-28T12:49:18-08:00] INFO: Processing dsc
_script[NetFramework35Core_dscScript] action run (Troubleshooting::default line
15)
myhost.mydomain.com [2016-11-28T12:49:21-08:00] WARN: Could not pars
e LCM output: Could not parse:
myhost.mydomain.com WARNING: Whatif is deprecated in this cmdlet. Pl
ease remove Whatif and try
myhost.mydomain.com again.
myhost.mydomain.com
myhost.mydomain.com [2016-11-28T12:49:26-08:00] INFO: DSC resource c
onfiguration completed successfully
myhost.mydomain.com [2016-11-28T12:49:26-08:00] INFO: Chef Run compl
ete in 13.517764 seconds
myhost.mydomain.com [2016-11-28T12:49:26-08:00] INFO: Running report
 handlers
myhost.mydomain.com https://myreportingnode.mydomain.com:444/Chef/chefCh
eckin.php?node=myhost.mydomain.com&status=0&runlist=recipe[POPBase],
recipe[Troubleshooting]&totalresources=11&updatedresources=3&elapsedtime=13.5177
64&updatedresourcestext=chef_handler[POPLogging::LogChefRuns],chef_handler[POPLo
gging::SendEmail],dsc_script[NetFramework35Core_dscScript]
myhost.mydomain.com [2016-11-28T12:49:26-08:00] INFO: Report handler
s complete
```

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by smurawski** [comment] 2016-11-29 01:15
Is this with wmf5?

Wmf5 changed the options on start-dscconfiguration which breaks out output parsing.

**Comment by rayterrill** [comment] 2016-11-29 02:32
@smurawski Indeed. I'm pushing WMF5 earlier in the process as well. Sorry - Didn't even think about that.

**Comment by smurawski** [comment] 2016-11-29 14:22
No worries @rayterrill - it's still a bug, but the primary use case for DSC when WMF 5 is present is via dsc_resource.

There are a couple of dsc_script/wmf 5 bugs out there - https://github.com/chef/chef/issues/5044 and https://github.com/chef/chef/issues/4999

**Comment by rayterrill** [comment] 2016-11-29 15:50
@smurawski Thanks for the detail. I'm also periodically getting errors like the below on nodes - Almost seems like a resource issue - it only happens first thing in the AM, only on some nodes.
`Chef::Exceptions::ProviderNotFound: dsc_script[NetFramework35Core] (SQLServer::default line 15) had an error: Chef::Exceptions::ProviderNotFound: Could not find PowerShell DSC support on the system Powershell was not found. Powershell 4.0 or higher was not detected on your system and is required to use the dsc_script resource.`

**Comment by rayterrill** [comment] 2016-11-29 15:52
@smurawski Also thanks for the detailed response. Looking into dsc_resource now. Seriously loving Chef. :)

**Comment by rayterrill** [comment] 2016-11-29 21:00
Oof - I remember why I didn't port this over to dsc_resource before. I'm using the command functionality of dsc_script to source a DSC file from within my cookbook because the Get/Set/Test sections are HUGE, and I didn't want to dirty up my cookbook.

I ported one of my dsc_script resources (a simple one) over to dsc_resource, but I left my complicated one as a dsc_script for now. Looks like I'm ok to leave it like this for now because I'm at WMF5 and Chef-Client > 12.6.

**Comment by eedwardsdisco** [comment] 2016-12-12 21:24
I'm getting bit by this as well.

I'm also using dsc_resource when possible, and I'm installing WMF 5 to support it.

However, dsc_resource doesn't support custom classes that are described inside the DSC Resource module, so I'm forced to use dsc_script. (note the `AccessControlInformation` property)

My script ends up causing the resource to get marked as updated every time.

### Chef Version

12.16.42

### Platform Version

Windows Server 2012 R2 and WMF 5.0

### Replication Case

web_app_dir.ps1

```
Configuration web_app_dir
{
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [String] $Path
    )

    Import-DscResource -ModuleName cNtfsAccessControl
    Import-DscResource -ModuleName PSDesiredStateConfiguration

    File web_app_dir
    {
        Ensure = 'Present'
        DestinationPath = $Path
        Type = 'Directory'
    }

    cNtfsPermissionsInheritance web_app_dir
    {
        Enabled = $false
        Path = $Path
        PreserveInherited = $false
    }

    cNtfsPermissionEntry web_app_dir_SYSTEM
    {
        Ensure = 'Present'
        Path = $Path
        Principal = 'S-1-5-18'
        AccessControlInformation = @(
            cNtfsAccessControlInformation
            {
                AccessControlType = 'Allow'
                FileSystemRights = 'FullControl'
                Inheritance = 'ThisFolderSubfoldersAndFiles'
                NoPropagateInherit = $false
            }
        )
        DependsOn = '[File]web_app_dir'
    }

    cNtfsPermissionEntry web_app_dir_Administrators
    {
        Ensure = 'Present'
        Path = $Path
        Principal = 'S-1-5-32-544'
        AccessControlInformation = @(
            cNtfsAccessControlInformation
            {
                AccessControlType = 'Allow'
                FileSystemRights = 'FullControl'
                Inheritance = 'ThisFolderSubfoldersAndFiles'
                NoPropagateInherit = $false
            }
        )
        DependsOn = '[File]web_app_dir'
    }

    cNtfsPermissionEntry web_app_dir_Users
    {
        Ensure = 'Present'
        Path = $Path
        Principal = 'S-1-5-32-545'
        AccessControlInformation = @(
            cNtfsAccessControlInformation
            {
                AccessControlType = 'Allow'
                FileSystemRights = 'ReadAndExecute'
                Inheritance = 'ThisFolderSubfoldersAndFiles'
                NoPropagateInherit = $false
            }
        )
        DependsOn = '[File]web_app_dir'
    }
}
```

recipe
```
# set up dsc script cache directory

dsc_script_cache_dir = "#{Chef::Config['file_cache_path']}\\dsc"

directory dsc_script_cache_dir do
  recursive true
  action :create
end

# set up web app pool directory

web_app_dir = node.deep_fetch!('disco', 'ravendb', 'web_app_dir')

web_app_dir_dsc_script_file = "#{dsc_script_cache_dir}\\web_app_dir.ps1"

cookbook_file web_app_dir_dsc_script_file do
  backup false
  source 'dsc/web_app_dir.ps1'
  action :create
end

dsc_script 'web_app_dir' do
  command web_app_dir_dsc_script_file
  flags ({ Path: web_app_dir })
end
```

### Output

```
<snip>

         * directory[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\dsc] action create (up to date)
         * cookbook_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\dsc\web_app_dir.ps1] action create (up to date)
         * dsc_script[web_app_dir] action run[2016-12-12T21:20:38+00:00] WARN: Could not parse LCM output: Could not parse:
       WARNING: Whatif is deprecated in this cmdlet. Please remove Whatif and try 
       again.
       
       
           - converge DSC configuration 'web_app_dir'
           - converge DSC resource Unknown DSC Resources by 
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 1/35 resources updated in 59 seconds
       Finished converging <setup-windows-2012r2-x64> (1m3.99s).
```

**Comment by rayterrill** [comment] 2016-12-12 21:26
I'm begrudgingly moving away from both dsc_script and dsc_resource for exactly the same reasons (dsc_resource doesn't have enough functionality, dsc_script always marks things as changed) - moving back to powershell_script + guards. :(

**Comment by JustinChristensen** [comment] 2017-01-26 00:11
@smurawski Do you guys have an idea on when this might be fixed?

**Comment by jugatsu** [comment] 2017-04-02 05:52
Any updates on this issue?

**Comment by smurawski** [comment] 2017-04-04 14:02
@rayterrill What functionality is `dsc_resource` missing?  It's just direct resource invocation?

@eedwardsdisco regarding the custom classes, there is a helper to make that scenario work in the `dsc_contrib` cookbook on Supermarket.

@JustinChristensen I don't think anything is planned for `dsc_script` in the immediate future.  While it's something I'd like to clean up, I doubt I'd get to it before ChefConf (so maybe into June).

As far as I'm aware, the only scenario that `dsc_resource` cannot handle is composite resources, because they are not really DSC resources, but helpers for the configuration DSL.

Personally, I'd rather put some effort into making `dsc_resource` work for composite resources (eval'ing them and invoking the right things) than updating `dsc_script`.  The mechanism for DSC script is very reliant on the output format from the configuration application and the behavior of Start-DscConfiguration which had breaking changes between v4 and v5.  It relied on `SuppportsShouldProcess` being implemented for resources (for `Start-DscConfiguration -whatif`), which was supported in DSC resources but never really shared as a guideline so almost no DSC resources actually support `-whatif` runs.

**Comment by jugatsu** [comment] 2017-04-04 14:26
@smurawski :+1: 

Also as `dsc_script` heavily rely on output it doesn't work on systems with codepage other than `437` by design. As opposite to `dsc_resource` which works great.

**Comment by rayterrill** [comment] 2017-04-04 21:15
@smurawski Maybe nothing based on your inputs above. I've moved away from the dsc_ stuff in Chef, because I kept running into little things - most of my stuff was moved into powershell_script with guards because I have full control over things at that point (example, here: https://github.com/rayterrill/ChefPlayground/blob/master/SQLServer/recipes/default.rb).

**Comment by btm** [comment] 2017-09-05 23:36
We're going to look into fixing `dsc_script` using `Test-DscConfiguration` instead of `Start-DscConfiguration -WhatIf`.

**Closed** 2017-09-12 16:01 UTC
Labels: Type: Bug, Windows

**Comment by btm** [comment] 2017-09-15 14:25
This is in 12.21.11+ (promoted to stable in 12.21.12)

It is also in 13.4.20+ (13.4.24 was recently promoted)
