### ISSUE TITLE
chef client 14.4.56 throwing error trying to turn FIPS mode on due to fingerprint not matching

### ISSUE THREAD

**Issue by muntaserq** [chef/chef#11054] opened 2021-02-15 21:47 UTC
# Describe the problem
I am experiencing an intermittent issue with FIPS and OpenSSL with Chef client 14.4.56. It happens randomly and requires a reboot of the VM to get it resolved, or I have to disable FIPS which I cannot do in the environment I'm working with. See stacktrace section for details.

## Software Version
Chef Client 14.4.56 running on Windows Server 2019 or Windows Server 2012 R2

## Replication Case
Running chef client with FIPS mode enabled and using the OpenSSL library. 

## Stacktrace
```
Traceback (most recent call last):
        9: from C:/opscode/chef/bin/chef-client:75:in `<main>'
        8: from C:/opscode/chef/bin/chef-client:75:in `load'
        7: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56-universal-mingw32/bin/chef-client:25:in `<top (required)>'
        6: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56-universal-mingw32/lib/chef/application.rb:64:in `run'
        5: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56-universal-mingw32/lib/chef/application/client.rb:313:in `reconfigure'
        4: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56-universal-mingw32/lib/chef/application.rb:55:in `reconfigure'
        3: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56-universal-mingw32/lib/chef/application.rb:99:in `configure_chef'
        2: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.4.56/lib/chef-config/config.rb:587:in `init_openssl'
        1: from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.4.56/lib/chef-config/config.rb:1132:in `enable_fips_mode'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.4.56/lib/chef-config/config.rb:1132:in `fips_mode=': Turning on FIPS mode failed: fingerprint does not match (OpenSSL::OpenSSLError)
```

## Possible Solution
The only way I've been able to resolve this is restarting the machine. You can also disable FIPS on the VM but I'm wondering if there is a better and more permanent fix that doesn't require a restart or disabling FIPS. 

Any ideas?

**Comment by tas50** [comment] 2021-04-13 22:38
@muntaserq Is this something you can try to reproduce on Chef Infra Client 16. 14 is no longer a supported release and uses an older OpenSSL and Ruby release.

**Comment by tas50** [comment] 2021-04-22 03:35
I'm going to close this out at this point since we didn't hear back about this issue on a supported Infra Client release.

**Closed by tas50** 2021-04-22 03:35 UTC
Labels: Status: Waiting on Contributor

**Comment by muntaserq** [comment] 2021-04-22 17:20
Thanks for the response on this @tas50, we'll upgrade to Chef Infra Client 16 and report back.
