### ISSUE TITLE
Private key validation error when trying to edit a client to be an admin using 'knife client edit <NAME>'

### ISSUE THREAD

**Issue by aiman-alsari** [chef/chef#2544] opened 2014-12-05 16:22 UTC
Hi,

I'm running open source chef server 12.0.0-1 with chef client 11.16.4.

The documentation would lead me to believe that I can edit a client to be an admin. I have attempted to do so:

```
knife client edit test
```

```
{
  "name": "test",
  "public_key": "removed for readability",
  "validator": false,
  "admin": false,
  "json_class": "Chef::ApiClient",
  "chef_type": "client"
}
```

I change admin from false to true. It then gives me this error:

```
ERROR: Chef::Exceptions::ValidationFailed: Option private_key must be a kind of String!  You passed false.
```

I've tried adding in a new attribute private_key with value of empty string, but I get the same error. The public key (not listed) is well formed and matches up with the private key I have on the client.

Seems like a bug.

Background:
I've updated from Chef 10.24 to 12 via 11.16. I've used the instructions in "Turn it to 11" chef blog and then the chef-server-ctl upgrade method.

I've had to make this user an admin because it's getting permission denied on a cookbook upload. Before it could do an upload (using berks) even though it wasn't an admin.

**Comment by kamidzi** [comment] 2015-02-19 19:29
I can confirm this on chef 12.0.3 as well:

```
$ export EDITOR=cat ; knife --version && knife client create -a fooadmin >/dev/null && knife client show fooadmin ; lsb_release  -a
Chef: 12.0.3
Created client[fooadmin]
admin:      false
chef_type:  client
json_class: Chef::ApiClient
name:       fooadmin
public_key: -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Tpo05hDThXQ09dY/jV4
32EarrvpyhM6mHsJ4UcthgHJ0RUblGtyL1/+V32GM7EyDlyWL3QQG7Rbq77CjATR
Ye3cmDcYzbDq5ZdrWgzP3jZH7xAQiaWbKV1V3A4JIVUBH602Ww2IM3cPgUfk/vQP
xuDPLX1+fGhfFTvLf5+VgGPrYZ5pOScRhTUn5VGyHVItYD7AWxxF8SflF3VBX5zS
JkBPS6SJyhxz2pznYVSi948AKYAPn7wctOw1ZLRLrFjTPLJi6lIHf0IjSdRrBegG
3DcAocakLl5eJTnOBtY+pjgmpYa1dvMzffzW/F4Yzg7LQOnmHGrmtdJXHwQxBP5L
twIDAQAB
-----END PUBLIC KEY-----


validator:  false
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

**Comment by paustin01** [comment] 2015-02-25 18:46
Repro'd as well with 12.0.3 and knife running on windows

**Comment by lamont-granquist** [comment] 2015-06-24 17:21
This looks to be part of #3517

**Comment by tas50** [comment] 2019-08-12 17:50
I'm going to close this issue at this point. Yes knife is providing a wildly unhelpful error message here, but the behavior of failing to allow a non-admin user to make another user an admin is correct. The root cause is the user making the change not being in the org, which is a side effect of the Chef Infra Server 11 -> 12 upgrade story. Since we're not seeing upgrades from 11 -> 12 at this point, there isn't a reason to tackle solving this.

**Closed by tas50** 2019-08-12 17:50 UTC
Labels: Component: Chef Core
