### ISSUE TITLE
64 bit chef-client silently fails with a heap corruption exitcode on package resource

### ISSUE THREAD

**Issue by jkerry** [chef/chef#4987] opened 2016-06-01 20:57 UTC
## Description

We've found that on windows server 2008R2 64 bit,  chef client 64 bit version 12.8.1+ (lower untested), with a 32 bit msi installer, running a package resource to install will cause a subsequent resource (and by extension the chef-client run) to fail silently and exit with an exit code indicating heap corruption.
## Chef Version

 chef client 64 bit version 12.8.1+ (lower untested)
## Platform Version

windows 2008r2
## Replication Case

https://github.com/jkerry/64bit_msi_chef_bug

I've created an installer and a cookbook to replicate with test-kitchen.
Testing procedure:
- kitchen create
- log into test-kitchen box, uninstall default chef-client version, download and install 64 bit chef-client
- kitchen converge

There should be an immediate exit on the remote_file resource converge
## Client Output

https://gist.github.com/jkerry/434b79b654820c543564039fa64764ad
## Stacktrace

no stack trace, silent failure with exit code "-1073740940"

**Comment by scolligan** [comment] 2018-01-03 22:22
This issue is starting to cause some significant issues with some of our deployment processes running on chef-client v12.19.36 on Windows Server 2008 R2.  It appears the chef run aborts during a remote_file resource execution.  I've gone through and removed the offending remote_file resource, and it will then abort on a different remote_file resource.

We've also experience this same behavior on Windows Server 2016 with chef-client 13.3.42.

**Comment by btm** [comment] 2018-03-13 22:39
I believe the call to `get_account_right` is the culprit in the original reproduction case here, which makes this a duplicate of #6589.

**Closed by btm** 2018-03-13 22:39 UTC
Labels: Area: Windows, Priority: Low
