### ISSUE TITLE
registry_value_exists? method doesn't check type or value attributes

### ISSUE THREAD

**Issue by Xoph** [chef/chef#2733] opened 2015-01-08 18:20 UTC
<h3>Version:</h3>

Chef_Client 11.16.4

<h3>Environment: [Details about the environment such as the Operating System, cookbook details, etc...]</h3>

OS: Windows Server 2008 R2 & Windows Server 2012 R2
Cookbook: Proprietary cookbook that sets up IE security for our product.

<h3>Scenario:</h3>

I am setting up Internet Explorer Enhanced Security Configuration for users and administrators. Users and admins are each their own value in their own keys. These registry entries always exist, but we want to update them. I realize we could just remove the guard completely, and just always let the registry value be set, but we guard every one of our resources, and we would like to check that the registry value exists and that it has the correct data type and value.

<h3>Steps to Reproduce:</h3>

1) Create a resource in a recipe as follows:

registry_key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}' do
	values [{:name => 'IsInstalled', :type => :dword, :data => 0}]
	action :create
	not_if {
		registry_value_exists?(
			'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}',
			{ :name => 'IsInstalled', :type => :dword, :data => 0}, 
			:machine)
	}
end

2) Run a converge with this recipe.
3) See that the chef run reports the resource is skipped due to not_if no matter what type the registry entry 'IsInstalled' is, or what the value is.

<h3>Additional Analysis/Information:</h3>
I have done alot of analysis around this. The documentation (http://docs.chef.io/dsl_recipe.html#registry-value-exists) reflects that what I am doing is correct.

I have alternatively tried reading in all the values by using registry_get_values and looping through them, but this also didn't work.

I also tried using the same code but used "{ name: 'IsInstalled', type: :dword, data: 0}" instead of "{ :name => 'IsInstalled', :type => :dword, :data => 0}". This gave the same results.

Thank you,
Christoph Griesshammer
GE Healthcare

**Comment by Xoph** [comment] 2015-01-08 18:24
Somebody else identified this previously as well: https://tickets.opscode.com/browse/CHEF-5079?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

**Comment by adamedx** [comment] 2015-05-20 17:46
fyi @btm -- I feel like we've run into this before.

**Comment by Sauraus** [comment] 2015-10-07 21:45
This is a PITA :(

```registry_value_exists?('HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\policies\\system', { name: 'EnableLUA', type: :dword, data: 1 })```

```registry_value_exists?('HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\policies\\system', { name: 'EnableLUA', type: :dword, data: 0 })```

Will both return true no matter what, which clearly is wrong.

Fortunately the Windows cookbook has this little helper:: https://github.com/chef-cookbooks/windows/blob/master/libraries/registry_helper.rb#L190 which does work properly.

**Comment by lamont-granquist** [comment] 2016-03-30 18:02
Doesn't `registry_data_exists?` do what you want?

**Comment by Sauraus** [comment] 2016-03-30 18:08
@lamont-granquist what do you mean? Has something changed that would invalidate my simple test above?

**Comment by lamont-granquist** [comment] 2016-03-30 18:18
convert `registry_value_exists?` to `registry_data_exists?` 

the latter checks that the key exists and that name, type, and data are all the same.   there's a hierarchy of three different tests from least specific to most specific:

- registry_key_exists?
- registry_value_exists?
- registry_data_exists?

**Comment by mwrock** [comment] 2016-04-14 00:54
I was looking and testing this and was at first convinced that `registry_value_exists?` was broken since my observations were the same as @Sauraus . Then after looking into the source, I understand what @lamont-granquist was getting at but see a fundamental flaw in this function's design and documentation.

* `registry_key_exists?` is straight forward. It checks the existence of a specified registry path disregarding any values.
* `registry_data_exists?` is also straight forward but you might miss it if you stumble upon `registry_value_exists?` first. `registry_data_exists?`does what @Sauraus and I expected of `registry_value_exists?` It takes a key path plus a hash of `:name`, `:type` and `:data` and checks if the key has the specified data of the specified type under the subkey name.
* `registry_value_exists` really should be renamed `registry_subkey_exists` and it should not accept `:type` or `:data` because it does absolutely nothing with those arguments.

Its hard to not confuse "data" with "value" especially since everyone talks about registry values in terms of data.

I think this should be cleaned up for chef v13 and I'm on the fence as to create a "fix" for chef 12. I would propose that if such a fix is made, it would treat `registry_value_exists?` just like `registry_data_exists?` if given a `:type` and `:data`. I'd propose Chef 13 should have `registry_value_exists?` replace the current `registry_data_exists` and add a `registry_subkey_exists` to perform what `registry_value_exists?` does today.

Thoughts @adamedx @smurawski @btm ?

**Comment by mwrock** [comment] 2016-04-14 00:56
Note the docs here: https://docs.chef.io/release/12-0/dsl_recipe.html#registry-value-exists

**Comment by stuartpreston** [comment] 2016-04-14 07:55
Can I link this issue I opened with InSpec if we're going to get a single definition of key/subkey/values/data/types? 

https://github.com/chef/inspec/issues/605

**Comment by mwrock** [comment] 2016-04-14 16:50
We are making some changes to the docs clarifying the differences of these functions and omiting `:type` and `:data` from the `registry_value_exists?` example.

**Comment by lamont-granquist** [comment] 2016-04-14 16:57
My only concern is that people who are using registry_value_exists? correctly right now will get broken and may get broken in ways that are a bit subtle.  I like deprecating the useless arguments of registry_value_exists and introducing registry_subkey_exists since it doesn't swap out the meanings on people.  You can even deprecate registry_value_exists entirely, and push people away from using it and onto registry_data_exists/registry_subkey_exists.  I'd be slow about it, though, hopefully we're close to Chef-13 and there won't be a lot of warning that all this is changing.

Even though you have very good reasons, people get real grouchy when they have to audit their entire codebase...

**Comment by stuartpreston** [comment] 2016-04-14 17:14
There are certainly subtleties in the language people are using to describe the registry in all of these threads and all the ServerSpec/InSpec/Chef code I've read recently whilst trying to help Windows customers navigate.  I personally dislike the use of "subkey" (there's no such thing) and would avoid at all costs. I don't really have an issue with registry_value_exists with all the overloads (as that's how I would expect to use it too).  It's registry_data_exists that seems a bit redundant to me...

![capture](https://cloud.githubusercontent.com/assets/6384654/14536732/ca533534-026b-11e6-88fd-7d6db27d2a74.PNG)

**Comment by mwrock** [comment] 2016-04-14 17:25
Yeah I have been looking through MSDN on the terminology and agree having a subkeys_exists? is a bad idea. To be clear, for now we are only making docs changes so no one should be broken. I'm tabling making any code changes now because I think we want to be careful about API changes here. I actually like the idea of depricating `registry_data_exists` and having `registry_value_exists` perform that same function if given `:type` and `:data` hash elements.

**Comment by lamont-granquist** [comment] 2016-04-14 17:27
@mwrock i kinda like that idea better...

you should probably issue a deprecation warning when registry_value_exists is given all the elements and the extra parameters would change the meaning of the function -- and immediately start allowing not passing :type and :data

**Comment by mwrock** [comment] 2016-04-14 17:29
absolutely @lamont-granquist

**Comment by lamont-granquist** [comment] 2016-04-14 18:46
👍

**Comment by mwrock** [comment] 2016-04-14 19:12
ok the [live docs](https://docs.chef.io/release/12-0/dsl_recipe.html#registry-value-exists) are now updated with corrected example and better clarification. I'm going to close this issue for now since I don't see a "code defect" here and we have added clarification to the docs. We can address future API changes separately.

**Closed by mwrock** 2016-04-14 19:12 UTC
Labels: Chef Core, Medium Priority, Windows

**Comment by zaytsevi** [comment] 2016-07-14 23:41
How did you reiterate through keys?

I am trying to loop through all the uninstall subkeys and look for a registries value data to equal 'X' or 'Y'

**Comment by mwrock** [comment] 2016-07-14 23:50
@zaytsevi you might have a look at https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/registry_uninstall_entry.rb where we do just that for the windows `package` resource.

**Comment by zaytsevi** [comment] 2016-07-14 23:53
the problem is this isn't a windows package. I am trying to uninstall a clickonce app.

`powershell_script 'remove_tempbadge' do
only_if{ 

    subkey_array = registry_get_subkeys("HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\")

    # need to figure out how to loop through the subkeys to look for data matching 'temp' and 'badge'

    registry_data_exists?(
      "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SOMEKEY",
      {
        :name => 'DisplayName', 
        :type => :string, 
        :data => 'Temporary Badges' 
      }
    )
}
    code <<-EOH
        #Find all installed Temp Badges
        $Apps  = Get-ChildItem -Path HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall,HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall,HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\ | `
                            Get-ItemProperty |  Where-Object {$_.DisplayName -match "Temp" -and $_.DisplayName -match 'Badge'}

        #Uninstall all
        if (($Apps|Measure).Count -ge 1){
            Foreach ($a in $Apps){
                $selectedUninstallString = $a.UninstallString
                $wshell = new-object -com wscript.shell
                $wshell.run("cmd /c $selectedUninstallString")
                Start-Sleep 5
                $wshell.sendkeys("`"OK`"~")
            }
        }
    EOH
end

`

**Comment by zaytsevi** [comment] 2016-07-15 19:15
@mwrock , is find_entries something that i can call from anywhere? 

: NoMethodError: No resource or method named `find_entries' for `Chef::Recipe "users_remove_appname"'

**Comment by mwrock** [comment] 2016-07-15 21:51
no its specific to the `package` resource code. You might have to do something similar in a `ruby_block`. I would say just use the `package` resource but you would need to know the exact display name and sometimes that gets a random string in click once apps. However, if that string was easily discoverable, the package resource would find it and run the uninstall command (as long as you are using the latest chef client).
